### PR TITLE
Fix duplicated counters (fix #32614)

### LINKED ISSUE #32614: Duplicated reblog count on i18n FormattedMessage
### Steps to reproduce the problem

Since https://github.com/mastodon/mastodon/pull/29585, the UI shows duplicated reblog/favorite counts.

Simply open up a regular toot and see the reblog/favorate box.

Image

### Expected behaviour

Having only one counter from the rendered UI

### Actual behaviour

Seeing the counters been duplicated.

### Detailed description

It's a convention that people on Crowdin translate the i18n string `{count, plural, one {boost} other {boosts}}` into `{count, plural, other {# 則轉嘟}}`, where `#` will be substituted with the value of `count`. Crowdin also provides the preview UI with the counter to see the substituted strings.

Image

Since the following code been introduced, both the `<AnimatedNumber>` tag and `<FormattedMessage>` will render the `reblogs_count` value if the translators follow the convention, which results in duplicated counts in the UI.

We should avoid this pattern in HTML constructs, or should **explicitly** inform the translators on Crowdin to avoid using `#` in the translated strings.

```html
        <Link to={`/@${status.getIn(['account', 'acct'])}/${status.get('id')}/reblogs`} className='detailed-status__link'>
          <span className='detailed-status__reblogs'>
            <AnimatedNumber value={status.get('reblogs_count')} />
          </span>
          <FormattedMessage id='status.reblogs' defaultMessage='{count, plural, one {boost} other {boosts}}' values={{ count: status.get('reblogs_count') }} />
        </Link>
```

### Mastodon instance

g0v.social

### Mastodon version

v4.3.0

### Browser name and version

Edge 131.0.2889.0 (Official build) dev (64-bit) 

### Operating system

Arch linux

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by xatier**
This PR fixes the duplicated counters by embedding `AnimatedNumber` inside the `FormattedMessage` component.

### CODE REVIEW

**Comment by xatier** [comment]
@renchap, this PR embraces the solution proposed in https://github.com/mastodon/mastodon/issues/32614, please kindly take a look.

@ClearlyClaire, this is a regression that caused confusion in the toot details UI.

**Comment by xatier** [comment]
Once this PR is merged, i18n authors need to update the translations with the `{counter}` variable. E.g., 

```
{count, plural, one {{counter} boost} other {{counter} boosts}}

{count, plural, other {{counter} 則轉嘟}}
```

File: app/javascript/mastodon/features/status/components/detailed_status.tsx [hunk 1]
```diff
@@ -271,13 +271,17 @@ export const DetailedStatus: React.FC<{
...
         <FormattedMessage
           id='status.reblogs'
-          defaultMessage='{count, plural, one {boost} other {boosts}}'
-          values={{ count: status.get('reblogs_count') }}
+          defaultMessage='{count, plural, one {{counter} boost} other {{counter} boosts}}'
+          values={{
+            count: status.get('reblogs_count'),
+            counter: (
+              <span className='detailed-status__reblogs'>
+              <AnimatedNumber value={status.get('reblogs_count')} />
```
Comment (ChaosExAnima) [inline app/javascript/mastodon/features/status/components/detailed_status.tsx]: Can you fix the indentation issue here and in the other areas? `<AnimatedNumber>` should get two more spaces- then the CI should pass.

**Review by ChaosExAnima — CHANGES_REQUESTED** [review]

File: app/javascript/mastodon/features/status/components/detailed_status.tsx (hunk 1 above)
Comment (xatier) [reply app/javascript/mastodon/features/status/components/detailed_status.tsx]: fixed, thanks!

**Review by ChaosExAnima — APPROVED** [review]
