### PR TITLE
Remove sign-in token authentication, instead send e-mail about new sign-in

### LINKED ISSUE #14676: Mastodon 3.2 major problem with new security mechanism and the token code
Ever since updating my instance to 3.2, I have received 4 different reports from users telling me they are unable to regain access to their accounts after logging in from a new computer/new location after a long period of time. 3 of them tell me that the email with the security code never arrives to their inbox even after several attempts and double-checking their spam folder. The other user tells me that even though they received the token security code, it does not seem to work.

Whenever I had users message me with issues regarding two-factor authentication and they were locked out of their accounts, it was easy for me to simply disable 2FA for them to be able to log in again. However, with Mastodon 3.2's newest feature that sends this security code, there is no way for me to disable this or manually confirm it as the admin. The user is effectively locked out if they do not receive this email or the security code is invalid for some reason.

Please, I implore the Masto devs to look into adding some kind of setting in the admin panel to disable or opt out if this new feature, or at least the ability to allow for troubleshooting this login issue for users without resorting to changing their email address for another attempt at security verification.

### LINKED ISSUE #17938: Users keep getting asked for login code every day
### Steps to reproduce the problem

As far as i understand right now, some users log in to their Mastodon account at least once a day and after the recent update, they each time get asked for a login code because their last login was "a long time ago".

Personally, i was unable to reproduct this by simply logging off and on again. I was wondering if this could somehow be related to my other problem here: https://github.com/mastodon/mastodon/discussions/17932

**Edit:** [asking users](https://social.tchncs.de/@milan/108061985637324850) reveals that this likely is related to the user IP, since normal household ones change every 24h or so. Since my problem linked above (which also affects other instances), it can get even more annoying because when the queue is not properly processes, it is not only one more step but also much more time added to the login routine...

### Expected behaviour

Either wording should be different or the timeframe more relaxed

### Actual behaviour

Login code because they last login was "a long time ago".

### Specifications

v3.5.0, git

### PR DESCRIPTION
**Pull request by Gargron**
Fix #17938, fix #14676

### CODE REVIEW

File: app/lib/suspicious_sign_in_detector.rb [hunk 1]
```diff
@@ -0,0 +1,42 @@
+# frozen_string_literal: true
+
+class SuspiciousSignInDetector
+  IPV6_TOLERANCE_MASK = 64
+  IPV4_TOLERANCE_MASK = 16
```
Comment (ClearlyClaire) [inline app/lib/suspicious_sign_in_detector.rb:5]: Worried this might be too permissive, but who knows.

**Review by ClearlyClaire — APPROVED** [review]
Worried this might be a bit too permissive, but I guess the change makes sense if it was being too much of a pain for users.

This also simplifies the code, so there's that.

**Comment by johannessen** [comment]
Still didn’t get any email. I monitor the MX’s mail log directly and there is no attempt to even contact it, which means the security code / sign-in warning was never sent by mastodon.social.

But since it’s just a warning now and no longer a challenge, I am able to log in again. Yay!

When I changed my email address and set up 2FA just now, mastodon.social did send me the expected emails. I suspect my prior email address was erroneously marked as “bouncing” by Mastodon, triggering the issue.

BTW, I sent mail to staff@mastdodon.social about this several times over the last two weeks. Would have appreciated a reply, or even just a pointer to #17970 once that issue was opened.

Anyway, this change solved my problem. Thanks for your work!

**Review by GitHomeKS — APPROVED** [review]
