### PR TITLE
Change how content warnings and filters are displayed in web UI

### LINKED ISSUE #31216: Group Notifications experimental feature: CWs are ignored
### Steps to reproduce the problem

1. turn on group notifications
2. post something with a CW
3. someone interacts with it
4. post shows up without CW on your notifications
        

### Expected behaviour

the CW should show up instead of the content

### Actual behaviour

the content is displayed, which could be sensitive

### Detailed description

_No response_

### Mastodon instance

wetdry.world

### Mastodon version

v4.3.0-alpha.5+chuckya

### Browser name and version

Firefox 128.0.2 (64-bit)

### Operating system

EndeavourOS x86_64, Linux 6.10.0-arch1-2

### Technical details

image
image

### PR DESCRIPTION
**Pull request by Gargron**
In notifications:

grafik

In timelines (and elsewhere):

grafik

When filtered:

grafik

___

Fixes MAS-297

### CODE REVIEW

File: app/javascript/mastodon/features/notifications_v2/components/embedded_status.tsx [hunk 1]
```diff
@@ -96,12 +98,17 @@ export const EmbeddedStatus: React.FC<{ statusId: string }> = ({
     [],
   );
 
+  const handleContentWarningClick = useCallback(() => {
+    setExpanded((v) => !v);
+  }, [setExpanded]);
+
```
Comment (ClearlyClaire) [inline app/javascript/mastodon/features/notifications_v2/components/embedded_status.tsx:104]: Shouldn't it rather use the shared redux state?

Comment (Gargron) [reply app/javascript/mastodon/features/notifications_v2/components/embedded_status.tsx:104]: I'm not actually sure that would be welcome or useful.

File: app/javascript/mastodon/components/content_warning.tsx [hunk 2]
```diff
@@ -0,0 +1,31 @@
+import { FormattedMessage } from 'react-intl';
+
+export const ContentWarning: React.FC<{
+  text: string;
+  expanded?: boolean;
+  onClick?: () => void;
+}> = ({ text, expanded, onClick }) => (
+  <div className='content-warning'>
+    <div className='content-warning__border' />
```
Comment (renchap) [inline app/javascript/mastodon/components/content_warning.tsx:9]: Maybe we could use `:before` (and `:after`) here to avoid having to add those to the DOM and have all the styling done in CSS?

File: app/javascript/mastodon/components/filter_warning.tsx [hunk 3]
```diff
@@ -0,0 +1,37 @@
+import { FormattedMessage } from 'react-intl';
+
+export const FilterWarning: React.FC<{
```
Comment (renchap) [inline app/javascript/mastodon/components/filter_warning.tsx:3]: This is duplicating most of `<ContentWarning>`, maybe the two of them could be specialised versions of a base component?

File: app/javascript/mastodon/components/status.jsx [hunk 4]
```diff
@@ -13,10 +13,13 @@ import AlternateEmailIcon from '@/material-icons/400-24px/alternate_email.svg?re
 import PushPinIcon from '@/material-icons/400-24px/push_pin.svg?react';
 import RepeatIcon from '@/material-icons/400-24px/repeat.svg?react';
 import ReplyIcon from '@/material-icons/400-24px/reply.svg?react';
+import { ContentWarning } from 'mastodon/components/content_warning';
+import { FilterWarning } from 'mastodon/components/filter_warning';
 import { Icon }  from 'mastodon/components/icon';
 import PictureInPicturePlaceholder from 'mastodon/components/picture_in_picture_placeholder';
 import { withOptionalRouter, WithOptionalRouterPropTypes } from 'mastodon/utils/react_router';
 
+
```
Comment (renchap) [inline app/javascript/mastodon/components/status.jsx:22]: Extra line

File: app/javascript/mastodon/components/status.jsx [hunk 5]
```diff
@@ -332,13 +335,8 @@ class Status extends ImmutablePureComponent {
...
 
-  handleUnfilterClick = e => {
-    this.setState({ forceFilter: false });
-    e.preventDefault();
-  };
-
-  handleFilterClick = () => {
-    this.setState({ forceFilter: true });
+  handleFilterToggle = () => {
+    this.setState({ forceFilter: !this.state.forceFilter });
```
Comment (renchap) [inline app/javascript/mastodon/components/status.jsx:339]: It might be cleaner to use something like `this.setState(state => ({ forceFilter: !state.forceFilter}))`. This would be better with hooks, but I dont remember if class components have the same issues here.

File: app/javascript/mastodon/components/status.jsx [hunk 6]
```diff
@@ -574,22 +553,27 @@ class Status extends ImmutablePureComponent {
...
+                />
 
-            {expanded && hashtagBar}
+                {media}
+                {hashtagBar}
+              </>
+            )}
 
-            <StatusActionBar scrollKey={scrollKey} status={status} account={account} onFilter={matchedFilters ? this.handleFilterClick : null} {...other} />
+            <StatusActionBar scrollKey={scrollKey} status={status} account={account} /*onFilter={matchedFilters ? this.handleFilterClick : null}*/ {...other} />
```
Comment (renchap) [inline app/javascript/mastodon/components/status.jsx:576]: You forgot to remove this?

**Review by renchap — COMMENTED** [review]
This looks very good to me overall.

We might want to update the composer to use the new colors (which have better contrast)
image

I think that the new notification components is also missing the hotkey to expand it, if I remember a previous discussion we had

File: app/javascript/mastodon/components/content_warning.tsx (hunk 2 above)
Comment (Gargron) [reply app/javascript/mastodon/components/content_warning.tsx]: Would that improve performance?

Comment (renchap) [reply app/javascript/mastodon/components/content_warning.tsx]: Slightly, having less things rendered in the DOM by React will make it faster (a simpler DOM is always better). It also decouples the document structure from visual appearance, which is always a good idea.

File: app/javascript/mastodon/components/status_banner.tsx [hunk 7]
```diff
@@ -0,0 +1,43 @@
...
+  onClick?: () => void;
+}> = ({ children, variant, expanded, onClick }) => (
+  <div
+    className={
+      variant === BannerVariant.Yellow
+        ? 'content-warning'
+        : 'content-warning content-warning--filter'
+    }
+  >
+    <div className='content-warning__border' />
```
Comment (renchap) [inline app/javascript/mastodon/components/status_banner.tsx:21]: As you switched to `:before` and `:after`, those divs can now be removed?

**Comment by ariasuni** [comment]
Having the same text for both content warnings and filtered posts is very confusing.

«Show anyway» makes sense for filters because you ask to not see them, while a content warning is more neutral by nature, especially because it’s sometimes used as a subject line. I see that «Hide post» is used by both features, but a CW isn’t hiding the post, only its content, I’d argue.

Using a different phrasing to clearly distinguish both since they don’t have the same use at all would be preferable in my opinion.

**Comment by DarkFox** [comment]
> ... while a content warning is more neutral by nature, especially because it’s sometimes used as a subject line.

It should still be clear that content is being hidden, re: #30724

**Review by ClearlyClaire — APPROVED** [review]
I like the consistency, increase in click area, and that media is finally under CWs,

I'm less convinced by some of the design choices, for instance the lack of differentiation between filters and CWs, how much space these banners take and how much attention they draw, or how they look when stacked.

On the code side, this looks fine.

**Comment by nclm** [comment]
The consistency with the CW compose design is nice.

However, it makes warnings and filters very visible in the timeline, more visible than any other posts, and I don’t think this is the intent? When scrolling through my timeline, my eyes and my scroll stop at each content warning like if they are more important than other posts because of how highlighted they are. Makes me want to click them. Worse, I see filtered posts even more than non-filtered posts, which is the opposite of why you would filter posts in the first place. 

I think this is good visual design but not great information design. Filtered posts should be more discreet than common posts, and content warnings shouldn’t be highlighted like if they were more important.

**Comment by mcclure** [comment]
Literally the first thing I did upon getting this feature this morning was write a Stylus script to reverse it. (I'm not good at CSS, so the reversal is only partial and I'm still not happy.) The new design is very distracting and I don't think it works with the way people actually use CWs on Mastodon.

Over the last couple days I have multiple times (and on the request of my followers!, some of whom didn't want to see this stuff un-CWed) made threads of three to ten posts at a go in which every single post was CW'd with "USPOL / DNC". If I had done this *after* you introduced the barber poles, this would have meant every one of my followers would have a timeline which is a continuous wall of barber poles until I'm done posting. What you've done here is *created a disincentive to use content warnings.* IMO you shouldn't do that.

In addition to what nclm said: "Show anyway" and "Hide post" are totally extraneous. "Show" and "Hide" are fine. Even with the barber poles removed in my custom CSS, I don't like how the CW box now takes up so much vertical space. And there is *no* reason for the LOOK AT ME LOOK AT ME LOOK AT ME bars to *continue* to be visible *after the post has been expanded*.

This increases the visual noise and cognitive load of using-Mastodon-in-a-basic-way while providing zero benefit except literally in the first ten minutes someone is using Mastodon.

**Comment by Gargron** [comment]
I'll bring your feedback to our internal discussions. FWIW, "Show anyway" and "Hide post" are larger click areas than "Show" and "Hide", one of my gripes with the old design was how precise you had to be with the click; and the banner itself remaining visible after expansion is necessary so you have a consistent place to hide the post again (e.g. compare this to how filters used to work, you click "Show anyway" in one place, then the button to re-hide the post appears in the bottom action bar). The new design also makes it a bit more obvious what a content warning is and that it's interactive, one of the problems with the old design we were aware of is that when non-users got sent a link to a Mastodon post with a CW, they sometimes wouldn't notice there's anything more than the CW at all.

**Comment by schmittlauch** [comment]
The screenshots/ mockups in the initial posts here reveal a foundation of the problem: Different parts of the community see *content warnings* as different things.

All the mockups just show a bland placeholder text or a text that specifically discourages users from even looking at that post. Using real-world use cases might have revealed a mismatch of expectations in the UX:
The attention-seeking design choice goes orthogonal to e.g. https://github.com/mastodon/mastodon/issues/20117 and the use case of adding a *Content* **Note**, meaning an annotation that hides the post body, but apart from that being a rather regular post, not a very rarely-used exception that is seen seldomly in your stream and requires super special caution when handling.

And then there are implementors of other ActivityPub software who complain about their precious neutral *subject* line being taken away from them… But that's another different can of worms :P

I do like the larger click area as well though.

**Comment by mcclure** [comment]
(The point about click area does make a lot of sense)

**Comment by l-mb** [comment]
The clickable area is nice, but instead of reducing the visibility of something in my feed, it's now more visually catchy than it used to be.

I don't want to hide it completely (occasionally I do unfold things), but see the attached screenshot of how this works in practice - this used to be a one liner.

Please reconsider.

Screenshot_20240824-112237

**Comment by Ember-ruby** [comment]
> FWIW, "Show anyway" and "Hide post" are larger click areas than "Show" and "Hide", one of my gripes with the old design was how precise you had to be with the click

have you considered using a button, like, one where you can see it's clickable bounds? and/or a longer but more neutral text like, *hmm*, "show more"?

> is that when non-users got sent a link to a Mastodon post with a CW, they sometimes wouldn't notice there's anything more than the CW at all.

generally on the internet clickable blue text that may or may not be underlined means "this is a link elsewhere", this design could very much be *less* clear on it's function
