### PR TITLE
Fix opening the language picker scrolling the single-column view to the top

### LINKED ISSUE #19915: Pressing the change language button makes the timeline reset to the top
### Steps to reproduce the problem

1. Scroll your timeline down
2. Press the change language button

### Expected behaviour

Change language button should open without effecting the page

### Actual behaviour

The change language button makes the timeline jump to the top

### Detailed description

_No response_

### Specifications

Mastodon v4.0.0rc1 (mastodon.online)

Firefox 106.0.5

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #19915

Similar to #17579

### CODE REVIEW

File: app/javascript/mastodon/features/compose/components/language_dropdown.js [hunk 1]
```diff
@@ -226,7 +237,7 @@ class LanguageDropdownMenu extends React.PureComponent {
           // react-overlays
           <div className={`language-dropdown__dropdown ${placement}`} style={{ ...style, opacity: opacity, transform: mounted ? `scale(${scaleX}, ${scaleY})` : null }} ref={this.setRef}>
             <div className='emoji-mart-search'>
-              <input type='search' value={searchValue} onChange={this.handleSearchChange} onKeyDown={this.handleSearchKeyDown} placeholder={intl.formatMessage(messages.search)} autoFocus />
+              <input type='search' value={searchValue} onChange={this.handleSearchChange} onKeyDown={this.handleSearchKeyDown} placeholder={intl.formatMessage(messages.search)} autoFocus={readyToFocus} />
```
Comment (guest20) [inline app/javascript/mastodon/features/compose/components/language_dropdown.js:240]: Doesn't autofocus only apply on page load?

Comment (ClearlyClaire) [reply app/javascript/mastodon/features/compose/components/language_dropdown.js:240]: True. The code can be simplified somewhat by getting rid of it.

**Review by Gargron — APPROVED** [review]
