### PR TITLE
Fix Mastodon listing updates older or equal to current version

### LINKED ISSUE #33772: "Mastodon update is available" shown even after upgrading
### Steps to reproduce the problem

I've upgraded to 4.2.15 successfully but under the Admin Dashboard it still shows the warning prompt of "A Mastodon update is available."
Clicking on that link takes me to a screen that displays both 4.2.15 as well as 4.3.3.

### Expected behaviour

Only 4.3.3 to appear in this list? 

### Actual behaviour

v4.2.15 should not appear in my list because I've already upgraded to it / it is present live version. Should it still show the "update available" even if you're on the latest prev branch?

### Detailed description

_No response_

### Mastodon instance

birdbutt.com

### Mastodon version

v4.2.15

### Browser name and version

Firefox 133

### Operating system

macOS 14.5

### Technical details

Let me know if any more is needed, but it was a very easy / straightforward 4.2.15 upgrade. Services and server restarted too, caches cleared.

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #33772

The reason we did not filter before is because we wanted to use server-provided values unconditionally to avoid being stuck with a possibly bogus version comparison.

However, even if version comparison can be awkward at times (e.g. `4.3.0-nightly.2024-03-05-security` being an inferior version to `4.3.0-nightly.2024-03-05`), we have consistently used the same versioning scheme for a while and for many situations now. I feel like it's fine to filter by version on Mastodon itself too.

### CODE REVIEW

File: app/controllers/admin/software_updates_controller.rb [hunk 1]
```diff
@@ -6,7 +6,7 @@ class SoftwareUpdatesController < BaseController
 
     def index
       authorize :software_update, :index?
-      @software_updates = SoftwareUpdate.by_version
+      @software_updates = SoftwareUpdate.by_version.filter(&:pending?)
```
Comment (mjankowski) [inline app/controllers/admin/software_updates_controller.rb:9]: Not necessary for this PR ... but it may make sense at some point to do a query object sort of thing, or some other approach to the various "scope"-like class methods on `SoftwareUpdate`, so the logic can stay in the class and externally have interface more like AR class scopes.

**Review by oneiros — APPROVED** [review]
