### PR TITLE
Fix post deletion not being deferred when those are part of an account warning

### LINKED ISSUE #30142: Appeal interface should display post content when an appeal is opened for review
### Pitch

Any content (post, media, or accounts) that is made inaccessible through moderation action should sill be accessible to moderators when an appeal is reviewed. Similarly, if the moderator intervention is overturned then the content should be restored; which is not possible if it's been purged from the system.

When intervening with reports, there should be an option to "deny appeal" which would have today's behavior of (near) immediate deletion. However, this should require opt-in so that any appeal can be fully actioned. 

### Motivation

While there are definitely compliance cases where media should be immediately purged, offending content should generally be accessible for appeal. The moderation team at SFBA requires that a different moderator than the intervening one reviews any appeal. Not having the context for the posts makes this checked workflow much more difficult; since the content is often deleted before the appeal is filed or reviewed. 

This aggressive deletion pattern makes auditing and reviewing moderation interventions near impossible at times. 

486-622-max

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #30142

Currently, deleted statuses that are part of an open report are not actually immediately deleted, but kept for 30 days to allow reviewing.

This change extends the check to allow prevent immediate deletion of posts that occur in an account warning, as the posts are relevant to the appeal process.

### CODE REVIEW

File: app/models/status.rb [hunk 1]
```diff
@@ -266,7 +266,7 @@ def non_sensitive_with_media?
   end
 
   def reported?
-    @reported ||= Report.where(target_account: account).unresolved.exists?(['? = ANY(status_ids)', id])
+    @reported ||= Report.where(target_account: account).unresolved.exists?(['? = ANY(status_ids)', id]) || AccountWarning.where(target_account: account).exists?(['? = ANY(status_ids)', id.to_s])
```
Comment (mjankowski) [inline app/models/status.rb:269]: Line could be slightly compressed with `account.targeted_reports...` in first part and `account.strikes...` in second part (I think those are same query?)

Possible future idea ... I think there are a few more models with the "collection of `status_ids` as array column" setup in place ... could pull out some shared querying ability or scope or something for those. Might be contingent on them all being exact same column type, which I haven't double checked.

**Review by mjankowski — APPROVED** [review]
Looks correct overall, left some style/refactor speculation on one line.

File: app/models/status.rb (hunk 1 above)
Comment (ClearlyClaire) [reply app/models/status.rb]: They are currently not all the same exact column type, unfortunately. `AccountWarning` have them be strings for some reason :/

**Review by renchap — APPROVED** [review]
