### PR TITLE
Fix dropdown menu positions when scrolling

### LINKED ISSUE #14266: When opening the context menu in the timeline, it flies away.
### Expected behaviour

Context menu should stay put while I select an option.

### Actual behaviour

Context menu flies up the page, preventing me from selecting an option.

### Steps to reproduce the problem

1. Click on the options button under a toot in either the federated or local timelines.
2. Wait for the timeline to update.
3. The context menu will fly up the page.

### Specifications

I'm using Fedora with Firefox 78.0.1 in the anticapitalist.party instance, although this issue happens on more than just this instance.

### PR DESCRIPTION
**Pull request by sidp**
This PR fixes #14266, an issue where dropdown positions, primarily in the compose UI, scroll together with the main timeline instead of staying fixed as expected. This is resolved by updating react-overlays from 0.9.3 to 5.2.1 (latest version as of today) and using `strategy: 'fixed'` in `popperConfig`.

Here is an outline of the changes I have made.

DropdownMenu component:
* Use react-overlays’ built-in arrow positioning feature.
* Re-implemented `.dropdown-menu__arrow`. The element needs to have a width and height be positioned correctly and this was easier than the previous approach with 
* Moved wrapping div (`.dropdown-menu` from `DropdownMenu` to `Dropdown`).
* Wrap button in a span to solve issue with ref.

EmojiPickerDropdown, LanguageDropdown, PrivacyDropdown and SearchPopout components:
* Update for new API (render prop as `children`, set `popperConfig`, `flip` and `target` props.
* Wrap menu components in a div where react-overlays’ props can be inserted.

Everywhere:
* Re-implemented the animations using css `@keyframes` animations to simplify the JavaScript code. No need to keep track of the mounted state to make the positioning of overlays work, or duplicate the animation parameters in multiple places in the codebase.

---

Two thing to consider when reviewing this PR:
- The placement (top, left, right, bottom) of the overlay. It was previously stored in the redux-managed state. This is no longer the case, since react-dropdowns flips the direction if needed to fit them in the viewport, and keeps track of this state itself. I don't know if this is still needed for some edge-case but I haven't seen that in my testing.
- Because the arrows (`.dropdown-menu__arrow`) have been changed from being drawn with border-width to an inline SVG path, this will break any third-party CSS that relies on the border-width method. Not sure if this is a problem in practice.

Any comments and feedback is very welcome!

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
This will take a while to properly review, but it looks good, thanks for your contribution!

File: app/javascript/mastodon/components/dropdown_menu.js [hunk 1]
```diff
@@ -336,19 +312,27 @@ export default class Dropdown extends React.PureComponent {
...
-            onClose={this.handleClose}
-            openedViaKeyboard={openedViaKeyboard}
-            renderItem={renderItem}
-            renderHeader={renderHeader}
-            onItemClick={this.handleItemClick}
-          />
+        <span ref={this.setTargetRef}>
+          {button}
+        </span>
+        <Overlay show={open} offset={[5, 5]} placement={dropdownPlacement} flip target={this.findTarget} popperConfig={{ strategy: 'fixed' }}>
```
Comment (ClearlyClaire) [inline app/javascript/mastodon/components/dropdown_menu.js:318]: I wonder if it would make sense just removing the `placement` logic and let `react-overlays` handle it through the `flip` prop.

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]
I think there's an opportunity to simplify some of the code further.

I'm also running into an issue where the compose dropdowns are not flipped for some reason I cannot understand:
image

File: app/javascript/mastodon/features/compose/components/privacy_dropdown.js [hunk 2]
```diff
@@ -272,14 +265,20 @@ class PrivacyDropdown extends React.PureComponent {
...
+                <PrivacyDropdownMenu
+                  items={this.options}
+                  value={value}
+                  onClose={this.handleClose}
+                  onChange={this.handleChange}
+                  placement={placement}
+                />
+              </div>
+            </div>
+          )}
```
Comment (ClearlyClaire) [inline app/javascript/mastodon/features/compose/components/privacy_dropdown.js:281]: There is another regression here in that the dropdown is displayed below the boost modal:
image

From my understanding, this is because the dropdown div is now wrapped by two more divs, so while it has a `z-index: 9999`, the wrapper doesn't.

File: app/javascript/mastodon/components/dropdown_menu.js (hunk 1 above)
Comment (sidp) [reply app/javascript/mastodon/components/dropdown_menu.js]: I've removed the `placement` state from the individual components and also from the redux actions, so react-overlays is now handling all the positioning state.

File: app/javascript/mastodon/features/compose/components/privacy_dropdown.js (hunk 2 above)
Comment (sidp) [reply app/javascript/mastodon/features/compose/components/privacy_dropdown.js]: I resolved this by removing the z-index from `.modal-root__modal`. z-index is already set to 9999 for `.modal-root` so this does not appear to make any practical difference other than that the overlays are now working properly in the modals.

**Comment by sidp** [comment]
@ClearlyClaire Thanks for the review! I've solved the issues you commented on, but discovered an additional one when I got the dropdowns in the compose UI to flip properly. This issue is that the button for the privacy dropdown should take on the color of the adjacent option, and now that the react-overlays is handling the positioning we don't have the state available to apply the correct color to the button anymore.

I'll request another review once I've fixed this.

**Comment by ClearlyClaire** [comment]
> I'll request another review once I've fixed this.

Is this ready for another round of review?

**Comment by sidp** [comment]
> Is this ready for another round of review?

Yes, please go ahead! I've done another round of testing here and I think it's ready for another review. CI fails on lint, but from what I can see it's not on lines touched by this PR.

File: app/javascript/mastodon/features/compose/components/language_dropdown.js [hunk 3]
```diff
@@ -37,8 +33,8 @@ class LanguageDropdownMenu extends React.PureComponent {
   };
 
   state = {
-    mounted: false,
     searchValue: '',
+    placement: 'bottom',
```
Comment (ClearlyClaire) [inline app/javascript/mastodon/features/compose/components/language_dropdown.js:37]: Shouldn't this be in `LanguageDropdown` instead?

**Review by ClearlyClaire — APPROVED** [review]
I have found no issue when testing, and I could only find one minor code issue. It should be fixed, but otherwise you can consider the PR approved.
Thank you for your contribution!

File: app/javascript/mastodon/features/compose/components/language_dropdown.js (hunk 3 above)
Comment (sidp) [reply app/javascript/mastodon/features/compose/components/language_dropdown.js]: Yes, that's correct! I've fixed this now.

**Review by ClearlyClaire — APPROVED** [review]

File: app/javascript/mastodon/features/compose/components/language_dropdown.js [hunk 4]
```diff
@@ -309,15 +305,20 @@ class LanguageDropdown extends React.PureComponent {
...
-            value={value}
-            frequentlyUsedLanguages={frequentlyUsedLanguages}
-            onClose={this.handleClose}
-            onChange={this.handleChange}
-            placement={placement}
-            intl={intl}
-          />
+        <Overlay show={open} placement={'bottom'} flip target={this.findTarget} popperConfig={{ strategy: 'fixed', onFirstUpdate: this.handleOverlayEnter }}>
+          {({ props, placement }) => (
+            <div {...props} style={{ ...props.style, width: 280 }}>
```
Comment (ClearlyClaire) [inline app/javascript/mastodon/features/compose/components/language_dropdown.js:310]: Sorry I just noticed that, but is there a way we can avoid such hardcoded values? The ideal width of the components depend on their text content, which depends on language, so it really should not be hardcoded.
