### PR TITLE
Fix installation failing when Redis password contains special characters

### LINKED ISSUE #13154: database is not properly seeded
### Expected behaviour

When I try to enable a relay, i get a 404 error.

### Actual behaviour

"method=POST path=/admin/relays/1/enable format=html controller=Admin::RelaysController action=enable status=404 duration=38.96 view=1.49 db=3.02"

### Specifications
v.3.1.1

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #13154

### CODE REVIEW

File: lib/mastodon/redis_config.rb [hunk 1]
```diff
@@ -14,7 +14,9 @@ def setup_redis_env_url(prefix = nil, defaults = true)
   ENV[prefix + 'REDIS_URL'] = if [password, host, port, db].all?(&:nil?)
                                 ENV['REDIS_URL']
                               else
-                                "redis://#{password.blank? ? '' : ":#{password}@"}#{host}:#{port}/#{db}"
+                                uri = Addressable::URI.parse("redis://#{host}:#{port}/#{db}")
```
Comment (Gargron) [inline lib/mastodon/redis_config.rb]: I feel like this would benefit from using `tap` instead of variables.

File: app/javascript/styles/mastodon/variables.scss [hunk 2]
```diff
@@ -12,7 +12,7 @@ $red-bookmark: $warning-red;
 $classic-base-color: #282c37;         // Midnight Express
 $classic-primary-color: #9baec8;      // Echo Blue
 $classic-secondary-color: #d9e1e8;    // Pattens Blue
-$classic-highlight-color: #2b90d9;    // Summer Sky
+$classic-highlight-color: #007ce6;    // Ziqkrr blue
```
Comment (nightpool) [inline app/javascript/styles/mastodon/variables.scss]: wrong PR?

Comment (ThibG) [reply app/javascript/styles/mastodon/variables.scss]: oops nvm

File: lib/tasks/mastodon.rake [hunk 3]
```diff
@@ -336,7 +336,20 @@ namespace :mastodon do
...
+          if value.is_a?(String) && value =~ /[\s\#\\"]/
+            if value =~ /[']/
+              value = value.to_s.gsub(/[\\"\$]/) { |x| "\\#{x}" }
+              "#{key}=\"#{value}\""
+            else
+              "#{key}='#{value}'"
+            end
+          else
+            "#{key}=#{value}"
+          end
```
[the remark this answers is not in the document]
Comment (ThibG) [reply lib/tasks/mastodon.rake]: we could, the reason i went against it is that `shellwords.escape` never makes use of single or double quotes, and instead always escape each and every “special” character, which is quickly unreadable

[the remark this answers is not in the document]
Comment (ThibG) [reply lib/tasks/mastodon.rake]: also, this wouldn't have worked, because dotenv stops at `#` even if it's escaped, when it's not in a single or double-quoted string :weary:

**Review by Gargron — APPROVED** [review]
