### PR TITLE
Change link previews to keep original URL from the status

### LINKED ISSUE #19538: Link preview cards removes URL fragment (everything after #) from links
### Steps to reproduce the problem

1. Post a toot with a URL containing a #, like https://cryptpad.fr/pad/#/2/pad/view/VbowAnzGBYRRL9axpkOxVXdJArhe8Y0QCVu2zPLR2-E/

### Expected behaviour

Clicking on the automatic link preview card attached to the toot should send you to the exact URL you added to the toot

### Actual behaviour

The link preview card strips the #, and everything after it

### Detailed description

Most of the time this stripping of the # and everything after it might only change where on a page people clicking a link gets sent to. That's bad enough in itself. But some times, like with my example above, stripping this information totally changes where you're linked to. Clicking the URL sends you to the correct content, while clicking on the preveiw card sends you to something completely different. This is a problem.

I tried searching to see if this was already reported, my apologies if I just didn't find it.

Thanks for your hard and very important work!

### Specifications

Mastodon 3.5.3

### LINKED ISSUE #21308: Link preview cards truncate URL
### Steps to reproduce the problem

1. Go to https://mastodon.me.uk/@mattedgar/109380474332652448
2. Click the link presented in status content text
3. Go back and click the link presented in status card
...

### Expected behaviour

Both links go to https://www.gatenbysanderson.com/job/GSe87375/Chief-Information-Officer/

### Actual behaviour

text link goes to the full URL (https://www.gatenbysanderson.com/job/GSe87375/Chief-Information-Officer/) but card link truncates to https://www.gatenbysanderson.com/job/

### Detailed description

This is related to [#19538](https://github.com/mastodon/mastodon/issues/19538) but seemingly a more wide ranging issue than just stripping URL content after a hash

### Specifications

Mastodon v4.0.2
Chrome 107.0.5304.110

### LINKED ISSUE #27056: Link in the post and link of preview are different
### Steps to reproduce the problem

1. Go to https://social.tchncs.de/@mspro/111092208456534993
2. Click on the post link
3. Click on the preview link

### Expected behaviour

After clicking on the preview link the remote web server shows the expected web page

### Actual behaviour

After clicking on the preview link the remote web server shows a 404 error page

### Detailed description

Post and preview links are different.
The '?' character is URL encoded:

Post link:
https://www.boeckler.de/de/faust-detail.htm?sync_id=HBS-008697
Preview link:
https://www.boeckler.de/de/faust-detail.htm%3Fsync_id=HBS-008697 (? is encoded by %3F)

There are 2 problems:

1. The remote web server does not show the correct page. I believe this is **_not_** Mastodon's fault: The web server should be able to decode the URL and display the correct web page anyway.
2. Mastodon creates a preview URL which is different from the URL in the post. I think this should be solved. Then the web page would not display the 404 error page. It is the post creators' responsibility to post a correct URL but Mastodon should not change it to a different URL in the preview, even if it it's semantically equivalent to the original URL (except for " of course which is used in the a href).

### Mastodon instance

https://social.tchncs.de/

### Mastodon version

v4.2.0

### Browser name and version

Firefox 117.0.1

### Operating system

Linux

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by Gargron**
Fix #27056, fix #21308, fix #19538

### CODE REVIEW

**Review by ykzts — DISMISSED** [review]

File: app/models/preview_card.rb [hunk 1]
```diff
@@ -50,7 +50,9 @@ class PreviewCard < ApplicationRecord
   enum type: { link: 0, photo: 1, video: 2, rich: 3 }
   enum link_type: { unknown: 0, article: 1 }
 
-  has_and_belongs_to_many :statuses
+  has_many :preview_cards_statuses, dependent: :destroy
```
Comment (ClearlyClaire) [inline app/models/preview_card.rb:53]: Wouldn't `:delete_all` be more fitting? I'm afraid `:destroy` could have quite some overhead here.

File: app/models/status.rb [hunk 2]
```diff
@@ -79,7 +79,9 @@ class Status < ApplicationRecord
   has_many :local_bookmarked, -> { merge(Account.local) }, through: :bookmarks, source: :account
 
   has_and_belongs_to_many :tags
-  has_and_belongs_to_many :preview_cards
+
+  has_many :preview_cards_statuses, dependent: :destroy
+  has_many :preview_cards, -> { select('preview_cards.*, preview_cards_statuses.url AS original_url').joins(:preview_cards_statuses) }, through: :preview_cards_statuses
```
Comment (ClearlyClaire) [inline app/models/status.rb:84]: Although I understand this is done to have minimal changes to the codebase, I'm uncomfortable with the model of a given record being populated with different attributes depending on where it was loaded from. Conceptually, this doesn't look very clean, and seems very fragile.

I'm not sure whether we should try going this way, or explicitly reference the model for the join table wherever we actually use it.

**Comment by Gargron** [comment]
I've updated the PR to load the join model explicitly, though this involves more code changes.

**Review by ClearlyClaire — APPROVED** [review]
