### PR TITLE
Fix author names as arrays in linked data.

### LINKED ISSUE #30937: LinkCrawlWorker NoMethodError: undefined method `encode' for an instance of Array
### Steps to reproduce the problem

Seen on these pages:

https://www.smithsonianmag.com/history/how-the-rise-of-the-camera-launched-a-fight-to-protect-gilded-age-americans-privacy-180984656/
https://www.bostonglobe.com/2024/07/05/metro/wampanoag-plymouth-dei-cape-cod/

CleanShot 2024-07-05 at 17 51 00@2x

### Expected behaviour

No error

### Actual behaviour

Error

### Detailed description

I seems like these are triggered from the author details on the page being listed in an array.

### Mastodon instance

vmst.io

### Mastodon version

v4.3.0-alpha.5

### Technical details

Latest `main`

### PR DESCRIPTION
**Pull request by oneiros**
Fixes #30937

Some websites seem to wrap author names in their linked data in arrays.

There are two seperate problems here:

#30929 introduced a change where we "preprocess" data before we pass it to `htmlentities`. `htmlentities` is pretty clear about wanting a string here, but what I overlooked is that it will call `#to_s` on any value it gets passed and thus silently accept any object. I fixed this but then realized there is a longer-standing issue with these cases here.

`Array#to_s` does not return the most human-readable output. So for URLs as the ones reported in the issue, we would persist author names like `["John Doe"]` (with the brackets and quotation marks) and display those on the preview cards. I can confirm that I have a couple of those on my tiny instance.

So I decided to fix this as well.

### CODE REVIEW

File: app/lib/link_details_extractor.rb [hunk 1]
```diff
@@ -294,7 +295,7 @@ def detector
   def html_entities_decode(string)
     return if string.nil?
 
-    unicode_string = string.encode('UTF-8')
+    unicode_string = string.to_s.encode('UTF-8')
```
Comment (renchap) [inline app/lib/link_details_extractor.rb:298]: I assume this is here as a fallback, so it is processed like it was before, but not used for the array-of-authors case?

Comment (oneiros) [reply app/lib/link_details_extractor.rb:298]: Exactly! I started out with this as a "fix" and then noticed the unfortunate display of "arrayed" author names. I thought it would make no sense to remove this afterwards, as this basically brings back the old behavior before #30929 for any other edge cases that might still be out there.

**Review by renchap — APPROVED** [review]
