### PR TITLE
Fix `min_id` and `max_id` causing error in search API

### LINKED ISSUE #32731: Search with `max_id` or `min_id` always fails with `422 Invalid date`
### Steps to reproduce the problem

1. make API call to search for statuses with a max_id, e.g. `https://mastodon.online/api/v2/search?q=search&type=statuses&max_id=113404702919566475`

Alternatively, using Ivory:
1. Perform any search (e.g. for the word “search”)
2. Scroll down far enough that it tries to load the next page of results, or refresh so it tries to load newer results

### Expected behaviour

Returns statuses with IDs below given max_id or above min_id

### Actual behaviour

422 Invalid date, with a date that was not in the request (example above returns `{"error":"Invalid date 2024-10-31T23:47:20Z”}`)

### Detailed description

This affects all searches in Ivory (probably other clients as well) which appears to use the min_id and/or max_id parameters for pagination

### Mastodon instance

mastodon.online, mastodon.gamedev.place

### Mastodon version

v4.3.1

### Technical details

The full error log entry from Ivory (with request and response headers) looks like:
```
GET 'https://mastodon.online/api/v2/search'
	Query Arguments:
		'min_id' = '113404702919566475'
		'q' = 'search'
		'type' = 'statuses'
		'limit' = '40'
	Request Headers:
		'Authorization' = '<REDACTED>'
	Response Headers:
		'x-runtime' = '0.019145'
		'content-security-policy' = 'default-src 'none'; frame-ancestors 'none'; form-action 'none''
		'Cache-Control' = 'private, no-store'
		'Strict-Transport-Security' = 'max-age=31557600'
		'x-ratelimit-reset' = '2024-11-01T00:00:00.638148Z'
		'Accept-Ranges' = 'bytes'
		'x-timer' = 'S1730419104.538322,VS0,VE169'
		'referrer-policy' = 'same-origin'
		'x-served-by' = 'cache-hel1410020-HEL, cache-iah1720101-IAH'
		'Alt-Svc' = 'h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400'
		'Content-Length' = '45'
		'Via' = '1.1 varnish, 1.1 varnish'
		'x-xss-protection' = '0'
		'Date' = 'Thu, 31 Oct 2024 23:58:23 GMT'
		'Vary' = 'Authorization, Origin'
		'x-cache-hits' = '0, 0'
		'x-ratelimit-limit' = '300'
		'x-request-id' = 'a0f61c8fd500a9ced9b872e837631ade'
		'x-frame-options' = 'DENY'
		'x-cache' = 'MISS, MISS'
		'Content-Type' = 'application/json; charset=utf-8'
		'x-ratelimit-remaining' = '267'
		'x-content-type-options' = 'nosniff'
	Error: PTHHTTPErrorDomain:422 'client error'
	Response:
		'error' = 'Invalid date 2024-10-31T23:47:20Z’
```

### PR DESCRIPTION
**Pull request by Gargron**
Fix #32731

### CODE REVIEW

**Review by ClearlyClaire — DISMISSED** [review]

File: lib/exceptions.rb [hunk 1]
```diff
@@ -8,7 +8,6 @@ class HostValidationError < ValidationError; end
   class LengthValidationError < ValidationError; end
   class DimensionsValidationError < ValidationError; end
   class StreamValidationError < ValidationError; end
-  class FilterValidationError < ValidationError; end
```
Comment (mjankowski) [inline lib/exceptions.rb:11]: From CI run - looks like spec still references this error class ... should be updated to use `Date::Error`?

Separately -- could we add some example date values which previously triggered errors but with this change now do not trigger errors to those specs to avoid future regression?

**Comment by ClearlyClaire** [comment]
There are two issues with this PR:
- it does not allow timestamps, which the previous version allowed and the specs account for
- the specs still refer to `FilterValidationError`

**Review by ClearlyClaire — APPROVED** [review]

**Comment by mjankowski** [comment]
> could we add some example date values which previously triggered errors but with this change now do not trigger errors to those specs to avoid future regression?

Looks like this portion didn't happen. If someone confirms the nature of the error values here, I can do this as followup.

**Comment by Gargron** [comment]
@mjankowski The errors that were fixed were from passing an ISO-8601 datetime into the `before:`/`after:` syntax.
