### PR TITLE
Embed js height fix

### LINKED ISSUE #22109: /embed.js doesn't always extend embeds height
### Steps to reproduce the problem

1. Copy embed code (e.g. `<iframe src="https://mastodon.social/@MattHodges/109297573695122961/embed" class="mastodon-embed" style="max-width: 100%; border: 0" width="400" allowfullscreen="allowfullscreen"></iframe><script src="https://static-cdn.mastodon.social/embed.js" async="async"></script>`)
2. Write to HTML, Open in a browser

### Expected behaviour

embed.js expands height, we can see full content

### Actual behaviour

Example of error:

Screen Shot 2022-12-06 at 5 55 59 PM

### Detailed description

This smells like a race condition. If I put a breakpoint, wait for a few seconds, and then remove it and proceed, the heights expand properly.
Screen Shot 2022-12-06 at 6 00 13 PM

Example HTML:

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <style>
        body {
            background-color: #292c36;
            font-family: "Arial", sans-serif;
        }

        div#container {
            margin: auto;
            max-width: 640px;
            padding: 10px;
            text-align: center;
        }

        div.post {
            margin-top: 20px;
        }

        a.home-link {
            color: white;
        }

        a.original-link {
            color: white;
        }

        span.link-divider {
            color: white;
        }

        iframe.mastodon-embed {
            max-width: 100%;
            border: 0;
        }
    </style>

    <script src="https://static-cdn.mastodon.social/embed.js" async="async"></script>

</head>

<body>
    <div id="container">

        <div class="post">
            <a class="home-link" href="https://mastodon.social/@ktboldy@mastodonapp.uk/109462532866227215"
                target="_blank">Home Link</a>
            <span class="link-divider"> | </span>
            <a class="original-link" href="https://mastodonapp.uk/@ktboldy/109462532889785980" target="_blank">Original
                Link</a>
            <br />
            <iframe src="https://mastodonapp.uk/@ktboldy/109462532889785980/embed" class="mastodon-embed"
                allowfullscreen="allowfullscreen" width="400"></iframe>
        </div>

        <div class="post">
            <a class="home-link" href="https://mastodon.social/@chrismessina@mastodon.xyz/109468858607903211"
                target="_blank">Home Link</a>
            <span class="link-divider"> | </span>
            <a class="original-link" href="https://mastodon.xyz/@chrismessina/109468858198913500"
                target="_blank">Original Link</a>
            <br />
            <iframe src="https://mastodon.xyz/@chrismessina/109468858198913500/embed" class="mastodon-embed"
                allowfullscreen="allowfullscreen" width="400"></iframe>
        </div>



    </div>
</body>

</html>
```

### Specifications

Mastodon 4.0.2
Firefox 107.0.1 
Chrome 108.0.5359.94

### PR DESCRIPTION
**Pull request by hodgesmr**
Fixes #22109 - executes the script to resize the iframes after `document.readyState === "complete"`

| Before  | After  |
|---------|-------|
| Screen Shot 2022-12-06 at 5 55 59 PM  | Screen Shot 2022-12-07 at 5 54 06 PM|

### CODE REVIEW

File: public/embed.js [hunk 1]
```diff
@@ -1,24 +1,24 @@
...
-      loaded();
-    } else {
-      document.addEventListener('DOMContentLoaded', loaded);
-    }
+  var ready = function (loaded) {
+    document.onreadystatechange = function () {
+      if (document.readyState === 'complete') {
+        loaded();
+      }
+    };
```
Comment (ClearlyClaire) [inline public/embed.js:14]: Wouldn't the following be better?

```suggestion
    document.addEventListener('readystatechange', function () {
      if (document.readyState === 'complete') {
        loaded();
      }
    });
```

**Review by ClearlyClaire — COMMENTED** [review]
If I understand correctly, the issue was that `loaded()` was called too early? I suppose `document.readyState` can't be `'complete'` at the time this script is executed, can it? If it can, the initial check should probably be kept to ensure `loaded()` is called even if the page is already in a `'complete'` `readyState`.

**Comment by hodgesmr** [comment]
> If I understand correctly, the issue was that `loaded()` was called too early? I suppose `document.readyState` can't be `'complete'` at the time this script is executed, can it? If it can, the initial check should probably be kept to ensure `loaded()` is called even if the page is already in a `'complete'` `readyState`.

Probably smart to add the initial check back just in case. Added.

**Review by ClearlyClaire — APPROVED** [review]

**Review by ClearlyClaire — APPROVED** [review]
