### PR TITLE
Link to local accounts from settings

### LINKED ISSUE #28922: Clicking a user in your follows and followers list should view the user on your server (not go to the original page)
### Steps to reproduce the problem

1. Go to your follows and followers list, e.g. https://fosstodon.org/relationships
2. Click on any user name to navigate to their profile.

### Expected behaviour

You view the profile on your server

### Actual behaviour

You get shown the original page

### Detailed description

I'm on fosstodon.org. If I click on Gargron (for example) in my follows and followers list I get taken to https://mastodon.social/@Gargron when I should be taken to https://fosstodon.org/@Gargron@mastodon.social.

I should never be taken out of my logged-in environment while navigating Mastodon normally. If I wanted to view the original page I'd select that option from the menu while viewing the profile.

### Mastodon instance

fosstodon.org, but I doubt this is server-specific

### Mastodon version

v4.2.4

### Browser name and version

Firefox 121.0.1

### Operating system

MacOS 14.2.1

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by diondiondion**
Fixes #28922

### Changes proposed in this PR:
- Change account links to link to local server rather than remote (except when the account was suspended)

### CODE REVIEW

File: app/helpers/home_helper.rb [hunk 1]
```diff
@@ -21,7 +21,7 @@ def account_link_to(account, button = '', path: nil)
                         end
                     end
                   else
-                    link_to(path || ActivityPub::TagManager.instance.url_for(account), class: 'account__display-name') do
+                    link_to(path || "@#{account.acct}", class: 'account__display-name') do
```
Comment (ClearlyClaire) [inline app/helpers/home_helper.rb]: I would suggest the following instead:
```suggestion
                    link_to(path || web_url("@#{account.pretty_acct}"), class: 'account__display-name') do
```

But I worry this is going to make things more painful for moderators investigating a suspended remote account, as this is going to replace the link with the local view, which won't show anything since the account is suspended.

Comment (diondiondion) [reply app/helpers/home_helper.rb]: Thanks, I was hoping that there'd be a better way to create this link!

> But I worry this is going to make things more painful for moderators investigating a suspended remote account

Do you think it'd be sufficient to use a remote link only if the account is suspended?

Otherwise, I'm also happy to only change the link on the "Follows and Followers" page as that's most likely to be used by non-moderators.

**Review by ClearlyClaire — APPROVED** [review]
We can go with that and adjust if it turns out to be an issue for moderators.

**Comment by ThisIsMissEm** [comment]
Would we say this solves the same problem as #31477 ?
