### PR TITLE
Fix Trending Tags pending review having an unstable sort order

### LINKED ISSUE #30135: Sort order on Pending Trending Hashtag moderation page inconsistant
### Steps to reproduce the problem

1. Goto the "pending review" page for trending hashtags (admin/trends/tags?status=pending_review) when there are multiple tags awaiting approval 
2. observe what hashtags are on the first page
3. Hit Ctrl+R or your favourite page reload process.
4. observe a completely different set of hashtags.

### Expected behaviour

The hashtags for review will always appear in a consistent order

### Actual behaviour

The sort order appears random, this is exacerbated when there are multiple pages 

### Detailed description

I think the above covers it well.  The reason this is a specific issue is I have ~800 tags to review and my intended process was to start at the end, allow all the ones I liked on the last page, then I could disallow anything remaining on the last page.  However since the contents of the page keep changing it means I can't know which tags on the page I have already discounted and haveto review them all again.

### Mastodon instance

mstdn.crmbl.uk

### Mastodon version

v4.2.8

### Browser name and version

Vivaldi 6.7.3329.21 (Stable channel) (64-bit) 

### Operating system

Windows 11

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by ThisIsMissEm**
Fixes: #30135

I think this would be an appropriate fix. The controller specs for this page currently do not concern themselves with the sort order at all. Arguably there isn't even any controller specs, because all it's testing is that the page loads successfully when logged in, and nothing else.

### CODE REVIEW

File: app/models/trends/tag_filter.rb [hunk 1]
```diff
@@ -14,7 +14,7 @@ def initialize(params)
 
   def results
     scope = if params[:status] == 'pending_review'
-              Tag.unscoped
+              Tag.unscoped.order(created_at: :desc)
```
Comment (ClearlyClaire) [inline app/models/trends/tag_filter.rb:17]: I think we should order by `id: desc` instead, this would result in the same order, but using the index on the primary key, instead of doing a potentially very expensive operation (we do not have an index on `created_at`)

```suggestion
              Tag.unscoped.order(id: :desc)
```

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]

File: app/models/trends/tag_filter.rb (hunk 1 above)
Comment (ThisIsMissEm) [reply app/models/trends/tag_filter.rb]: Sure, that works too!

**Review by ClearlyClaire — APPROVED** [review]
