### PR TITLE
Check OpenSearch compatibility version instead of regular version

### LINKED ISSUE #18535: OpenSearch support (Elasticsearch fork)
### Steps to reproduce the problem

1. Install OpenSearch instead of Elasticsearch.
2. Enable Elasticsearch: `ES_ENABLED=true`
3. Go to admin dashboard.

### Expected behaviour

No warning message.

### Actual behaviour

Incompatible Elasticsearch version: Elasticsearch X.Y.Z is running while 7.x is required

### Specifications

[OpenSearch](https://github.com/opensearch-project/OpenSearch) is a fork of Elasticsearch.

It _seems_ v1.3.1 (and even v2.0.0) are fully supported by Mastodon (v3.5.1 - v3.5.3), but the version check at the admin dashboard is still annoying:

opensearch

## Considerations
Is OpenSearch really supported by Mastodon?

* Yes: Update version check in file `elasticsearch_check.rb` (if possible)
* No: Make it happen in the future 😁

## Details
Maybe the relevant data is available at `Chewy.client.info['version']['distribution']`?

`$ curl localhost:9200`
```json
{
  "version" : {
    "distribution" : "opensearch",
    "number" : "2.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

(Irrelevant lines removed.)

### PR DESCRIPTION
**Pull request by VyrCossont**
OpenSearch clusters have a `version.number` field in their info which reflects the actual version of OpenSearch and a `version.minimum_wire_compatibility_version` that reflects the version of compatible Elasticsearch clients. We should be checking the latter when connecting to an OpenSearch cluster. (Regular ES clusters don't have it.) This gets rid of a spurious warning when using the currently shipping OpenSearch 2.4.0, which is compatible with the ES 7.x that Mastodon expects.

Fixes #18535.

### CODE REVIEW

File: app/lib/admin/system_check/elasticsearch_check.rb [hunk 1]
```diff
@@ -13,7 +13,14 @@ def pass?
 
   def message
     if running_version.present?
-      Admin::SystemCheck::Message.new(:elasticsearch_version_check, I18n.t('admin.system_checks.elasticsearch_version_check.version_comparison', running_version: running_version, required_version: required_version))
```
Comment (VyrCossont) [inline app/lib/admin/system_check/elasticsearch_check.rb:16]: This change is only to fix a linter error about line length in this file.

**Review by ClearlyClaire — APPROVED** [review]

**Comment by jordemort** [comment]
Just wanna chime in that I've been running OpenSearch with Mastodon for a few weeks on my small instance and it seems to be just fine, aside from the warning that this fixes.

**Comment by ClearlyClaire** [comment]
This seems to actually cause spurious warnings with ElasticSearch 7.x, as ElasticSearch 7.x will accept clients using the 6.8 version of the protocol, thus messing with our comparison.
