### PR TITLE
Give SINGLE_USER a chance to register

### LINKED ISSUE #1817: Brand new instance with SINGLE_USER_MODE=true fails with an exception
Trying to access brand new `SINGLE_USER_MODE=true` instance right after installation causes:

````
[f593578a-1a02-4572-98a1-ff79126279df] method=GET path=/ format=html controller=HomeController action=index status=500 error='ActionController::UrlGenerationError: No route matches {:action=>"show", :controller=>"accounts", :username=>nil} missing required keys: [:username]' duration=99.90 view=0.00 db=20.01
[f593578a-1a02-4572-98a1-ff79126279df]   
[f593578a-1a02-4572-98a1-ff79126279df] ActionController::UrlGenerationError (No route matches {:action=>"show", :controller=>"accounts", :username=>nil} missing required keys: [:username]):
[f593578a-1a02-4572-98a1-ff79126279df]   
[f593578a-1a02-4572-98a1-ff79126279df] app/controllers/home_controller.rb:15:in `authenticate_user!'
[f593578a-1a02-4572-98a1-ff79126279df] app/controllers/concerns/localized.rb:24:in `block in set_locale'
[f593578a-1a02-4572-98a1-ff79126279df] app/controllers/concerns/localized.rb:23:in `set_locale'
````
- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### PR DESCRIPTION
**Pull request by saper**
An attempt to open a brand new Mastodon instance configured
as SINGLE_USER_MODE=true will cause an exception.

Enable temporary registration if we have no users in the database

Fixes #1817

### CODE REVIEW

**Comment by saper** [comment]
Looks like controller helper_method is a trick that the test suite does not like, will have a look at it

**Comment by mjankowski** [comment]
Instead of doing this check on every request, could we improve the docs to make it more clear that single user instances need to create accounts prior to being able to use the app?

File: app/controllers/application_controller.rb [hunk 1]
```diff
@@ -69,6 +69,10 @@ def unprocessable_entity
     end
   end
 
+  def single_user_mode
```
Comment (Gargron) [inline app/controllers/application_controller.rb]: I suggest renaming this to `single_user_mode?`

File: app/controllers/application_controller.rb [hunk 2]
```diff
@@ -69,6 +69,10 @@ def unprocessable_entity
...
+    Rails.configuration.x.single_user_mode && Account.first
```
Comment (Gargron) [inline app/controllers/application_controller.rb]: And this could be `@single_user_mode ||= Rails.configuration.x.single_user_mode && Account.first` for multiple calls

**Review by Gargron — APPROVED** [review]

**Review by Gargron — CHANGES_REQUESTED** [review]
Didn't mean to click approve, meant to click reqest changes

**Comment by saper** [comment]
I was thinking about spitting out the error message instead.

Is the Account.first check expensive? If yes, then we could store the result somewhere?

**Comment by Gargron** [comment]
@mjankowski The DB check only occurs when single user mode is enabled, and it would occur anyway for the redirect to the right profile, so I think that's not a big deal

File: app/controllers/application_controller.rb (hunk 1 above)
Comment (saper) [inline app/controllers/application_controller.rb]: It was that in my first draft :) thanks

**Review by Gargron — APPROVED** [review]

**Comment by saper** [comment]
Wow, thanks.

I've tried to fix the tests by doing

````
diff --git a/spec/views/accounts/show.html.haml_spec.rb b/spec/views/accounts/show.html.haml_spec.rb
index 8265b2f4..1fc75da7 100644
--- a/spec/views/accounts/show.html.haml_spec.rb
+++ b/spec/views/accounts/show.html.haml_spec.rb
@@ -10,6 +10,8 @@ describe "stream_entries/show.html.haml" do
   end
 
   it "has valid author h-card and basic data for a detailed_status" do
+    allow(view).to receive(:single_user_mode?).and_return(false)
+
     alice  =  Fabricate(:account, username: 'alice', display_name: 'Alice')
     bob    =  Fabricate(:account, username: 'bob', display_name: 'Bob')
     status =  Fabricate(:status, account: alice, text: 'Hello World')
@@ -32,6 +34,8 @@ describe "stream_entries/show.html.haml" do
   end
 
   it "has valid h-cites for p-in-reply-to and p-comment" do
+    allow(view).to receive(:single_user_mode?).and_return(false)
+
     alice   =  Fabricate(:account, username: 'alice', display_name: 'Alice')
     bob     =  Fabricate(:account, username: 'bob', display_name: 'Bob')
     carl    =  Fabricate(:account, username: 'carl', display_name: 'Carl')
````
but causes the `<someverylangeclassdescription does not implement: single_user_mode?` which looks like https://github.com/rspec/rspec-rails/issues/1076 to me

**Comment by Gargron** [comment]
@saper Right, I am still encountering the test issue. Really annoying. Any solution?

**Comment by Gargron** [comment]
Never mind, found a hacky way to fix those tests.

**Comment by saper** [comment]
Nice.

What would be the proper way ? Providing spec for application controller?
