### PR TITLE
Change Request connection logic to try both IPv6 and IPv4 when available

### LINKED ISSUE #19751: Problem running on an IPv6-only server
### Steps to reproduce the problem

1. Install Mastodon on a system that has no IPv4 addresses
2. Attempt to search for someone on a server that has both IPv4 and IPv6 addresses

### Expected behaviour

The user should be found and displayed in the search results

### Actual behaviour

Error "503 Remote data could not be fetched" is displayed for some servers, but not for others

### Detailed description

To try to diagnose this, I edited `app/controllers/api/base_controller.rb` to return the exception`.as_s` instead of "Remote data could not be fetched". It appears that Mastodon is trying to connect to an IPv4 address, even though there are both IPv4 and IPv6 addresses for the remote server in the DNS.

I'm suspicious about this line: https://github.com/mastodon/mastodon/blob/bb89f83cc06b9665205c62db21163f2ce43d97ed/app/lib/request.rb#L196

_Why_ are only the first two addresses looked up in the DNS being used? Many servers have more than two addresses; for example, mastodon.scot has two IPv4 and two IPv6 addresses. The `take(2)` appears to originate in commit fd8145d2322d8b13b6aaa9cd2a61331ff660c9dd but there's no rationale provided for it.

I don't think the addresses are guaranteed to be returned in any particular order? My guess is that, for some servers, the first two addresses returned happen to be IPv4 addresses and the IPv6 addresses aren't being tried at all.

If I remove the `take(2)` then the problem appears to be fixed for me.

### Specifications

Mastodon 3.5.3

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #19751

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

File: app/lib/request.rb [hunk 1]
```diff
@@ -199,7 +199,8 @@ def open(host, *args)
         rescue IPAddr::InvalidAddressError
           Resolv::DNS.open do |dns|
             dns.timeouts = 5
-            addresses = dns.getaddresses(host).take(2)
+            addresses = dns.getaddresses(host)
+            addresses = addresses.filter { |addr| addr.is_a?(Resolv::IPv6) }.take(2) + addresses.filter { |addr| !addr.is_a?(Resolv::IPv6) }.take(2)
```
Comment (telmich) [inline app/lib/request.rb:203]: Hey guys! Isn't this two times IPv6? Shouldn't it be IPv6 + IPv4?

Comment (ClearlyClaire) [reply app/lib/request.rb:203]: There's a `!`!. But explicitly checking IPv4 instead of non-IPv4 would make sense too I guess.
