### PR TITLE
Fix streaming server refusing unix socket path in `DATABASE_URL`

### LINKED ISSUE #34080: Streaming server can't deal with unix socket path in DATABASE_URL
### Steps to reproduce the problem

Use unix socket as the method to access Postgres, with username and password set, by setting `DATABASE_URL` to this value:

```
DATABASE_URL=postgresql://<username>:<password>@%2F<path>%2F<to>%2F<socket>/<database_name>?host=/<path>/<to>/<socket>
```

This URL works well with `web` container.

### Expected behaviour

Streaming server boots up

### Actual behaviour

Streaming server won't boot due to missing port number

### Detailed description

I can add this small patch in `database.js`:

```js
//...
  if (env.DATABASE_URL_STREAMING) {
    baseConfig = pgConnectionString.parse(env.DATABASE_URL_STREAMING);
  } else if (env.DATABASE_URL) {
//...
```

And add a additional environment variable as workaround:

```
DATABASE_URL_STREAMING=socket://<username>:<password>@/<path>/<to>/<socket>?db=<database_name>
```

### Mastodon instance

N/A

### Mastodon version

v4.3.4

### Environment

N/A

### Technical details

Error before mitigation applied:

```
Node.js v20.18.0
file:///opt/mastodon/streaming/database.js:55
        throw new Error('Invalid port specified in DATABASE_URL environment variable');
              ^

Error: Invalid port specified in DATABASE_URL environment variable
    at Module.configFromEnv (file:///opt/mastodon/streaming/database.js:55:15)
    at startServer (file:///opt/mastodon/streaming/index.js:104:44)
    at file:///opt/mastodon/streaming/index.js:1401:1
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
```

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #34080

### CODE REVIEW

File: streaming/database.js [hunk 1]
```diff
@@ -49,7 +49,7 @@ export function configFromEnv(env, environment) {
     if (typeof parsedUrl.password === 'string') baseConfig.password = parsedUrl.password;
     if (typeof parsedUrl.host === 'string') baseConfig.host = parsedUrl.host;
     if (typeof parsedUrl.user === 'string') baseConfig.user = parsedUrl.user;
-    if (typeof parsedUrl.port === 'string') {
+    if (typeof parsedUrl.port === 'string' && parsedUrl.port) {
```
Comment (ThisIsMissEm) [inline streaming/database.js:52]: Perhaps: 
```suggestion
    if (typeof parsedUrl.port === 'string' && parsedUrl.port.length > 0) {
```

just so we don't accidentally not validate zeros or something due to type casting.

Comment (ClearlyClaire) [reply streaming/database.js:52]: You are right, while `'0' == false` being true is an interesting Javascript quirk, `'0'` is still truthy like any other non-empty string. Reverted that change.

**Review by oneiros — APPROVED** [review]
