### PR TITLE
Fix Undo Announce activity is not sent, when not followed by the reblogged post author

### LINKED ISSUE #18471: Undo Announce activity is not sent when unboosting posts from unfollowed remote accounts
### Steps to reproduce the problem

1. Boost posts on remote accounts that don't follow you.
2. Remove boost.
...

### Expected behaviour

Undo Announce activity sent to remote server.

### Actual behaviour

Undo Announce activity is not sent．

### Specifications

Reproducible version: v3.5.2

### Note
The process of sending an Undo Announce was probably introduced with the following commit.
https://github.com/mastodon/mastodon/pull/7959

However, the relevant part has been rewritten with the following commit. (However, looking at his implementation of StatusReachFinder at the time, it seems to be working fine at the time of this commit.)
https://github.com/mastodon/mastodon/commit/e7e099d1a06700d14fa10258f5509fc5c52738c8

https://github.com/mastodon/mastodon/blob/e7e099d1a06700d14fa10258f5509fc5c52738c8/app/lib/status_reach_finder.rb

In the latest version, the following conditional branch processing is introduced in StatusReachFinder, and it seems that the URL of Inbox is not returned in the case of posting.
https://github.com/mastodon/mastodon/blob/54bb659ad14fda8d3427752d2c99716420997d6e/app/lib/status_reach_finder.rb#L22

### PR DESCRIPTION
**Pull request by MitarashiDango**
fix #18471

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
This Pull Request looks correct, but I wonder if it wouldn't make more sense to change the `StatusReachFinder` to include the author of the reblogged status. This would also require a change to `ReblogService` to avoid sending the ActivityPub payload twice, though.

**Comment by MitarashiDango** [comment]
When I was investigating a bug, I was planning to add a process to `StatusReachFinder`.
Therefore, there is no objection to the policy of unifying the processing with `StatusReachFinder`.

If it is not necessary to integrate the processes of `ReblogStatus` and` RemoveStatusService` as a refactoring task separate from this Pull-Request, this Pull-Request will be used to integrate the processes.

**Comment by MitarashiDango** [comment]
Merged reblog and unreblog notification processes into the `StatusReachFinder`.

**Comment by MitarashiDango** [comment]
When sending `Announce` activity or `Undo Announce` activity, should the ID of the poster of the original post be included in the `to`? Or should it be included in `cc`?

File: app/lib/status_reach_finder.rb [hunk 1]
```diff
@@ -20,7 +20,12 @@ def reached_account_inboxes
...
-      []
+      reblogged_status_account = @status.reblog.account
+      if !reblogged_status_account.local? && reblogged_status_account.activitypub? && !reblogged_status_account.following?(@status.account)
+        [reblogged_status_account.inbox_url]
+      else
+        []
+      end
     else
       Account.where(id: reached_account_ids).inboxes
     end
```
Comment (nightpool) [inline app/lib/status_reach_finder.rb:31]: I think keeping the original `Account.where(...).inboxes` code makes more sense, instead of checking for `.local?` and `.activitypub?` manually. Instead, we should move the `if @status.reblog?` condition down to `reached_account_ids`, so that we return either `[reblog_of_account_id]` if the status is a reblog, or `[replied_to_account_id, mentioned_account_ids, ...]` etc otherwise

Comment (nightpool) [reply app/lib/status_reach_finder.rb:31]: (Also, the `!following?` condition isn't needed anymore, since the `uniq` on line 13 takes care of that)

**Review by nightpool — DISMISSED** [review]

**Comment by nightpool** [comment]
> When sending Announce activity or Undo Announce activity, should the ID of the poster of the original post be included in the to? Or should it be included in cc?

I don't think it really matters. IMO `to` makes more sense, but if it complicates the code too much to add it, then `cc` should be fine

File: app/lib/status_reach_finder.rb (hunk 1 above)
Comment (ClearlyClaire) [reply app/lib/status_reach_finder.rb:31]: I think it should read:

```ruby
[@status.reblog.account.preferred_inbox_url.presence].compact
```

Indeed, local and OStatus accounts won't have an `inbox_url` or `shared_inbox_url`, it will return `''`, so `#presence` will turn that into a `null`, and `compact` will take care of that.

Comment (nightpool) [reply app/lib/status_reach_finder.rb:31]: As I mentioned in my comment, while `[@status.reblog.account.preferred_inbox_url.presence].compact` would *work*, I think keeping the logic in this method the same for both reblog and non-reblog statuses and modifying `reached_account_ids` makes more sense and keeps the code cleaner.

Comment (ClearlyClaire) [reply app/lib/status_reach_finder.rb:31]: Yeah, that works too. I read your comment a bit fast and I think your solution is indeed slightly more elegant.

Comment (MitarashiDango) [reply app/lib/status_reach_finder.rb]: Moved the process of getting the inbox url of the poster of original post to `reached_account_ids`.

**Comment by MitarashiDango** [comment]
> When sending `Announce` activity or `Undo Announce` activity, should the ID of the poster of the original post be included in the `to`? Or should it be included in `cc`?

When I checked the implementation part before fixing this problem, the process of adding the url of the poster of the original post to `cc` was already implemented.
https://github.com/mastodon/mastodon/blob/2f6416db53fd987b702969afa0de69a06caf0d27/app/lib/activitypub/tag_manager.rb#L110

Therefore, in order to make the content of the generated activity consistent, we will not implement the process of adding id to `to`, and we will leave this process as it is.
Instead, I'm thinking of modifying the test code to expect the id to be included in `cc`, is that okay?

**Comment by ClearlyClaire** [comment]
> Therefore, in order to make the content of the generated activity consistent, we will not implement the process of adding id to `to`, and we will leave this process as it is. Instead, I'm thinking of modifying the test code to expect the id to be included in `cc`, is that okay?

Sounds good to me!

Also, the `reblog_service_spec.rb` tests need change, because they stub `ActivityPub::DistributionWorker` and expect the delivery to the reblogged user to happen somewhere else.

**Comment by MitarashiDango** [comment]
Deleted tests that are no longer needed and added tests.

**Review by ClearlyClaire — DISMISSED** [review]

**Comment by ClearlyClaire** [comment]
Sorry this PR slipped through. I'll rebase it and make sure it's merged!

**Review by ClearlyClaire — APPROVED** [review]

**Review by ClearlyClaire — APPROVED** [review]

**Review by renchap — APPROVED** [review]
