### PR TITLE
Fix spaces not being stripped in admin account search

### LINKED ISSUE #21058: Regression: When searching for accounts in the admin interface, spaces are no longer stripped from username
### Steps to reproduce the problem

I just upgraded my instance from v3.5.5 to v4.0.2. 

As I spend a lot of time in the admin/moderation interface [searching for users](https://digitalcourage.social/admin/accounts) by username, I noticed that when copying and pasting usernames from another website into the search form, I now often get no result. The reason is that leading and trailing whitespace is no longer removed automatically before the lookup is performed.

### Expected behaviour

user search should be indifferent to leading or trailing whitespace

### Actual behaviour

whitespace before or after the username leads to no search result

### Detailed description

Please perform a `.strip` on the input before searching for the user in order to revert to the behaviour of Mastodon 3.

### Specifications

Mastodon 4.0.2
Ruby 3.0.4
LibreWolf 107 browser
instance: https://digitalcourage.social

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #21058

Regression from #18641

### CODE REVIEW

File: app/models/account_filter.rb [hunk 1]
```diff
@@ -43,13 +43,13 @@ def scope_for(key, value)
     when 'status'
       status_scope(value)
     when 'by_domain'
-      Account.where(domain: value.to_s)
+      Account.where(domain: value.to_s.strip)
```
Comment (casaper) [inline app/models/account_filter.rb:46]: Why does value only need sanitizing with these scopes, but not the others?

**Review by Gargron — APPROVED** [review]
