### PR TITLE
Deduplicate IDs in relationships and familiar_followers APIs

### LINKED ISSUE #26564: `/api/v1/accounts/relationships` do not de-duplicate accounts
### Steps to reproduce the problem

1. Make a query to the relationships endpoint, with 10 times the same ID. For example `http://localhost:3000/api/v1/accounts/relationships?id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332&id[]=110321186862529332`
2. Look at the response

### Expected behaviour

I would expect account 110321186862529332 to only appear once

### Actual behaviour

It appears once for every ID specified in the request

### Detailed description

We probably need to patch the controller to add `uniq` to the list of inbound IDs

```ruby
  def account_ids
    Array(params[:id]).map(&:to_i).uniq
  end
```

I wonder if this could be done in other places as well

### Mastodon instance

_No response_

### Mastodon version

`main`

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by KevinBongart**
Fixes https://github.com/mastodon/mastodon/issues/26564

Hi @renchap and team 👋 Thanks for encouraging folks to look at and fix Mastodon issues! This is my first contribution to the project, so I'd love to use this PR as a way to learn how I can help further. Feedback more than welcome.

Some quick notes about the PR:

1. ~In addition to deduplication logic, I've added a bit of memoization as the `account_ids` methods were called multiple times in their respective controller action.~
2. There's a third place where `account_ids` is defined and could use some deduplication logic: `Api::V1::Crypto::Keys::QueriesController`. However, the routes are commented out, so I assume this is either dead code (can I remove it?) or work in progress (should this be in a branch instead?)

And some general notes about contributing to Mastodon:

1. To run some tests, debug and inspect responses, I added the two gems `pry-rails` and `pry-byebug` to the `test` and `development` groups (not in this PR). In my own Rails dev experience, these are essential tools I use every day. Would anyone be interested in adding these gems to the repo, or do developers have their own debugger and preferences?
2. I'm not sure if these discussions happen (in or outside GitHub), but the repo could use a label for issues that are ideal for first-time contributors, like the issue related to this PR. This provided me with a very easy way into the project, and I'd love to find more PRs like these, for me to continue helping or for the junior Ruby developers I help.

### CODE REVIEW

File: spec/controllers/api/v1/accounts/relationships_controller_spec.rb [hunk 1]
```diff
@@ -0,0 +1,36 @@
+# frozen_string_literal: true
+
+require 'rails_helper'
+
+describe Api::V1::Accounts::RelationshipsController do
```
Comment (mjankowski) [inline spec/controllers/api/v1/accounts/relationships_controller_spec.rb:5]: FYI - we are in the progress of (Slowly!) migrating much of the api request coverage from controller specs to request specs. I think this one (/api/v1/accounts/relationships) has already been moved and you could add this coverage to that spot, instead of re-adding this controller spec?

**Review by mjankowski — COMMENTED** [review]
Looks good overall -- left one comment about a request spec.

Also - no objection to adding the pry- gems to test/development bundle groups ... feel free to lump in here and/or open separate PR with explanation just for that.

**Comment by KevinBongart** [comment]
Thanks for the quick feedback, @mjankowski! I didn't even look at the request specs, glad the team is in the process of migrating some controller specs over there. I've updated the PR, let me know what you think.

**Comment by ClearlyClaire** [comment]
> Hi @renchap and team 👋 Thanks for encouraging folks to look at and fix Mastodon issues! This is my first contribution to the project, so I'd love to use this PR as a way to learn how I can help further. Feedback more than welcome.

Hi! Thanks for your contribution! I'm not sure this particular change is safe to do with regards to API stability, as pointed out in https://github.com/mastodon/mastodon/issues/26564#issuecomment-1818772197

> Some quick notes about the PR:
> 
>     1. In addition to deduplication logic, I've added a bit of memoization as the `account_ids` methods were called multiple times in their respective controller action.

This is a pretty established pattern in the codebase, but afaik this may cause issues with Ruby 3.2's optimizations: https://island94.org/2023/10/writing-object-shape-friendly-code-in-ruby

>     2. There's a third place where `account_ids` is defined and could use some deduplication logic: `Api::V1::Crypto::Keys::QueriesController`. However, the routes are commented out, so I assume this is either dead code (can I remove it?) or work in progress (should this be in a branch instead?)

`/api/v1/crypto` is indeed disabled. It's been merged a while ago in https://github.com/mastodon/mastodon/pull/13820 but disabled because it was not ready. We decided to have it in `main` rather than in a branch to avoid code rot. That being said, this feature isn't much closer to release than it was 3 years ago so maybe that decision could be reconsidered.

**Comment by KevinBongart** [comment]
Hi @ClearlyClaire and @mjankowski, I've removed the ordering of the accounts in the response according to https://github.com/mastodon/mastodon/issues/26564#issuecomment-1818772197 (which also removes the need for memoization altogether). PR is simpler, smaller, and ready to be reviewed :)

File: app/controllers/api/v1/accounts/familiar_followers_controller.rb [hunk 2]
```diff
@@ -12,14 +12,14 @@ def index
   private
 
   def set_accounts
-    @accounts = Account.without_suspended.where(id: account_ids).select('id, hide_collections').index_by(&:id).values_at(*account_ids).compact
+    @accounts = Account.without_suspended.where(id: account_ids).select('id, hide_collections').compact
```
Comment (ClearlyClaire) [inline app/controllers/api/v1/accounts/familiar_followers_controller.rb:15]: `compact` isn't required anymore!
```suggestion
    @accounts = Account.without_suspended.where(id: account_ids).select('id, hide_collections')
```

File: app/controllers/api/v1/accounts/familiar_followers_controller.rb [hunk 3]
```diff
@@ -12,14 +12,14 @@ def index
...
   end
 
   def familiar_followers
     FamiliarFollowersPresenter.new(@accounts, current_user.account_id)
   end
 
   def account_ids
-    Array(params[:id]).map(&:to_i)
+    Array(params[:id]).map(&:to_i).uniq
```
Comment (ClearlyClaire) [inline app/controllers/api/v1/accounts/familiar_followers_controller.rb:23]: I would drop the `uniq`, ActiveRecord and/or PostgreSQL will treat it just fine.
```suggestion
    Array(params[:id]).map(&:to_i)
```

File: app/controllers/api/v1/accounts/relationships_controller.rb [hunk 4]
```diff
@@ -20,6 +18,6 @@ def relationships
   end
 
   def account_ids
-    Array(params[:id]).map(&:to_i)
+    Array(params[:id]).map(&:to_i).uniq
```
Comment (ClearlyClaire) [inline app/controllers/api/v1/accounts/relationships_controller.rb:21]: Same
```suggestion
    Array(params[:id]).map(&:to_i)
```

File: app/controllers/api/v1/accounts/relationships_controller.rb [hunk 5]
```diff
@@ -7,9 +7,7 @@ class Api::V1::Accounts::RelationshipsController < Api::BaseController
   def index
     scope = Account.where(id: account_ids).select('id')
     scope.merge!(Account.without_suspended) unless truthy_param?(:with_suspended)
-    # .where doesn't guarantee that our results are in the same order
-    # we requested them, so return the "right" order to the requestor.
-    @accounts = scope.index_by(&:id).values_at(*account_ids).compact
+    @accounts = scope.compact
```
Comment (ClearlyClaire) [inline app/controllers/api/v1/accounts/relationships_controller.rb:10]: `compact` is not required, I'd remove it altogether or possibly change that to `to_a` if an array is required

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]
Thanks for your contribution! I think this can be simplified further, as explained in inline comments!

**Review by ClearlyClaire — APPROVED** [review]
Thank you for your contribution, this is a nice simplification of the code!

**Comment by KevinBongart** [comment]
Thanks @ClearlyClaire for the help! I'll be on the lookout for more work around APIs, but if you have any suggestions or requests please let me know 🙂
