### PR TITLE
Fix ・ detection in hashtag regex to construct hashtag correctly

### LINKED ISSUE #22871: Poor Hashtag Detection Results in Incomplete Hashtag
### Steps to reproduce the problem

1. Toot with hashtag `#ぼっち・ざ・ろっく`
2. Expected result `[#ぼっち・ざ・ろっく](link to hashtag)`
3. Actual result is `[#ぼっち](link to hashtag)・ざ・ろっく`

### Expected behaviour

Hashtag becomes `[#ぼっち・ざ・ろっく](link to hashtag)`

### Actual behaviour

Actually becomes `[#ぼっち](link to hashtag)・ざ・ろっく`

### Detailed description

Hashtag detection seems to stop when it encounters the Unicode character `・` when it should continue to some other delimiter.

### Specifications

Server:
Mastodon v4.0.2
Ruby 3.0.3p157

Client:
Firefox v108.0.1
macOS Ventura 13.1

### PR DESCRIPTION
**Pull request by parthoghosh24**
This fixes #22871 as per which hastag was not getting properly generated for strings containing ・

### CODE REVIEW

File: app/models/tag.rb [hunk 1]
```diff
@@ -26,7 +26,7 @@ class Tag < ApplicationRecord
   has_many :featured_tags, dependent: :destroy, inverse_of: :tag
   has_many :followers, through: :passive_relationships, source: :account
 
-  HASHTAG_SEPARATORS = "_\u00B7\u200c"
+  HASHTAG_SEPARATORS = "_\u00B7\u30FB\u200c"
```
Comment (parthoghosh24) [inline app/models/tag.rb:29]: Added the unicode for the character in separators to fix the issue.

**Review by ykzts — APPROVED** [review]
