### PR TITLE
Fix add validation to webpush subscription keys

### LINKED ISSUE #30541: Web::PushSubscription created with invalid keys
### Steps to reproduce the problem

When creating a `Web::PushSubscription` via `POST /api/v1/push/subscription`, there is no validation in place for the `keys` properties, as such, it's possible to create a `Web::PushSubscription` which will cause errors in `Web::PushNotificationWorker`

### Expected behaviour

Invalid keys should result in a 422

### Actual behaviour

Invalid keys are accepted

### Detailed description

This is related to #21481, where it's possible for the keys values in the `Web::PushSubscription` to not actually be valid base64 data, nor valid keys on an elliptical curve.

I suspect this is what creates #28023 #29716 issues.

### Mastodon instance

_No response_

### Mastodon version

main

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by ThisIsMissEm**
This is based off of #30540, and fixes #30541 — Seems like the simplest validation would be to just try to encrypt something with the supplied keys. It's gonna blow up if something's not wrong.

The error types come from looking at the webpush module's code, and trial and error, so maybe I haven't gotten them all.

### CODE REVIEW

File: spec/fabricators/web_push_subscription_fabricator.rb [hunk 1]
```diff
@@ -2,6 +2,10 @@
 
 Fabricator(:web_push_subscription, from: Web::PushSubscription) do
   endpoint   Faker::Internet.url
-  key_p256dh Faker::Internet.password
-  key_auth   Faker::Internet.password
+  key_p256dh do
+    curve = OpenSSL::PKey::EC.generate('prime256v1')
+    ecdh_key = curve.public_key.to_bn.to_s(2)
+    Base64.urlsafe_encode64(ecdh_key)
```
Comment (ThisIsMissEm) [inline spec/fabricators/web_push_subscription_fabricator.rb:8]: @ClearlyClaire I was using the same code as in the [WebPush library](https://github.com/ClearlyClaire/webpush/blob/master/spec/webpush/encryption_spec.rb#L5-L10), however, found that the OpenSSL interface has changed, resulting in the following error
```
Failure/Error: curve.generate_key

      OpenSSL::PKey::PKeyError:
        pkeys are immutable on OpenSSL 3.0
```

We may want to make sure we're testing the WebPush library against the supported ruby versions, particular 3.1 and above.

Comment (ClearlyClaire) [reply spec/fabricators/web_push_subscription_fabricator.rb:8]: This migration has long been done, it's been at least a year that we primarily run everything on OpenSSL 3.0 and recent ruby versions.

Regarding my WebPush library fork, you want to check the `openssl-3` branch: https://github.com/ClearlyClaire/webpush/blob/openssl-3/spec/webpush/encryption_spec.rb#L5-L10

**Review by ClearlyClaire — DISMISSED** [review]

File: spec/fabricators/web_push_subscription_fabricator.rb (hunk 1 above)
Comment (ThisIsMissEm) [reply spec/fabricators/web_push_subscription_fabricator.rb:8]: Ah cool!

**Comment by ThisIsMissEm** [comment]
@ClearlyClaire have rebased these changes so that they're mergeable

**Review by ClearlyClaire — APPROVED** [review]
