### PR TITLE
Fix `alerts` booleans not being typecast correctly in push subscription

### LINKED ISSUE #10789: [API] Push subscription type inconsistency
`GET /api/v1/push/subscription` returns a `Push subscription` object containing an `alerts` dict which specifies which alert types are currently active. It’s a boolean value but they are presented as strings instead of true booleans. In other places the API correctly uses the boolean type to represent such values. I would expect this to be the case here also.

Edit: Also the `alert` object is currently undocumented.

### Expected behaviour
```json
{"id":1,"endpoint":"https://example.com","alerts":{"follow":true,"favourite":true,"reblog":true,"mention":true},"server_key":"foobar"}
```

### Actual behaviour
```json
{"id":1,"endpoint":"https://example.com","alerts":{"follow":"true","favourite":"true","reblog":"true","mention":"true"},"server_key":"foobar"}
```

### Steps to reproduce the problem

GET /api/v1/push/subscription

### Specifications

Tested using Mastodon 2.8.2

### PR DESCRIPTION
**Pull request by Gargron**
Fix #10789

### CODE REVIEW

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]
Seems good apart from what CodeClimate is complaining about

File: app/serializers/rest/web_push_subscription_serializer.rb [hunk 1]
```diff
@@ -4,7 +4,7 @@ class REST::WebPushSubscriptionSerializer < ActiveModel::Serializer
   attributes :id, :endpoint, :alerts, :server_key
 
   def alerts
-    object.data&.dig('alerts') || {}
+    (object.data&.dig('alerts') || {}).each_with_object({}) { |(k, v), hash| hash.merge(k => ActiveModel::Type::Boolean.new.cast(v)) }
```
Comment (ThibG) [inline app/serializers/rest/web_push_subscription_serializer.rb]: Why not just `hash[k] = ActiveModel::Type::Boolean.new.cast(v)`?
The point of `each_with_object` is to mutate the object.

**Review by ClearlyClaire — APPROVED** [review]
