### PR TITLE
Fix `/settings/applications` rejecting scopes parameter

### LINKED ISSUE #33801: Cannot assign any scopes to applications in Preferences > Development
### Steps to reproduce the problem

1. In the web interface, go to Preferences > Development (`/settings/applications`)
2. Click “New Application”
3. Give it a name
4. Check any of the boxes under Scopes
5. Click “Submit”
6. Look at the details of the application and/or try to use its access token to make queries

### Expected behaviour

the scopes you checked in step 4 should still be checked, and you can use it to make queries that are covered under those scopes

### Actual behaviour

the scopes are all unchecked, and any queries made with the access token return the error "This action is outside the authorized scopes"

### Detailed description

Any new application I create here has no scopes, and I can’t add any scopes to existing applications.

I do have an application on this page that I created a long time ago (months?) that does still have the scopes I created it with and still works as expected, only new ones fail. I haven’t tested to see what happens if I try to edit the scopes on the older application.

I can reproduce this issue on both mastodon.social and .online running v4.4.0-nightly.2025-01-28. I tried on another server running v4.3.3 and it works as expected there.

### Mastodon instance

mastodon.social, mastodon.online

### Mastodon version

v4.4.0-nightly.2025-01-28

### Browser name and version

Safari 18.3

### Operating system

macOS 15.3

### Technical details

According to the web inspector, the request body when I submitted the form with “read” and “profile” scopes checked is:
```
authenticity_token=[redacted]&doorkeeper_application%5Bname%5D=testing123&doorkeeper_application%5Bwebsite%5D=&doorkeeper_application%5Bredirect_uri%5D=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&doorkeeper_application%5Bscopes%5D%5B%5D=&doorkeeper_application%5Bscopes%5D%5B%5D=read&doorkeeper_application%5Bscopes%5D%5B%5D=&doorkeeper_application%5Bscopes%5D%5B%5D=profile&doorkeeper_application%5Bscopes%5D%5B%5D=&doorkeeper_application%5Bscopes%5D%5B%5D=&doorkeeper_application%5Bscopes%5D%5B%5D=&doorkeeper_application%5Bscopes%5D%5B%5D=&button=
```

All scopes are unchecked when I look at this application.

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #33801

Fixes a regression from #33717

The logic of this controller is pretty weird, it receive an array of `scopes` in parameters but turns it into a string. The change in the previous PR ignored that.

### CODE REVIEW

File: app/controllers/settings/applications_controller.rb [hunk 1]
```diff
@@ -61,11 +60,9 @@ def set_application
...
     params
-      .expect(doorkeeper_application: [:name, :redirect_uri, :scopes, :website])
-  end
-
-  def prepare_scopes
-    scopes = application_params.fetch(:doorkeeper_application, {}).fetch(:scopes, nil)
-    params[:doorkeeper_application][:scopes] = scopes.join(' ') if scopes.is_a? Array
+      .expect(doorkeeper_application: [:name, :redirect_uri, :website, scopes: []])
+      .tap do |params|
+      params[:scopes] = params[:scopes]&.join(' ')
```
Comment (mjankowski) [inline app/controllers/settings/applications_controller.rb:65]: Apologies for missing this one ... I was on the look out for nested attributes and missed this array.

I wonder if we could move the "accept an array but save a string" portion to a `normalizes` on the model? Something like `Array(value).join(' ')` (maybe a `compact` in there too) would handle both the inbound string and inbound array scenarios (I think?), and might make this controller portion less odd.

**Comment by searls** [comment]
Thanks for this, bit me today too while working on a new app: https://mastodon.social/@searls/113935304808404795

**Review by Gargron — APPROVED** [review]

**Comment by ZorzStudios** [comment]
I'm still experiencing this issue, unfortunately.
