### PR TITLE
Fix #1141, fix #1126 - Avatar/profile info fetching

### LINKED ISSUE #1126: External user avatars not working.
I finished setting up a heroku instance today and I got s3 working for uploaded avatars but my instance is not pulling in external user avatars from other instances. The same thing is happening in my timeline so it's not just that 1 user, all external user avatars are broken.

https://social.spunkiedesign.com/users/Spunkie/following

Anyone know what I need to do to fix this?

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### LINKED ISSUE #1141: Avatar and stuff from other instance not fetched
My two instances do not fetch avatar and stuff from other instance since rev 5442083 :-/
Users profil are empty, no avatar, no description, no banner.

Reset to c19e0f1 solve this issue.

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### PR DESCRIPTION
**Pull request by Gargron**
Work through `UpdateRemoteProfileService` for both `<feed>` and `<entry>` top-level tags, as they both may contain an `<author>`.

It was previously discarding top-level `<entry>` tags because of historical usage in `ProcessFeedService`.

### CODE REVIEW

File: app/services/process_feed_service.rb [hunk 1]
```diff
@@ -50,6 +49,7 @@ def create_status
       if verb == :share
         original_status, = status_from_xml(@xml.at_xpath('.//activity:object', activity: TagManager::AS_XMLNS))
         status.reblog    = original_status
+        status.text      = ''
```
Comment (blackle) [inline app/services/process_feed_service.rb]: what's this addition doing? fixing null text for reblogged entries? is this necessarily part of the fix?

File: app/services/update_remote_profile_service.rb [hunk 2]
```diff
@@ -1,7 +1,12 @@
 # frozen_string_literal: true
 
 class UpdateRemoteProfileService < BaseService
-  def call(xml, account, resubscribe = false)
+  def call(body, account, resubscribe = false)
+    xml = Nokogiri::XML(body)
+    xml.encoding = 'utf-8'
+
+    xml = xml.at_xpath('/xmlns:feed', xmlns: TagManager::XMLNS) || xml.at_xpath('/xmlns:entry', xmlns: TagManager::XMLNS)
```
Comment (blackle) [inline app/services/update_remote_profile_service.rb]: I'm glad to see that pulling the author info out of the body is now the callee's responsibility instead of the caller, it feels more DRY

File: app/services/update_remote_profile_service.rb [hunk 3]
```diff
@@ -12,7 +17,7 @@ def call(xml, account, resubscribe = false)
       account.note         = author_xml.at_xpath('./poco:note', poco: TagManager::POCO_XMLNS).content unless author_xml.at_xpath('./poco:note', poco: TagManager::POCO_XMLNS).nil?
       account.locked       = author_xml.at_xpath('./mastodon:scope', mastodon: TagManager::MTDN_XMLNS)&.content == 'private'
 
-      unless account.suspended? || DomainBlock.find_by(domain: account.domain)&.reject_media?
+      if !account.suspended? && !DomainBlock.find_by(domain: account.domain)&.reject_media?
         account.avatar_remote_url = author_xml.at_xpath('./xmlns:link[@rel="avatar"]', xmlns: TagManager::XMLNS)['href'] unless author_xml.at_xpath('./xmlns:link[@rel="avatar"]', xmlns: TagManager::XMLNS).nil? || author_xml.at_xpath('./xmlns:link[@rel="avatar"]', xmlns: TagManager::XMLNS)['href'].blank?
         account.header_remote_url = author_xml.at_xpath('./xmlns:link[@rel="header"]', xmlns: TagManager::XMLNS)['href'] unless author_xml.at_xpath('./xmlns:link[@rel="header"]', xmlns: TagManager::XMLNS).nil? || author_xml.at_xpath('./xmlns:link[@rel="header"]', xmlns: TagManager::XMLNS)['href'].blank?
```
Comment (blackle) [inline app/services/update_remote_profile_service.rb]: the repetition in these lines make me uncomfortable.. idk if ruby has pass by reference (I'm still kinda rusty) but I feel like this could be a helper function like populate_from_feed(account.avatar_remote_url, xml, "avatar"). not necessary for the fix tho I guess

File: app/services/process_feed_service.rb (hunk 1 above)
Comment (Gargron) [inline app/services/process_feed_service.rb]: Not necessary for the fix, but I noticed that remote reblogs had their wrapper text stored, which is inconsistent with local reblogs (empty text). That storage space is wasted. Also, when a bug like #1114 happens, in order of best-caseness:

1. do not have that bug happen at all
2. display "RT [original author] [text]" instead of just "[text]"
3. display an empty toot to make it obvious it's broken and not misattribute content visually

File: app/services/update_remote_profile_service.rb [hunk 4]
```diff
@@ -12,9 +17,9 @@ def call(xml, account, resubscribe = false)
       account.note         = author_xml.at_xpath('./poco:note', poco: TagManager::POCO_XMLNS).content unless author_xml.at_xpath('./poco:note', poco: TagManager::POCO_XMLNS).nil?
       account.locked       = author_xml.at_xpath('./mastodon:scope', mastodon: TagManager::MTDN_XMLNS)&.content == 'private'
 
-      unless account.suspended? || DomainBlock.find_by(domain: account.domain)&.reject_media?
-        account.avatar_remote_url = author_xml.at_xpath('./xmlns:link[@rel="avatar"]', xmlns: TagManager::XMLNS)['href'] unless author_xml.at_xpath('./xmlns:link[@rel="avatar"]', xmlns: TagManager::XMLNS).nil? || author_xml.at_xpath('./xmlns:link[@rel="avatar"]', xmlns: TagManager::XMLNS)['href'].blank?
-        account.header_remote_url = author_xml.at_xpath('./xmlns:link[@rel="header"]', xmlns: TagManager::XMLNS)['href'] unless author_xml.at_xpath('./xmlns:link[@rel="header"]', xmlns: TagManager::XMLNS).nil? || author_xml.at_xpath('./xmlns:link[@rel="header"]', xmlns: TagManager::XMLNS)['href'].blank?
+      if !account.suspended? && !DomainBlock.find_by(domain: account.domain)&.reject_media?
```
Comment (ineffyble) [inline app/services/update_remote_profile_service.rb]: Ruby best practice doesn't like IF NOT tests, from memory (e.g. better to have unless X than if !X). Not sure if that matters too much, but worth noting (I've been bugged a lot by Rubocop about this in past).

Comment (Gargron) [inline app/services/update_remote_profile_service.rb]: Afaik, "If not [thing]" is better as "unless [thing]", but if the thing is a more complex boolean operation, "if" is preferred.
