### PR TITLE
Fix processing of mentions for post edits with an existing corresponding silent mention

### LINKED ISSUE #33208: Toot edit appears to fail due to invalid mention
## Description

At least on a few toots (not every toot) I'm experiencing a bug where I try to edit the toot, Mastodon shows an error,  `422 Mention is invalid`. Despite the visible error, the edit DOES go through, but mentions on the toot lose their special highlighting.

As far as I can tell, these should be valid mentions.

Image

## Reproduce steps

1. Edit the toot by adding a period at the end or something and hit save.
2. Mastodon shows "422 Mention is invalid".
3. Any mentions in the toot that were previously highlighted will now lose their highlight. If this is a reply toot, the Mastodon UI will now show in plain text the mention of the person you're replying to (it normally hides this).

If you refresh the page, your toot will show your new update. So, it actually didn't lose your edit. But, the mentions are still broken.

Experienced on FOSStodon.org, server version `4.3.2`.

## Examples

💡  It may be of note that the 2 examples I have below are mentions of Mastodon servers that are on subdomains. My "counter example" further down where the edit works, mentions servers that are not on a subdomain.

### 1. https://fosstodon.org/@chris_hayes/113601188329843140

I cannot edit this toot without Mastodon claiming the mention to be invalid. As you can see in the toot, the mention is not highlighted.

Both FOSStodon.org and the server of the user mentioned (mastodon.gamedev.place) are on `4.3.2`.

**Network request details:**

❌ PUT 422

**Request payload**

```json
{
  "status": "@GameDeveloperDotCom@mastodon.gamedev.place Kind of funny they had to clarify this, but I can appreciate when you're explaining technical topics in non-technical terms, sometimes you have to talk like this.",
  "in_reply_to_id": "113601048795197020",
  "media_ids": [
    "113601183876992602"
  ],
  "media_attributes": [
    {
      "id": "113601183876992602",
      "description": "Highlighted text from a document about multiplayer video games, stating: 'Computer systems have relied on players to specifically input the actual voice message and/or the typed message ... because computers are unable to read players' minds to determine what the players want to say to each other."
    }
  ],
  "sensitive": false,
  "spoiler_text": "",
  "visibility": "unlisted",
  "poll": null,
  "language": "en"
}
```

**Response payload**

```json
{"error":"Validation failed: Mentions is invalid"}
```

### 2. https://fosstodon.org/@chris_hayes/113601138476058347

Same issue but with a mention of a user from a different server (peertube.kaleidos.net).

**Network request details**

❌  PUT 422

**Request payload**

```json
{
  "status": "@penpot_app@peertube.kaleidos.net Is the thumbnail right? January 29, 2024 at 3 PM UTC",
  "in_reply_to_id": "113600977448739941",
  "media_ids": [],
  "media_attributes": [],
  "sensitive": false,
  "spoiler_text": "",
  "visibility": "unlisted",
  "poll": null,
  "language": "en"
}
```

**Response payload**

```json
{
  "error": "Validation failed: Mentions is invalid"
}
```

## Counter examples

✅  This edit worked fine without any errors and the mentions also highlight correctly.

### 1. https://fosstodon.org/@chris_hayes/113595569877203984

Request payload

```json
{
  "status": "@jencmars@mastodon.art @KeithAmmann@dice.camp Ooh, very cool. Out of curiosity - any specific reason for using a blue pencil? I've seen that in 2d animation in combination with red, but I'm not that familiar with illustrator tools.",
  "in_reply_to_id": "113595546472505158",
  "media_ids": [],
  "media_attributes": [],
  "sensitive": false,
  "spoiler_text": "",
  "visibility": "unlisted",
  "poll": null,
  "language": "en"
}
```

Response payload

```json
{
  "id": "113595569877203984",
  "created_at": "2024-12-04T16:47:19.191Z",
  "in_reply_to_id": "113595546472505158",
  "in_reply_to_account_id": "109246683751549830",
  "sensitive": false,
  "spoiler_text": "",
  "visibility": "unlisted",
  "language": "en",
  "uri": "https://fosstodon.org/users/chris_hayes/statuses/113595569877203984",
  "url": "https://fosstodon.org/@chris_hayes/113595569877203984",
  "replies_count": 1,
  "reblogs_count": 0,
  "favourites_count": 0,
  "edited_at": "2024-12-06T22:53:15.171Z",
  "favourited": false,
  "reblogged": false,
  "muted": false,
  "bookmarked": false,
  "pinned": false,
  "content": "<p><span class=\"h-card\" translate=\"no\"><a href=\"https://mastodon.art/@jencmars\" class=\"u-url mention\">@<span>jencmars</span></a></span> <span class=\"h-card\" translate=\"no\"><a href=\"https://dice.camp/@KeithAmmann\" class=\"u-url mention\">@<span>KeithAmmann</span></a></span> Ooh, very cool. Out of curiosity - any specific reason for using a blue pencil? I&#39;ve seen that in 2d animation in combination with red, but I&#39;m not that familiar with illustrator tools.</p>",
  "filtered": [],
  "reblog": null,
  "application": {
    "name": "Elk",
    "website": "https://elk.zone"
  },
  "account": {
    "id": "109260516197188241",
    "username": "chris_hayes",
    "acct": "chris_hayes",
    "display_name": "Chris​‌​‬ Hayes‌​​​",
    "locked": false,
    "bot": false,
    "discoverable": true,
    "indexable": true,
    "group": false,
    "created_at": "2022-10-31T00:00:00.000Z",
    "note": "<p>👨‍💻 Creative Frontend Developer</p><p>🪄 The web needs more whimsy<br />🏠 <a href=\"https://fosstodon.org/tags/Connecticut\" class=\"mention hashtag\" rel=\"tag\">#<span>Connecticut</span></a>, USA</p><p>🔥 I post <a href=\"https://fosstodon.org/tags/foss\" class=\"mention hashtag\" rel=\"tag\">#<span>foss</span></a>, <a href=\"https://fosstodon.org/tags/webdev\" class=\"mention hashtag\" rel=\"tag\">#<span>webdev</span></a>, <a href=\"https://fosstodon.org/tags/ai\" class=\"mention hashtag\" rel=\"tag\">#<span>ai</span></a>, <a href=\"https://fosstodon.org/tags/design\" class=\"mention hashtag\" rel=\"tag\">#<span>design</span></a>, <a href=\"https://fosstodon.org/tags/space\" class=\"mention hashtag\" rel=\"tag\">#<span>space</span></a><br />Will ⭐ toots with rats, corvids, ants</p><p>♻️❤️🌎 - 🇺🇸🤝🇺🇦</p>",
    "url": "https://fosstodon.org/@chris_hayes",
    "uri": "https://fosstodon.org/users/chris_hayes",
    "avatar": "https://cdn.fosstodon.org/accounts/avatars/109/260/516/197/188/241/original/1102267ae3078e60.png",
    "avatar_static": "https://cdn.fosstodon.org/accounts/avatars/109/260/516/197/188/241/original/1102267ae3078e60.png",
    "header": "https://cdn.fosstodon.org/accounts/headers/109/260/516/197/188/241/original/b36b3e77ce0396df.png",
    "header_static": "https://cdn.fosstodon.org/accounts/headers/109/260/516/197/188/241/original/b36b3e77ce0396df.png",
    "followers_count": 294,
    "following_count": 687,
    "statuses_count": 3242,
    "last_status_at": "2024-12-06",
    "hide_collections": false,
    "noindex": false,
    "emojis": [],
    "roles": [
      {
        "id": "8",
        "name": "Supporter 💰♥️",
        "color": "#4f7a28"
      }
    ],
    "fields": [
      {
        "name": "Blog",
        "value": "<a href=\"https://hayes.software\" target=\"_blank\" rel=\"nofollow noopener noreferrer me\" translate=\"no\"><span class=\"invisible\">https://</span><span class=\"\">hayes.software</span><span class=\"invisible\"></span></a>",
        "verified_at": "2022-11-24T05:43:11.167+00:00"
      },
      {
        "name": "GitHub",
        "value": "<a href=\"https://github.com/christopher-hayes\" target=\"_blank\" rel=\"nofollow noopener noreferrer me\" translate=\"no\"><span class=\"invisible\">https://</span><span class=\"\">github.com/christopher-hayes</span><span class=\"invisible\"></span></a>",
        "verified_at": "2022-11-22T17:23:43.140+00:00"
      },
      {
        "name": "Pronouns",
        "value": "He/Him",
        "verified_at": null
      }
    ]
  },
  "media_attachments": [],
  "mentions": [
    {
      "id": "109246683751549830",
      "username": "jencmars",
      "url": "https://mastodon.art/@jencmars",
      "acct": "jencmars@mastodon.art"
    },
    {
      "id": "108195503596938380",
      "username": "KeithAmmann",
      "url": "https://dice.camp/@KeithAmmann",
      "acct": "KeithAmmann@dice.camp"
    }
  ],
  "tags": [],
  "emojis": [],
  "card": null,
  "poll": null
}
```

---

_Originally posted by @Christopher-Hayes in https://github.com/mastodon/mastodon/issues/33161#issuecomment-2520908927_

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #33208

### CODE REVIEW

File: spec/services/activitypub/process_status_update_service_spec.rb [hunk 1]
```diff
@@ -26,13 +26,14 @@
 
   let(:alice) { Fabricate(:account) }
   let(:bob) { Fabricate(:account) }
+  let(:eve) { Fabricate(:account) }
```
Comment (oneiros) [inline spec/services/activitypub/process_status_update_service_spec.rb:29]: Is this used anywhere?

**Review by oneiros — COMMENTED** [review]
I think this solves the issue rather nicely.

I do wonder though: There is some overlap between local and remote posts here. Implementing this logic twice means there is always a risk of those implementations to get out of sync at some point. It is not at all obvious to me how, but I still wonder if this could be extracted somehow so both cases always work the same way.

File: spec/services/activitypub/process_status_update_service_spec.rb (hunk 1 above)
Comment (ClearlyClaire) [reply spec/services/activitypub/process_status_update_service_spec.rb]: Apparently not. I'm surprised this didn't get caught by any of our linters.

**Comment by ClearlyClaire** [comment]
> I do wonder though: There is some overlap between local and remote posts here. Implementing this logic twice means there is always a risk of those implementations to get out of sync at some point. It is not at all obvious to me how, but I still wonder if this could be extracted somehow so both cases always work the same way.

I hear you, though I'm not sure how this can be improved either. There's common logic but there's also quite a bit that is different: parsing mentions, rewriting text, deciding when to commit the changes…

File: spec/services/activitypub/process_status_update_service_spec.rb (hunk 1 above)
Comment (oneiros) [reply spec/services/activitypub/process_status_update_service_spec.rb]: Me too. Pretty sure rubocop yelled at me before because of a similar situation :man_shrugging:

**Review by oneiros — APPROVED** [review]
