### PR TITLE
Fix race condition in `POST /api/v1/push/subscription`

### LINKED ISSUE #30103: API to subscribe to push notification does not seem to delete previous subscription?
### Steps to reproduce the problem

1.  [POST `/api/v1/push/subscription`](https://docs.joinmastodon.org/methods/push/#create) many times. (Not sure if many times in a short time matters though, just stating based on what I (accidentally) did)
2. Send a post via another account, tagging the logged in user.
3. Wait for notification to arrive
4. Realised that tons of notifications came flooding in, only one decoded correctly (non unexpected, since my app only saved the latest keys)

### Expected behaviour

1 notification with correct contents.

### Actual behaviour

hundreds? of notifications.

### Detailed description

Now, I am not entirely sure if the fault is on my end, but I am somewhat confident that it is the API's fault. Please advise if I'm doing something terribly wrong without noticing 😅

I am referring to the [POST `/api/v1/push/subscription`](https://docs.joinmastodon.org/methods/push/#create) endpoint.
So the story here is that, new (unreleased) app here, where a bug occurred, which resulted in an endless loop, causing the app to accidentally send out many requests.

I realised this probably after like 2 seconds, shut the app down, fixed the issue, and relaunched the app.

I sent a post out using another account, tagging my app's logged in account, the rest is explained in the steps to reproduce section.

The documentation for that, states: 

>  If you create a new subscription, the old subscription is deleted.

In this case, it didn't seem to be true? Eventually, I also tried calling [DELETE `/api/v1/push/subscription`](https://docs.joinmastodon.org/methods/push/#delete), but symptoms remains.

My setup is for a watchOS app. Notifications are relayed using [metatext-apns](https://github.com/metabolist/metatext-apns), which by the looks of it is just a simple relay so that shouldn't be the cause, right?

 I am very new to this Mastodon/Web Push notifications stuff, so please let me know if you believe it's an issue from my end. Thank you!

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-nightly.2024-04-18

### Technical details

- watchOS 10.2
- Both accounts are on mastodon.social

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #30103

Ideally, we probably would have a unique constraint at the database level. However, I decided to leave that out for now because:
- it is unclear how we should treat existing duplicates: if there are duplicate registrations for an authentication token, we don't know which the application is actually able to process, so deduplicating may break existing legitimate notifications (those are very unlikely though)
- I haven't dug into `/api/web/push_subscriptions` which has no deduplication logic whatsoever, so I'm not completely sure the uniqueness constraint is something we always want

### CODE REVIEW

File: app/controllers/api/v1/push/subscriptions_controller.rb [hunk 1]
```diff
@@ -1,26 +1,31 @@
 # frozen_string_literal: true
 
 class Api::V1::Push::SubscriptionsController < Api::BaseController
+  include Redisable
+  include Lockable
+
   before_action -> { doorkeeper_authorize! :push }
   before_action :require_user!
-  before_action :set_push_subscription
+  before_action :set_push_subscription, only: [:show, :update]
```
Comment (mjankowski) [inline app/controllers/api/v1/push/subscriptions_controller.rb:9]: Ignorable style advice: wrap this line and one below it in `with_options only: ...` block

File: app/controllers/api/v1/push/subscriptions_controller.rb [hunk 2]
```diff
@@ -1,26 +1,31 @@
...
-      key_auth: subscription_params[:keys][:auth],
-      data: data_params,
-      user_id: current_user.id,
-      access_token_id: doorkeeper_token.id
-    )
+    with_redis_lock("push_subscription:#{current_user.id}") do
+      Web::PushSubscription.where(access_token_id: doorkeeper_token.id).destroy_all
+
+      @push_subscription = Web::PushSubscription.create!(
+        endpoint: subscription_params[:endpoint],
```
Comment (mjankowski) [inline app/controllers/api/v1/push/subscriptions_controller.rb:21]: Ignorable style advice: pull out this whole hash into a `web_push_subscription_params` method or something.

File: app/controllers/api/v1/push/subscriptions_controller.rb [hunk 3]
```diff
@@ -1,26 +1,31 @@
...
-    @push_subscription = Web::PushSubscription.create!(
-      endpoint: subscription_params[:endpoint],
-      key_p256dh: subscription_params[:keys][:p256dh],
-      key_auth: subscription_params[:keys][:auth],
-      data: data_params,
-      user_id: current_user.id,
-      access_token_id: doorkeeper_token.id
-    )
+    with_redis_lock("push_subscription:#{current_user.id}") do
+      Web::PushSubscription.where(access_token_id: doorkeeper_token.id).destroy_all
```
Comment (mjankowski) [inline app/controllers/api/v1/push/subscriptions_controller.rb:18]: Ignorable style advice:

- I believe there's a model which the doorkeeper token class includes ... could add an association there to be able to use `doorkeeper_token.web_push_subscriptions....` here.
- Pull out `destroy_previous_web_push_subscriptions` private method and call it from here and from the destroy action below.

**Review by mjankowski — APPROVED** [review]
Left small style ideas, looks good overall. Agree with the inclination to handle this way for now and review adding unique index after more review.

**Review by renchap — DISMISSED** [review]

**Review by renchap — APPROVED** [review]
