### PR TITLE
Change local media attachments to perform heavy processing asynchronously

### LINKED ISSUE #9106: Video processing for media uploads happens in the req/res cycle, and not in background
Nginx's current stable version does not have support for modifying an upstream keepalive timeout. Nginx is currently the recommended way to proxy for mastodon. My server is too slow to process the video in under 1 minute, even for webms as small as 2.4 MB, so I effectively cannot upload webms.

### Expected behaviour
Video processing happens in the background.

### Actual behaviour
Video processing happens during the request response cycle.

### Steps to reproduce the problem
 - run mastodon
 - upload webm

### Specifications
version 2.5.2

### PR DESCRIPTION
**Pull request by Gargron**
Fix #9106

Introduces REST API endpoints:

- `POST /api/v2/media`, which is equal to v1 in all except it returns HTTP 202, and the returned JSON object has a `url` of `null`, because while the thumbnail is prepared synchronously, the full version of the media attachment will be processed in the background
- `GET /api/v1/media/:id`, which returns the JSON for a given media attachment, as long as it is not yet attached and belongs to the user. The endpoint returns HTTP 200 when the attachment has been processed and `url` is ready, HTTP 206 while it is not ready and `url` is `null`, and HTTP 422 if there was an error processing the media attachment

The same HTTP code semantics are added to `PUT /api/v1/media/:id`, but as long as clients use it together with the v1 version of the upload, it will return HTTP 200.

When trying to create a status with media attachments that have not finished processing, or failed processing, an error will be returned.

The web UI will simply continue displaying the uploading loading bar until the media attachments have finished processing (or fail).

I would label this PR with "Performance", because the asynchronous approach frees up web workers to serve more HTTP requests and thus minimizes a DoS vector, however, I cannot while the v1 version of the endpoint is kept for backwards compatibility.

### CODE REVIEW

File: app/workers/post_process_media_worker.rb [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+  include Sidekiq::Worker
+
+  def perform(media_attachment_id)
+    media_attachment = MediaAttachment.find(media_attachment_id)
+    media_attachment.processing = :in_progress
+    media_attachment.save
+    media_attachment.file.reprocess!
+    media_attachment.processing = :complete
+    media_attachment.save
+  rescue Paperclip::Error
```
Comment (ThibG) [inline app/workers/post_process_media_worker.rb]: I wonder if there are possibly other exceptions we might run into. Also it may make sense to log *why* processing failed somewhere.

File: app/workers/post_process_media_worker.rb [hunk 2]
```diff
@@ -0,0 +1,19 @@
+# frozen_string_literal: true
+
+class PostProcessMediaWorker
+  include Sidekiq::Worker
+
+  def perform(media_attachment_id)
+    media_attachment = MediaAttachment.find(media_attachment_id)
+    media_attachment.processing = :in_progress
+    media_attachment.save
+    media_attachment.file.reprocess!
```
Comment (ThibG) [inline app/workers/post_process_media_worker.rb]: Does that mean the thumbnail will be re-processed?

**Review by ClearlyClaire — COMMENTED** [review]
Overall the approach seems ok, but it's still lacking something for the clients to know right away when some media is ready, and not only for sending the toot, but also for the focus point & media description dialog.

File: app/workers/post_process_media_worker.rb (hunk 1 above)
Comment (Gargron) [reply app/workers/post_process_media_worker.rb]: Validation happens in the request/response cycle, so there should be very little unexpected here. Errors that wouldn't fit under Paperclip::Error that I can think of would be disk-related (not writeable, directory doesn't exist) or network related (S3 timeout)

If you mean logging to the Rails log, I'm for it, but I wouldn't go to saving the exception in a special column, I think that would be overkill and not really useful.

The question is do we bother to retry these on failures? I think most such failures would likely not recover within seconds, and that means it's already keeping the end-user waiting too long, so maybe best to communicate failure to the UI somehow.

File: app/workers/post_process_media_worker.rb (hunk 2 above)
Comment (Gargron) [reply app/workers/post_process_media_worker.rb]: Yeah, I think I could limit it but maybe it's not a big deal. I'll look into it

**Comment by Gargron** [comment]
Yeah, communication to the UI is not done yet. I'm thinking we probably can't use streaming API for this because that's not very mobile-friendly (in terms of 3rd party apps). Polling an endpoint that returns the attachment is probably a better path, but that means a new endpoint (`GET /api/v1/media/:id`?).

File: app/workers/post_process_media_worker.rb (hunk 1 above)
Comment (Gargron) [reply app/workers/post_process_media_worker.rb]: Actually one thing to watch out for is that case when a converted file is bigger than the uploaded one. I don't think it happens too much with media attachments though, it's mostly when a GIF is converted to GIF, on avatars and headers. A video should never be bigger than a GIF to the point of exceeding the limit, I think...

File: app/models/concerns/attachmentable.rb [hunk 3]
```diff
@@ -74,7 +74,7 @@ def obfuscate_file_name
     self.class.attachment_definitions.each_key do |attachment_name|
       attachment = send(attachment_name)
 
-      next if attachment.blank? || attachment.queued_for_write[:original].blank?
+      next if attachment.blank? || attachment.queued_for_write[:original].blank? || attachment.options[:preserve_files]
```
Comment (ThibG) [inline app/models/concerns/attachmentable.rb]: How does the `preserve_files` thing work?

File: app/workers/backup_worker.rb [hunk 4]
```diff
@@ -9,8 +9,12 @@ class BackupWorker
...
 
     ActiveRecord::Base.connection_pool.with_connection do
-      backup = Backup.find(backup_id)
-      backup&.destroy
+      begin
+        backup = Backup.find(backup_id)
+        backup.destroy
+      rescue ActiveRecord::RecordNotFound
+        true
+      end
```
Comment (ThibG) [inline app/workers/backup_worker.rb]: Is this related to this PR? :thinking:

**Review by ClearlyClaire — APPROVED** [review]
Apart from the few inlined questions and my worry that it just moves the problem a bit, this looks fine to me.
I guess it should see some testing in a real environment.
A worry I have is that it may introduce additional delay between upload and processing for the majority of cases using the new API.

File: app/workers/backup_worker.rb (hunk 4 above)
Comment (Gargron) [reply app/workers/backup_worker.rb]: No, but there was no point doing `backup&.destroy` after `find` because `find` raises an error.

File: app/models/concerns/attachmentable.rb (hunk 3 above)
Comment (Gargron) [reply app/models/concerns/attachmentable.rb]: `preserve_files` is set to `true` when `reprocess!` is called. It is not set in any other case. So it is a good signal for when we don't want to rename files. But it's actually a little problematic because I think it could leave the previous file around if the format (and extension) changes, and I plan on solving that before the PR is merged.

Comment (Gargron) [reply app/models/concerns/attachmentable.rb]: Here is a comment from the `reprocess!` method:

> NOTE: Calling reprocess WILL NOT delete existing files. This is due to
> inconsistencies in timing of S3 commands. It's possible that calling
> #reprocess! will lose data if the files are not kept.

If the output filename is the same (such as when the file extension does not change), the file will be overwritten, and that's fine. I just need to add a special case when the `:original` file name changes and cause it to be deleted afterwards somehow.

Comment (Gargron) [reply app/models/concerns/attachmentable.rb]: In the commit https://github.com/thoughtbot/paperclip/commit/5a06d85097c325905cd16b13c04d1d3e9d7ec0d9, it describes the problem as:

> Apparently, Amazon can not guarantee that PUT's called after DELETE's
is actually executed in that order.

In the case where we want to delete a file with a different extension, I think that doesn't matter, so should be fine to make it do that.
