### PR TITLE
Fix deletes not being signed in authorized fetch mode

### LINKED ISSUE #17483: `Delete`s are not signed when using AUTHORIZED_FETCH
### Steps to reproduce the problem

1. set `AUTHORIZED_FETCH=true`
2. delete a public toot

### Expected behaviour

The `Delete` activity should be signed.
Since Mastodon does not record which servers/actors accessed each individual toot, delivering `Delete` activities relies in part on forwarding by remote servers who `Announe`d it, which requires the `Delete` activity to be signed.

### Actual behaviour

The `Delete` activity isn't signed.

### Specifications

Any version with support for `AUTHORIZED_FETCH`.

### PR DESCRIPTION
**Pull request by Gargron**
Fix #17483

### CODE REVIEW

File: app/services/remove_status_service.rb [hunk 1]
```diff
@@ -95,7 +95,7 @@ def remove_from_remote_reach
   end
 
   def signed_activity_json
-    @signed_activity_json ||= Oj.dump(serialize_payload(@status, @status.reblog? ? ActivityPub::UndoAnnounceSerializer : ActivityPub::DeleteSerializer, signer: @account))
+    @signed_activity_json ||= Oj.dump(serialize_payload(@status, @status.reblog? ? ActivityPub::UndoAnnounceSerializer : ActivityPub::DeleteSerializer, signer: @account, always_sign: true))
```
Comment (ClearlyClaire) [inline app/services/remove_status_service.rb:98]: Need to check the status isn't inlined in either `Undo { Announce }` nor `Delete { Status }`. I think `Undo { Announce }` could leak the status on self-boosts.

Comment (ClearlyClaire) [reply app/services/remove_status_service.rb:98]: Since `always_sign` does not override `Status#sign?`, this is safe, and private self-unboosts would not get signed, but private self-unboosts do indeed include the original status, addressed in #17516

**Review by ClearlyClaire — APPROVED** [review]

File: app/services/concerns/payloadable.rb [hunk 2]
```diff
@@ -1,13 +1,21 @@
 # frozen_string_literal: true
 
 module Payloadable
+  # @param [ActiveModelSerializers::Model] record
+  # @param [ActiveModelSerializers::Serializer] serializer
+  # @param [Hash] options
+  # @option options [Account] :signer
+  # @option options [String] :sign_with
+  # @option options [Boolean] :always_sign
```
Comment (ClearlyClaire) [inline app/services/concerns/payloadable.rb:9]: Maybe describe what `always_sign` actually does. “Sign even when `AUTHORIZED_FETCH` is set” or something like that
