### PR TITLE
Select correct self link when parsing Webfinger response

### LINKED ISSUE #31084: Mastodon rejects multiple rel=self links in webfinger, breaching webfinger spec
### Steps to reproduce the problem

1. implement webfinger endpoint with multiple ``rel: self`` entries in the ``links`` array, but using different ``type``s (example: application/json & application/activity+json)
2. query it using mastodon (for example @aprl@social.lysand.org), see that the user isnt resolved
3. query webfinger yourself, and see that there are multiple rel tags indeed (for example: https://social.lysand.org/.well-known/webfinger?resource=acct:aprl@social.lysand.org )

### Expected behaviour

Mastodon picks rel=self with type=application/activity+json

### Actual behaviour

mastodon shits itself

### Detailed description

This is valid, in spec webfinger, and thus every other fedi server for example akkoma and misskey support such webfinger, but mastodon discards it as invalid for some reason. I did not find the place in code yet but this issue has been around for a long time but never got fixed. Afaik this breaches webfinger spec because the spec never mentions there only being one rel=self tag. it instead should scan for a rel=self & type=application/activity+json tag

### Mastodon instance

any

### Mastodon version

v4.2.10

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)

### PR DESCRIPTION
**Pull request by adamniedzielski**
Fixes #31084

### CODE REVIEW

File: app/lib/webfinger.rb [hunk 1]
```diff
@@ -6,6 +6,7 @@ class GoneError < Error; end
   class RedirectError < Error; end
 
   class Response
+    ACIVITYPUB_READY_TYPE = ['application/activity+json', 'application/ld+json; profile="https://www.w3.org/ns/activitystreams"'].freeze
```
Comment (oneiros) [inline app/lib/webfinger.rb:9]: I think this should be `ACTIVITYPUB_READY_TYPE` (a `T` is missing).

And while I am nitpicking :slightly_smiling_face: : You might want to add a newline to separate the constant from the `attr_reader` below.

File: app/lib/webfinger.rb [hunk 2]
```diff
@@ -20,17 +21,28 @@ def subject
     end
 
     def link(rel, attribute)
-      links.dig(rel, attribute)
+      links.dig(rel, 0, attribute)
+    end
```
Comment (oneiros) [inline app/lib/webfinger.rb:25]: I like how you reworked the method to still work as it did before. But did you check if it is actually used anymore?

I only had a cursory glance, but I think it might not be needed anymore.

File: app/services/resolve_account_service.rb [hunk 3]
```diff
@@ -106,8 +106,6 @@ def split_acct(acct)
   end
 
   def fetch_account!
-    return unless activitypub_ready?
```
Comment (oneiros) [inline app/services/resolve_account_service.rb:109]: Just to be sure: You removed this because `Webfinger#validate_response!` will now raise if that is not the case. Right?

**Review by oneiros — CHANGES_REQUESTED** [review]
Thanks a lot for this contribution. I left some tiny remarks, but overall this is already looking pretty good.

What do you think about adding a couple of small tests for `app/lib/webfinger.rb` specifcally? I think it would be nice to have at least 3 examples, one showing that `application/activity+json` works, one showing that `application/ld+json; profile="https://www.w3.org/ns/activitystreams"` works as well and one that demonstrates the error raised when a completely unrelated type is used.

(And for future reference: The original issue was already assigned to me. If an issue is assigned this might mean someone is already working on this. Asking if help would be welcome, can help prevent developer time being wasted in these cases. Yours or mine :wink:)

File: app/lib/webfinger.rb (hunk 2 above)
Comment (adamniedzielski) [reply app/lib/webfinger.rb:25]: It's used in just one place - https://github.com/mastodon/mastodon/blob/a8330be93ee825948a17c810af33e28bfa2c56c8/app/models/remote_follow.rb#L65

**Comment by adamniedzielski** [comment]
> (And for future reference: The original issue was already assigned to me. If an issue is assigned this might mean someone is already working on this. Asking if help would be welcome, can help prevent developer time being wasted in these cases. Yours or mine 😉)

Sorry for that! I assumed that it's going to be some time before you start looking into the issue.

File: app/lib/webfinger.rb (hunk 2 above)
Comment (oneiros) [reply app/lib/webfinger.rb:26]: Ah, good catch. Thanks!

File: app/services/resolve_account_service.rb (hunk 3 above)
Comment (oneiros) [reply app/services/resolve_account_service.rb:109]: Brilliant, thanks!

**Review by oneiros — APPROVED** [review]

**Comment by oneiros** [comment]
>> (And for future reference: The original issue was already assigned to me. If an issue is assigned this might mean someone is already working on this. Asking if help would be welcome, can help prevent developer time being wasted in these cases. Yours or mine 😉)
>
> Sorry for that! I assumed that it's going to be some time before you start looking into the issue.

No harm was done in this case as I had not yet written any code. One could say the opposite is true: Already being on to this put me in the unique position to review this quickly :slightly_smiling_face: 

Just something to keep in mind for the future.

Thanks again for your help!

**Review by ClearlyClaire — APPROVED** [review]
This looks good to me.

This might possibly break compatibility with some ActivityPub software, but I have found no actual example of this. Furthermore, we were already checking the `type` in one of the codepaths, so compatibility would have already been rocky before this change.

**Comment by adamniedzielski** [comment]
Thank you for your quick reviews @oneiros and @ClearlyClaire 💛
