### PR TITLE
Fix synchronous recursive fetching of deeply-nested quoted posts

### LINKED ISSUE #35572: Fetching deeply-nested quote posts crashes with `SystemStackError`
### Steps to reproduce the problem

Primary Issue: Paperclip Image Processing Loop
```
lib/paperclip/vips_lazy_thumbnail.rb:100:in 'Paperclip::LazyThumbnail#transformed_image'
lib/paperclip/vips_lazy_thumbnail.rb:68:in 'Paperclip::LazyThumbnail#make'
app/models/concerns/remotable.rb:27:in 'MediaAttachment#remotable_attachment'
```

Secondary Issue: ActivityPub Quote Processing Loop
```
app/lib/activitypub/activity/create.rb:209:in 'ActivityPub::Activity::Create#attach_quote'
app/services/activitypub/verify_quote_service.rb:12:in 'ActivityPub::VerifyQuoteService#call'
app/services/activitypub/fetch_remote_status_service.rb:55:in 'ActivityPub::FetchRemoteStatusService#call'
app/lib/activitypub/activity/create.rb:25:in 'ActivityPub::Activity::Create#create_status'
```

Crash: Last line in log
```
INFO -- : Command :: ffmpeg -nostdin -ss '0' -i '/tmp/58feccb35433f95717b3489986244cc920250727-7-h6ck47.mp4' -loglevel 'fatal' -vf 'scale='\''min(640\, iw):min(640\, ih)'\'':force_original_aspect_ratio=decrease' -f 'image2' -vframes '1' -y '/tmp/58feccb35433f95717b3489986244cc920250727-7-h6ck4720250727-7-52n6sj.png'
```

### Expected behaviour

Fail or Process

### Actual behaviour

Recursion loop

### Detailed description

The following error caused a loop on Sidekiq:
```
WARN: SystemStackError: stack level too deep
WARN: lib/paperclip/vips_lazy_thumbnail.rb:100:in 'Paperclip::LazyThumbnail#transformed_image'
lib/paperclip/vips_lazy_thumbnail.rb:68:in 'Paperclip::LazyThumbnail#make'
lib/paperclip/attachment_extensions.rb:21:in 'block in Paperclip::AttachmentExtensions#post_process_style'
lib/paperclip/attachment_extensions.rb:20:in 'Array#each'
lib/paperclip/attachment_extensions.rb:20:in 'Enumerable#inject'
lib/paperclip/attachment_extensions.rb:20:in 'Paperclip::AttachmentExtensions#post_process_style'
app/models/concerns/remotable.rb:27:in 'Kernel#public_send'
app/models/concerns/remotable.rb:27:in 'block (2 levels) in MediaAttachment#remotable_attachment'
app/lib/request.rb:122:in 'Request#perform'
app/models/concerns/remotable.rb:24:in 'block in MediaAttachment#remotable_attachment'
app/lib/activitypub/activity/create.rb:304:in 'block in ActivityPub::Activity::Create#process_attachments'
app/lib/activitypub/activity/create.rb:285:in 'Array#each'
app/lib/activitypub/activity/create.rb:285:in 'ActivityPub::Activity::Create#process_attachments'
app/lib/activitypub/activity/create.rb:93:in 'ActivityPub::Activity::Create#process_status_params'
app/lib/activitypub/activity/create.rb:51:in 'ActivityPub::Activity::Create#process_status'
app/lib/activitypub/activity/create.rb:25:in 'block in ActivityPub::Activity::Create#create_status'
app/models/concerns/lockable.rb:12:in 'block (2 levels) in Lockable#with_redis_lock'
app/models/concerns/lockable.rb:10:in 'block in Lockable#with_redis_lock'
```
After that, I see the following lines repeating many, many times:
```
app/lib/redis_connection.rb:10:in 'RedisConnection.with'
app/models/concerns/redisable.rb:9:in 'Redisable#with_redis'
app/models/concerns/lockable.rb:9:in 'Lockable#with_redis_lock'
app/lib/activitypub/activity/create.rb:19:in 'ActivityPub::Activity::Create#create_status'
app/lib/activitypub/activity/create.rb:11:in 'ActivityPub::Activity::Create#perform'
app/services/activitypub/fetch_remote_status_service.rb:55:in 'ActivityPub::FetchRemoteStatusService#call'
app/services/activitypub/verify_quote_service.rb:75:in 'ActivityPub::VerifyQuoteService#fetch_quoted_post_if_needed!'
app/services/activitypub/verify_quote_service.rb:12:in 'ActivityPub::VerifyQuoteService#call'
app/lib/activitypub/activity/create.rb:209:in 'ActivityPub::Activity::Create#attach_quote'
app/lib/activitypub/activity/create.rb:61:in 'block in ActivityPub::Activity::Create#process_status'
app/lib/activitypub/activity/create.rb:56:in 'ActivityPub::Activity::Create#process_status'
app/lib/activitypub/activity/create.rb:25:in 'block in ActivityPub::Activity::Create#create_status'
app/models/concerns/lockable.rb:12:in 'block (2 levels) in Lockable#with_redis_lock'
app/models/concerns/lockable.rb:10:in 'block in Lockable#with_redis_lock'
```
Until it ends all processing after:
```
app/lib/activitypub/activity/announce.rb:8:in 'ActivityPub::Activity::Announce#perform'
app/services/activitypub/process_collection_service.rb:69:in 'ActivityPub::ProcessCollectionService#process_item'
app/services/activitypub/process_collection_service.rb:60:in 'block in ActivityPub::ProcessCollectionService#process_items'
app/services/activitypub/process_collection_service.rb:60:in 'Array#reverse_each'
app/services/activitypub/process_collection_service.rb:60:in 'Enumerator#each'
app/services/activitypub/process_collection_service.rb:60:in 'Enumerable#filter_map'
app/services/activitypub/process_collection_service.rb:60:in 'ActivityPub::ProcessCollectionService#process_items'
app/services/activitypub/process_collection_service.rb:39:in 'ActivityPub::ProcessCollectionService#call'
app/workers/activitypub/processing_worker.rb:16:in 'ActivityPub::ProcessingWorker#perform'
lib/mastodon/sidekiq_middleware.rb:8:in 'block in Mastodon::SidekiqMiddleware#call'
lib/mastodon/sidekiq_middleware.rb:73:in 'Mastodon::SidekiqMiddleware#setup_query_log_tags'
lib/mastodon/sidekiq_middleware.rb:7:in 'Mastodon::SidekiqMiddleware#call'
2025-07-27T07:45:22.705Z pid=7 tid=2gzdmv class=ActivityPub::ProcessingWorker jid=adb2a983f93f96ff84bb7023 INFO: start
2025-07-27T07:45:22.928Z pid=7 tid=2gzx9b class=LinkCrawlWorker jid=1a737b3dce815b54ecec3c6f INFO: start
...
2025-07-27T07:45:23.188Z pid=7 tid=2gzdmv class=ActivityPub::ProcessingWorker jid=adb2a983f93f96ff84bb7023 elapsed=0.483 INFO: done
...
I, [2025-07-27T07:45:23.414090 #7]  INFO -- : [paperclip] Trying to link /tmp/c76621e9870a0303da80223ab0f5a83220250727-7-g7heym.getB to /tmp/88f52d3b5a7debc0081549063a6a936b20250727-7-d12qh4.mp4
I, [2025-07-27T07:45:23.414371 #7]  INFO -- : Command :: file -b --mime '/tmp/88f52d3b5a7debc0081549063a6a936b20250727-7-d12qh4.mp4'
2025-07-27T07:45:23.481Z pid=7 tid=2h3v6f class=ActivityPub::ProcessingWorker jid=8f8afe6cd962623f89889283 INFO: start
I, [2025-07-27T07:45:23.510573 #7]  INFO -- : Command :: ffmpeg -nostdin -i '/tmp/c76621e9870a0303da80223ab0f5a83220250727-7-g7heym.getB' -loglevel 'fatal' -map_metadata '-1' -movflags 'faststart' -c:v 'copy' -c:a 'copy' -y '/tmp/c76621e9870a0303da80223ab0f5a83220250727-7-g7heym20250727-7-wams65.mp4'
I, [2025-07-27T07:45:23.539914 #7]  INFO -- : [paperclip] Trying to link /tmp/c76621e9870a0303da80223ab0f5a83220250727-7-g7heym20250727-7-wams65.mp4 to /tmp/58feccb35433f95717b3489986244cc920250727-7-h6ck47.mp4
2025-07-27T07:45:23.546Z pid=7 tid=2h3v6f class=ActivityPub::ProcessingWorker jid=8f8afe6cd962623f89889283 elapsed=0.065 INFO: done
I, [2025-07-27T07:45:23.558106 #7]  INFO -- : Command :: ffmpeg -nostdin -ss '0' -i '/tmp/58feccb35433f95717b3489986244cc920250727-7-h6ck47.mp4' -loglevel 'fatal' -vf 'scale='\''min(640\, iw):min(640\, ih)'\'':force_original_aspect_ratio=decrease' -f 'image2' -vframes '1' -y '/tmp/58feccb35433f95717b3489986244cc920250727-7-h6ck4720250727-7-52n6sj.png'
```

I believe the `Paperclip::LazyThumbnail` error is related to VIPS and likely the source of Sidekiq getting stuck randomly, starting with version 4.3.0 and VIPS. I have noticed this in more than one instance.

Not sure if the fact that those instances use OpenStack Swift for object storage is related, but it's not a problem for all instances using OpenStack Swift, or at least it has only impacted a small number of those.

### Mastodon instance

Multiple

### Mastodon version

v4.4.2

### Technical details

- VIPS enabled
- OpenStack Swift Object Storage

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #35572

Like other resources, quote posts can be recursively fetched, and the depth is limited through the `request_id` mechanism.

However, unlike other resources, they are fetched synchronously, which is required for a good user experience, but drastically changes the nature of the recursion, and the global asynchronous recursion limit we use is far too high for synchronous recursion.

This commit introduces a synchronous recursion depth limit to only fetch a maximum of 2 nested quotes synchronously, leaving the rest to later jobs.

### CODE REVIEW

File: app/services/activitypub/verify_quote_service.rb [hunk 1]
```diff
@@ -72,10 +75,12 @@ def fetch_quoted_post_if_needed!(uri, prefetched_body: nil)
     return if uri.nil? || @quote.quoted_status.present?
 
     status = ActivityPub::TagManager.instance.uri_to_resource(uri, Status)
-    status ||= ActivityPub::FetchRemoteStatusService.new.call(uri, on_behalf_of: @quote.account.followers.local.first, prefetched_body:, request_id: @request_id)
+    raise Mastodon::RecursionLimitExceededError if @depth > MAX_SYNCHRONOUS_DEPTH
```
Comment (oneiros) [inline app/services/activitypub/verify_quote_service.rb]: Tiny thing, but I would probably move this up. No need to get the status if you are planning to raise anyway.

**Review by oneiros — DISMISSED** [review]

File: app/services/activitypub/verify_quote_service.rb (hunk 1 above)
Comment (ClearlyClaire) [reply app/services/activitypub/verify_quote_service.rb]: Oh, I actually wanted to raise only if the status wasn't known. I'll change that.

**Review by oneiros — APPROVED** [review]
