### PR TITLE
Fix wrong filters sometimes applying in streaming

### LINKED ISSUE #25952: Filtered posts but no filters set up
### Steps to reproduce the problem

Browsing the Local feed, saw a post behind a filter but I have no filters set up. 

### Expected behaviour

The post would be shown without the filter

### Actual behaviour

The post was shown behind a filter

### Detailed description

I don't have any filters set up, but a post appeared behind a filter in my feed that I had to click through to see the post. This was on mastodon.art on the Curator account, we're on 4.1.4.

### Specifications

Mastodon 4.1.4

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #25952

The streaming server code for filtering relied on mutating the payload, but since #25278, the payload object is now shared across multiple subscribers, meaning that one user's filters may affect another user.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
cc @ThisIsMissEm

File: streaming/index.js [hunk 1]
```diff
@@ -626,7 +626,7 @@ const startServer = async () => {
     const listener = message => {
       const { event, payload, queued_at } = message;
 
-      const transmit = () => {
+      const transmit = (payload) => {
```
Comment (renchap) [inline streaming/index.js:629]: I would not re-use the same `payload` name as it is already defined in the above scope, this is confusing (and `eslint` should complain about it?)

File: streaming/index.js [hunk 2]
```diff
@@ -733,27 +732,30 @@ const startServer = async () => {
...
-            const status = unpackedPayload;
+          if (req.cachedFilters && !payload.filtered) {
+            const mutatedPayload = { ...payload };
+            const status = payload;
             const searchContent = ([status.spoiler_text || '', status.content].concat((status.poll && status.poll.options) ? status.poll.options.map(option => option.title) : [])).concat(status.media_attachments.map(att => att.description)).join('\n\n').replace(/<br\s*\/?>/g, '\n').replace(/<\/p><p>/g, '\n\n');
             const searchIndex = JSDOM.fragment(searchContent).textContent;
 
             const now = new Date();
-            payload.filtered = [];
+            mutatedPayload.filtered = [];
```
Comment (renchap) [inline streaming/index.js:742]: You could avoid defining `mutatedPayload`, have `const filtered = []` (or a more explicit name) here, and then below use use `transmit({ ...payload, filtered })`?

File: streaming/index.js (hunk 1 above)
Comment (ThisIsMissEm) [reply streaming/index.js:629]: In my refactor on top of this branch I lifted the transmit method up in scope entirely, which resolves the shadowing of the payload variable here

File: streaming/index.js (hunk 2 above)
Comment (ThisIsMissEm) [reply streaming/index.js:742]: Also did this in my refactoring PR, but used a reduce instead of array declaration / forEach / push

**Review by renchap — APPROVED** [review]
Good for me if we also merge #26172
