### PR TITLE
fix: Update hashtags when (un)following a hashtag

### LINKED ISSUE #35060: “Followed Hashtags” in sidebar only shows a subset of followed hashtags without any indication there are more
### Steps to reproduce the problem

1. Click the disclosure chevron next to “Followed hashtags” in the sidebar to see followed hashtags

### Expected behaviour

Either all followed hashtags should be shown, or if a subset is shown there should be some indication there are more

### Actual behaviour

Only a subset is shown, but there is no indication there are more

### Detailed description

I think I’d expect to see something like “and 6 more” that, when clicked, would open the full list.

I’m also not sure I understand how the subset of shown hashtags is chosen. For me, it shows four hashtags that I was following but haven’t had any activity in a long time. I think I’d rather see recently active ones in the sidebar. Or maybe prioritize ones that I followed recently (say, within the past week) and then recently active ones?

### Mastodon instance

mastodon.online

### Mastodon version

v4.4.0-beta.1+pr-35029-e7685a1

### Browser name and version

Safari 18.5

### Operating system

macOS 15.5

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by diondiondion**
Fixes #35059
Fixes #35060

### Changes proposed in this PR:
- Refactors followed hashtags data fetching to use Redux
- Following or unfollowing a hashtag now marks both queries as stale & triggers a refetch
- ~~Adds a "View all" link to the end of the list of followed hashtags when there are more than 5 tags~~ This was removed again in favour of a better future solution

### Screenshots

image

https://github.com/user-attachments/assets/1b162ec7-6a42-4e43-8bf6-6a525ea6a51b

### CODE REVIEW

File: app/javascript/mastodon/features/ui/components/column_link.tsx [hunk 1]
```diff
@@ -16,7 +16,7 @@ export const ColumnLink: React.FC<{
   method?: string;
   badge?: React.ReactNode;
   transparent?: boolean;
-  optional?: boolean;
```
Comment (diondiondion) [inline app/javascript/mastodon/features/ui/components/column_link.tsx:19]: I couldn't find a use of this prop or the associated CSS class.

File: app/javascript/mastodon/actions/tags_typed.ts [hunk 2]
```diff
@@ -1,12 +1,39 @@
...
 import { createDataLoadingThunk } from 'mastodon/store/typed_functions';
 
+export const fetchFollowedHashtags = createDataLoadingThunk(
+  'tags/fetch-followed',
+  async ({
+    context,
+    limit,
+    next,
+  }: {
+    context: 'full' | 'sidebar';
```
Comment (Gargron) [inline app/javascript/mastodon/actions/tags_typed.ts]: I think it might be simpler to fetch a full page of tags from the API and limit to displaying the first 4 in the sidebar, if it means avoiding keeping track of "where will this be displayed" in actions/reducers. That's what we do with lists.

File: app/javascript/mastodon/features/navigation_panel/components/followed_tags_panel.tsx [hunk 3]
```diff
@@ -54,16 +57,26 @@ export const FollowedTagsPanel: React.FC = () => {
...
+          transparent
           icon='hashtag'
           key={tag.name}
           iconComponent={TagIcon}
           text={`#${tag.name}`}
           to={`/tags/${tag.name}`}
-          transparent
         />
       ))}
+      {hasMoreTags && (
```
Comment (Gargron) [inline app/javascript/mastodon/features/navigation_panel/components/followed_tags_panel.tsx]: I would be more at peace if we didn't have a "View all" link. The top link already links to all tags. I'd like to keep the menus as short as possible.

Comment (diondiondion) [reply app/javascript/mastodon/features/navigation_panel/components/followed_tags_panel.tsx]: Ok, I can remove the link again. Would we close #35060 as not planned for now, then?

Comment (Gargron) [reply app/javascript/mastodon/features/navigation_panel/components/followed_tags_panel.tsx]: I'd feel bad about closing it, it's a feature request, and it has merit, we just need to invest way more thinking into a proper solution now than makes sense for 4.4.

File: app/javascript/mastodon/actions/tags_typed.ts (hunk 2 above)
Comment (diondiondion) [reply app/javascript/mastodon/actions/tags_typed.ts]: Done, simplified the state so that there's just a single list now.

**Review by Gargron — APPROVED** [review]
