### PR TITLE
fix filter search index being too strict when looking for line breaks

### LINKED ISSUE #6316: regex timeline filters don't handle newlines well
this is an oddity I noticed when trying to block the new 

V
E
R
T
I
C
A
L

meme.

`([\r\n]+[A-Z])+` should do the trick here, but it blocks only *some* instances of the meme. I haven't figured out what's the difference between those that are and aren't caught.

### PR DESCRIPTION
**Pull request by codl**
while local toots do have the XHTML-formatted `<br />`, remote toots seem to have the modern HTML `<br>`

this fixes #6316

### CODE REVIEW

File: app/javascript/mastodon/reducers/statuses.js [hunk 1]
```diff
@@ -54,7 +54,7 @@ const normalizeStatus = (state, status) => {
     normalStatus.reblog = status.reblog.id;
   }
 
-  const searchContent = [status.spoiler_text, status.content].join('\n\n').replace(/<br \/>/g, '\n').replace(/<\/p><p>/g, '\n\n');
+  const searchContent = [status.spoiler_text, status.content].join('\n\n').replace(/<br ?\/?>/g, '\n').replace(/<\/p><p>/g, '\n\n');
```
Comment (ykzts) [inline app/javascript/mastodon/reducers/statuses.js]: I think it's better to call `\s *` instead of ` \`.

**Review by akihikodaki — APPROVED** [review]

**Comment by MightyPork** [comment]
good stuff, thanks
