### PR TITLE
Change dismissed banners to be stored server-side

### LINKED ISSUE #25957: Completely useless post appearing at the top of timelines in the web client
### Steps to reproduce the problem

1. Visit your home timeline
2. That's it, maybe you see it maybe you don't: intermittent

### Expected behaviour

Not having this post 

### Actual behaviour

Post appears intermittently

### Detailed description

There is a post which is not real. 

It says "This is your home base within Mastodon". It appears at the top of your timeline. It serves no purpose whatsoever. It is extra annoying because it cannot be disabled and it appears intermittently. 

### Specifications

Brave on Linux
Mastodon 4.1.4+nightly-20230711

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #25957

Store dismissed banners server-side in addition to local-storage. LocalStorage is kept for now, to provide an upgrade path, but could be removed in the future.

### CODE REVIEW

File: app/javascript/mastodon/components/dismissable_banner.tsx [hunk 1]
```diff
@@ -21,13 +28,23 @@ export const DismissableBanner: React.FC<PropsWithChildren<Props>> = ({
...
   const intl = useIntl();
 
   const handleDismiss = useCallback(() => {
     setVisible(false);
     bannerSettings.set(id, true);
-  }, [id]);
+    dispatch(changeSetting(['dismissed_banners', id], true));
+  }, [id, dispatch]);
+
+  if (!visible && !dismissed) {
```
Comment (renchap) [inline app/javascript/mastodon/components/dismissable_banner.tsx:45]: Actions should not be dispatched from a `render` function.

This needs to be done in `useEffect`

**Review by renchap — CHANGES_REQUESTED** [review]

**Review by renchap — APPROVED** [review]
