### PR TITLE
fix: YouTube iframe being able to start at a defined time

### LINKED ISSUE #9944: Embedded time-marked Youtube videos ignore time mark
**Embedded time-marked Youtube videos ignore time mark**

### Actual behaviour
The time mark is ignored.

Videos play from the beginning  (da capo)

### Steps to reproduce the problem
Create a new Mastodon toot and embed a video including a time mark, then post it.
For example, the following video URI
https://www.youtube.com/watch?v=ciqB03-t028&feature=youtu.be&t=1433

Embedding a video with a time mark, similar to this toot.  Twitter's behaviour is what I expected and it works correctly on that platform.
https://twitter.com/vruz/status/1090263821162209282

This is the behaviour of the same embedded video on Mastodon, it plays from the beginning, ignoring the time mark.
https://sunbeam.city/@h/101500477120985245

### Specifications
It applies under all OSes and browsers.
Tested on Sunbeam.city running Mastodon 2.6.5

### LINKED ISSUE #22238: Youtube videos always start at the beginning despite a time specified as a parameter in URL
### Steps to reproduce the problem

1. Play a youtube video on the youtube website
2. right click on video and select "copy video url at current time"
3. post the link on Mastodon
...

### Expected behaviour

When you press play on the video embedded in a post, it should start at the time specified

### Actual behaviour

Video always starts at the beginning, despite the ?t=123 parameter

### Detailed description

It looks like the time parameter is ignored on playback. Oddly, the parameter is taken into account on generating the still image for the post, despite, it will always play from the beginning. 

### Specifications

Not a new issue, but observed on Mastodon 3.5.x and newer.

### PR DESCRIPTION
**Pull request by BrunoViveiros**
Closes #9944, Closes #22238

This update addresses the issue where YouTube videos were not starting at the correct time when a parameter was passed in the URL.
Currently, I'm adding the parameter to the URL the same way autoplay is being added.

### CODE REVIEW

**Comment by renchap** [comment]
Thanks for your contribution!

This adds the `start` parameter to every iframe, if there is a `t` parameter, but this might not be a youtube iframe.

I do not think we want to have a list of domains here (lot of them, painful to maintain), but could this cause unexpected issues somehow?

**Comment by shleeable** [comment]
Resolving this would be an nice quality of life improvement. Thanks for investigating it.

**Comment by BrunoViveiros** [comment]
> 

I think all YouTube links have a “provider” that we can use, so we can only add the start if it is a YouTube link.
I'll make the change and will let you know.

File: app/javascript/mastodon/features/status/components/card.jsx [hunk 1]
```diff
@@ -32,18 +32,20 @@ const getHostname = url => {
...
-      iframe.src += '&';
-    } else {
-      iframe.src += '?';
-    }
+    const iframeUrl = new URL(iframe.src)
+
+    iframeUrl.searchParams.set('autoplay', 1)
+    iframeUrl.searchParams.set('auto_play', 1)
+
+    if (startTime && providerName === "YouTube") iframeUrl.searchParams.set('start', startTime)
```
Comment (BrunoViveiros) [inline app/javascript/mastodon/features/status/components/card.jsx:46]: @renchap That should work for only adding the start parameter to YouTube links

**Comment by shleeable** [comment]
FYI YT has multiple domains... `https://youtu.be/KG2ttRgc5Zk?t=443`

**Comment by BrunoViveiros** [comment]
I just did a rebase to update the PR and checked that it works in both domains, and should work for other domains too.

image

**Comment by ldexterldesign** [comment]
👀

**Comment by mjankowski** [comment]
Looks like this needs CI approval, but otherwise might be ready or close to it?

**Review by ChaosExAnima — APPROVED** [review]
