### PR TITLE
Fix display of toots without text content

### LINKED ISSUE #12343: Remote statuses with CW but no content do not render CW in web UI
observed on mastodon.social (master) and nulled.red (2.9.0)

### no cw upon receipt
image

### cw'd on origin
image

### object representation
https://pl.ohno.host/objects/46813368-9801-4bd4-8ad3-f0caaa78344a

```
{ '@context': [ 'https://www.w3.org/ns/activitystreams',
                'https://pl.ohno.host/schemas/litepub-0.1.jsonld',
                {'@language': 'und'}],
  'actor': 'https://pl.ohno.host/users/pie',
  'attachment': [ { 'mediaType': 'image/jpeg',
                    'name': 'Tusky_1573418213439_D2BPRPZNE9.jpg',
                    'type': 'Document',
                    'url': 'https://pl.ohno.host/media/0f394c711e080d7aeb920abbf08ecf4f1b81f08fd1321c131f3c2009b5bb4130.jpg?name=Tusky_1573418213439_D2BPRPZNE9.jpg'}],
  'attributedTo': 'https://pl.ohno.host/users/pie',
  'cc': ['https://pl.ohno.host/users/pie/followers'],
  'content': '',
  'context': 'https://pl.ohno.host/contexts/5efb382d-66be-4262-9b96-c104392690ef',
  'conversation': 'https://pl.ohno.host/contexts/5efb382d-66be-4262-9b96-c104392690ef',
  'id': 'https://pl.ohno.host/objects/46813368-9801-4bd4-8ad3-f0caaa78344a',
  'published': '2019-11-10T20:37:01.963097Z',
  'sensitive': True,
  'summary': 'cursed image',
  'tag': [ { 'href': 'https://pl.ohno.host/tags/nsfw',
             'name': '#nsfw',
             'type': 'Hashtag'}],
  'to': ['https://www.w3.org/ns/activitystreams#Public'],
  'type': 'Note'}
```

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #12343

- fixes CWs from other implementations not showing up if toot has no text contents (e.g., Pleroma allows sending a message with a CW, media attachments, but no text contents)
- fixes the “Read more” thread indicator not showing up on threaded toots with no text contents

### CODE REVIEW

**Comment by trwnh** [comment]
Fixes #12343 I think?

**Comment by ClearlyClaire** [comment]
Indeed!

**Comment by ClearlyClaire** [comment]
ping @Gargron

File: app/javascript/mastodon/components/status_content.js [hunk 1]
```diff
@@ -170,10 +170,6 @@ export default class StatusContent extends React.PureComponent {
   render () {
     const { status } = this.props;
 
-    if (status.get('content').length === 0) {
```
Comment (Gargron) [inline app/javascript/mastodon/components/status_content.js:173]: If there is a CW but no text, why don't we move the CW to the text? Avoid annoying click-through. That's what we do when somebody writes a CW but no text locally.

Comment (ClearlyClaire) [reply app/javascript/mastodon/components/status_content.js:173]: I have no strong feeling about this, except that if we do that, it might be better if it were strictly a display thing, so that the CW carries over on reply.

Comment (Gargron) [reply app/javascript/mastodon/components/status_content.js:173]: I'm not personally a fan of the CW-carry-over behaviour at all... 99% of the time I've seen it the reply does not contain anything CW-worthy so it just makes you click extra for nothing. Like if the original post talks about a medical situation under a CW that's fair but then all the "Get well soon!" also get a CW that's really unnecessary.

Comment (ClearlyClaire) [reply app/javascript/mastodon/components/status_content.js:173]: eh. changed that so a CW is considered as the toot's content if that content was empty, and replying here would lose the CW carry-over behavior, even though I don't really like that

**Review by Gargron — APPROVED** [review]
