### PR TITLE
Fix list error messages

### LINKED ISSUE #22697: Inaccurate error message when trying to add an account to a list that is already in that list
### Steps to reproduce the problem

Attempt to use the API to add an account to a list it is already in. This can also occur if the UI element doesn't update for some reason and the user tries clicking add again.

### Expected behaviour

422: Account already added

### Actual behaviour

422: Account already taken

### Detailed description

_No response_

### Specifications

4.0.2

### PR DESCRIPTION
**Pull request by Gargron**
Fixes #22697

### CODE REVIEW

File: app/models/list_account.rb [hunk 1]
```diff
@@ -25,17 +25,16 @@ class ListAccount < ApplicationRecord
   private
 
   def set_follow
-    self.follow = Follow.find_by!(account_id: list.account_id, target_account_id: account.id)
-  rescue ActiveRecord::RecordNotFound
```
Comment (mjankowski) [inline app/models/list_account.rb:29]: I think the CI failure here - https://github.com/mastodon/mastodon/actions/runs/12042045495/job/33575078943?pr=33082 - is that the controller was implicitly relying on this raise to convert into a 404...

Comment (Gargron) [reply app/models/list_account.rb:29]: I'm not sure if claiming 404 in the API is the desired outcome. The `validate_relationship` method was supposed to give more specific error messages but the code was never reached because of the exception...

Comment (mjankowski) [reply app/models/list_account.rb:29]: Yeah ... sort of related - https://github.com/mastodon/mastodon/pull/31896 - on that PR I had troubled (because of the combination of the raise and the factory setup) adding any non-convoluted coverage for this latter method. I was able to do the follow setting, and meant to do the validation part as followup.

It would definitely be easier to accomplish that if the raise comes out.

LMK if pulling out the raise and adding validation coverage (but not yet changing the API or this validation message string) in advanced of this would be useful...?

**Review by ClearlyClaire — APPROVED** [review]
