### PR TITLE
Properly remove tIME chunk from PNG uploads

### LINKED ISSUE #27105: imagemagick parameters for avoiding tIME chunk incorrect
### Steps to reproduce the problem

1. Upload an image.

### Expected behaviour

There should not be a modification time encoded into the file.

### Actual behaviour

There is a modification time encoded into the file.

### Detailed description

image

### Mastodon instance

_No response_

### Mastodon version

_No response_

### Technical details

This should be a simple find-and-replace to fix.

### PR DESCRIPTION
**Pull request by TheEssem**
Fixes #27105. ImageMagick wasn't properly removing the `date:create`, `date:modify`, and `date:timestamp` chunks from PNG uploads, so this should fix it.

### CODE REVIEW

**Review by ClearlyClaire — APPROVED** [review]

**Comment by ClearlyClaire** [comment]
Seems to fix an issue indeed with ImageMagick 6.9.11, but are the previous flags perhaps working or useful on other versions?

File: app/models/concerns/account_avatar.rb [hunk 1]
```diff
@@ -18,7 +18,7 @@ def avatar_styles(file)
 
   included do
     # Avatar upload
-    has_attached_file :avatar, styles: ->(f) { avatar_styles(f) }, convert_options: { all: '+profile "!icc,*" +set modify-date +set create-date' }, processors: [:lazy_thumbnail]
+    has_attached_file :avatar, styles: ->(f) { avatar_styles(f) }, convert_options: { all: '+profile "!icc,*" +set date:modify +set date:create +set date:timestamp' }, processors: [:lazy_thumbnail]
```
Comment (ClearlyClaire) [inline app/models/concerns/account_avatar.rb:21]: I would keep `+set modify-date` and `+set create-date` unless we can identify which ImageMagick versions output these and make sure they are not in use anymore:
```suggestion
    has_attached_file :avatar, styles: ->(f) { avatar_styles(f) }, convert_options: { all: '+profile "!icc,*" +set modify-date +set create-date +set date:modify +set date:create +set date:timestamp' }, processors: [:lazy_thumbnail]
```

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]

File: app/models/concerns/account_avatar.rb (hunk 1 above)
Comment (TheEssem) [reply app/models/concerns/account_avatar.rb:21]: Did some further testing, it seems like the old flags are broken on ImageMagick versions 7.1.1 (latest release), 6.9.10 (used on Ubuntu 20.04), and 6.9.11 (used on current Debian/Ubuntu), but do indeed work with 6.9.12 (latest legacy). The new flags seem to work on all versions listed above, so I don't see the old flags being of much use here.

**Review by ClearlyClaire — APPROVED** [review]
