### PR TITLE
Change search popout to not list unusable search options when logged out

### LINKED ISSUE #27273: search for posts 'broken' when not logged in (4.2.0)
### Steps to reproduce the problem

1. Go to a server running Mastodon 4.2 without logging in (https://mastodon.social/search)
2. Enter a search term. For instance, I used "Gaetz" since he's in the news today.
3. View the search results. There will be no posts listed under the "all" tab, and the 'posts' tab will provide the misleading message "Could not find anything for these search terms"
...

### Expected behaviour

Either show search results the same as for logged-in users, or clarify the response to say that search is turned off for anonymous users

### Actual behaviour

"post" search results are not shown. Instead shows misleading message "Could not find anything for these search terms"

### Detailed description

Note, this is not a problem with search itself. When logged in, I see plenty of search results (mstdn.science). It also is not a problem with displaying posts to anonymous users - the hashtag search works as expected and displays the posts properly (https://mastodon.social/tags/gaetz)

If this behavior is intentional, then the website should be clear about why it is not returning any results. The current response could give the wrong impression to someone who is curious about Mastodon and uses the search function to see what sort of activity is on Mastodon (concluding either that there is no activity, or that search is broken).

I tested on both mastodon.social (v4.2.1-rc1+pr-27261-dd5f312) and mstdn.sciesce (4.2.0)

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.1-rc1+pr-27261-dd5f312

### Browser name and version

Firefox 118.0.1 (64-bit)

### Operating system

Windows 11

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #27273

### CODE REVIEW

File: app/javascript/mastodon/features/compose/components/search.jsx [hunk 1]
```diff
@@ -386,7 +387,11 @@ class Search extends PureComponent {
             </div>
           ) : (
             <div className='search__popout__menu__message'>
-              <FormattedMessage id='search_popout.full_text_search_disabled_message' defaultMessage='Not available on {domain}.' values={{ domain }} />
+              {searchEnabled ? (
```
Comment (panarom) [inline app/javascript/mastodon/features/compose/components/search.jsx:390]: should this be `signedIn` instead of `searchEnabled`?

Comment (ClearlyClaire) [reply app/javascript/mastodon/features/compose/components/search.jsx:390]: You're right! Fixing that.

**Review by panarom — APPROVED** [review]

**Review by panarom — APPROVED** [review]

**Review by renchap — APPROVED** [review]
