### PR TITLE
Fix mute duration not being shown in list of muted accounts in web UI

### LINKED ISSUE #32371: No apparent way to see mute durations in revised web interface 4.3.0
### Steps to reproduce the problem

1. Give someone a timed mute
2. Navigate to list of muted users via "…" "muted users"

### Expected behaviour

A list of muted users complete with remaining mute duration should appear

### Actual behaviour

No distinction is made between the users muted for a limited time and those muted indefinitely. 

### Detailed description

IIRC in the previous version the "plain" interface used to show remaining mute duration as well as presenting the option to unmute. The "deck" view didn't show duration due to space constraints. 

Now neither show them nor are the durations or end date shown on the individual profiles so you have to have a really good memory or a third party app. 

### Mastodon instance

en.osm.towm

### Mastodon version

 v4.3.0

### Browser name and version

131.0 (64-bit)

### Operating system

Windows 11

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #32371

Basically, `/api/v1/mutes` returns `MutedAccount` objects that are `Account` with an additional `mute_expires_at`, but we ignored that attribute in the common handling of `Account` objects.

This PR changes it back so that the redux-stored accounts contain `mute_expires_at`. That being said, this does not seem to be a very clean solution, and a better solution is probably to store that information in another piece of redux state to not pollute the `Account` record definition.

### CODE REVIEW

File: app/javascript/mastodon/api_types/accounts.ts [hunk 1]
```diff
@@ -44,4 +44,5 @@ export interface ApiAccountJSON {
   limited?: boolean;
   memorial?: boolean;
   hide_collections: boolean;
+  mute_expires_at?: string | null;
```
Comment (renchap) [inline app/javascript/mastodon/api_types/accounts.ts:47]: This is not pretty as this should be an `ApiMutedAccountJSON`, but I guess changing that would be a huge endeavour.

We should at least add a comment here to explain where this field comes from.

Alternatively, we could rename the existing one to `BaseApiAccountJSON`, create a new `ApiMutedAccountJSON` interface  that extends the base, and have `type ApiAccountJSON = BaseApiAccountJSON | ApiMutedAccountJSON`.

This would make it clear about what is happening, and maybe some day we can change this.

Another alternative is simply to have something like:

```ts
interface ApiMutedAccountJSON extends ApiAccountJSON {
  mute_expires_at?: string | null;
}
```

Then have `createAccountFromServerJSON` accept both `ApiMutedAccountJSON` and `ApiAccountJSON` (which makes sense, as at the moment in the code the 2 API results are converted to the same Immutable object)

Comment (renchap) [reply app/javascript/mastodon/api_types/accounts.ts:47]: Yes, at the end it will be very similar to my previous proposal with `type ApiAccountJSON`, except that you expand the type in every place

**Review by renchap — APPROVED** [review]
This is not ideal, but a proper fix would be much more complex.

We will probably need to review this when we remove usage of Immutable for the accounts reducer.
