### PR TITLE
fix: Remove redundant focus stop within status

### LINKED ISSUE #20073: Status wrappers have redundant `tabindex` attributes
### Steps to reproduce the problem

1. Navigate to a toot by <kbd>Tab</kbd> on a keyboard
2. The whole toot is focusable (`.status__wrapper`/`.detailed-status__wrapper`)
3. Use <kbd>Tab</kbd> until you reach the content element itself (`.status__content`)

### Expected behaviour

Only the whole toot should be focusable (since clicking on it will result in an action)

### Actual behaviour

The content itself is focusable as well

### Detailed description

From my point of view, `.status__content` does not need `tabindex="0"` since it's a non-interactive element and it's missing a visual focus style anyway.

For toots with content warnings, having `tabindex="0"` may appear helpful since the content warning will get read by screen readers. However, this can be handled in another way:

1. Remove `tabindex="0"` from `.status__content`.
2. Give the content warning text wrapper (`<span class="translate" lang="">`) an `id` attribute
3. Give the content warning toggle button (`.status__content__spoiler-link`) an `aria-describedby` attribute and refer to the `id`.
4. The content warning will get read by screen readers when focussing the toggle button.

### Specifications

* Mastodon 4.0.0rc1
* Safari 16.1
* macOS 13.0
* VoiceOver

### PR DESCRIPTION
**Pull request by diondiondion**
Fixes #20073

### Changes proposed in this PR:
- Removes focus stop around post content as it's not by itself interactive
- Adds content/filter warning text to "Show more" button as an aria description
- Changes content/filter warning container from `<label>` to `<div>` as already-labelled controls like buttons shouldn't have one. The existing "click anywhere to open" functionality is preserved by forwarding container clicks to the button.

### CODE REVIEW

File: app/javascript/mastodon/components/status_banner.tsx [hunk 1]
```diff
@@ -10,33 +13,52 @@ export const StatusBanner: React.FC<{
...
-        />
-      )}
-    </button>
-  </label>
-);
+      <button
+        ref={buttonRef}
+        className='link-button'
+        onClick={onClick}
+        aria-describedby={descriptionId}
```
Comment (ClearlyClaire) [inline app/javascript/mastodon/components/status_banner.tsx:43]: > The `aria-describedby` property is appropriate when the associated content contains plain text. If the content is extensive, contains useful semantics, or has a complex structure requiring user navigation, use [aria-details](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-details) instead.

Content warnings are mostly textual but they are allowed to include emojis, including custom ones, so I wonder if we should use `aria-details` instead?

Comment (diondiondion) [reply app/javascript/mastodon/components/status_banner.tsx:43]: Emojis and other images that have alt text should resolve fine as a description, as far as I know. I'll do a quick test to confirm.

Comment (diondiondion) [reply app/javascript/mastodon/components/status_banner.tsx:43]: The name (shortcode) of custom emojis is read out normally, so I think `aria-describedby` works here. But thanks for looking into this! 🙏 

https://github.com/user-attachments/assets/775f9180-c666-48bb-abec-711f7b479807

In the future it would be good to allow defining dedicated alt text for custom emojis where the shortcode might not be very descriptive.

**Review by ClearlyClaire — APPROVED** [review]
