### PR TITLE
Fix interaction settings migration error when encountering no settings

### LINKED ISSUE #29526: Can't execute "Migrate interaction settings to policy"
### Steps to reproduce the problem

1. Run `RAILS_ENV=production DB_HOST=10.0.0.115 DB_PORT=5432 bundle exec rails db:migrate`

### Expected behaviour

Status should be `up 20240304090449  Migrate interaction settings to policy`

### Actual behaviour

Migration fails

### Detailed description

When I try to run the database migrations, ends in this error.

<details>
<summary>Click to toggle contents of `code`</summary>

```
RAILS_ENV=production DB_HOST=10.0.0.115 DB_PORT=5432 bundle exec rails db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Invoke db:pre_migration_check (first_time)
** Invoke environment
** Execute db:pre_migration_check
** Execute db:migrate
I, [2024-03-07T18:45:48.122499 #3092892]  INFO -- : Migrating to MigrateInteractionSettingsToPolicy (20240304090449)
== 20240304090449 MigrateInteractionSettingsToPolicy: migrating ===============
WARNING:  you don't own a lock of type ExclusiveLock
bin/rails aborted!
ActiveRecord::ConcurrentMigrationError:  (ActiveRecord::ConcurrentMigrationError)

Failed to release advisory lock

/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1603:in `ensure in with_advisory_lock'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1603:in `with_advisory_lock'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1448:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy/railtie.rb:28:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy/strategy.rb:60:in `wrap'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy.rb:151:in `strategy'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy/railtie.rb:28:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1274:in `up'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1249:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/tasks/database_tasks.rb:243:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/strong_migrations-1.7.0/lib/strong_migrations/database_tasks.rb:5:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/railties/databases.rake:93:in `block (2 levels) in <main>'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `block in execute'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `execute'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:199:in `synchronize'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:188:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:182:in `invoke_task'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `block in top_level'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:147:in `run_with_threads'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:132:in `top_level'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands/rake/rake_command.rb:27:in `block (2 levels) in perform'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:208:in `standard_exception_handling'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands/rake/rake_command.rb:27:in `block in perform'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands/rake/rake_command.rb:44:in `block in with_rake'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/rake_module.rb:59:in `with_application'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/command.rb:156:in `invoke_rake'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/command.rb:73:in `block in invoke'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/command.rb:149:in `with_argv'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/command.rb:69:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands.rb:18:in `<main>'
<internal:/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'

Caused by:
StandardError: An error has occurred, all later migrations canceled: (StandardError)

undefined method `[]' for nil:NilClass
/home/mastodon/live/db/migrate/20240304090449_migrate_interaction_settings_to_policy.rb:26:in `block in up'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/relation/batches.rb:82:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/relation/batches.rb:82:in `block in find_each'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/relation/batches.rb:158:in `block in find_in_batches'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/relation/batches.rb:396:in `block in batch_on_unloaded_relation'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/relation/batches.rb:372:in `loop'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/relation/batches.rb:372:in `batch_on_unloaded_relation'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/relation/batches.rb:269:in `in_batches'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/relation/batches.rb:157:in `find_in_batches'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/relation/batches.rb:81:in `find_each'
/home/mastodon/live/db/migrate/20240304090449_migrate_interaction_settings_to_policy.rb:21:in `up'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:989:in `public_send'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:989:in `exec_migration'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:970:in `block (2 levels) in migrate'
/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/3.2.0/benchmark.rb:296:in `measure'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:969:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:227:in `with_connection'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:968:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/strong_migrations-1.7.0/lib/strong_migrations/migration.rb:5:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy/railtie.rb:28:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy/strategy.rb:60:in `wrap'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy.rb:151:in `strategy'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy/railtie.rb:28:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1178:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1529:in `block in execute_migration_in_transaction'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1582:in `ddl_transaction'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/strong_migrations-1.7.0/lib/strong_migrations/migrator.rb:4:in `ddl_transaction'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1528:in `execute_migration_in_transaction'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1503:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1503:in `migrate_without_lock'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1448:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1600:in `with_advisory_lock'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1448:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy/railtie.rb:28:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy/strategy.rb:60:in `wrap'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy.rb:151:in `strategy'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy/railtie.rb:28:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1274:in `up'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1249:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/tasks/database_tasks.rb:243:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/strong_migrations-1.7.0/lib/strong_migrations/database_tasks.rb:5:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/railties/databases.rake:93:in `block (2 levels) in <main>'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `block in execute'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `execute'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:199:in `synchronize'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:188:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:182:in `invoke_task'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `block in top_level'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:147:in `run_with_threads'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:132:in `top_level'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands/rake/rake_command.rb:27:in `block (2 levels) in perform'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:208:in `standard_exception_handling'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands/rake/rake_command.rb:27:in `block in perform'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands/rake/rake_command.rb:44:in `block in with_rake'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/rake_module.rb:59:in `with_application'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/command.rb:156:in `invoke_rake'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/command.rb:73:in `block in invoke'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/command.rb:149:in `with_argv'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/command.rb:69:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands.rb:18:in `<main>'
<internal:/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'

Caused by:
NoMethodError: undefined method `[]' for nil:NilClass (NoMethodError)

      if deserialized_settings['interactions.must_be_follower']
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/mastodon/live/db/migrate/20240304090449_migrate_interaction_settings_to_policy.rb:26:in `block in up'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/relation/batches.rb:82:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/relation/batches.rb:82:in `block in find_each'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/relation/batches.rb:158:in `block in find_in_batches'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/relation/batches.rb:396:in `block in batch_on_unloaded_relation'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/relation/batches.rb:372:in `loop'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/relation/batches.rb:372:in `batch_on_unloaded_relation'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/relation/batches.rb:269:in `in_batches'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/relation/batches.rb:157:in `find_in_batches'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/relation/batches.rb:81:in `find_each'
/home/mastodon/live/db/migrate/20240304090449_migrate_interaction_settings_to_policy.rb:21:in `up'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:989:in `public_send'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:989:in `exec_migration'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:970:in `block (2 levels) in migrate'
/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/3.2.0/benchmark.rb:296:in `measure'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:969:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:227:in `with_connection'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:968:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/strong_migrations-1.7.0/lib/strong_migrations/migration.rb:5:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy/railtie.rb:28:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy/strategy.rb:60:in `wrap'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy.rb:151:in `strategy'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy/railtie.rb:28:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1178:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1529:in `block in execute_migration_in_transaction'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1582:in `ddl_transaction'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/strong_migrations-1.7.0/lib/strong_migrations/migrator.rb:4:in `ddl_transaction'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1528:in `execute_migration_in_transaction'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1503:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1503:in `migrate_without_lock'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1448:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1600:in `with_advisory_lock'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1448:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy/railtie.rb:28:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy/strategy.rb:60:in `wrap'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy.rb:151:in `strategy'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy/railtie.rb:28:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1274:in `up'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1249:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/tasks/database_tasks.rb:243:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/strong_migrations-1.7.0/lib/strong_migrations/database_tasks.rb:5:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/railties/databases.rake:93:in `block (2 levels) in <main>'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `block in execute'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `execute'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:199:in `synchronize'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:188:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:182:in `invoke_task'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `block in top_level'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:147:in `run_with_threads'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:132:in `top_level'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands/rake/rake_command.rb:27:in `block (2 levels) in perform'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:208:in `standard_exception_handling'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands/rake/rake_command.rb:27:in `block in perform'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands/rake/rake_command.rb:44:in `block in with_rake'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/rake_module.rb:59:in `with_application'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/command.rb:156:in `invoke_rake'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/command.rb:73:in `block in invoke'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/command.rb:149:in `with_argv'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/command.rb:69:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands.rb:18:in `<main>'
<internal:/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
```
</details>

When I try to run it again:
<details>
<summary>Click to toggle contents of `code`</summary>

```
RAILS_ENV=production DB_HOST=10.0.0.115 DB_PORT=5432 bundle exec rails db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Invoke db:pre_migration_check (first_time)
** Invoke environment
** Execute db:pre_migration_check
** Execute db:migrate
bin/rails aborted!
ActiveRecord::ConcurrentMigrationError:  (ActiveRecord::ConcurrentMigrationError)

Cannot run migrations because another migration process is currently running.

/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1598:in `with_advisory_lock'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1448:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy/railtie.rb:28:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy/strategy.rb:60:in `wrap'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy.rb:151:in `strategy'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.5.1/lib/chewy/railtie.rb:28:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1274:in `up'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/migration.rb:1249:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/tasks/database_tasks.rb:243:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/strong_migrations-1.7.0/lib/strong_migrations/database_tasks.rb:5:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/railties/databases.rake:93:in `block (2 levels) in <main>'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `block in execute'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `execute'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:199:in `synchronize'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:188:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:182:in `invoke_task'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `block in top_level'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:147:in `run_with_threads'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:132:in `top_level'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands/rake/rake_command.rb:27:in `block (2 levels) in perform'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:208:in `standard_exception_handling'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands/rake/rake_command.rb:27:in `block in perform'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands/rake/rake_command.rb:44:in `block in with_rake'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/rake_module.rb:59:in `with_application'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/command.rb:156:in `invoke_rake'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/command.rb:73:in `block in invoke'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/command.rb:149:in `with_argv'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/command.rb:69:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/commands.rb:18:in `<main>'
<internal:/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
```
</details>

Even if I manually release the lock using `SELECT pid, locktype, mode FROM pg_locks WHERE locktype = 'advisory';`, or if I wait long enough, we're back to the first error. So the database migration status is always:

`down    20240304090449  Migrate interaction settings to policy`.

All the other migrations are up:

```
  (...)
   up     20230822081029  Create software updates
   up     20230904134623  Fix kmr locale settings
   up     20230907150100  Add index account stats on last status at and account
   up     20231006183200  Add URL to preview cards statuses
   up     20231211234923  Create follow recommendation mutes
   up     20231212073317  Add languages index to account summaries
   up     20231222100226  Add allow with approval to email domain blocks
   up     20240109103012  Fix canadian french locale
   up     20240111033014  Create generated annual reports
   up     20240221195424  Add filtered to notifications
   up     20240221195828  Create notification requests
   up     20240221211359  Notification request ids to timestamp ids
   up     20240222193403  Create notification permissions
   up     20240222203722  Create notification policies
   up     20240227191620  Add filtered index on notifications
```

### Mastodon instance

bolha.one

### Mastodon version

v4.3.0-alpha.3

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: `ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x86_64-linux]`
- Node.js version: `v20.10.0`

### PR DESCRIPTION
**Pull request by Gargron**
Fix #29526

### CODE REVIEW

**Review by renchap — APPROVED** [review]

File: db/migrate/20240304090449_migrate_interaction_settings_to_policy.rb [hunk 1]
```diff
@@ -20,6 +20,9 @@ class NotificationPolicy < ApplicationRecord
   def up
     User.includes(account: :notification_policy).find_each do |user|
       deserialized_settings = Oj.load(user.attributes_before_type_cast['settings'])
+
+      next if deserialized_settings.nil?
```
Comment (mjankowski) [inline db/migrate/20240304090449_migrate_interaction_settings_to_policy.rb:24]: I realize this is committed already, but -- could we push this check into the initial User query, and only get records that are something like `where.not(settings: [nil, '', '{}'])` (or similar) ... or does that not work here b/c of the serialization on the column?
