### PR TITLE
Fix backups stopping due to read timeouts

### LINKED ISSUE #12280: BackupWorker fails if S3 media read times out
Requesting an archive which would contain media that cannot be accessed on S3 fails. Symptom: users report trying to export account archives but seeing the export disappear after several minutes with no error message or result.

### Expected behaviour

Media that cannot be retrieved is not included in the archive, but the backup succeeds otherwise. (This is the case for local media in the public/ folder if S3 is not configured, and media for which S3 promptly returns a 404.).

### Actual behaviour

As described above. I suspect DigitalOcean Spaces is being slow with stale media accesses. Inspecting a failed job in sidekiq gives the following stack trace:

<details>
<summary>BackupWorker stack trace</summary>
<p>

```
"Net::ReadTimeout with #<TCPSocket:(closed)>",
"error_class"=>"Seahorse::Client::NetworkingError",
"failed_at"=>1572676141.4297757, "retry_count"=>1, "error_backtrace"=>[
"/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/protocol.rb:217:in `rbuf_fill'",
"/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/protocol.rb:191:in `readuntil'",
"/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/protocol.rb:201:in `readline'",
"/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http/response.rb:40:in `read_status_line'",
"/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http/response.rb:29:in `read_new'",
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http.rb:1509:in `block in transport_request'",
"/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http.rb:1506:in `catch'",
"/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http.rb:1506:in `transport_request'",
"/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http.rb:1479:in `request'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/httplog-1.3.2/lib/httplog/adapters/net_http.rb:12:in `block in request'",
"/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/httplog-1.3.2/lib/httplog/adapters/net_http.rb:11:in `request'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.65.1/lib/seahorse/client/net_http/connection_pool.rb:342:in `request'",
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.65.1/lib/seahorse/client/net_http/handler.rb:74:in `block in transmit'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.65.1/lib/seahorse/client/net_http/handler.rb:126:in `block in session'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.65.1/lib/seahorse/client/net_http/connection_pool.rb:100:in `session_for'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.65.1/lib/seahorse/client/net_http/handler.rb:121:in `session'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.65.1/lib/seahorse/client/net_http/handler.rb:73:in `transmit'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.65.1/lib/seahorse/client/net_http/handler.rb:47:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.65.1/lib/seahorse/client/plugins/content_length.rb:17:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.48.0/lib/aws-sdk-s3/plugins/s3_signer.rb:109:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.48.0/lib/aws-sdk-s3/plugins/s3_signer.rb:57:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.48.0/lib/aws-sdk-s3/plugins/s3_host_id.rb:15:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.65.1/lib/aws-sdk-core/xml/error_handler.rb:8:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.65.1/lib/aws-sdk-core/plugins/transfer_encoding.rb:26:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.65.1/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.48.0/lib/aws-sdk-s3/plugins/s3_signer.rb:87:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.48.0/lib/aws-sdk-s3/plugins/redirects.rb:18:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.48.0/lib/aws-sdk-s3/plugins/dualstack.rb:34:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.48.0/lib/aws-sdk-s3/plugins/accelerate.rb:50:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.48.0/lib/aws-sdk-s3/plugins/md5s.rb:31:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.48.0/lib/aws-sdk-s3/plugins/bucket_name_restrictions.rb:13:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.48.0/lib/aws-sdk-s3/plugins/expect_100_continue.rb:22:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.65.1/lib/aws-sdk-core/rest/handler.rb:8:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.65.1/lib/aws-sdk-core/plugins/use_agent.rb:13:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.65.1/lib/seahorse/client/plugins/endpoint.rb:45:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.65.1/lib/aws-sdk-core/plugins/param_validator.rb:24:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.65.1/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.48.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:22:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.48.0/lib/aws-sdk-s3/plugins/dualstack.rb:26:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.48.0/lib/aws-sdk-s3/plugins/accelerate.rb:35:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.65.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.65.1/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.65.1/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.65.1/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.65.1/lib/seahorse/client/plugins/response_target.rb:23:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.65.1/lib/seahorse/client/request.rb:70:in `send_request'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.48.0/lib/aws-sdk-s3/client.rb:2935:in `get_object'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.48.0/lib/aws-sdk-s3/object.rb:697:in `get'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/paperclip-6.0.0/lib/paperclip/storage/s3.rb:416:in `block in copy_to_local_file'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/paperclip-6.0.0/lib/paperclip/storage/s3.rb:415:in `open'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/paperclip-6.0.0/lib/paperclip/storage/s3.rb:415:in `copy_to_local_file'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/paperclip-6.0.0/lib/paperclip/io_adapters/attachment_adapter.rb:34:in `copy_to_tempfile'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/paperclip-6.0.0/lib/paperclip/io_adapters/attachment_adapter.rb:26:in `cache_current_values'", 
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/paperclip-6.0.0/lib/paperclip/io_adapters/attachment_adapter.rb:18:in `initialize'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/paperclip-6.0.0/lib/paperclip/io_adapters/registry.rb:33:in `new'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/paperclip-6.0.0/lib/paperclip/io_adapters/registry.rb:33:in `for'",
"/home/mastodon/live/app/services/backup_service.rb:138:in `download_to_tar'",
"/home/mastodon/live/app/services/backup_service.rb:66:in `block (2 levels) in dump_media_attachments!'",
"/home/mastodon/live/app/services/backup_service.rb:65:in `each'",
"/home/mastodon/live/app/services/backup_service.rb:65:in `block in dump_media_attachments!'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/relation/batches.rb:238:in `block in in_batches'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/relation/batches.rb:222:in `loop'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/relation/batches.rb:222:in `in_batches'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/relation/batches.rb:135:in `find_in_batches'",
"/home/mastodon/live/app/services/backup_service.rb:64:in `dump_media_attachments!'",
"/home/mastodon/live/app/services/backup_service.rb:45:in `block (3 levels) in build_archive!'",
"/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/package/tar_writer.rb:86:in `new'",
"/home/mastodon/live/app/services/backup_service.rb:44:in `block (2 levels)  in build_archive!'",
"/home/mastodon/live/app/services/backup_service.rb:43:in `wrap'",
"/home/mastodon/live/app/services/backup_service.rb:43:in `block in build_archive!'",
"/home/mastodon/live/app/services/backup_service.rb:42:in `open'",
"/home/mastodon/live/app/services/backup_service.rb:42:in `build_archive!'",
"/home/mastodon/live/app/services/backup_service.rb:13:in `call'",
"/home/mastodon/live/app/workers/backup_worker.rb:21:in `perform'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:192:in `execute_job'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:165:in `block (2 levels) in process'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'",
"/home/mastodon/live/app/lib/sidekiq_error_handler.rb:5:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-unique-jobs-6.0.13/lib/sidekiq_unique_jobs/server/middleware.rb:29:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/middleware/chain.rb:133:in `invoke'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:164:in `block in process'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/job_retry.rb:109:in `local'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/rails.rb:43:in `block in call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:87:in `wrap'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/reloader.rb:73:in `block in wrap'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:87:in `wrap'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/reloader.rb:72:in `wrap'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/rails.rb:42:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:250:in `stats'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/job_logger.rb:8:in `call'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/job_retry.rb:74:in `global'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:125:in `block in dispatch'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/logging.rb:48:in `with_context'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/logging.rb:42:in `with_job_hash_context'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:124:in `dispatch'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:163:in `process'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:83:in `process_one'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/processor.rb:71:in `run'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/util.rb:16:in `watchdog'",
"/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/util.rb:25:in `block in safe_thread'",
]
```

</details>

### Steps to reproduce the problem

1. Configure your mastodon instance to use S3 or an S3-compatible API
2. Upload a piece of media
3. Cause a read timeout (I managed this by hacking up Minio and adding a `sleep` before returning any object over HTTP, but there might be easier ways).
4. Request an archive on the data export page

### Specifications

Discovered on v3.0.1, repro'd on master

Server running on Ubuntu 18.04

### PR DESCRIPTION
**Pull request by chr-1x**
If an attachment read times out, assume that the attachment is inaccessible and continue the backup without it. This fixes #12280.

### CODE REVIEW

File: app/services/backup_service.rb [hunk 1]
```diff
@@ -143,6 +143,7 @@ def download_to_tar(tar, attachment, filename)
       end
     end
   rescue Errno::ENOENT
+  rescue Seahorse::Client::NetworkingError
```
Comment (nightpool) [inline app/services/backup_service.rb]: Why are we getting a Seahorse error instead of a `::Fog::Errors::Error`, which paperclip rescues by default? This feels like a `fog` bug

Comment (Gargron) [reply app/services/backup_service.rb]: Paperclip doesn't use fog for S3.

File: app/services/backup_service.rb [hunk 2]
```diff
@@ -143,6 +143,7 @@ def download_to_tar(tar, attachment, filename)
       end
     end
   rescue Errno::ENOENT
```
Comment (Gargron) [inline app/services/backup_service.rb]: This should be: `rescue Errno::ENOENT, Seahorse::Client::NetworkingError`

Comment (chr-1x) [reply app/services/backup_service.rb]: Done

**Review by Gargron — APPROVED** [review]
