### PR TITLE
fix: Fix Safari volume bug, #34797

### LINKED ISSUE #34797: Audio player volume control has no effect
### Steps to reproduce the problem

1. Search for “has:audio”
2. Click play on one of the resulting audio players
3. Drag the volume slider and/or click the volume icon to mute/unmute

### Expected behaviour

Volume changes

### Actual behaviour

Audio keeps playing at original volume

### Detailed description

I think the volume slider on *video* players does work, just not audio players

### Mastodon instance

mastodon.online

### Mastodon version

v4.4.0-nightly.2025-05-24

### Browser name and version

Safari 18.5

### Operating system

macOS Sequoia 15.5

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by diondiondion**
Fixes #34797

### Changes proposed in this PR:
- Fixes unresponsive volume control in Safari
- …which required a larger refactor than I hoped for. The issue was caused by a conflict between the main `Audio` component and the audio context created inside of `useAudioVisualizer`, which I cleaned up by creating a new `useAudioContext` hook and using that in the top-level component. That context is then passed into the visualizer hook.
  The context hook also returns a `gainNode` instance which reliably controls the volume in Safari.
- Moves the `resumeAudio` and `suspendAudio` into `useAudioContext` which returns unified `playAudio` and `pauseAudio` callbacks.

### Screencap

Note that the audio player currently looks broken in Safari and doesn't show the visualizer. This will be fixed in a follow-up PR

https://github.com/user-attachments/assets/ccde891e-a121-4ee1-bb63-03826f8a9482

### CODE REVIEW

**Review by Gargron — APPROVED** [review]

File: app/javascript/mastodon/hooks/useAudioContext.ts [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+    void audioElementRef.current?.play();
+    void audioContextRef.current?.resume();
+  }, [audioElementRef]);
+
+  const pauseAudio = useCallback(() => {
+    audioElementRef.current?.pause();
+    void audioContextRef.current?.suspend();
+  }, [audioElementRef]);
+
+  return {
```
Comment (ChaosExAnima) [inline app/javascript/mastodon/hooks/useAudioContext.ts:55]: i know this is merged already, but i feel the readability could be somewhat improved by returning a `setVolume` callback as well, as `gainNodeRef.current.gain.value = 1` is unclear if you don't know what a GainNode is.

Comment (ChaosExAnima) [reply app/javascript/mastodon/hooks/useAudioContext.ts:55]: it's also unclear to me why Safari needs a GainNode at all 😅

Comment (diondiondion) [reply app/javascript/mastodon/hooks/useAudioContext.ts:55]: Agree with both of these points! Would've been nice to do without this complication, and I suspect there is some way, but I'm not that familiar with the Web Audio API…
