### PR TITLE
Fix featured tags for remote accounts not being kept up to date

### LINKED ISSUE #33357: Featured hashtag last used date is incorrect for remote users
### Steps to reproduce the problem

1. Load `/api/v1/accounts/[id]/featured_hashtags` with the ID of a remote user

### Expected behaviour

`last_status_at` should show the date of the most recent post from this user using that hashtag that is either public or viewable to the person making the query

### Actual behaviour

`last_status_at` shows a long ago date for a hashtag with recent public posts. I think `statuses_count` is also incorrect. I also found at least one example (possibly specific to the web UI) where a future date is displayed as the last usage date of a featured hashtag, even though the user’s posts are all dated correctly.

### Detailed description

I’ve seen this frequently on multiple servers where it will either give a long ago date or even say “no posts” for a featured hashtag that someone uses very frequently. I can see the user’s posts just fine from the affected server so it’s not an issue of the posts not federating. When looking at my own featured hashtags on my own server, or looking at local users’ featured hashtags, the date appears to be correct, only remote accounts seem to be affected.

For example, https://mastodon.social/api/v1/accounts/109281825849025262/featured_tags should be the featured tags of my own mastodon.online account, viewed from mastodon.social. The `last_status_at` for the swiftui hashtag is `2024-02-19`, almost a year ago, but I’ve posted about it several times since then, including in the last few days.

Possibly related to #22665 where someone saw the `last_status_at` date getting updated correctly but not the `statuses_count`. In my case, the `last_status_at` is also incorrect.

### Mastodon instance

mastodon.social, mastodon.online, mastodon.gamedev.place

### Mastodon version

v4.4.0-nightly.2024-12-18, v4.3.2

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #33357

Note that this does not retroactively recount affected stats, for performance reasons.

### CODE REVIEW

**Review by oneiros — APPROVED** [review]

File: app/lib/activitypub/activity/create.rb [hunk 1]
```diff
@@ -53,6 +53,7 @@ def process_status
     ApplicationRecord.transaction do
       @status = Status.create!(@params)
       attach_tags(@status)
+      attach_mentions(@status)
```
Comment (renchap) [inline app/lib/activitypub/activity/create.rb:56]: Why do we need to call `attach_mentions` here? I am not sure I understand how it relates

Comment (ClearlyClaire) [reply app/lib/activitypub/activity/create.rb:56]: `attach_tags` was handling both hashtags and mentions, I split `attach_tags` into `attach_tags` and `attach_mentions` because I thought that was confusing

Comment (renchap) [reply app/lib/activitypub/activity/create.rb:56]: Ha yes I missed the new `def attach_mentions` line in the diff, thanks!
