### PR TITLE
Fix parsing `TRUSTED_PROXY_IP`

### LINKED ISSUE #13288: TRUSTED_PROXY_IP apparently non functional
In an effort to close tootsuit/flodgatt#23, I am attempting to duplicate the functionality of the Node.js's `TRUSTED_PROXY_IP` environmental value.  However, unless I'm misunderstanding
something – entirely possible! – that environmental variable is currently non-functional.

That variable is read just once, on line 111:

```js
app.set('trusted proxy', process.env.TRUSTED_PROXY_IP || 'loopback,uniquelocal');
```

Based on the relevant [Express documentation](http://expressjs.com/en/guide/behind-proxies.html), this line has no effect for two reasons.  First, it has a typo: the relevant Express setting is set with the key `'trust proxy'`, not `'trusted proxy'`.  Based on
this alone, the environmental variable doesn't have any effect.

Second, I'm not sure that setting `'trust proxy'` would have any effect either. According to the docs:

> Enabling trust proxy will have the following impact:
> * The value of req.hostname is derived from the value set in the X-Forwarded-Host header, which can be set by the client or by the proxy.
> * X-Forwarded-Proto can be set by the reverse proxy to tell the app whether it is https or http or even an invalid name. This value is reflected by req.protocol.
> * The req.ip and req.ips values are populated with the list of addresses from X-Forwarded-For.

However, the streaming server does not currently read any of these values as far as I can tell.

Given all of the above, would it make sense to cut the `TRUSTED_PROXY_IP` variable altogether? If it is currently non-functional and no one has noticed, it must not be strongly in demand.  Checking the commit that added it (cfea28216f), it appears that we may never have needed the variable – I think the `setRemoteAddress` function achieves the commit's goals without needing the (nonfunctional) call to `app.set`.

On the other hand, if we do want to keep `TRUSTED_PROXY_IP`, we should probably correct the `app.set` call and read the variables it sets.  If we go that route, I can duplicate the new behavior for Flodgatt.

### PR DESCRIPTION
**Pull request by ykzts**
The `TRUSTED_PROXY_IP` requires a space delimiter (e.g. `130.211.0.0/22 35.191.0.0/16`) in the Rails App, while the streaming server requires a comma delimiter (e.g. `130.211.0.0/22,35.191.0.0/16`) is requested. This is confusing and should be corrected so that both can use both space and comma delimiters.

Closes #13288

### CODE REVIEW

File: streaming/index.js [hunk 1]
```diff
@@ -146,7 +146,7 @@ const startWorker = async (workerId) => {
 
   const app = express();
 
-  app.set('trusted proxy', process.env.TRUSTED_PROXY_IP || 'loopback,uniquelocal');
+  app.set('trust proxy', process.env.TRUSTED_PROXY_IP ? process.env.TRUSTED_PROXY_IP.split(/(?:\s*,\s*|\s+)/) : 'loopback,uniquelocal');
```
Comment (ykzts) [inline streaming/index.js:149]: It seems that `trust proxy` is a valid value in express.

https://expressjs.com/en/guide/behind-proxies.html

**Review by Gargron — APPROVED** [review]
