### PR TITLE
Fix intermediary responsive layout, accessibility on navigation in web UI

### LINKED ISSUE #19321: Accessibility: new web interface has unlabeled links with screen readers
### Steps to reproduce the problem

1. Go to mastodon.social or mastodon.online
2. Enable a screen reader (i used talkback on android
3. Touch the mastodon logo and talkback reads "link
4. Touch the hashtag, local, fedi, and more along the right edge and talkback only reads " link" for each
...

### Expected behaviour

the links should be properly labeled such as "explore" for the hashtag link, "local timeline" "federated timeline" and "more options"

### Actual behaviour

Talkback only reads "link" when these elements are in focus

### Specifications

Frontend issue
Firefox v105
Android 11

### PR DESCRIPTION
**Pull request by Gargron**
There was an intermediary responsive layout that showed the layout without the compose panel, but did not provide any way to access compose or your own profile. I've extended the "no-gap" breakpoint to get rid of it.

Also, added titles and aria descriptions to some navigation elements that were missing them. Apparently, the navigation panel was not using the dedicated `ColumnLink` components!

Fix #19321

### CODE REVIEW

**Comment by ykzts** [comment]
#19321 ?

File: app/javascript/mastodon/features/ui/components/navigation_panel.js [hunk 1]
```diff
@@ -1,24 +1,46 @@
-import PropTypes from 'prop-types';
 import React from 'react';
-import { FormattedMessage } from 'react-intl';
-import { Link, NavLink } from 'react-router-dom';
+import PropTypes from 'prop-types';
+import { defineMessages, injectIntl } from 'react-intl';
+import { Link } from 'react-router-dom';
 import Icon from 'mastodon/components/icon';
```
Comment (ykzts) [inline app/javascript/mastodon/features/ui/components/navigation_panel.js:5]: Remove this line.

**Review by ykzts — CHANGES_REQUESTED** [review]

**Review by ykzts — APPROVED** [review]
