### PR TITLE
User agent for WebFinger

### LINKED ISSUE #6294: Webfinger requests do not contain hostname in user agent
As in title. they just say `http.rb/2.2.2` in the user agent. so if a webfinger fails, I will not know which instance tried to find a specific user.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### PR DESCRIPTION
**Pull request by hcmiya**
closes #6294

### CODE REVIEW

File: lib/mastodon/version.rb [hunk 1]
```diff
@@ -48,5 +48,9 @@ def source_url
         source_base_url
       end
     end
+
+    def user_agent
+      @user_agent ||= "#{HTTP::Request::USER_AGENT} (Mastodon/#{Version}; +http#{Rails.configuration.x.use_https ? 's' : ''}://#{Rails.configuration.x.local_domain}/)"
```
Comment (ThibG) [inline lib/mastodon/version.rb]: Why not use `root_url`? Also, this is going to link to e.g., https://sitedethib.com instead of https://social.sitedethib.com, (`WEB_DOMAIN` vs. `LOCAL_DOMAIN`) which isn't a huge deal I guess, but it still feels a bit weird.

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]

File: lib/mastodon/version.rb (hunk 1 above)
Comment (hcmiya) [reply lib/mastodon/version.rb]: `root_url` requires `RoutingHelper` but not loaded in this scope.
I will rewrite to use WEB_DOMAIN...

**Review by Gargron — APPROVED** [review]

**Review by ClearlyClaire — APPROVED** [review]

**Comment by Gargron** [comment]
CircleCI not working here..?
