### PR TITLE
Fix `LinkCrawlWorker` error when encountering empty OEmbed response

### LINKED ISSUE #28233: LinkCrawlWorker throws a NoMethodError `[]` for `nilClass` because Link Oembed json resolves to "null"
This is mostly a reproducibility report for a certain bug that'll cause `LinkCrawlWorker`s to pile up in the dead queue.

Given a status which contains the following link;
- https://www.fimfiction.net/oembed\?url\=https%3A%2F%2Fwww.fimfiction.net%2Fblog%2F1027689%2Fasking-for-help

It'll eventually crash a `LinkCrawlWorker` with the following error;

`NoMethodError: undefined method '[]' for nil:NilClass`

Because of the following backtrace;

<details>
<summary>Backtrace</summary>

```
live/app/services/fetch_oembed_service.rb:103:in `validate'
live/app/services/fetch_oembed_service.rb:88:in `fetch!'
live/app/services/fetch_oembed_service.rb:19:in `call'
live/app/services/fetch_link_card_service.rb:107:in `attempt_oembed'
live/app/services/fetch_link_card_service.rb:42:in `process_url'
live/app/services/fetch_link_card_service.rb:28:in `block in call'
live/app/models/concerns/lockable.rb:12:in `block (2 levels) in with_redis_lock'
live/vendor/bundle/ruby/3.0.0/gems/mario-redis-lock-1.2.1/lib/redis_lock.rb:44:in `acquire'
live/app/models/concerns/lockable.rb:10:in `block in with_redis_lock'
live/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with'
live/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt'
live/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with'
live/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt'
live/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with'
live/app/lib/redis_configuration.rb:10:in `with'
live/app/models/concerns/redisable.rb:9:in `with_redis'
live/app/models/concerns/lockable.rb:9:in `with_redis_lock'
live/app/services/fetch_link_card_service.rb:26:in `call'
live/app/workers/link_crawl_worker.rb:9:in `perform'
```

</details>

Because `body` on the following line will become the string `"null"`;

https://github.com/mastodon/mastodon/blob/89a8e6e6227eb901b5811d8417d81dc8ab1427a9/app/services/fetch_oembed_service.rb#L84

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #28233

### CODE REVIEW

File: app/services/fetch_oembed_service.rb [hunk 1]
```diff
@@ -100,7 +100,7 @@ def parse_for_format(body)
   end
 
   def validate(oembed)
-    oembed if oembed[:version].to_s == '1.0' && oembed[:type].present?
+    oembed if oembed.present? && oembed[:version].to_s == '1.0' && oembed[:type].present?
```
Comment (mjankowski) [inline app/services/fetch_oembed_service.rb:103]: Does this handle the scenario where a response body was present ... but was not parsable in the prior `Oj.load` step?

**Review by renchap — APPROVED** [review]

**Comment by stevek101** [comment]
Since installing 4.2.4, the IndexingScheduler is running nonstop (4-7 Scheduler::IndexingScheduler jobs running). This is maxxing the CPU. Could this be related to the LinkCrawlWorker changes?

**Comment by ClearlyClaire** [comment]
No, that does not seem related at all. Can you open an issue for this, with information on your Elasticsearch deployment, whether you updated from 4.2.3 or from an older release, what size your instance is and whether you have had a recent increase in traffic?
