### PR TITLE
Change “Translate” button to only show up when a translation backend is configured

### LINKED ISSUE #19346: Translate link shows up even if no translation backend is configured
### Steps to reproduce the problem

1. Do not set a translation backend
2. Find a post in a different language than your interface language

### Expected behaviour

No “Translate” button is displayed

### Actual behaviour

A “Translate” button shows up and triggers a 404 Not Found error

### Specifications

Latest `main`

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Also export the information in `/api/v2/instance` as a `translation` attribute in the `configuration` object.

Fixes #19346 #19328.

### CODE REVIEW

File: app/lib/translation_service.rb [hunk 1]
```diff
@@ -17,6 +17,12 @@ def self.configured
     end
   end
 
+  def self.configured?
+    configured.present?
```
Comment (Gargron) [inline app/lib/translation_service.rb:21]: Probably don't need to instantiate a new class just to check if `DEEPL_API_KEY` or `LIBRE_TRANSLATE_ENDPOINT` are set.

**Review by Gargron — APPROVED** [review]
