### PR TITLE
Change RSS feeds

### LINKED ISSUE #10782: improve the rss feeds to work as media rss
### Pitch
I tried using the rss feed of a mastodon account (https://high.cat/@archillect.rss) as a media rss source for variety wallpaper changer. Variety claims this feed isnt a proper media rss feed (such as e.g. https://backend.deviantart.com/rss.xml?q=gallery%3Ajollyjack&type=deviation ).

Would it be possible to adapt the feeds of mastodon accounts to behave like this?

### LINKED ISSUE #14538: Include images in toot content for Feed readers
### Expected behaviour

When opening the Feed for a Mastodon account in a typical feed reader, and viewing the entry for a toot that has one or more images, those images should rendered by the reader as part of the content.

### Actual behaviour

Only the text is shown. Neither the first nor other images are included in the the content or anywhere else in the reader interfaces.

### Steps to reproduce the problem

1. Open <https://polyglot.city/@krinkle.rss> in a common feed reader, such as the NetNewsWire app on iOS or macOS.
2. Observe that in the overview, there is no cover image.
3. Observe that when rendering an entry, there is not a single image.

| Original | Feed reader
|--|--
| Mastodon site | NetNewsWire

### Specifications

* Mastodon v3.2.0.

In searching for related I found, but I'm not sure if these cover this issue (https://github.com/tootsuite/mastodon/issues/7444, https://github.com/tootsuite/mastodon/issues/9286). I also noticed several mentions of an Atom feed, but in the HTML head on profile pages I only found an rss+xml feed and an activity+json feed.

### LINKED ISSUE #17392: Use `media` extension to better describe media in RSS feed.
Right now multiple images on one post are represented as multiple top-level `<enclosure>` elements. Unfortunately what this means varies wildly between feeds as to be basically useless. In some cases it is meant to be multiple representations of the same image (different quality, formats...) whereas for some feeds (like mastodon's current feed) it represents multiple different images. [The specification](https://validator.w3.org/feed/docs/rss2.html#ltenclosuregtSubelementOfLtitemgt) doesn't even mention if multiple enclosures are allowed.

```xml
<rss version="2.0">
  <channel>
    <item>
      <enclosure url="{{image1.url}}" length="{{image1.size}}" type="{{image1.mime}}"/>
      <enclosure url="{{image2.url}}" length="{{image2.size}}" type="{{image2.mime}}"/>
    </item>
  </channel>
</rss>
```

In order to mitigate this and ensure a consistent experience across RSS clients I think the [mrss AKA media extension](https://www.rssboard.org/media-rss#media-group) should be used. This is a widely supported extension which has support for explicit grouping. The end result would look something like:

```xml
<rss version="2.0" xmlns:media="http://search.yahoo.com/mrss/">
  <channel>
    <item>
      <!-- Deprecated legacy elements to minimize change -->
      <enclosure url="{{image1.url}}" length="{{image1.size}}" type="{{image1.mime}}"/>
      <enclosure url="{{image2.url}}" length="{{image2.size}}" type="{{image2.mime}}"/>

      <!-- New more well defined structure -->
      <media:group>
        <media:content url="{{image1.url}}" fileSize="{{image1.size}}" type="{{image1.mime}}" isDefault="true" height="{{image1.height}}" width="{{image1.width}}" />
      </media:group>
      <media:group>
        <media:content url="{{image2.url}}" fileSize="{{image2.size}}" type="{{image2.mime}}" isDefault="true" height="{{image2.height}}" width="{{image2.width}}" />
      </media:group>
    </item>
  </channel>
</rss>
```

This also opens the door to other rich information such as [description](https://www.rssboard.org/media-rss#media-description).

### PR DESCRIPTION
**Pull request by Gargron**
- Use date and time for titles instead of ellipsized text
- Use full content in body, even when there is a content warning
- Use media extensions

Fix #17392, fix #14538, fix #10782

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

File: app/lib/emoji_formatter.rb [hunk 1]
```diff
@@ -85,14 +86,29 @@ def count_tag_nesting(tag)
...
+    animate? ? 'emojione' : 'emojione custom-emoji'
+  end
+
+  def image_style
+    @options[:style]
   end
 
   def animate?
-    @options[:animate]
+    @options[:animate] || @options.key?(:style)
```
Comment (ClearlyClaire) [inline app/lib/emoji_formatter.rb:112]: What?

Comment (Gargron) [reply app/lib/emoji_formatter.rb:112]: If we use inline styles, we won't be using JS to animate on-hover

Comment (ClearlyClaire) [reply app/lib/emoji_formatter.rb:112]: Alright, though that makes the method's name pretty misleading and the whole thing a little harder to understand.
