### PR TITLE
Disable submit button when no text.

### LINKED ISSUE #1961: 422 when trying to submit an empty status
To reproduce:
* Don't enter any status text
* Click `Toot` (or whatever)

Expected behavior:
* The button should probably just be disabled if there's no text

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

### PR DESCRIPTION
**Pull request by zautumnz**
Fixes #1961

### CODE REVIEW

**Comment by Gargron** [comment]
Actually, the reason this isn't already the case is that we want to greet users with a blue, ready-to-go "toot" button, rather than a grayed out one.

I suggest that perhaps you could achieve a similar effect just by returning early from the submitCompose action if the text is empty

**Comment by zacanger** [comment]
Ah, understood. Changed to return early from `submitCompose` if no text, and dispatch a `success` so the button and textarea aren't disabled.

File: app/assets/javascripts/components/actions/compose.jsx [hunk 1]
```diff
@@ -74,8 +74,13 @@ export function mentionCompose(account, router) {
 export function submitCompose() {
   return function (dispatch, getState) {
     dispatch(submitComposeRequest());
+    const status = emojione.shortnameToUnicode(getState().getIn(['compose', 'text'], ''));
+    if (!status || !status.length) {
```
Comment (Gargron) [inline app/assets/javascripts/components/actions/compose.jsx]: It can be simpler. Just do this before the dispatch of the request above, then you don't have to dispatch an extra success

**Review by Gargron — CHANGES_REQUESTED** [review]

File: app/assets/javascripts/components/actions/compose.jsx (hunk 1 above)
Comment (zacanger) [inline app/assets/javascripts/components/actions/compose.jsx]: Fix, thanks.

**Review by Gargron — APPROVED** [review]
