### PR TITLE
Fix duplicate notifications in notification groups when using slow mode

### LINKED ISSUE #32993: Duplicate notifications in notification groups in slow mode
### Steps to reproduce the problem

1. Enable slow mode
2. Get some notifications in a group that is already displayed
3. Load the pending notifications

### Expected behaviour

Older notifications are not re-added to the group

### Actual behaviour

Loading pending notifications causes already-loaded notifications to be duplicated

### Detailed description

This is because the logic in the following code does not distinguish between old and new notifications:
https://github.com/mastodon/mastodon/blob/174c687ca0234285fac87d47196bbf0b1b606c33/app/javascript/mastodon/reducers/notification_groups.ts#L534-L543

### Mastodon instance

any

### Mastodon version

v4.3.1

### Browser name and version

any

### Operating system

any

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #32993

This adds a `partial` boolean to notification groups to indicate whether they contain only new notifications (`partial: true`, coming from the streaming server) or they contain (a summary of) all notifications for the group (`partial: false`, comes from the REST API).

This new flag is used to conditionally replace (if `partial: false`) or extend (if `partial: true`) existing groups in slow mode.

### CODE REVIEW

File: app/javascript/mastodon/models/notification_group.ts [hunk 1]
```diff
@@ -171,31 +176,33 @@ export function createNotificationGroupFromJSON(
...
     sampleAccountIds: [notification.account.id],
     group_key: notification.group_key,
     notifications_count: 1,
-    type: notification.type,
     most_recent_notification_id: notification.id,
     page_min_id: notification.id,
     page_max_id: notification.id,
     latest_page_notification_at: notification.created_at,
-  } as NotificationGroup;
+    partial: true,
```
Comment (renchap) [inline app/javascript/mastodon/models/notification_group.ts:204]: Should this be hardcoded here? I have a feeling that this function could be use in both cases, and the caller knows if its partial or not, so I would add it as a function parameter?

File: app/javascript/mastodon/models/notification_group.ts [hunk 2]
```diff
@@ -204,24 +211,37 @@ export function createNotificationGroupFromNotificationJSON(
     case 'mention':
     case 'poll':
     case 'update':
-      return { ...group, statusId: notification.status?.id };
+      return {
+        ...group,
+        type: notification.type,
```
Comment (renchap) [inline app/javascript/mastodon/models/notification_group.ts:216]: I assume those changes were made so Typescript better understands the notification type, but I am not sure I understand what this PR changed that requires it?

Comment (ClearlyClaire) [reply app/javascript/mastodon/models/notification_group.ts:216]: The is the first commit. The second one does not require it, but as I was working on the PR, I noticed Typescript did not catch type errors there, because of the `as NotificationGroup` which basically bypassed it.

Comment (ClearlyClaire) [reply app/javascript/mastodon/models/notification_group.ts:216]: This is required for the change in the first commit because Typescript does not keep track of the fact that `group.type` was equal to `notification.type`, while in the `switch` case, it does keep track of the value and can correctly handle the different cases.

**Review by renchap — APPROVED** [review]
