### PR TITLE
Fix tag normalization and migration not removing duplicate tags

### LINKED ISSUE #11428: db:migrate fails after #11416
### Actual behaviour

If I update to #11416 or later Mastodon master branch, `db:migrate` will fail.
At that time, the following error occurs:

    Migrating to AddCaseInsensitiveIndexToTags (20190726175042)
    == 20190726175042 AddCaseInsensitiveIndexToTags: migrating ====================
    -- execute("CREATE UNIQUE INDEX CONCURRENTLY index_tags_on_name_lower ON tags (lower(name))")
    rake aborted!
    StandardError: An error has occurred, all later migrations canceled:

    PG::UniqueViolation: ERROR:  could not create unique index "index_tags_on_name_lower"
    DETAIL:  Key (lower(name::text))=(pawoo人増えたし自己紹介しようぜ) is duplicated.`

~~I think this is happening because hashtags `pawoo...` and `Pawoo...` exist.~~
I'm sorry, capital letters were also registered in tags table in lower case.

However, it seems that the same problem occurs with hashtags with only Japanese strings.

https://mastodon.zunda.ninja/@zundan/102520658283114897
>     PG::UniqueViolation: ERROR:  could not create unique index "index_tags_on_name_lower"
>     DETAIL:  Key (lower(name::text))=(銀河丼だじゃれ部) is duplicated.

### Specifications

Equivalent to Mastodon master branch f371b32137ccd7e74ca29d25af2072fb79654b15 or later

### PR DESCRIPTION
**Pull request by Gargron**
Fix #11428

### CODE REVIEW

**Comment by mayaeh** [comment]
The following error occurred in my environment:

    $ RAILS_ENV=production bundle exec rake db:migrate
    Migrating to AddCaseInsensitiveIndexToTags (20190726175042)
    == 20190726175042 AddCaseInsensitiveIndexToTags: migrating ====================
    -- execute("CREATE UNIQUE INDEX CONCURRENTLY index_tags_on_name_lower ON tags (lower(name))")
    rake aborted!
    StandardError: An error has occurred, all later migrations canceled:

    PG::UniqueViolation: ERROR:  could not create unique index "index_tags_on_name_lower"
    DETAIL:  Key (lower(name::text))=(pawoo人増えたし自己紹介しようぜ) is duplicated.
    : CREATE UNIQUE INDEX CONCURRENTLY index_tags_on_name_lower ON tags (lower(name))

However, this may be due to  my trial and error...

**Comment by mayaeh** [comment]
I applied this PR and ran `db:migrate`.
The following error occurred in my environment:

    $ RAILS_ENV=production bundle exec rake db:migrate
    Migrating to AddCaseInsensitiveIndexToTags (20190726175042)
    == 20190726175042 AddCaseInsensitiveIndexToTags: migrating ====================
    -- execute("UPDATE accounts_tags SET tag_id = 887 WHERE tag_id IN (2368)")
       -> 0.0035s
    -- execute("UPDATE statuses_tags SET tag_id = 887 WHERE tag_id IN (2368)")
       -> 0.0078s
    -- execute("UPDATE account_tag_stats SET tag_id = 887 WHERE tag_id IN (2368)")
       -> 0.0049s
    -- execute("UPDATE featured_tags SET tag_id = 887 WHERE tag_id IN (2368)")
       -> 0.0008s
    -- execute("UPDATE accounts_tags SET tag_id = 1814 WHERE tag_id IN (1813)")
       -> 0.0004s
    -- execute("UPDATE statuses_tags SET tag_id = 1814 WHERE tag_id IN (1813)")
       -> 0.0032s
    -- execute("UPDATE account_tag_stats SET tag_id = 1814 WHERE tag_id IN (1813)")
    rake aborted!
    StandardError: An error has occurred, all later migrations canceled:

    PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_account_tag_stats_on_tag_id"
    DETAIL:  Key (tag_id)=(1814) already exists.
    : UPDATE account_tag_stats SET tag_id = 1814 WHERE tag_id IN (1813)

1813 and 1814 are as follows:

    $ bundle exec rails console

    Tag.where("name like 'pawoo人増えたし自己紹介しようぜ%'").select('id','name')
    => #<ActiveRecord::Relation [#<Tag id: 192, name: "pawoo人増えたし自己紹介しようぜ">, #<Tag id: 1687, name: "pawoo人増えたし自己紹介しようぜ">, #<Tag id: 1813, name: "pawoo人増えたし自己紹介しよう">, #<Tag id: 1814, name: "pawoo人増えたし自己紹介しよう">]>

**Comment by Gargron** [comment]
I have updated the migration to omit updating rows where a row with the canonical tag already exists. Can you please try again @mayaeh?

**Comment by mayaeh** [comment]
Thank you! I will try now.

File: db/migrate/20190726175042_add_case_insensitive_index_to_tags.rb [hunk 1]
```diff
@@ -2,6 +2,20 @@ class AddCaseInsensitiveIndexToTags < ActiveRecord::Migration[5.2]
...
 
   def up
+    Tag.connection.select_all('SELECT string_agg(id::text, \',\') AS ids FROM tags GROUP BY lower(name) HAVING count(*) > 1').to_hash.each do |row|
+      canonical_tag_id  = row['ids'].split(',').first
+      redundant_tag_ids = row['ids'].split(',')[1..-1]
+
+      safety_assured do
+        execute "UPDATE accounts_tags AS t0 SET tag_id = #{canonical_tag_id} WHERE tag_id IN (#{redundant_tag_ids.join(', ')}) AND NOT EXISTS (SELECT t1.tag_id FROM accounts_tags AS t1 WHERE t1.tag_id = #{canonical_tag_id} AND t1.account_id = t0.account_id)"
+        execute "UPDATE statuses_tags AS t0 SET tag_id = #{canonical_tag_id} WHERE tag_id IN (#{redundant_tag_ids.join(', ')}) AND NOT EXISTS (SELECT t1.tag_id FROM statuses_tags AS t1 WHERE t1.tag_id = #{canonical_tag_id} AND t1.status_id = t0.status_id)"
+        execute "UPDATE account_tag_stats AS t0 SET tag_id = #{canonical_tag_id} WHERE tag_id IN (#{redundant_tag_ids.join(', ')})  AND NOT EXISTS (SELECT t1.tag_id FROM account_tag_status AS t1 WHERE t1.tag_id = #{canonical_tag_id} AND t1.account_id = t0.account_id)"
```
Comment (mayaeh) [inline db/migrate/20190726175042_add_case_insensitive_index_to_tags.rb]: @Gargron  Perhaps, `SELECT t1.tag_id FROM account_tag_stats` instead of `SELECT t1.tag_id FROM account_tag_status`?

Comment (Gargron) [reply db/migrate/20190726175042_add_case_insensitive_index_to_tags.rb]: Oops

**Comment by mayaeh** [comment]
Errors still occur in my environment.

    $ RAILS_ENV=production bundle exec rake db:migrate
    Migrating to AddCaseInsensitiveIndexToTags (20190726175042)
    == 20190726175042 AddCaseInsensitiveIndexToTags: migrating ====================
    -- execute("UPDATE accounts_tags AS t0 SET tag_id = 1813 WHERE tag_id IN (1814) 
    AND NOT EXISTS (SELECT t1.tag_id FROM accounts_tags AS t1 WHERE t1.tag_id = 1813
     AND t1.account_id = t0.account_id)")
       -> 0.0013s
    -- execute("UPDATE statuses_tags AS t0 SET tag_id = 1813 WHERE tag_id IN (1814) 
    AND NOT EXISTS (SELECT t1.tag_id FROM statuses_tags AS t1 WHERE t1.tag_id = 1813 
    AND t1.status_id = t0.status_id)")
       -> 0.0011s
    -- execute("UPDATE account_tag_stats AS t0 SET tag_id = 1813 WHERE tag_id IN 
    (1814)  AND NOT EXISTS (SELECT t1.tag_id FROM account_tag_stats AS t1 WHERE t1.tag_
    id = 1813 AND t1.account_id = t0.account_id)")
    rake aborted!
    StandardError: An error has occurred, all later migrations canceled:

    PG::UndefinedColumn: ERROR:  column t1.account_id does not exist
    LINE 1: ...ccount_tag_stats AS t1 WHERE t1.tag_id = 1813 AND t1.account...
                                                                 ^
    : UPDATE account_tag_stats AS t0 SET tag_id = 1813 WHERE tag_id IN (1814)  
    AND NOT EXISTS (SELECT t1.tag_id FROM account_tag_stats AS t1 WHERE t1.tag_id = 1813 
    AND t1.account_id = t0.account_id)

**Comment by Gargron** [comment]
Sorry, I got confused about what `account_tag_stats` represents. There is need to update it. Fixed

**Comment by mayaeh** [comment]
Thank you! I will try now.

**Comment by mayaeh** [comment]
The following error still occurred.
Is this because I ran `db: migrate` after #11416 ?

    rake aborted!
    StandardError: An error has occurred, all later migrations canceled:

    PG::DuplicateTable: ERROR:  relation "index_tags_on_name_lower" already exists
    : CREATE UNIQUE INDEX CONCURRENTLY index_tags_on_name_lower ON tags (lower(name))

**Comment by Gargron** [comment]
Yes, probably. Try to drop that index manually first.

**Comment by mayaeh** [comment]
I ran `DROP INDEX index_tags_on_name_lower;`.
But I got the following error:

    $ RAILS_ENV=production bundle exec rake db:migrate
    Migrating to AddCaseInsensitiveIndexToTags (20190726175042)
    == 20190726175042 AddCaseInsensitiveIndexToTags: migrating ====================
    -- execute("CREATE UNIQUE INDEX CONCURRENTLY index_tags_on_name_lower ON tags (lower(name))")
       -> 0.0542s
    -- remove_index(:tags, {:name=>"index_tags_on_name"})
    rake aborted!
    StandardError: An error has occurred, all later migrations canceled:

    PG::UndefinedObject: ERROR:  index "index_tags_on_name" does not exist
    : DROP INDEX  "index_tags_on_name"

So I commented out [this line](https://github.com/tootsuite/mastodon/pull/11441/files#diff-d56e91e82e9e17460ce5b3d81364a323R19) (`remove_index :tags, name: 'index_tags_on_name'`) and executed `db:migrate`.
Then `db:migrate` succeeded successfully.

Perhaps I think this error only happens to people running `db:migrate` after 11416

**Review by mayaeh — APPROVED** [review]
