### PR TITLE
Fix `/api/v2/search` not working with following query param

### LINKED ISSUE #25678: Search V2 API set query param following=true not working
### Steps to reproduce the problem

1. Call https://[instance]/api/v2/search?q=no&type=accounts&limit=20&offset=0&following=true

### Expected behaviour

Search results return only accounts that are followed

### Actual behaviour

Search results include accounts that are not followed

### Detailed description

I encounter the same issue as described in https://github.com/mastodon/documentation/issues/876

### Specifications

Reproduced with mastodon.world which says is using Mastodon v4.1.2+nightly-20230517

### PR DESCRIPTION
**Pull request by danielmbrasil**
Fixes #25678.

### CODE REVIEW

File: app/services/search_service.rb [hunk 1]
```diff
@@ -31,7 +31,8 @@ def perform_accounts_search!
       limit: @limit,
       resolve: @resolve,
       offset: @offset,
-      use_searchable_text: true
+      use_searchable_text: true,
+      following: @options[:following]&.downcase == 'true'
```
Comment (Gargron) [inline app/services/search_service.rb:35]: Use `truthy_param?(:following)` in the controller instead

**Review by Gargron — COMMENTED** [review]
Was this ever supposed to work on this API?

**Review by Gargron — APPROVED** [review]
