### PR TITLE
Streaming: Improve Redis connection options handling

### LINKED ISSUE #29770: Inconsistent handling of REDIS environment variables across streaming and puma images
### Steps to reproduce the problem

It seems that the redis configuration is being parsed differently in `streaming/index.js` to the rest of Mastodon. 

Specifically in `redisConfigFromEnv`:

``` 
const redisConfigFromEnv = (env) => {
  ...
  let redisPort = parseIntFromEnv(env.REDIS_PORT, 6379, 'REDIS_PORT');
  let redisDatabase = parseIntFromEnv(env.REDIS_DB, 0, 'REDIS_DB');

  /** @type {import('ioredis').RedisOptions} */
  const redisParams = {
    host: env.REDIS_HOST || '127.0.0.1',
    port: redisPort,
    db: redisDatabase,
    password: env.REDIS_PASSWORD || undefined,
  };

  return {
    redisParams,
    redisPrefix,
    redisUrl: typeof env.REDIS_URL === 'string' ? env.REDIS_URL : undefined,
  };
```
This code will cause an exception when `REDIS_PORT` contains any `NaN` string other than `""`, even when `REDIS_URL` is used to overwrite this very setting. 

This is inconsistent with how the rest of mastodon handles the redis configuration, where all other `REDIS_` env variables are ignored as long as a `REDIS_URL` is provided.

### Expected behaviour

Both streaming, sidekiq and puma should interpret the config the same

### Actual behaviour

streaming processes `REDIS_PORT` and `REDIS_DB` even when `REDIS_URL` is set.

### Detailed description

_No response_

### Mastodon instance

_No response_

### Mastodon version

_No response_

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)

### PR DESCRIPTION
**Pull request by ThisIsMissEm**
This does the following:

- [x] Migrates streaming to using `keyPrefix` which appears to work correctly in ioredis, since we don't use KEYS or SCAN commands. Note: we still need to manually prefix `subscribe` and `unsubscribe` commands.
- [x] Prefers `REDIS_URL` over all other `REDIS_*` options. This does mean that we don't merge those options with `REDIS_URL`, which is the expected behavior from the Ruby side. Fixes #29770 
- [x] Adds support for Redis in Sentinel mode, per #26571, but uses the following environment variables:
  - `REDIS_SENTINELS`
  - `REDIS_SENTINEL_MASTER`
  - `REDIS_SENTINEL_PORT`
  - `REDIS_SENTINEL_USERNAME` (defaults to `REDIS_USERNAME`)
  - `REDIS_SENTINEL_PASSWORD` (defaults to `REDIS_PASSWORD`)

We may also want to consider a method here for setting TLS options.

### CODE REVIEW

File: streaming/redis.js [hunk 1]
```diff
@@ -4,44 +4,110 @@ import { parseIntFromEnvValue } from './utils.js';
...
+      // https://github.com/redis/ioredis/issues/1576
+      family: 0
+    };
+  });
+
+  return {
+    db: redisDatabase,
+    name: env.REDIS_SENTINEL_MASTER,
+    username: env.REDIS_USERNAME,
+    password: env.REDIS_PASSWORD,
```
Comment (ThisIsMissEm) [inline streaming/redis.js:53]: I'm not sure if these are necessary here / if there's potential for different passwords?

File: streaming/redis.js [hunk 2]
```diff
@@ -4,44 +4,110 @@ import { parseIntFromEnvValue } from './utils.js';
...
+ *
+ * @param {NodeJS.ProcessEnv} env
+ * @returns {boolean}
+ */
+function hasSentinelConfiguration(env) {
+  return (
+    typeof env.REDIS_SENTINELS === 'string' &&
+    env.REDIS_SENTINELS.length > 0 &&
+    typeof env.REDIS_SENTINEL_MASTER === 'string' &&
+    env.REDIS_SENTINEL_MASTER.length > 0
```
Comment (ThisIsMissEm) [inline streaming/redis.js:21]: I think we want to require both `REDIS_SENTINELS` and `REDIS_SENTINEL_MASTER` to enable sentinel mode, rather than setting a default master name like `mymaster` which was originally in #26571.

File: streaming/redis.js [hunk 3]
```diff
@@ -4,44 +4,110 @@ import { parseIntFromEnvValue } from './utils.js';
...
+      port: port ?? sentinelPort,
+      // Force support for both IPv6 and IPv4, by default ioredis sets this to 4,
+      // only allowing IPv4 connections:
+      // https://github.com/redis/ioredis/issues/1576
+      family: 0
+    };
+  });
+
+  return {
+    db: redisDatabase,
```
Comment (ThisIsMissEm) [inline streaming/redis.js:50]: I don't see anything saying `db` wouldn't still apply in Sentinel Mode.

**Comment by ThisIsMissEm** [comment]
@oneiros I think this handles the Node.js / Streaming side of #26571 for redis sentinel mode.

@renchap I think the system specs are failing due to something in the redis connection parameters, I'm not entirely what's going wrong here?

**Comment by ThisIsMissEm** [comment]
The failure may also be due to the REDIS_NAMESPACE [override here](https://github.com/mastodon/mastodon/blob/d5f02adad716520b6b9014553bc730dcef5b2f50/lib/mastodon/redis_config.rb#L53):

```
ENV['REDIS_NAMESPACE'] = "mastodon_test#{ENV['TEST_ENV_NUMBER']}" if Rails.env.test?
```

I suspect that maybe we want this in the [`StreamingServerManager`](https://github.com/mastodon/mastodon/blob/8098d27f84028c226729c76f1ebdeadec881b1c5/spec/support/streaming_server_manager.rb) instead of in `redis_config.rb`

**Comment by ThisIsMissEm** [comment]
image

Turns out ioredis **doesn't** support `keyPrefix` for pub/sub after all. Have opened https://github.com/redis/ioredis/issues/1910 and added code to transparently add and remove the redis keyPrefix for pub/sub commands.

File: streaming/index.js [hunk 4]
```diff
@@ -273,7 +275,9 @@ const startServer = async () => {
 
     if (subs[channel].length === 0) {
       logger.debug(`Subscribe ${channel}`);
-      redisSubscribeClient.subscribe(channel, (err, count) => {
+
+      // FIXME: https://github.com/redis/ioredis/issues/1910
+      redisSubscribeClient.subscribe(`${redisNamespace}${channel}`, (err, count) => {
```
Comment (ThisIsMissEm) [inline streaming/index.js:280]: This is probably the better way of handling the keyPrefix instead of littering every `subscribe` and `unsubscribe` callsite with the prefix.

File: streaming/redis.js [hunk 5]
```diff
@@ -4,44 +4,114 @@ import { parseIntFromEnvValue } from './utils.js';
...
  * @returns {RedisConfiguration} configuration for the Redis connection
  */
 export function configFromEnv(env) {
-  // ioredis *can* transparently add prefixes for us, but it doesn't *in some cases*,
-  // which means we can't use it. But this is something that should be looked into.
-  const redisPrefix = env.REDIS_NAMESPACE ? `${env.REDIS_NAMESPACE}:` : '';
-
-  let redisPort = parseIntFromEnvValue(env.REDIS_PORT, 6379, 'REDIS_PORT');
-  let redisDatabase = parseIntFromEnvValue(env.REDIS_DB, 0, 'REDIS_DB');
+  const redisNamespace = env.REDIS_NAMESPACE ? `${env.REDIS_NAMESPACE}:` : '';
```
Comment (ThisIsMissEm) [inline streaming/redis.js:67]: This does actually need to be an empty string and not `undefined` due to how we're constructing channel names for `subscribe`/`unsubscribe` commands

**Comment by ClearlyClaire** [comment]
Do we really want to switch to `keyPrefix`? The fact that it works for some things but not others makes things particularly difficult to follow imho

**Comment by oneiros** [comment]
Having read up on this a bit, I fear that `keyPrefix` does not work for `subscribe` etc. because the argument to those functions (conceptually speaking) is not a `key` but a `channel`. There might not be a huge difference between the two in practice, but the redis docs at least hint at the fact that those are different concepts. Given that, I am doubtful that https://github.com/redis/ioredis/issues/1910 will be addressed (but maybe a separate `channelPrefix` might be considered :thinking:).

File: streaming/redis.js (hunk 1 above)
Comment (oneiros) [reply streaming/redis.js:54]: As far as I understand they can be different.

File: streaming/redis.js (hunk 3 above)
Comment (oneiros) [reply streaming/redis.js:51]: Yeah, the docs are not super-clear on this, but there needs to be a way to select a database in any case, so I agree.

File: streaming/redis.js (hunk 2 above)
Comment (oneiros) [reply streaming/redis.js:22]: I think the idea came from the sentinel docs always using "mymaster" as an example. And since this not a hostname but just an identifier, it could be assumed that many will just copy those examples.

But I agree, blindly copying examples and not using sensible identifiers is not something we need to support :slightly_smiling_face:

**Comment by oneiros** [comment]
> Do we really want to switch to keyPrefix? The fact that it works for some things but not others makes things particularly difficult to follow imho

Having looked at all of the changes in more detail now, I kind of agree with Claire. `keyPrefix` seems to simplify things, but I can only spot one `SET` command where it is actually used. And a lot of "noise" is added to simplify a single line.

I wonder if a small utility function (maybe `prefixedName()`, `namespaced()` or something similar) might not serve us better. It could be used in place of the redundant seeming template strings and would work the same for the `set` and the `subscribe`/`unsubscribe` operations.

So something like:

```js
function prefixedName(name) {
  return `${redisNamespace}${name}`;
}

// and then later

redisClient.set(prefixedName(`subscribed:${channel}`));

// and

redisSubscribeClient.subscribe(prefixedName(channell));
```

**Comment by ThisIsMissEm** [comment]
> Do we really want to switch to `keyPrefix`? The fact that it works for some things but not others makes things particularly difficult to follow imho

@ClearlyClaire I think yes, because it reduces the number of places we manually prefix to just two, making the code more maintainable imo

File: streaming/redis.js (hunk 1 above)
Comment (ThisIsMissEm) [reply streaming/redis.js:54]: Yeah, I'm just not 100% sure how they apply.

**Comment by ThisIsMissEm** [comment]
I *knew* there was a reason why we didn't just use `REDIS_URL` exclusively.. there was this issue for the database connection handling about using both `DATABASE_URL` and `DB_PASS`, so we'd be introducing variance by not supporting both `REDIS_URL` and `REDIS_PASSWORD` simultaneously.

**Comment by ThisIsMissEm** [comment]
Have revised the namespacing to not use keyPrefix and instead have two helper methods.

File: streaming/index.js [hunk 6]
```diff
@@ -111,6 +111,35 @@ const startServer = async () => {
...
+   */
+  function redisUnnamespaced(channel) {
+    if (typeof redisConfig.namespace === "string") {
+      // Note: this removes the configured namespace and the colon that is used
+      // to separate it:
+      return channel.slice(redisConfig.namespace.length + 1);
+    } else {
+      return channel;
+    }
+  }
```
Comment (ThisIsMissEm) [inline streaming/index.js:141]: I don't really like these "floating" functions, because it makes code very hard to split up later, ideally we'd have something identical to `Redis::Namespaced` from the ruby side, but for JavaScript that would wrap a Redis Client, I think. Though I'm not really wanting to get into the whole "wrapping redis clients" thing right now.

**Comment by oneiros** [comment]
> I _knew_ there was a reason why we didn't just use `REDIS_URL` exclusively.. there was this issue for the database connection handling about using both `DATABASE_URL` and `DB_PASS`, so we'd be introducing variance by not supporting both `REDIS_URL` and `REDIS_PASSWORD` simultaneously.
> 
> #26295

I do not think giving both `DATABASE_URL` and `DB_PASS` currently works on the ruby side. And there is no easy way to make it work if I am correct. The separate environment variables are being evaluated in our `config/database.yml` while `DATABASE_URL` is an override that rails offers which bypasses whatever is in `config/database.yml`. So I do not see this changing anytime soon.

Also, I see no need for it. If you want to specify the password separately, simply use the separate environment variables. If you want to give the full configuration in a single variable, use `DATABASE_URL`. I do not see why we would need to support mixed use cases. It makes the code needlessly complex, makes it harder to explain and makes it easier to introduce subtle errors.

I think the same reasoning applies to redis.

**Review by oneiros — APPROVED** [review]

**Comment by oneiros** [comment]
I just approved these changes. I am currently working on adding sentinel support to the ruby side. We should wait with merging this until both PRs are ready and then merge them together.

**Comment by oneiros** [comment]
The ruby part is ready (well, for review that is) here #31744

I combined both PRs and created a small test setup (3 redis instances, 3 sentinels) locally and everything (inlcuding failover) worked perfectly.
