### PR TITLE
Change lists to be able to include accounts with pending follow requests

### LINKED ISSUE #19707: Adding an account you just followed to a list errors out
### Steps to reproduce the problem

1. Follow account
2. Immediately add account to an existing list

### Expected behaviour

Add account to list without raw HTTP errors popping up

### Actual behaviour

404 Record not found

### Detailed description

When you try to add an account you only just followed to an existing list, it consistently errors out with a 404 Record not found toast message.

After a while, a minute or 2–3, it succeeds.

But the current behaviour will definitely have people scratch their head why this is not working.

### Specifications

v4.0.0rc1 (current mastodon.social)
Firefox 106.0.3

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #19707 by allowing accounts in lists as soon as they have a follow request, but not distributing posts to the list before the follow request is accepted.

### CODE REVIEW

File: app/models/concerns/account_interactions.rb [hunk 1]
```diff
@@ -264,6 +264,7 @@ def followers_for_local_distribution
 
   def lists_for_local_distribution
     lists.joins(account: :user)
+         .where('list_accounts.follow_id IS NOT NULL')
```
Comment (ClearlyClaire) [inline app/models/concerns/account_interactions.rb:267]: This might require an extra index: indeed, `list_accounts` are indexed by `account_id`, and by `follow_id` separately, so the query planner would have to use two indexes. It may be worth adding an index on `account_id, follow_id` (`WHERE follow_id IS NOT NULL`).

**Comment by Gargron** [comment]
The UX benefit is clear but I'm worried about touching this logic in a hurry, esp. if there are database index considerations...

**Comment by ClearlyClaire** [comment]
> The UX benefit is clear but I'm worried about touching this logic in a hurry, esp. if there are database index considerations...

Understandable. The optimal index for this is fairly simple, I just wonder if it's worth adding at all.

**Review by Gargron — APPROVED** [review]
