### PR TITLE
Fix og:images from The Guardian (and possibly other CDNs that check URL hashes)

### LINKED ISSUE #14983: WebP images don’t work in og:image (external link previews)
### Expected behaviour

Toots with WebP images in their OpenGraph thumbnail image in WebP format should work as a preview image in Mastodon. (`<meta name="og:image" content="https://example.com/image.webp">`)

### Actual behaviour

The toot is shown with the default image. The external image (WebP format) fails to load.

### Steps to reproduce the problem

Share any link from e.g. reddit.com (any thread that’s shown in their interface with an image) or ctrl.blog and open the toot in the web interface.

### Specifications

Firefox 81 on Fedora 32 and Windows 10.

### Related
[#14819 SVG support](#14819)

### PR DESCRIPTION
**Pull request by phocks**
For years this has been broken and really bugging me that Bluesky and every other site can easily get the og:images for The Guardian but Mastodon just gets a grey box. This is the easiest way I could fix it.

The problem I traced to being due to `Addressable::URI.parse(url).normalize` the normalization of the query string turns a %2C into a comma (,) and so breaks og:images due to `overlay-align=bottom%2Cleft` being turned into `overlay-align=bottom,left` and so the URL hash fails (401 error, doesn't match) and we get no image.

Getting rid of the normalization `Addressable::URI.parse(url)` is enough to fix the issue, but I understand that normalization probably is good for the host and probably the path if it contains emoji characters or languages other than English etc eg:

```
uri = Addressable::URI.parse("http://www.詹姆斯.com/")
uri.normalize
#=> #<Addressable::URI:0xc9a4c8 URI:http://www.xn--8ws00zhy3a.com/>
```

So this PR just creates a new variable with normalized host and path and the original query string.

Anyway it seems to work, finally. I'm going to make these changes on my instance so at least we can get og:images for our users. Feel free to pull this in to main or else change it to make it better, as I'm not really a Ruby developer.

Cheers, have a good one.

(Tangentially related to this closed issue which wasn't fully resolved https://github.com/mastodon/mastodon/issues/14983#issuecomment-1520594700)

Edit 2025-09-17: I'm just going to update this code to be a specific exception for The Guardian CDN which requires an un-altered URL to match the hash otherwise it gives a "Error 401 Unauthorized - invalid signature" 

So instead of:

```ruby
@url            = Addressable::URI.parse(url)
@normal_url     = Addressable::URI.new(
  scheme: @url.scheme,
  userinfo: @url.userinfo,
  host: @url.normalized_host,
  port: @url.port,
  path: @url.normalized_path,
  query: @url.query, # Don't normalize query strings. Breaks og:images on The Guardian etc.
  fragment: @url.fragment
)
```

It'll just be:

```ruby
# Skip normalization for The Guardian's signed image URLs
parsed_url = Addressable::URI.parse(url)
@url = if parsed_url.host&.downcase == 'i.guim.co.uk'
  parsed_url
else
  parsed_url.normalize
end
```

Simpler and cleaner and won't mess with other URL query strings.

Update - even simpler thanks @mjankowski  :

```ruby
@url         = Addressable::URI.parse(url).normalize
@url.query_values = @url.query_values.to_a # restore the URL encoding stripped by normalize
```

Update 2025-09-17: But that seems to be failing tests, so I'm reverting, although as commented hard coding host exceptions isn't ideal. If anyone can help that would be great. It shouldn't be this hard should it?

---

As this behaviour was previously approved and merged by @Gargron but then reverted by @ClearlyClaire (https://github.com/mastodon/mastodon/pull/26219 & https://github.com/mastodon/mastodon/commit/94893cf24fc95b32cc7a756262acbe008c20a9d2). I'm wondering if we could get their input into this? Thanks so much.

**Update 2025-09-19:** 

Found this better way to keep all the security (newlines carriage returns etc) but leave the encoded comma %2C alone.

```ruby
def normalize_and_restore_original_comma_encoding(url)
  original_uri = Addressable::URI.parse(url)

  if original_uri.query
    normalized_query = Addressable::URI.normalize_component(
      original_uri.query,
      Addressable::URI::CharacterClasses::RESERVED_AND_UNRESERVED,
      ',' # Leave commas encoded if they were originally encoded
    )

    normalized_uri = original_uri.normalize
    normalized_uri.query = normalized_query
    normalized_uri
  else
    original_uri.normalize
  end
end
```

---

Current code fixes the issue and doesn't remove normalization. All good to go.

Update 2025-10-01:

After @ClearlyClaire 's input, updated function:

```ruby
def normalize_preserving_url_encodings(url, preserved_chars = SAFE_PRESERVED_CHARS, *flags)
  original_uri = Addressable::URI.parse(url)
  normalized_uri = original_uri.normalize

  if original_uri.query
    modified_query_class = Addressable::URI::CharacterClasses::QUERY.dup
    modified_query_class.sub!('\\&', '').sub!('\\;', '')

    pairs = original_uri.query.split('&', -1)
    pairs.delete_if(&:empty?).uniq! if flags.include?(:compacted)
    pairs.sort! if flags.include?(:sorted)

    normalized_query = pairs.map do |pair|
      Addressable::URI.normalize_component(
        pair,
        modified_query_class,
        preserved_chars
      )
    end.join('&')

    normalized_uri.query = normalized_query == '' ? nil : normalized_query
  end

  normalized_uri
end
```

To more closely match query function in Addressable 

Fixes https://github.com/mastodon/mastodon/issues/36273

### CODE REVIEW

**Comment by mjankowski** [comment]
I think I get what you're saying, but -- can you give a link to an article/page which has the relevant og markup (and/or a full html snippet) that does not get properly extracted?

I think you are probably correct that we need to fix the handling of escaped query params, but I'm not sure the request class is the best spot for that, since more than just og extraction flows through there...

**Comment by phocks** [comment]
Virtually every Guardian article has this error. And yeah I tried to find a specific handling for og:images but couldn't find it sorry. I feel like query strings shouldn't be normalized anyway. Not sure. I originally thought it was an issue with The Guardian hashing the URL and then Mastodon changing the URL before querying the image so then the hashes don't match. Anyway. I need some sleep. Hope this can be fixed anyway. It's been way too long.

https://www.theguardian.com/film/live/2025/sep/16/robert-redford-dies-tributes-cinema-hollywood-legend-latest-news-updates
https://www.theguardian.com/environment/2025/sep/14/australian-bird-of-the-year-2025-poll-vote-nominate-shortlist-guardian-birdlife-australia

**Comment by Techn1x** [comment]
This looks like it was encountered and 'solved' before
https://github.com/mastodon/mastodon/pull/26219
I haven't read that fully, it's quite long, just linking because it's relevant.

But I think parts of that PR were then reverted to resolve a security advisory
https://github.com/mastodon/mastodon/commit/94893cf24fc95b32cc7a756262acbe008c20a9d2
https://github.com/mastodon/mastodon/security/advisories/GHSA-hcqf-fw2r-52g4

**Comment by mjankowski** [comment]
Yeah - I assumed at first it might be a link extraction issue, but it seems the links are extracted correctly, but then the normalize before the request is made does change the uri encoded comma back to an actual comma. Smaller example...

```
mastodon(dev)> url = "https://host.example/image.jpg?width=10&overlay-align=bottom%2Cleft"
=> "https://host.example/image.jpg?width=10&overlay-align=bottom%2Cleft"
mastodon(dev)> Addressable::URI.parse(url).to_s
=> "https://host.example/image.jpg?width=10&overlay-align=bottom%2Cleft"
mastodon(dev)> Addressable::URI.parse(url).normalize.to_s
=> "https://host.example/image.jpg?width=10&overlay-align=bottom,left"
```

I see from that history this has been attempted before, and the rollback re: security - though it's not totally clear to me if any specs emerged from that to capture the user input risk?

I wonder if something like ...

```
mastodon(dev)> url = "https://host.example/image.jpg?width=10&overlay-align=bottom%2Cleft"
=> "https://host.example/image.jpg?width=10&overlay-align=bottom%2Cleft"
mastodon(dev)> uri = Addressable::URI.parse(url).normalize
=> #<Addressable::URI:0x95a28 URI:https://host.example/image.jpg?width=10&overlay-align=bottom,left>
mastodon(dev)> uri.query_values = uri.query_values
=> {"width" => "10", "overlay-align" => "bottom,left"}
mastodon(dev)> uri.to_s
=> "https://host.example/image.jpg?overlay-align=bottom%2Cleft&width=10"
```

...where we essentially re-encode the query params that we didn't want decoded would assist with this guardian-style og:image issue, while preserving the value of the normalize?

**Comment by phocks** [comment]
Thanks everyone. I think my initial thought was correct that the Guardian's CDN uses a hash to make sure the URL hasn't been altered when requesting the image. I do understand there are security concerns around URLs and injection etc. I'd be happy with something like this just making an exception for the guardian image CDN host. Tested this and it also works. We get OG Images on The Guardian, and all other URLs are normalized. What do you reckon?

```ruby
# Skip normalization for The Guardian's signed image URLs
parsed_url = Addressable::URI.parse(url)
if parsed_url.host&.downcase == 'i.guim.co.uk'
  @url = parsed_url
else
  @url = parsed_url.normalize
end
```

Edit: Hmm I'm getting a linting error. I think might be better?

```ruby
@url = if parsed_url.host&.downcase == 'i.guim.co.uk'
 parsed_url
else
 parsed_url.normalize
end
```

Ah damn it's failing tests because of indentation. Will fix later. Gotta go to work.

**Comment by mjankowski** [comment]
We should avoid hard-coding that source if we can avoid it ... and I'm also wary of removing the `normalize` without more information about the user input possibilities we are guarding against there.

I confirmed that assigning the query values ... to themselves ... would work -- https://github.com/mastodon/mastodon/compare/main...mjankowski:request-og-image-things -- but would like to have more info first about what the normalize guards against before PR'ing that.

**Comment by phocks** [comment]
I agree hard coding an exception is not ideal. An alternative could be putting the hosts we want to ignore as a list in some kind of env value or something perhaps?

Probably also a good idea to keep the normalisation unless necessary (ie. CDNs that hash the URL). Although I saw this in the docs last night that seems to suggest it's mostly for caching issues and maybe not so much guarding against attacks etc, which the parsing function probably handles I'm guessing.

https://www.rubydoc.info/gems/addressable/Addressable/URI#normalize-instance_method

> NOTE: This method does not attempt to fully conform to specifications. It exists largely to correct other people’s failures to read the specifications, and also to deal with caching issues since several different URIs may represent the same resource and should not be cached multiple times.

I also noticed in the changelog of Addressable they sometimes don't normalise certain %strings as well, so that could be an option, we just don't normalise the comma string %2C

https://github.com/sporkmonger/addressable/blob/3450895887d0a1770660d8831d1b6fcfed9bd9d6/CHANGELOG.md?plain=1#L157C3-L157C51
> normalize should now ignore %2B in query strings

I'm happy to let someone more experienced in Ruby to take this over, but I think it's important that it is fixed, as I've seen many people asking why their links aren't getting the image here when they work on Bluesky and Threads etc and they're moving over to those platforms instead.

In the meantime I might just do the quick hardcode URL hack locally so I can fix my instances for now.

Thanks again for looking into this.

**Comment by phocks** [comment]
> I confirmed that assigning the query values ... to themselves ... would work -- [main...mjankowski:request-og-image-things](https://github.com/mastodon/mastodon/compare/main...mjankowski:request-og-image-things) -- but would like to have more info first about what the normalize guards against before PR'ing that.

ps. I really like this approach. It's nice and clean for if we want to go down that route of using the de-normalized query string for all requests. I hope we can get some other discussion and then get the right fix in either this PR (feel free to edit this one) or another.

**Comment by phocks** [comment]
Hmm, seems like this one is failing a few tests :( @mjankowski 

```ruby
@url         = Addressable::URI.parse(url).normalize
@url.query_values = @url.query_values.to_a # restore the URL encoding stripped by normalize
```

(Just reverting. Will wait until we have feed in from others about the security concerns of not normalizing query strings https://github.com/mastodon/mastodon/security/advisories/GHSA-hcqf-fw2r-52g4)

And some more interesting info here about the vulnerability: https://scumjr.github.io/2023/10/12/from-ssrf-to-rce-on-mastodon-cve-2023-42450/

> All in all, this vulnerability is not that useful from an attacker point of view. Indeed, it is not exploitable in production in default configurations and the affected version is a pre-release (>= 4.2.0-beta1, < 4.2.0-rc2). [private_address_check](https://github.com/jtdowney/private_address_check) being used for every HTTP queries, it effectively blocks SSRF attacks.

**Comment by phocks** [comment]
Can confirm, works in the wild 😁

Screenshot 2025-09-17 at 4 54 45 pm

**Comment by mjankowski** [comment]
> seems like this one is failing a few tests

I had not run the full suite, just the spec I added to see if it would preserve the string as a POC of sorts. Updated the branch to only update query values when present, which should fix that failure.

That said, as you noted, the correct thing to do here is not use this until we can add a spec which fails when normalize is removed, and then see if we can still work around that.

**Comment by ClearlyClaire** [comment]
The security issue that was briefly introduced by the reverted commit was that an attacker could sneak in newlines and use that for request smuggling / server-side request forgery. This specific issue is probably easily avoided, but there could be similar ones.

**Comment by mjankowski** [comment]
Seems like at minimum a spec which sends in a newline-containing URL and asserts that the subsequently requested url value has those as `%0A` instead of newlines might be useful? We could then rebase the diff ideas here onto that...

**Comment by phocks** [comment]
Had some time to take another look at this and I've got it! I noticed that `.normalize_component` has a `leave_encoded` parameter. https://www.rubydoc.info/gems/addressable/Addressable/URI#normalize_component-class_method so we can use that to normalize the query string and we get all the protection we already had (taking care of \n newline carriage returns and whitespace in the security advisory) but any "," comma encodings as %2C are left encoded.

```ruby
def normalize_preserving_url_encodings(url, preserve_chars = SAFE_PRESERVED_CHARS)
  original_uri = Addressable::URI.parse(url)

  if original_uri.query
    normalized_query = Addressable::URI.normalize_component(
      original_uri.query,
      Addressable::URI::CharacterClasses::RESERVED_AND_UNRESERVED,
      preserve_chars
    )

    normalized_uri = original_uri.normalize
    normalized_uri.query = normalized_query
    normalized_uri
  else
    original_uri.normalize
  end
end
```

**Comment by phocks** [comment]
Note: Closes this issue https://github.com/mastodon/mastodon/issues/36273

File: app/lib/request.rb [hunk 1]
```diff
@@ -148,6 +149,24 @@ def http_client
 
   private
 
+  def normalize_preserving_url_encodings(url, preserve_chars = SAFE_PRESERVED_CHARS)
+    original_uri = Addressable::URI.parse(url)
+
+    if original_uri.query
+      normalized_query = Addressable::URI.normalize_component(
```
Comment (ClearlyClaire) [inline app/lib/request.rb]: I'm looking at the original implementation and it's pretty different:
https://github.com/sporkmonger/addressable/blob/3450895887d0a1770660d8831d1b6fcfed9bd9d6/lib/addressable/uri.rb#L1609-L1635

I'm not sure how far from that we want to go.

Comment (phocks) [reply app/lib/request.rb]: Ah cool, so if I'm reading that right, `normalized_query` uses `normalize_component` internally, and adds some sorting and duplicate removal stuff etc around it.

```ruby
Addressable::URI.normalize_component(
    pair,
    Addressable::URI::NormalizeCharacterClasses::QUERY,
    "+"
  )
```

https://github.com/sporkmonger/addressable/blob/3450895887d0a1770660d8831d1b6fcfed9bd9d6/lib/addressable/uri.rb#L1624C11-L1628C12

And it is preserving (not encoding) the "+" character. So I guess if we can just somehow add the SAFE_PRESERVED_CHARS = "," to that and make it "+," that might work and it might be closer to the original query encoding.

Makes it more difficult that the code is in the external addressable repo though.

**Comment by phocks** [comment]
OK I've modified the function to more closely reflect the implementation here: https://github.com/sporkmonger/addressable/blob/3450895887d0a1770660d8831d1b6fcfed9bd9d6/lib/addressable/uri.rb#L1609-L1635 (although from what I can tell it's almost doing the same things, except for some optional sorting, splitting apart queries and putting them back together, etc?)

```ruby
def normalize_preserving_url_encodings(url, preserved_chars = SAFE_PRESERVED_CHARS, *flags)
  original_uri = Addressable::URI.parse(url)
  normalized_uri = original_uri.normalize

  if original_uri.query
    modified_query_class = Addressable::URI::CharacterClasses::QUERY.dup
    modified_query_class.sub!('\\&', '').sub!('\\;', '')

    pairs = original_uri.query.split('&', -1)
    pairs.delete_if(&:empty?).uniq! if flags.include?(:compacted)
    pairs.sort! if flags.include?(:sorted)

    normalized_query = pairs.map do |pair|
      Addressable::URI.normalize_component(
        pair,
        modified_query_class,
        preserved_chars
      )
    end.join('&')

    normalized_uri.query = normalized_query == '' ? nil : normalized_query
  end

  normalized_uri
end
```

Tested with a few Guardian links and it still gets the og:image

File: app/lib/request.rb (hunk 1 above)
Comment (phocks) [reply app/lib/request.rb]: https://github.com/mastodon/mastodon/pull/36139#issuecomment-3354271086

ps. thanks for looking at this 🙏

**Comment by sjlongland** [comment]
A backported version of this patch applied to v4.4.5 (yes, I'll get to 4.4.6) works.

image

https://gist.github.com/sjlongland/57a5b7f0c969551f1ce5c04a8ca33f7d if anyone needs it.

I'd recommend this getting merged though.

**Comment by phocks** [comment]
Thanks for this @sjlongland I actually have to apply this again anyway to my single-user instance after a migration, so I'll just use this backport patch. Thanks again!

Edit: It worked! A simple `git apply gh36273-4.4.5.patch` in the ~/live directory and then restarted the mastodon services and it's good to go!

File: app/lib/request.rb [hunk 2]
```diff
@@ -148,6 +149,32 @@ def http_client
...
+      pairs.delete_if(&:empty?).uniq! if flags.include?(:compacted)
+      pairs.sort! if flags.include?(:sorted)
+
+      normalized_query = pairs.map do |pair|
+        Addressable::URI.normalize_component(
+          pair,
+          modified_query_class,
+          preserved_chars
+        )
+      end.join('&')
```
Comment (ClearlyClaire) [inline app/lib/request.rb:172]: Upstream uses `Addressable::URI::NormalizeCharacterClasses::QUERY`, not `modified_query_class`… but it also doesn't make use of `modified_query_class` after mutating it, so that's a bit confusing.

Looking at git blame output: https://github.com/sporkmonger/addressable/blame/main/lib/addressable/uri.rb#L1617 and the history, this seems to come down to https://github.com/sporkmonger/addressable/commit/5f38ef41a364c63bab6097de0eef9ac98921e0b6 introducing a pre-computed class and the `modified_query_class` maybe being reintroduced in a merge?

I would use the `Addressable::URI::NormalizeCharacterClasses::QUERY` as upstream and remove the `modified_query_class` code then.

The more I look at the addressable code, the more it is a mess honestly. I think eventually we may want to move away from it, but it's a big undertaking.

```suggestion
      pairs = original_uri.query.split('&', -1)
      pairs.delete_if(&:empty?).uniq! if flags.include?(:compacted)
      pairs.sort! if flags.include?(:sorted)

      normalized_query = pairs.map do |pair|
        Addressable::URI.normalize_component(
          pair,
          Addressable::URI::NormalizeCharacterClasses::QUERY,
          preserved_chars
        )
      end.join('&')
```

I would also add a comment that points to the addressable code stating this is lifted from there and why it was changed.

Otherwise, it looks good to me!

Comment (phocks) [reply app/lib/request.rb:172]: Yeah I was confused as to why it doesn't use `modified_query_class` too. I figured it was just a mistake. Agree probably a good idea to move away from it eventually, but would be good to get a relatively quick win in.

Comment (phocks) [reply app/lib/request.rb:172]: I'm just going to do a test to see if this is still fetching the og:images because I have a faint memory that I tried using `Addressable::URI::NormalizeCharacterClasses::QUERY` directly before and something was going wrong....

Comment (phocks) [reply app/lib/request.rb:172]: Yes, it was what I remember `Addressable::URI::NormalizeCharacterClasses::QUERY` DOESN'T actually fix the issue, and that's why I kept the modified_query_class stuff:

```
modified_query_class = Addressable::URI::CharacterClasses::QUERY.dup
modified_query_class.sub!('\\&', '').sub!('\\;', '')
```

Screenshot 2025-10-30 105213

So we can either revert or I can maybe try to work out what's actually going on, after I finish work. Thanks @ClearlyClaire

Comment (phocks) [reply app/lib/request.rb:172]: I'm just doing a little bit of investigation. Here is the difference between `Addressable::URI::CharacterClasses::QUERY` and `Addressable::URI::NormalizeCharacterClasses::QUERY`

```
 === CHARACTER CLASS COMPARISON ===
01:41:33 sidekiq.1 | CharacterClasses: "a-zA-Z0-9\\-\\.\\_\\~\\!\\$\\&\\'\\(\\)\\*\\+\\,\\;\\=\\:\\@\\/\\?"
01:41:33 sidekiq.1 | NormalizeCharacterClasses: /[^a-zA-Z0-9\-\.\_\~\!\$\'\(\)\*\+\,\=\:\@\/\?%]|%(?!2B|2b)/
01:41:33 sidekiq.1 | === END COMPARISON ===
```

So with NormalizeCharacterClasses `overlay-align=bottom%2Cleft` gets double encoded as `overlay-align=bottom%252Cleft` and so it breaks.

%25 is the % character 

%2C is a , (comma)

Comment (phocks) [reply app/lib/request.rb:172]: So, in the [normalize_component](https://github.com/sporkmonger/addressable/blob/3450895887d0a1770660d8831d1b6fcfed9bd9d6/lib/addressable/uri.rb#L552-L598) function, it can take a regex or a String, and if we pass in a regex, it seems to skip over the leave_encoded logic (if I'm reading this correctly).

```
if character_class.kind_of?(String)
  leave_re = if leave_encoded.length > 0
    character_class = "#{character_class}%" unless character_class.include?('%')

    bytes = leave_encoded.bytes
    leave_encoded_pattern = bytes.map { |b| SEQUENCE_ENCODING_TABLE[b] }.join('|')
    "|%(?!#{leave_encoded_pattern}|#{leave_encoded_pattern.upcase})"
  end

  character_class = if leave_re
                      /[^#{character_class}]#{leave_re}/
                    else
                      /[^#{character_class}]/
                    end
end
```

So it would be better to use the string if we want the leave_encoded functionality.

It's all a bit messy, but I might revert back to Addressable::URI::CharacterClasses::QUERY and add a comment that points to the addressable code where it is from. Hopefully that's OK and this can be fixed now and worked on more in the future.

Comment (phocks) [reply app/lib/request.rb:172]: Done!

Screenshot 2025-10-30 130717

**Review by ClearlyClaire — APPROVED** [review]

**Comment by mjankowski** [comment]
Wow that's really verbose and more complicated than I'd hoped, but good to see it finished/merged.

Looks like the specs got dropped in a rebase maybe?
