### PR TITLE
Fix infinite loading instead of soft 404 for non-existing remote accounts

### LINKED ISSUE #21278: Accessing non-existent remote user makes loader spin forever
### Steps to reproduce the problem

1. Go to the local instance URL for a remote user who hasn't been fetched by the server
2. See that the API call to `api/v1/accounts/lookup` is throwing a 404 in the JS console
3. See that the web client just shows the loading screen forever.

### Expected behaviour

An error message is shown

### Actual behaviour

It shows the loading page forever

### Detailed description

_No response_

### Specifications

Mastodon 4.0.2 (mastodon.social)

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #21278, #21021

### CODE REVIEW

File: app/javascript/mastodon/reducers/accounts_map.js [hunk 1]
```diff
@@ -7,6 +8,8 @@ const initialState = ImmutableMap();
 
 export default function accountsMap(state = initialState, action) {
   switch(action.type) {
+  case ACCOUNT_LOOKUP_FAIL:
```
Comment (MaciekBaron) [inline app/javascript/mastodon/reducers/accounts_map.js:11]: Should we also cater here for `ACCOUNT_FETCH_FAIL`?

Comment (ClearlyClaire) [reply app/javascript/mastodon/reducers/accounts_map.js:11]: No, `ACCOUNT_FETCH_FAIL` is for getting an `Account` object from its `id`, `accounts_map` is for storing a mapping from `acct` handle to `id`.

**Review by ineffyble — APPROVED** [review]

**Review by Gargron — APPROVED** [review]
