### PR TITLE
Fix poll API not requiring authentication on non-public polls

### LINKED ISSUE #10959: Polls API doesn't require authentication
### Expected behaviour

Polls posted to followers or DM's require authentication.

### Actual behaviour

The poll API returns the data publicly.

### Steps to reproduce the problem

Create a poll that's posted to followers only or DM, get the poll ID using the network inspector, go to the API page in an unauthenticated window.

Example: 
image
https://linuxrocks.online/api/v1/polls/2502 is the poll API URL, which works without authentication.

### Specifications

v2.8.4

### PR DESCRIPTION
**Pull request by Gargron**
That API does not reveal the content of the status, i.e. the question itself, nor who the author is, nor which status it belongs to, but it does reveal the poll options and how many answers they got

Fix #10959

### CODE REVIEW

**Review by ClearlyClaire — APPROVED** [review]
LGTM. Adding a test for that might be good.

File: spec/controllers/api/v1/polls_controller_spec.rb [hunk 1]
```diff
@@ -10,14 +10,26 @@
...
+
+      it 'returns http success' do
+        expect(response).to have_http_status(200)
+      end
+    end
+
+    context 'when parent status is private' do
+      let(:visibility) { 'private' }
+
+      it 'returns http success' do
```
Comment (ThibG) [inline spec/controllers/api/v1/polls_controller_spec.rb]: “returns http unauthorized”

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]

**Review by ClearlyClaire — APPROVED** [review]
