### PR TITLE
Fix expiration date of filters being set to “Never” when editing them

### LINKED ISSUE #9506: Custom filter edition page always show that the edited filter never expires
### Expected behaviour

When saving a filter with an expiry other than "never", clicking to edit the filter should show the original expiry that was selected when first saving the filter.

### Actual behaviour

Clicking to edit a filter shows the expiry "never" every time, no matter which expiry you selected and saved originally.

### Steps to reproduce the problem

1) Make new filter with the expiry "one week".
2) Save.
3) In the filtered words list, click "edit" next to the filter you just saved.
4) Expiry is "never".

### Specifications

Vanilla Mastodon 2.6.1, https://queer.party.

fliter timing doesn t stick

### PR DESCRIPTION
**Pull request by ClearlyClaire**
When editing a custom filter, select the shortest preset duration that
still covers the remaining time of that filter.

Fixes #9506

### CODE REVIEW

File: app/models/custom_filter.rb [hunk 1]
```diff
@@ -35,6 +35,13 @@ class CustomFilter < ApplicationRecord
   before_validation :clean_up_contexts
   after_commit :remove_cache
 
+  def expires_in
+    return @expires_in if defined?(@expires_in)
+    return nil if expires_at.nil?
+
+    [30.minutes, 1.hour, 6.hours, 12.hours, 1.day, 1.week].filter { |expires_in| expires_in.from_now >= expires_at }.first
```
Comment (Gargron) [inline app/models/custom_filter.rb]: Use `find` instead of `filter` and `first` (also we prefer `select` to `filter` (they are the same thing))

**Review by Gargron — CHANGES_REQUESTED** [review]

**Review by Gargron — APPROVED** [review]

File: app/models/custom_filter.rb [hunk 2]
```diff
@@ -35,6 +35,13 @@ class CustomFilter < ApplicationRecord
   before_validation :clean_up_contexts
   after_commit :remove_cache
 
+  def expires_in
+    return @expires_in if defined?(@expires_in)
```
Comment (mjankowski) [inline app/models/custom_filter.rb:39]: I realize this PR is 5 years old, but bumped into this while doing something else ... it seems like this memoization is never actually used? (ie, this ivar is never assigned to anything) or am I missing something here?

Comment (ClearlyClaire) [reply app/models/custom_filter.rb:39]: I don't think you're missing anything, I think this line is useless.
