### PR TITLE
Fix `tootctl upgrade storage-schema` misbehaving

### LINKED ISSUE #13594: "tootctl upgrade storage-schema" fails to move "original" custom_emoji files to cache
### Expected behaviour

When you execute "tootctl upgrade storage-schema" added in https://github.com/tootsuite/mastodon/pull/12821 , remote media files cached in system/custom_emojis/images/xxx/xxx/xxx/original are moved to respective cache folders.

### Actual behaviour

"Original" custom emoji files remain where they are. "Static" files are moved as expected.

### Steps to reproduce the problem

Execute "tootctl upgrade storage-schema."

### Specifications

Found in https://github.com/tootsuite/mastodon/commit/5cff7910c2c519af2d255454b66b0bfa6cf5288c

### PR DESCRIPTION
**Pull request by Gargron**
- Fix not moving original files of custom emojis
- Fix command failing to move any files with S3 storage
- Fix command marking records as upgraded when move failed

Fix #13594

### CODE REVIEW

File: lib/mastodon/upgrade_cli.rb [hunk 1]
```diff
@@ -41,23 +41,33 @@ def storage_schema
...
               end
 
               progress.increment
             end
 
-            attachment.instance_write(:storage_schema_version, CURRENT_STORAGE_SCHEMA_VERSION)
+            # Hopefully if this does happen, it happens for all styles, but if
+            # transfer of one or more of the styles fails, we should not mark
+            # the record as upgraded
+            attachment.instance_write(:storage_schema_version, CURRENT_STORAGE_SCHEMA_VERSION) if success
```
Comment (ThibG) [inline lib/mastodon/upgrade_cli.rb:70]: If an error occurs for one style and not the others, we'll have some files already moved, and re-running the task will always fail, right? Is there something sensible we can do?

Comment (Gargron) [reply lib/mastodon/upgrade_cli.rb:70]: Hm, what if only `:original` will determine whether upgrade failed or not, and the other styles will be ignored? Because you could re-generate other styles from `:original` as long as you had it.

Comment (ThibG) [reply lib/mastodon/upgrade_cli.rb:70]: Hm, ok, but we don't have anything to actually re-generate other styles, do we?

Comment (Gargron) [reply lib/mastodon/upgrade_cli.rb:70]: That's what paperclip's `reprocess!` does

Comment (ThibG) [reply lib/mastodon/upgrade_cli.rb]: ok, but there's nothing for an admin to run it, and it wouldn't get triggered automatically either, would it?

File: lib/mastodon/upgrade_cli.rb [hunk 2]
```diff
@@ -41,23 +41,32 @@ def storage_schema
...
+            styles.each do |style|
+              success = begin
+                case Paperclip::Attachment.default_options[:storage]
+                when :s3
+                  upgrade_storage_s3(progress, attachment, style)
+                when :fog
+                  upgrade_storage_fog(progress, attachment, style)
+                when :filesystem
+                  upgrade_storage_filesystem(progress, attachment, style)
+                end
```
Comment (ThibG) [inline lib/mastodon/upgrade_cli.rb:61]: Now it will report success if the last style gets moved, but not if there is any error, and especially not if an error occurs on the `:original` style but not on another one.

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]

File: lib/mastodon/upgrade_cli.rb (hunk 1 above)
Comment (Gargron) [reply lib/mastodon/upgrade_cli.rb]: No, but I still consider it fixable, e.g. you'd give the admin code to run in console.

File: lib/mastodon/upgrade_cli.rb (hunk 2 above)
Comment (Gargron) [reply lib/mastodon/upgrade_cli.rb:61]: I think you are possibly mistaken? I've renamed some variables. The `success` tracks the success of the current, given style only. Then the `upgraded` variable is only set when the move succeeded and it was the `:original` style

Comment (ThibG) [reply lib/mastodon/upgrade_cli.rb:61]: Oh, right. I just thought there was a global return value for this, and looked at another part of the code.

**Review by ClearlyClaire — APPROVED** [review]
