### PR TITLE
Fix random `NoMethodError` errors on cached `CustomFilter` objects

### LINKED ISSUE #27622: NoMethodError (undefined method `title' for #<CustomFilter...
### Steps to reproduce the problem

1. Upgrade to main version at [a918208](https://github.com/mastodon/mastodon/commit/a918208ec61836f911bd9775d2f2dd6db72ac1a5)
2. Run bundle install && rm -rfv public/packs && yarn install --frozen-lockfile && RAILS_ENV=production bundle exec rails assets:precompile 
3. Restart services

### Expected behaviour

Mastodon should work without errors

### Actual behaviour

Fatal error and "500" notification present

### Detailed description

I noticed it takes time for Explore etc. tabs to populate, but after a while they appear. 

Got a fatal error couple of times (log below).

I haven't seen this before in prior versions, even in 4.3.0-alpha.0. Is it a regression? What causes it? It's related to my muted words in the filter "War, death and destruction". There are normal words there, why does it throw that? 

### Mastodon instance

mementomori.social

### Mastodon version

v4.3.0-alpha.0

### Browser name and version

Google Chrome 118.0.5993.70 (Official Build) (64-bit)

### Operating system

Pop!_OS Linux 22.04 LTS

### Technical details

```
Oct 30 18:11:49 mementomori bundle[786873]: F, [2023-10-30T18:11:49.098377 #786873] FATAL -- : [7d20891b-5303-4486-b404-2fddd2aa2882]
Oct 30 18:11:49 mementomori bundle[786873]: [7d20891b-5303-4486-b404-2fddd2aa2882] NoMethodError (undefined method `title' for #<CustomFilter id: 93, account_id: 109293050593156468, expires_at: nil, phrase: "War, death and destruction", context: ["home", "notifications", "public", "thread", "account"], created_at: "2023-10-19 16:04:59.040990000 +0000", updated_at: "2023-10-19 16:08:48.866924000 +0000", action: "hide">):
```

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #27622

For some reason, `alias_attribute`-generated methods do not get generated when loading from the Rails cache. So instead, explicitly define just the methods we need as a workaround.

### CODE REVIEW

File: app/models/custom_filter.rb [hunk 1]
```diff
@@ -17,8 +17,23 @@
 class CustomFilter < ApplicationRecord
   self.ignored_columns += %w(whole_word irreversible)
 
-  alias_attribute :title, :phrase
-  alias_attribute :filter_action, :action
```
Comment (Gargron) [inline app/models/custom_filter.rb:21]: I am not familiar with `alias_attribute` but wouldn't `alias` for each method work?

Comment (ClearlyClaire) [reply app/models/custom_filter.rb:21]: No, because `alias` copies already-declared methods. In this case, `phrase` and `action` are not defined methods at the moment of class declaration.

**Review by Gargron — APPROVED** [review]
