### PR TITLE
Fix /api/v1/admin/accounts

### LINKED ISSUE #17870: 500 on admin API when filtering by `pending`
### Steps to reproduce the problem

HTTP GET to `/api/v1/admin/accounts?pending=True` with correct `admin:read:accounts` token.

### Expected behaviour

Should return a filtered list of pending approval accounts. As documented here: https://docs.joinmastodon.org/methods/admin/

### Actual behaviour

Returns no content and a 500 error

### Specifications

If you don't provide this query param it returns the normal un-filtered response.

This used to work fine on an older version (I think 3.3). Since upgrading to v3.4 this long running script has broken.

No combination of `pending`, `pending=True`, `pending=true`, `pending=1` works.

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #17870 by restoring support for old parameters to `/api/v1/admin/accounts`.

Also creates `/api/v2/admin/accounts` with the new parameters.

### CODE REVIEW

File: app/models/account_filter.rb [hunk 1]
```diff
@@ -80,6 +80,8 @@ def status_scope(value)
       accounts_with_users.merge(User.pending)
     when 'suspended'
       Account.suspended
+    when 'disabled'
```
Comment (Gargron) [inline app/models/account_filter.rb:83]: I think `silenced` also used to be there 😅

File: app/models/account_filter.rb [hunk 2]
```diff
@@ -80,6 +80,8 @@ def status_scope(value)
...
+      accounts_with_users.merge(User.disabled)
```
Comment (Gargron) [inline app/models/account_filter.rb:84]:
```suggestion
      accounts_with_users.merge(User.disabled)
    when 'silenced'
      Account.silenced
```

**Review by Gargron — APPROVED** [review]
