### PR TITLE
Emoji loading performance

### LINKED ISSUE #38759: `cleanExtraEmojis` call on an instance with over 12k emojis hangs/crashes the frontend
### Steps to reproduce the problem

1. open "edit profile" page, or press the announcements button.
2. the page hangs for 15s or crashes the browser.

### Expected behaviour

it shouldn't hang or crash

### Actual behaviour

it hangs or crashes

### Detailed description

i'm pretty sure this is a regression..? the frontend used to work OK.

the instance is running a custom fork, but the components involved are identical on both glitch and vanilla mastodon. 

### Mastodon instance

merping.synth.download

### Mastodon version

v4.6.0-nightly

### Browser name and version

Firefox 149.0/Chromium 147.0.7727.101

### Operating system

Fedora 44

### Technical details

the issue is with the [`normalize.ts#cleanExtraEmojis`](https://github.com/mastodon/mastodon/blob/d82bada742c85ec2369806c2dadac1315c7c68af/app/javascript/mastodon/features/emoji/normalize.ts#L184) function, it's the one taking 15s in chrome's tracer. i believe this is due to the function spreading the massive 12k emoji array.

what's also strange, is that the result is not cached? every click on the announcement dropdown or navigation to the 'edit profile' page hangs the tab.

### PR DESCRIPTION
**Pull request by ChaosExAnima**
Fixes #38759 and maybe #36694.

This adds a new hook `useCustomEmojis` that loads all emojis from IndexedDB instead of Redux and improves efficiency of the `cleanExtraEmojis` to not use recursion.

To test, you'll need a large number of custom emojis which can be created via the Rails console:
```
Fabricate.times(12_000, :custom_emoji, category: CustomEmojiCategory.find_or_create_by!(name: 'too many emojis'))
```
And to clean up afterwards, run this:
```
CustomEmojiCategory.find_by(name: 'too many emojis').emojis.destroy_all
```

### CODE REVIEW

**Comment by ChaosExAnima** [comment]
@zenfyrdev and @cadusilva, are either of you able to test this PR on your servers? i tried with the mock emojis above and the speed dramatically improved, but i also have a pretty beefy machine.

**Comment by cadusilva** [comment]
I've just applied the patch at `bolha.one` and the delay is gone :1st_place_medal: Emoji panel, announcements panel and profile edit page are now opening way faster. I guess that any perceivable delay is due to my machine.

gif

**Comment by ChaosExAnima** [comment]
> I've just applied the patch at `bolha.one` and the delay is gone 🥇 Emoji panel, announcements panel and profile edit page are now opening way faster. I guess that any perceivable delay is due to my machine.

great to hear! just as a note, opening any emoji picker will still have a delay with excessive emojis. there's not a great way to fix that till we create a new picker in 4.7, but i can try to optimize a bit in a later PR.

File: app/javascript/mastodon/hooks/useCustomEmojis.ts [hunk 1]
```diff
@@ -0,0 +1,32 @@
+import { useEffect } from 'react';
+
+import type { ExtraCustomEmojiMap } from '../features/emoji/types';
+
+let emojis: ExtraCustomEmojiMap | null = null;
+
+export function useCustomEmojis() {
+  useEffect(() => {
+    if (!emojis) {
+      void loadEmojisIntoCache();
```
Comment (diondiondion) [inline app/javascript/mastodon/hooks/useCustomEmojis.ts]: Don't you need to trigger a state update here to make the component using the hook re-render so that `emojis` is actually updated?
(Or maybe it's a case for `useSyncExternalStore`?)

**Review by diondiondion — COMMENTED** [review]
It looks like the new hook needs a tweak to be able to work in components that don't happen to re-render incidentally, otherwise LGTM

File: app/javascript/mastodon/hooks/useCustomEmojis.ts (hunk 1 above)
Comment (ChaosExAnima) [reply app/javascript/mastodon/hooks/useCustomEmojis.ts]: pushed up a fix. i experimented with `useSyncExternalStore`, but it didn't seem to be worth it for this use case. if we had a lot of these hooks at once or something that'd be different maybe.

**Review by diondiondion — APPROVED** [review]

**Comment by zenfyrdev** [comment]
hello, yes, can confirm, this fixed the problem on our server too!
