### PR TITLE
Fix #26849 by adding the domain of the current SSO provider to the form-action CSP

### LINKED ISSUE #26849: When OMNIAUTH_ONLY=true the web interface stuck and cannot log in v4.2.0
### Steps to reproduce the problem

1. Use the latest nightly docker image
2. In the env, set `OMNIAUTH_ONLY=true` because I am using OIDC login and it works well
3. Run `docker compose up -d` and you will see that you stuck on the page you are in
4. The problem never happens on 4.1.7 or earlier version

### Expected behaviour

It should not be stuck and when you click log in you will be able to see the login page with a single button log in with the OAuth

### Actual behaviour

It will stuck on the page

### Detailed description

_No response_

### Mastodon instance

mfy.social

### Mastodon version

v4.2.0 Nightly

### Browser name and version

Edge Latest

### Operating system

macOS 13.5.1

### Technical details

https://github.com/mastodon/mastodon/blob/81caafbe84240bfb730f5001b33add97ebcbe9dc/spec/requests/content_security_policy_spec.rb#L20

I checked the detailed log and browser's console log, seems like this line is causing the problem? I am just guessing

### PR DESCRIPTION
**Pull request by CSDUMMI**
Fixes #26849

Without the SSO provider in form-action CSP, a browser will reject the redirect to the SSO provider after clicking on the 'Login or Register' button introduced by #26083.

The CSP header on instances not using a single SSO method as their sole authentication method should remain unaltered.

### CODE REVIEW

**Comment by MFYDev** [comment]
@CSDUMMI Hi is it possible that you can request someone to review the changes of it? Thanks!

File: config/initializers/content_security_policy.rb [hunk 1]
```diff
@@ -29,7 +39,11 @@ def host_to_url(str)
   p.media_src       :self, :https, :data, assets_host
   p.frame_src       :self, :https
   p.manifest_src    :self, assets_host
-  p.form_action     :self
+
+  sso_host = choose_sso_host
+  p.form_action     :self if sso_host.nil?
+  p.form_action     :self, sso_host unless sso_host.nil?
```
Comment (ClearlyClaire) [inline config/initializers/content_security_policy.rb:45]: This would become:
```suggestion
  if sso_host.present?
    p.form_action :self, sso_host
  else
    p.form_action :self
  end
```

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]
I wonder if it's the correct approach, I'm a bit uneasy with broadening the CSP here, as an attacker could perform `POST` queries against the SSO provider.

File: config/initializers/content_security_policy.rb [hunk 2]
```diff
@@ -19,6 +19,16 @@ def host_to_url(str)
...
 
+def choose_sso_host
+  return if ENV['OMNIAUTH_ONLY'] != 'true'
+
+  uri = ENV['CAS_URL'] if ENV['CAS_ENABLED'] == 'true'
+  uri = ENV['SAML_ISSUER'] if ENV['SAML_ISSUER'] == 'true'
+  uri = ENV['OIDC_ISSUER'] if ENV['OIDC_ISSUER'] == 'true'
+
+  URI(uri).host
+end
```
[the remark this answers is not in the document]
Comment (CSDUMMI) [reply config/initializers/content_security_policy.rb:30]: I agree with you that this is a better pattern, but I'm unsure whether it possible to use it (without creating a global variable) as we are not inside any class here and can thus not use instance variables inside of methods.

**Comment by CSDUMMI** [comment]
> I wonder if it's the correct approach, I'm a bit uneasy with broadening the CSP here, as an attacker could perform `POST` queries against the SSO provider.

What could be done, at least for the OpenID Connect protocol, is to access the precise URI on the SSO provider, where a user is redirected to. An attacker could then only make POST requests to that precise URI - which ought to have little sensitive information for them - providing either a login form or a redirect back to mastodon.

I'm looking into how to do this for OIDC and then I'll see whether / how this can be done for SAML and CAS.

**Comment by MFYDev** [comment]
Hi guys, I just started to wonder if a one-click log in is necessary for us who have the set OMNIAUTH_ONLY=true.
Can't we just use the older log in page with only one log in button? I do not mind that honestly... I went through all PRs related to this function and I can see it is causing some problems. @ClearlyClaire could you please tell me what do you think?

**Comment by CSDUMMI** [comment]
> Hi guys, I just started to wonder if a one-click log in is necessary for us who have set OMNIAUTH_ONLY=true. Can't we just use the old log in page with only one log in button? I do not mind that honestly... I went through all PRs related to this function and I can see it is causing some problems. @ClearlyClaire could you please tell me what do you think?

By introducing this, Mastodon has made it more convenient and less confusing to use an external identity provider with OMNIAUTH_ONLY=true. The `/auth/sign_in` page on instance with this setup is pointless and thus can confuse users when first encountering it & waste their time thereafter every time they login.

**Comment by MFYDev** [comment]
> > Hi guys, I just started to wonder if a one-click log in is necessary for us who have set OMNIAUTH_ONLY=true. Can't we just use the old log in page with only one log in button? I do not mind that honestly... I went through all PRs related to this function and I can see it is causing some problems. @ClearlyClaire could you please tell me what do you think?
> 
> By introducing this, Mastodon has made it more convenient and less confusing to use an external identity provider with OMNIAUTH_ONLY=true. The `/auth/sign_in` page on instance with this setup is pointless and thus can confuse users when first encountering it & waste their time thereafter every time they login.

Got it, make sense, thanks for the explaination

**Comment by ClearlyClaire** [comment]
> I just started to wonder if a one-click log in is necessary for us who have set OMNIAUTH_ONLY=true.
> Can't we just use the old log in page with only one log in button?

I'd honestly be fine with that, the one-click flow requires widening the security exceptions a little more than I'd like.

File: config/initializers/content_security_policy.rb [hunk 3]
```diff
@@ -29,7 +40,15 @@ def host_to_url(str)
...
   p.manifest_src    :self, assets_host
-  p.form_action     :self
+
+  if sso_host.present?
+    p.form_action     :self, sso_host
+  else
+    p.form_action     :self
+  end
+
+  p.form_action     :self, sso_host unless sso_host.nil?
```
Comment (ClearlyClaire) [inline config/initializers/content_security_policy.rb:50]: This line should be deleted, it's already included above.

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]

**Comment by CSDUMMI** [comment]
To reduce those security exceptions, I'm now using the exact URI that CAS, SAML and OpenID redirect to.
Any attacker can thus only create forms that go to that exact URI and nowhere else on the IdP.

**Comment by ClearlyClaire** [comment]
> To reduce those security exceptions, I'm now using the exact URI that CAS, SAML and OpenID redirect to. Any attacker can thus only create forms that go to that exact URI and nowhere else on the IdP.

Unfortunately, you cannot use paths/full URIs in Content-Security-Policy values

**Comment by CSDUMMI** [comment]
> > To reduce those security exceptions, I'm now using the exact URI that CAS, SAML and OpenID redirect to. Any attacker can thus only create forms that go to that exact URI and nowhere else on the IdP.
> 
> Unfortunately, you cannot use paths/full URIs in Content-Security-Policy values


Are you sure about that? According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/Sources#sources) a host-source can contain a scheme, host, port and path.

**Comment by ClearlyClaire** [comment]
> > > To reduce those security exceptions, I'm now using the exact URI that CAS, SAML and OpenID redirect to. Any attacker can thus only create forms that go to that exact URI and nowhere else on the IdP.
> > 
> > 
> > Unfortunately, you cannot use paths/full URIs in Content-Security-Policy values
> 
> Are you sure about that? According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/Sources#sources) a host-source can contain a scheme, host, port and path.

Oh, you appear to be right! Not sure why I thought otherwise!

This sounds like a good idea in theory, but I'm afraid this would cause the Mastodon server to fail starting if the OIDC provider is momentarily down.

File: config/initializers/content_security_policy.rb [hunk 4]
```diff
@@ -19,6 +19,18 @@ def host_to_url(str)
...
 media_host ||= assets_host
 
+def sso_host
+  return if ENV['OMNIAUTH_ONLY'] != 'true' || Devise.omniauth_providers.length != 1
+
+  provider = Devise.omniauth_configs[Devise.omniauth_providers[0]]
+  @sso_host ||= begin
+    uri = provider.cas_url if ENV['CAS_ENABLED'] == 'true'
+    uri = provider.options[:idp_sso_target_url] if ENV['SAML_ENABLED'] == 'true'
+    uri = OpenIDConnect::Discovery::Provider::Config.discover!(ENV['OIDC_ISSUER']).authorization_endpoint if ENV['OIDC_ENABLED'] == 'true'
```
Comment (ClearlyClaire) [inline config/initializers/content_security_policy.rb:29]: While I like the idea, I'm afraid this line specifically will cause the server to fail starting up if the OIDC provider is temporarily down or unreachable.

Comment (CSDUMMI) [reply config/initializers/content_security_policy.rb:29]: Yeah. You are right about that. 

Disappointingly I don't see any way around this - except arguing that an instance with this configuration will not work regardless, if the OIDC IdP isn't setup - but there may be valid reasons why the IdP is down while Mastodon is starting.

File: config/initializers/content_security_policy.rb [hunk 5]
```diff
@@ -19,6 +19,20 @@ def host_to_url(str)
...
 
+def sso_host
+  return if ENV['OMNIAUTH_ONLY'] != 'true' || Devise.omniauth_providers.length != 1
+
+  provider = Devise.omniauth_configs[Devise.omniauth_providers[0]]
+  @sso_host ||= begin
+    # using CAS
+    provider.cas_url if ENV['CAS_ENABLED'] == 'true'
+    # using SAML
+    provider.options[:idp_sso_target_url] if ENV['SAML_ISSUER'] == 'true'
```
Comment (ClearlyClaire) [inline config/initializers/content_security_policy.rb:30]: You probably meant `SAML_ENABLED` rather than `SAML_ISSUER`, right?
```suggestion
    provider.options[:idp_sso_target_url] if ENV['SAML_ENABLED'] == 'true'
```

File: config/initializers/content_security_policy.rb [hunk 6]
```diff
@@ -19,6 +19,20 @@ def host_to_url(str)
...
+    # or using OIDC
+    ENV['OIDC_AUTH_ENDPOINT'] || (OpenIDConnect::Discovery::Provider::Config.discover!(ENV['OIDC_ISSUER']).authorization_endpoint if ENV['OIDC_ISSUER'] == 'true')
```
Comment (ClearlyClaire) [inline config/initializers/content_security_policy.rb:32]: Likewise for `OIDC_ISSUER`:
```suggestion
    ENV['OIDC_AUTH_ENDPOINT'] || (OpenIDConnect::Discovery::Provider::Config.discover!(ENV['OIDC_ISSUER']).authorization_endpoint if ENV['OIDC_ENABLED'] == 'true')
```

File: config/initializers/content_security_policy.rb (hunk 3 above)
Comment (ClearlyClaire) [reply config/initializers/content_security_policy.rb:53]: This is still redundant.
```suggestion
```

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]

File: config/initializers/content_security_policy.rb (hunk 4 above)
Comment (ClearlyClaire) [reply config/initializers/content_security_policy.rb]: I agree this seems to be the best that you can do under the circumstances. However, I'm still uncomfortable with that.

What about introducing another environment variable to enable this one-click behavior? This way, no surprise for existing user, but the new behavior can be opt-in and be properly documented regarding these failure modes.

**Comment by CSDUMMI** [comment]
I have added the `ONE_CLICK_SSO_LOGIN` environment variable. If this is set to true, the one-click login is enabled and the CSP policy is also set.

**Comment by ClearlyClaire** [comment]
This is getting better, thanks!

In the meantime, I've been investigating how to *tighten* `form-action` and came up with https://github.com/mastodon/mastodon/pull/26897

To avoid crashes at start, we may want to use a lambda and rescue any OIDC discovery error (but only cache the result when there is no error)

File: config/initializers/content_security_policy.rb [hunk 7]
```diff
@@ -19,6 +19,22 @@ def host_to_url(str)
...
+  return unless Devise.omniauth_providers.length == 1
+
+  provider = Devise.omniauth_configs[Devise.omniauth_providers[0]]
+  @sso_host ||= begin
+    # using CAS
+    provider.cas_url if ENV['CAS_ENABLED'] == 'true'
+    # using SAML
+    provider.options[:idp_sso_target_url] if ENV['SAML_ENABLED'] == 'true'
+    # or using OIDC
+    ENV['OIDC_AUTH_ENDPOINT'] || (OpenIDConnect::Discovery::Provider::Config.discover!(ENV['OIDC_ISSUER']).authorization_endpoint if ENV['OIDC_ENABLED'] == 'true')
```
Comment (ClearlyClaire) [inline config/initializers/content_security_policy.rb:34]: I believe this should be:
```suggestion
    ENV['OIDC_AUTH_ENDPOINT'] || OpenIDConnect::Discovery::Provider::Config.discover!(ENV['OIDC_ISSUER']).authorization_endpoint if ENV['OIDC_ENABLED'] == 'true'
```

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]
Can you also edit `app/controllers/concerns/web_app_controller_concern.rb` to handle `ONE_CLICK_SSO_LOGIN`?

**Comment by CSDUMMI** [comment]
I'm wondering whether, in this setup, having Mastodon silently fail when the IdP is down is actually wanted. 

Given that we are only talking about a scenario, where all authentication has to go through the IdP, that IdP being down will severely impact Mastodon users. They will see a 502 error when trying to  login & logout.

So, perhaps having the startup fail is actually what we want to happen in this case, with the ability to circumvent the failure (knowingly, instead of silently) using `ONE_CLICK_SSO_LOGIN=false`.

**Comment by ClearlyClaire** [comment]
I think transient failures preventing Mastodon from starting up may be an issue, yes, for instance in cases the IDP and Mastodon or on the same network and it is recovering from a power failure, Mastodon failing to start because the IDP hasn't started yet could be an issue.

In any case, I'm ok with the fail-at-startup as long as it is behind a documented switch, so I'm fine with this PR as is (except for it missing `app/controllers/concerns/web_app_controller_concern.rb`)

**Comment by CSDUMMI** [comment]
I adjusted that now.

**Review by ClearlyClaire — APPROVED** [review]
Looks good to me, thanks!
