### PR TITLE
Fix being able to spoof link verification

### LINKED ISSUE #20195: rel="me" links are no longer included for profile metadata
### Steps to reproduce the problem

1. Add a link to profile metadata

### Expected behaviour

Fetching the profile page should include a link with `rel="me"` in the HTML, 

### Actual behaviour

The link does not appear anywhere in the HTML

### Detailed description

According to https://docs.joinmastodon.org/user/profile/:

> Behind the scenes, Mastodon checks for the `rel="me"` attribute on the link back. Likewise, Mastodon puts `rel="me"` on the links within profile metadata.

This is true for older versions of Mastodon. However, this is no longer the case. This functionality was especially useful to allow two accounts to link to each other and have both links be considered verified.

Previously, the attribute was just added to the `<a>` tag itself. However, with the removal of server-side rendered pages, this no longer happens. The server should likely add `<link>` tags, similarly to how Open Graph metadata is handled.

### Specifications

Mastodon v4.0.0rc2 (glitch-soc with some additional patches, which shouldn't be relevant)

### PR DESCRIPTION
**Pull request by Gargron**
Also, generally improve link verification stability:

- Change verification to happen in `default` queue
- Change verification worker to only be queued if there's something to do
- Add `link` tags from metadata fields to page header of profiles

Fix #20195

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

File: app/models/account/field.rb [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+  end
+
+  def character_limit
+    account.local? ? MAX_CHARACTERS_LOCAL : MAX_CHARACTERS_COMPAT
+  end
+
+  def extract_url_from_html
+    doc = Nokogiri::HTML(value).at_xpath('//body')
+
+    return if doc.children.size > 1
```
Comment (emilyst) [inline app/models/account/field.rb:65]: Note that if `at_xpath` fails to find this element, `doc` will be `nil`, resulting in an error.

Comment (emilyst) [reply app/models/account/field.rb:65]: Proposed a fix: https://github.com/mastodon/mastodon/pull/20428.
