### PR TITLE
Fix polls not being validated on edition

### LINKED ISSUE #33742: Streaming API and REST API language filtering is inconsistent
### Steps to reproduce the problem

1. select chosen languages in `/settings/preferences/other`
2. open the public timeline
3. observe new posts appearing
4. refresh page

### Expected behaviour

refreshing the page should result in the same posts

### Actual behaviour

streaming gets more posts than REST API

### Detailed description

At first glance, this seems to be due to the language filtering logic being different in the streaming server (`streamFrom` function) and the Ruby server (`PublicFeed#language_scope`):
- the streaming code treats posts with an unknown language as acceptable (`payload.language !== null `)
- when language filtering is enabled, the Ruby code does not return posts with `language: nil`

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #33742

### CODE REVIEW

**Review by oneiros — APPROVED** [review]

File: app/validators/poll_expiration_validator.rb [hunk 1]
```diff
@@ -0,0 +1,13 @@
+# frozen_string_literal: true
+
+class PollExpirationValidator < ActiveModel::Validator
+  MAX_EXPIRATION = 1.month.freeze
+  MIN_EXPIRATION = 5.minutes.freeze
+
+  def validate(poll)
+    current_time = Time.now.utc
+
+    poll.errors.add(:expires_at, I18n.t('polls.errors.duration_too_long')) if poll.expires_at.nil? || poll.expires_at - current_time > MAX_EXPIRATION
```
Comment (mjankowski) [inline app/validators/poll_expiration_validator.rb:10]: I realize this was just moving around existing code, not something changing here, but...

- In the parent class we have a presence validation on `expires_at` which runs when poll is local
- This validator class runs on local and expires_at_changed?

It seems sort of odd to add a "too long" error when the value is missing, given that it will already have the presence validation error added. I wonder if we could have this validator only run when expires_at is present (and keep the changed, and poll is local checks as-is) - which would let this validator remove those extra checks, assume it has a value, and just do the too_long/too_short checks?
