### PR TITLE
Change /api/v1/statuses/:id/history to always return at least one item

### LINKED ISSUE #25398: `api/v1/statuses/.../history` endpoint can return an empty array on an edited status
### 1 - search for status

On a Mastodon server running 4.1.2 (I used tooot.im), search for the post with the URL https://spore.social/@tamarasiuda/110522895217050705.

Nothing particularly special about this post (I think), except that it's been edited.

This makes the following HTTP request:

`GET https://tooot.im/api/v2/search?q=https%3A%2F%2Fspore.social%2F%40tamarasiuda%2F110522895217050705&type=statuses&resolve=true&limit=20&offset=0&following=false`

As expected, this returns JSON with a single entry in the `statuses` property:

```
...

    "statuses": [
        {
            "id": "110522895225071526",
            "created_at": "2023-06-11T01:05:44.000Z",
...
```

### 2 - fetch the status

Use the ID from the `id` property to fetch the status, and `GET https://tooot.im/api/v1/statuses/110522895225071526`

This returns `200`, and a status with the `edited_at` property set:

```
...
    "edited_at": "2023-06-11T11:24:17.000Z",
...
```

### 3 - fetch the edit history

Fetch the edit history of the status, with `GET https://tooot.im/api/v1/statuses/110522895225071526/history`

Per https://docs.joinmastodon.org/methods/statuses/#history, fetching the history should "Get all known versions of a status, including the initial and current states.".

Given that this status **has** been edited this should return an array of at least two entries.

It returns an empty array.

### Expected behaviour

An N-element array with at least two entries should have been returned.

### Actual behaviour

An empty JSON array, `[]`, is returned.

### Detailed description

In the web UI this manifests as a "Edited -1 times" tooltip if you hover over the "Edited Jun 11, 13:24" text on the status. In clients that expect the API endpoints to follow documented behaviour it results in a crash (https://github.com/tuskyapp/Tusky/issues/3743).

I think this is two bugs.

1. The status has been edited, so there should be at least two entries.
2. Even if the status hadn't been edited, fetching the history of a status should always return at least one entry, which would be the original status content (per the documentation, which says it fetches "all known versions of a status, including the **initial** and current state" (emphasis mine).

This may be related to https://github.com/mastodon/mastodon/issues/23292, I'm unsure.

### Specifications

Mastodon 4.1.2

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #25398

### CODE REVIEW

File: app/controllers/api/v1/statuses/histories_controller.rb [hunk 1]
```diff
@@ -8,11 +8,16 @@ class Api::V1::Statuses::HistoriesController < Api::BaseController
...
     cache_if_unauthenticated!
-    render json: @status.edits.includes(:account, status: [:account]), each_serializer: REST::StatusEditSerializer
+    render json: status_edits, each_serializer: REST::StatusEditSerializer
   end
 
   private
 
+  def status_edits
+    @status_edits ||= @status.edits.includes(:account, status: [:account]).to_a
+    @status_edits.presence || [@status.build_snapshot(at_time: @status.edited_at || @status.created_at)]
```
Comment (renchap) [inline app/controllers/api/v1/statuses/histories_controller.rb:18]: This is not cached if `@status_edits` is empty, should it be?

Comment (ClearlyClaire) [reply app/controllers/api/v1/statuses/histories_controller.rb:18]: I don't think this needs caching at all, I'll simplify the code.

**Review by renchap — APPROVED** [review]
