### PR TITLE
Fix caret position after selected suggestion and media upload

### LINKED ISSUE #6089: when using autocomplete cursor jumps to end of input
If you autocomplete an emojo in the middle of some text the cursor will jump to the end of the text currently in the input. This is bad.
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

### PR DESCRIPTION
**Pull request by ClearlyClaire**
This fixes caret position when selecting a suggestion (emoji or account) from the suggestion box.

Also, this fixes some overlooked cases in my previous PR.

### CODE REVIEW

File: app/javascript/mastodon/features/compose/components/compose_form.js [hunk 1]
```diff
@@ -141,7 +141,6 @@ export default class ComposeForm extends ImmutablePureComponent {
     const emojiChar    = data.native;
```
Comment (ykzts) [inline app/javascript/mastodon/features/compose/components/compose_form.js]: delete this line.

**Review by ykzts — CHANGES_REQUESTED** [review]

File: app/javascript/mastodon/features/compose/components/compose_form.js (hunk 1 above)
Comment (ThibG) [reply app/javascript/mastodon/features/compose/components/compose_form.js]: Fixed

**Review by ykzts — APPROVED** [review]
