### PR TITLE
Fix `tootctl accounts create` failing because of date-of-birth check

### LINKED ISSUE #34644: Can't re-enable deleted account username, `tootctl` asks for `date_of_birth`
### Steps to reproduce the problem

1. Enable minimum age for sign up
2. Type `tootctl accounts create JohnDoe --reattach --force --email user@example.com`
3. The procedure fails with `Failure/Error: date_of_birth    blank`

### Expected behaviour

Deleted user is enabled again

### Actual behaviour

An error calls for `date_of_birth`

### Detailed description

A user deleted their account and now asked to come back, so I tried to re-enable the username. But `tootctl` returns the following:

```
I, [2025-05-07T19:41:21.006300 #1643610]  INFO -- : [dotenv] Loaded .env.production
Failure/Error: date_of_birth
    blank
```

I think it's related to #34150.

### Mastodon instance

bolha.one

### Mastodon version

v4.4.0-alpha.5-741f166+bolhinha

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: `ruby 3.4.2`
- Node.js version: `v22.15.0`

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #34644

An alternative to this would be to actually pass a date of birth, but given the fact this is manual action from the admin, this seems unnecessary.

### CODE REVIEW

File: spec/lib/mastodon/cli/accounts_spec.rb [hunk 1]
```diff
@@ -70,6 +70,25 @@ def account_from_options
         end
       end
 
+      context 'with min_age setting' do
+        let(:options) { { email: 'tootctl@example.com', confirmed: true } }
+
+        before do
+          Setting.min_age = 42
+        end
```
Comment (oneiros) [inline spec/lib/mastodon/cli/accounts_spec.rb:78]: If this is not rolled-backed automatically after each test, it might be good to do so manually in an `after` hook.

**Review by oneiros — APPROVED** [review]
