### PR TITLE
Have `Follow` activities bypass availability

### LINKED ISSUE #27458: Stuck Follow Request when following a WordPress Profile
### Steps to reproduce the problem

1. Go to for example mastodon.art
2. Search for `pfefferle@notiz.blog`
3. Press "Follow" button

### Expected behaviour

Mastodon user follows WordPress User

### Actual behaviour

Process seem to be stuck ("Cancel follow")

### Detailed description

We have received some reports (here is the [ticket](https://github.com/Automattic/wordpress-activitypub/issues/523) on the WordPress plugin repo) that the Follow process seems to be stuck and not accepted by the WordPress instance.

Debugging on the WordPress site shows that when searching for the WordPress profile, all required endpoints (WebFinger, Followers, ...) are requested and the profile is displayed correctly in the Mastodon UI. However, after clicking the follow button, WordPress does not receive a follow request (or any other requests to the inbox), this also applies to a unfollow/re-follow. Sending an `accept` by hand, on the other hand, seems to work.

Another way to reset the follow process seems to be an @-reply. After sending an @-reply to the Mastodon profile,an unfollow/re-follow also seems to work.

An example profile: @pfefferle@notiz.blog
An example group: @notiz.blog@notiz.blog

For a few weeks now, the Mastodon UI has also been displaying a 500 error in the UI when requesting the internal featured-tags endpoint: https://mastodon.social/api/v1/accounts/[...]/featured_tags.

Here is an example endpoint for the Featured Tags endpoint of WordPress: https://notiz.blog/wp-api/activitypub/1.0/users/0/collections/tags

### Mastodon instance

mastodon.art, mastodon.ie, twit.social

### Mastodon version

v4.2.1

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by ShadowJonathan**
This fixes https://github.com/mastodon/mastodon/issues/27458, and is related to (but does not resolve) https://github.com/Automattic/wordpress-activitypub/issues/523

This is in accordance with the suggestion I made here: https://github.com/mastodon/mastodon/issues/27525#issuecomment-1779880830

The consequences of this is that Follow requests can bounce around the queue for a while, without being affected by availability. They'll still be affected by stoplight, but those are temporary.

A user could technically spam follows and have them enter the queue en-masse, but these would be short-circuited by stoplight all the same, so I don't think that has much impact. (Besides, users could still do this with the likes of fav-unfav or other activities, so there's not much increased risk)

---

This PR is intended to help "wedged" federation, where a remote account is not "accessible" (or "stuck in Follow Request state") because the local server has stopped delivery for that server.

This is especially notable in cases where the remote server is a follow-along-like actor (such as a blog) which is not intended to have social dynamics, such as "following back", or "mentioning" the account out of the blue, which would've otherwise unwedged federation in other cases.

This PR adds a simple availability bypass to the delivery worker, which is only granted on the case of a user-initiated follow request.

These follow requests are then often accompanied by an authorisation, which then unwedges the delivery failure tracker, as it has now "seen" a response from that inbox. Normal federation can resume hereafter.

By effect, a `Follow` activity then becomes a SYN-like first step to re-establish federation after it has broken down or bugged via the availability tracker.

### CODE REVIEW

File: app/services/follow_service.rb [hunk 1]
```diff
@@ -71,7 +71,7 @@ def request_follow!
     if @target_account.local?
       LocalNotificationWorker.perform_async(@target_account.id, follow_request.id, follow_request.class.name, 'follow_request')
     elsif @target_account.activitypub?
-      ActivityPub::DeliveryWorker.perform_async(build_json(follow_request), @source_account.id, @target_account.inbox_url)
+      ActivityPub::DeliveryWorker.perform_async(build_json(follow_request), @source_account.id, @target_account.inbox_url, { "bypass_availability" => true })
```
Comment (ClearlyClaire) [inline app/services/follow_service.rb:74]: There's a small lint issue to be fixed here.

```suggestion
      ActivityPub::DeliveryWorker.perform_async(build_json(follow_request), @source_account.id, @target_account.inbox_url, { 'bypass_availability' => true })
```

File: app/workers/activitypub/delivery_worker.rb [hunk 2]
```diff
@@ -23,9 +23,10 @@ class ActivityPub::DeliveryWorker
   HEADERS = { 'Content-Type' => 'application/activity+json' }.freeze
 
   def perform(json, source_account_id, inbox_url, options = {})
-    return unless DeliveryFailureTracker.available?(inbox_url)
-
     @options        = options.with_indifferent_access
+
+    return unless DeliveryFailureTracker.available?(inbox_url) || @options[:bypass_availability]
```
Comment (ClearlyClaire) [inline app/workers/activitypub/delivery_worker.rb:28]: I'd check the option before the `DeliveryFailureTracker`, as this is less expensive. But this is very minor either way.

```suggestion
    return unless @options[:bypass_availability] || DeliveryFailureTracker.available?(inbox_url)
```

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]
There's a minor lint issue to be fixed, and I left another inline minor comment.

The reasoning makes sense to me, and `Follow` activity seem to be one of the safest choices for an exemption, as they are deliberate, one-to-one, generally low-traffic activities.

**Review by ClearlyClaire — APPROVED** [review]
