### PR TITLE
Fix #3550 - Add all missing foreign keys

### LINKED ISSUE #3550: Foreign keys for account_id references?
Quite some time ago, before Mastodon refreshed infos from webfinger, I instructed another instance's admin to manually remove information on my remote account (that is, delete rows of the “accounts” database with domain = 'mydomain'). We are still unable to communicate now, and I suspect it is actually because of the instructions I have given this admin at the time (I am able to communicate with other instances just fine).

I tried to reproduce this issue and couldn't completely. However, in the process, I manually removed a remote account (which got re-created just fine afterwards), without removing the toots referencing it, leading to runtime errors.

It appears to me that `statuses (account_id)`, `follows (account_id)`, `follows (target_account_id)` etc. should all have a `foreign key` constraint on `accounts (id)`. Is there any reason why that is not the case?

### PR DESCRIPTION
**Pull request by Gargron**
The rule on media attachments table is nullify instead of cascade, because presumably we would want to keep the records so that we have a reference to the files that need to be deleted, otherwise those files would be orphaned.

In fact, this is kind of a concern for accounts table as well, since it keeps references to avatars and headers, which is why you should use `Account#destroy` instead of deleting it directly from the database, but I digress.

Another concern is that the database *will* complain and the migration will fail if there are violations of these constraints, which will require manual intervention from the person doing the upgrade. Suggestions of how to handle this are welcome.

### CODE REVIEW

File: db/migrate/20170604144747_add_foreign_keys_for_accounts.rb [hunk 1]
```diff
@@ -0,0 +1,36 @@
+class AddForeignKeysForAccounts < ActiveRecord::Migration[5.1]
+  def change
+    add_foreign_key :statuses, :accounts, on_delete: :cascade
```
Comment (ThibG) [inline db/migrate/20170604144747_add_foreign_keys_for_accounts.rb]: There is still a missing foreign key for `in_reply_to_account_id`. Maybe the action for this one should be `nullify`.

File: db/migrate/20170604144747_add_foreign_keys_for_accounts.rb [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+    add_foreign_key :mutes, :accounts, on_delete: :cascade
+    add_foreign_key :mutes, :accounts, column: :target_account_id, on_delete: :cascade
+    add_foreign_key :imports, :accounts, on_delete: :cascade
+    add_foreign_key :media_attachments, :accounts, on_delete: :nullify
+    add_foreign_key :mentions, :accounts, on_delete: :cascade
+    add_foreign_key :mentions, :statuses, on_delete: :cascade
+    add_foreign_key :notifications, :accounts, on_delete: :cascade
+    add_foreign_key :preview_cards, :statuses, on_delete: :cascade
+    add_foreign_key :reports, :accounts, on_delete: :cascade
+    add_foreign_key :reports, :accounts, column: :target_account_id, on_delete: :cascade
```
Comment (ThibG) [inline db/migrate/20170604144747_add_foreign_keys_for_accounts.rb]: I think it is still missing a foreign key for `action_taken_by_account_id`.

File: db/migrate/20170604144747_add_foreign_keys_for_accounts.rb [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+    add_foreign_key :follow_requests, :accounts, column: :target_account_id, on_delete: :cascade
+    add_foreign_key :follows, :accounts, on_delete: :cascade
+    add_foreign_key :follows, :accounts, column: :target_account_id, on_delete: :cascade
+    add_foreign_key :mutes, :accounts, on_delete: :cascade
+    add_foreign_key :mutes, :accounts, column: :target_account_id, on_delete: :cascade
+    add_foreign_key :imports, :accounts, on_delete: :cascade
+    add_foreign_key :media_attachments, :accounts, on_delete: :nullify
+    add_foreign_key :mentions, :accounts, on_delete: :cascade
+    add_foreign_key :mentions, :statuses, on_delete: :cascade
+    add_foreign_key :notifications, :accounts, on_delete: :cascade
```
Comment (ThibG) [inline db/migrate/20170604144747_add_foreign_keys_for_accounts.rb]: I think `from_account_id` is still missing.

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]
I think some foreign keys are still missing. I only focused on `:accounts` for now.

File: db/migrate/20170604144747_add_foreign_keys_for_accounts.rb [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+    add_foreign_key :blocks, :accounts, on_delete: :cascade
+    add_foreign_key :blocks, :accounts, column: :target_account_id, on_delete: :cascade
+    add_foreign_key :follow_requests, :accounts, on_delete: :cascade
+    add_foreign_key :follow_requests, :accounts, column: :target_account_id, on_delete: :cascade
+    add_foreign_key :follows, :accounts, on_delete: :cascade
+    add_foreign_key :follows, :accounts, column: :target_account_id, on_delete: :cascade
+    add_foreign_key :mutes, :accounts, on_delete: :cascade
+    add_foreign_key :mutes, :accounts, column: :target_account_id, on_delete: :cascade
+    add_foreign_key :imports, :accounts, on_delete: :cascade
+    add_foreign_key :media_attachments, :accounts, on_delete: :nullify
```
Comment (ThibG) [inline db/migrate/20170604144747_add_foreign_keys_for_accounts.rb]: I think `media_attachments` is still missing a foreign key to `statuses`.

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]
`media_attachments` is also missing a foreign key on `statuses`

**Review by ClearlyClaire — APPROVED** [review]
Looks good to me

**Comment by Gargron** [comment]
@ThibG The only problem is that this migration might fail if the db contains records that violate these constraints. I don't know how to solve that. Doing data checks inside the migration will likely be taking too long, and given that migrations put a lock on the whole db, that's not acceptable

**Comment by ThibG** [comment]
Indeed, but if this case arises, it means the database is in an inconsistent state, and that the admin should take action anyway. So I don't see the migration failing as much of an issue, as long as the failure is easily understandable and clear instructions are given (e.g., a command to remove database entries with unmet constraints).

File: db/migrate/20170604144747_add_foreign_keys_for_accounts.rb [hunk 5]
```diff
@@ -0,0 +1,41 @@
...
+    add_foreign_key :mentions, :statuses, on_delete: :cascade
+    add_foreign_key :notifications, :accounts, on_delete: :cascade
+    add_foreign_key :notifications, :accounts, column: :from_account_id, on_delete: :cascade
+    add_foreign_key :preview_cards, :statuses, on_delete: :cascade
+    add_foreign_key :reports, :accounts, on_delete: :cascade
+    add_foreign_key :reports, :accounts, column: :target_account_id, on_delete: :cascade
+    add_foreign_key :reports, :accounts, column: :action_taken_by_account_id, on_delete: :nullify
+    add_foreign_key :statuses_tags, :statuses, on_delete: :cascade
+    add_foreign_key :statuses_tags, :tags, on_delete: :cascade
+    add_foreign_key :stream_entries, :accounts, on_delete: :cascade
```
Comment (akihikodaki) [inline db/migrate/20170604144747_add_foreign_keys_for_accounts.rb]: Stream entries are bound to statuses, aren't they?

File: db/migrate/20170604144747_add_foreign_keys_for_accounts.rb [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+    add_foreign_key :blocks, :accounts, on_delete: :cascade
+    add_foreign_key :blocks, :accounts, column: :target_account_id, on_delete: :cascade
+    add_foreign_key :follow_requests, :accounts, on_delete: :cascade
+    add_foreign_key :follow_requests, :accounts, column: :target_account_id, on_delete: :cascade
+    add_foreign_key :follows, :accounts, on_delete: :cascade
+    add_foreign_key :follows, :accounts, column: :target_account_id, on_delete: :cascade
+    add_foreign_key :mutes, :accounts, on_delete: :cascade
+    add_foreign_key :mutes, :accounts, column: :target_account_id, on_delete: :cascade
+    add_foreign_key :imports, :accounts, on_delete: :cascade
+    add_foreign_key :media_attachments, :accounts, on_delete: :nullify
```
Comment (akihikodaki) [inline db/migrate/20170604144747_add_foreign_keys_for_accounts.rb]: Is there any particular intention by keeping media attachments alive when accounts are deleted, while the deletion cascades for statuses?

**Review by akihikodaki — CHANGES_REQUESTED** [review]

File: db/migrate/20170604144747_add_foreign_keys_for_accounts.rb (hunk 5 above)
Comment (Gargron) [inline db/migrate/20170604144747_add_foreign_keys_for_accounts.rb]: Polymorphic associations cannot be constrained via postgres foreign keys, unfortunately.

File: db/migrate/20170604144747_add_foreign_keys_for_accounts.rb (hunk 6 above)
Comment (Gargron) [inline db/migrate/20170604144747_add_foreign_keys_for_accounts.rb]: >The rule on media attachments table is nullify instead of cascade, because presumably we would want to keep the records so that we have a reference to the files that need to be deleted, otherwise those files would be orphaned.

**Review by akihikodaki — APPROVED** [review]

**Comment by clworld** [comment]
FYI: This is SQL I used to make db:migrate success in my environment. https://pastebin.com/GpbtGmbU
Other admins require additional SQLs for other tables maybe.

**Comment by Gargron** [comment]
@clworld Perhaps I will add a rake task for this.
