### PR TITLE
Change design of compose form in web UI

### LINKED ISSUE #1249: An icon for “Content warning”
There’s one for adding a media, one for setting audience, but adding a content warning settle for “cw” which isn’t really clear, especially for users not on the English version of the interface.

Since we appear to be using FontAwesome, some possibilities:
* `exclamation-triangle` or `exclamation-circle`, though they may be interpreted as “there’s an issue with your status”, and are somewhat aggressive.
* `eye-slash`, if not already used somewhere else. It’s not a common use for that icon, but it makes sense in context? Alternative: `low-vision`, maybe even better except if it’s a real established symbol for low vision.
* `flag`? Could work, though may seem to refer to some kind of multi-language content feature (which is a suggestion for later). A triangle minesweeper flag would also be more fitting than the rectangle one.
* `hand-stop-o`?
* `user-secret` could be fun.
* `sticky-note` is a bit uninspired but straightforward.
* another I haven’t thought of.
* something custom yet to design.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### LINKED ISSUE #13258: Text input field and emoji selection in dark mode have a white background
Dark mode is not fully dark on mastodon. Emoji selection is affected, too. 

### Expected behaviour

The text area should be dark, too

### Actual behaviour

it has a white background

### Specifications

Firefox 74 on Ubuntu 19.10

Screenshot_2020-03-13 gruene social

### LINKED ISSUE #18191: inconsistency in exclamation point for send button when replying vs when composing a new post
### Steps to reproduce the problem

1. note that it says "Toot!" when there is no reply
2. note that it says "Toot" when there is a reply

### Expected behaviour

they should both say the same thing, preferably "toot!" instead of "toot"

### Actual behaviour

they are different

### Specifications

mastodon.social

### LINKED ISSUE #19561: Dark Mode - Edit box is not dark
### Steps to reproduce the problem

1. Set Web GUI preferences to Dark Mode
2. Go to main page.
3. Enter a new toot.

### Expected behaviour

Expect white text on a dark background.

### Actual behaviour

You are now looking at black text on a white background.

### Detailed description

Complaining that the edit box isn't in dark mode in Dark Mode may seem like nit-picking. Far from it.

Dark Mode is not a trendy toy. It is actually a fix for an accessibility issue: Partially sighted people can see white text on black far easier than black text on white.

While it may look all aesthetical, it's not helping accessibility.

### Specifications

Mastodon v3.5.1
Firefox 105.0
Ubuntu 20.06

### LINKED ISSUE #19816: Remove padding from the compose form
### Pitch

Why does `<div class="compose-form">` have padding? It means the search and compose boxed are different widths, which looks odd.

Current
Screen Shot 2022-11-05 at 23 27 07

Proposed
Screen Shot 2022-11-05 at 23 31 03

... and actually I'd also remove the padding from `navigation-bar` so the user picture is in line as well. Like so:

Screen Shot 2022-11-05 at 23 38 02

### Motivation

UI consistency.

### LINKED ISSUE #24878: Scope icons are problematic
### Pitch

The post scope icons should be changed to something else. My initial proposal is something like:

Public - Radio tower ("Broadcasting your post")
Unlisted - Loudspeaker ("Everyone within earshot")
Private - Person with checkmark, or a piece of paper with a list ("Authorised persons", maybe for people with open-follow profiles this could be changed to something else)
Direct - Envelope (This is a good metaphor, a letter may be intercepted but is intended for specific recipients)

Note that the descriptions are just meant to connect the metaphor to the semantics, the description should still be there.

### Motivation

The current scope icons for a post are as follows:

1. A globe icon for public posts
2. An open padlock for unlisted posts
3. A closed padlock for private posts
4. An envelope for direct messages

The padlocks in this are problematic simply because it's commonly accepted to mean that something is secure (closed) or insecure (open) via encryption or lack thereof respectively. This might give a false impression that a private post is secured with encryption, and that unlisted posts are somehow insecure compared to private ones. Also, the padlock is visually similar to the private option, a better distinction would be helpful. The icons should also do a better job of describing the semantics of the scope. So the icons for post scopes should be changed.

### LINKED ISSUE #24927: Dark mode is ignored by certain elements
### Steps to reproduce the problem

1. Hide a jarringly bright media element while set to dark mode.
2. Open Mastodon instance in browser with dark mode set note flaming white toot box.
3. Hiding the element replaces it with something nearly as bright which is counter to having dark mode set.

...

### Expected behaviour

The element to denote a hidden media element should have been dark in keeping with the user preference.

### Actual behaviour

I got the same element used for the light mode.

### Detailed description

This also extends to the "What's on your mind" as it does not adhere to the user preference and is always jarringly bright.
High Contrast is the same as Dark.

I did some experimenting and unchecking "Show colorful gradients for hidden media" finally hides things appropriately. However given the original issue was basically just a white placeholder it is unclear that a setting for "colorful gradients" would be the issue when there was no color or gradient.

### Specifications

Platform => web => Waterfox G5.1.5

### LINKED ISSUE #27068: emoji picker not displayed in dark mode
### Steps to reproduce the problem

On desktop when creating a post, choose the emoji picker. Emoji chart will be displayed in light mode instead of dark mode

Forced dark mode in browser and still same light mode

For quick test, I switched Mastodon to light mode
-menu matches both light and dark
-emoji picker stays light mode for both modes

mastodonlightmodeemoji
mastodonemoji

### Expected behaviour

emoji picker also display in dark mode

### Actual behaviour

displayed in light mode

### Detailed description

_No response_

### Mastodon instance

mastoon.social

### Mastodon version

v4.2.0

### Browser name and version

Firefix 117.0.1

### Operating system

Ubuntu

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by Gargron**
One of our testers said that the compose form had an outdated "Windows 7" look about it, so I asked our designer what we could do about it. Also, now it's dark in dark mode, and I've renamed the confusing "Unlisted" into a slightly less misleading "Quiet public".

**Editing a post:**

Screenshot 2024-01-23 at 08-35-45 Localhost

**Replying to a post:**

Screenshot 2024-01-23 at 08-35-29 Localhost

**Adding a content warning:**

Screenshot 2024-01-23 at 08-35-10 Localhost

**Adding media:**

Screenshot 2024-01-23 at 08-34-56 Localhost

**Adding a poll:**

Screenshot 2024-01-23 at 08-34-29 Localhost

**Empty:**

Screenshot 2024-01-23 at 08-34-05 Localhost

**Selecting post visibility:**

grafik

___

Fixes MAS-206

Additionally:

- Fixes #27068
- Fixes #24927
- Fixes #19561
- Fixes #13258
- Fixes #24878
- Fixes #18191

### CODE REVIEW

**Comment by connie-e** [comment]
The composer looks cramped with the post button being with the icons.

**Comment by renchap** [comment]
This is a work in progress and we are working on improving this with our designer.

We do not plan large changes to the compose box at the moment (because they would require a large redesign), like moving it elsewhere on the screen, but the final design will be less cramped.

**Comment by jmking-iftas** [comment]
I feel like the privacy and language "public" and "english" should be inverted to white on blue along the same lines as a selected post type. In these examples they look more like content tags. If they were inverted so they are "selected" (and assuming when i tap ore click I get the drop down options which would not be selected/blue on white) it might help them.

I like graying out (and disabling?) the eg media attachment when poll is selected or vice versa, nice touch, better than hiding it IMO. Will the grayed out get a desc of "a poll cannot be added to posts with uploaded media" type language? Should compose-form__upload-button be white on blue if at least one item has been uploaded?

Moving privacy to include the word (public/followers-only etc) is an upgrade (maybe lose the icons altogether?) and having language next to it also a plus. I see some logic as to what languages show up there, but in general I'd want to be sure the languages I use mostly appear at the top of that list, or restrict it if I've set language filters to only show me eg ten languages, those are the ten that should be in this list.

Should these two be separated from the compose area? When I add a poll I get a HR feature in compose-form__uploads-wrapper, maybe something similar to tease these two post configurations apart from the post content itself? ( I note the hr has been removed in these mockups, I think it should be reviewed for helpfulness understanding the free text compose area vs fixed items)

Changing the button text to reply or update when relevant is a great idea, and will help folks who think they're replying to a toot realise it's unattached. There will be some holdouts (probably me included) who still want the "post" to read "toot" instead, which may impact the update and reply option due to hacky CSS workarounds, but in general having context-sensitive button text is an improvement.

The emoji icon was likely moved for good reasons, but I'm curious why it's no longer up in the content area - that's where emojis go. Having this icon down with the "post configuration stuff" makes it seem like I need to set this post's mood or something, not insert emoji.

**Comment by vmstan** [comment]
Edit button coloring is inverted on High Contrast theme.

Screenshot 2023-12-18 at 9 32 22 AM
Screenshot 2023-12-18 at 9 31 49 AM

**Comment by ClearlyClaire** [comment]
This looks more modern overall and I'm happy language and visibility options are visible and spelled out, and I'm happy about the single/multiple poll options being explicit now!

This feels a bit cramped overall, but the two-line fallback looks very good!
image

The new reply indicator has potential, but I feel the inconsistent layout confusing (I think the display name and handle should be on two lines):
image

The contrast overall seems off, especially in the CW field:
image

The lack of border or contrast between the dropdowns and the composer feels confusing as well:
image

Margins are missing from the mobile UI:
image

… as well as the advanced interface:
image

**Comment by vmstan** [comment]
Yeah can confirm mobile margins are missing.

**Comment by Andre601** [comment]
I think the CW needs a bit more work. This yellow-black stripe patterns doesn't fit the overall style from what I can tell and a simple yellow border would do the trick too.

File: app/javascript/mastodon/components/autosuggest_textarea.jsx [hunk 1]
```diff
@@ -183,40 +183,41 @@ const AutosuggestTextarea = forwardRef(({
...
-    <div className='autosuggest-textarea__suggestions-wrapper' key='suggestions-wrapper'>
-      <div className={`autosuggest-textarea__suggestions ${suggestionsHidden || suggestions.isEmpty() ? '' : 'autosuggest-textarea__suggestions--visible'}`}>
-        {suggestions.map(renderSuggestion)}
-      </div>
-    </div>,
-  ];
+  return (
+    <div className='autosuggest-textarea'>
+      <label>
+        <span style={{ display: 'none' }}>{placeholder}</span>
```
Comment (vvalentin-lucca) [inline app/javascript/mastodon/components/autosuggest_textarea.jsx:189]: This text is used to identify the nature of the form field associated with the wrapping label.

With `display: none`, it's considered absent to user agents, so we end up with a form field that has no label. 

Instead, you should apply a `sr-only` class to it.
Something like:
```css
.sr-only {
	border: 0 !important;
	clip: rect(1px, 1px, 1px, 1px) !important;
	-webkit-clip-path: inset(50%) !important;
	clip-path: inset(50%) !important;
	height: 1px !important;
	width: 1px !important;
	margin: -1px !important;
	overflow: hidden !important;
	padding: 0 !important;
	position: absolute !important;
	white-space: nowrap !important;
}
```

**Comment by ClearlyClaire** [comment]
This seems to break the styling of the category picker in the moderation interface:
image

Also slightly affects the selection in the report modal:
image

**Comment by ThisIsMissEm** [comment]
On the composer, having everything with a white background feels a little.. ungrounded / lacking visual distinction. I did up this rather quick mock-up of inverting the colours on the bottom bar:

image

I've also moved the count up into the "textarea" section, which would allow for more buttons in the composer if more features get added. This is like a cross between the current design and the new design, I guess (yes the margins/padding are messed up, because I did this in the developer tools)

Out of band hashtags could also be added in this UI where the visibility and language selectors are too.

**Comment by ThisIsMissEm** [comment]
As for the content warning design.. I'm not a fan at all of the yellow/black striped pattern. This feels like it's very.. risky or unsafe to do? i.e., the visual language almost discourages the usage of content warnings, I think?

image

It feels like there's probably a better design for these? It's also not immediately obvious that there's a text input there, which could confuse users.

**Comment by ThisIsMissEm** [comment]
> This seems to break the styling of the category picker in the moderation interface: image
> 
> Also slightly affects the selection in the report modal: image

These two UI elements currently re-use styles from the composer, which really needs to be cleaned up and fixed (we've had many breakages due to this "reuse")

**Comment by ThisIsMissEm** [comment]
I'm also not sure "Style" is the right label for the poll type selector.. Maybe it should just be a toggle? "Multiple Options / Single Option"

**Comment by Andre601** [comment]
> On the composer, having everything with a white background feels a little.. ungrounded / lacking visual distinction. I did up this rather quick mock-up of inverting the colours on the bottom bar:
> 
> image
> 
> I've also moved the count up into the "textarea" section, which would allow for more buttons in the composer if more features get added. This is like a cross between the current design and the new design, I guess (yes the margins/padding are messed up, because I did this in the developer tools)
> 
> Out of band hashtags could also be added in this UI where the visibility and language selectors are too.
> 
> (The design in claire's first image is also similar: [#28119 (comment)](https://github.com/mastodon/mastodon/pull/28119#issuecomment-1860927317) )

That design doesn't look good. Using the brand color that much hurts the UI more than helping it, primarely because it makes the buttons less noticable as such.
I feel like just using a slightly darker white color to give it a separation may work better here. But the purple is just too agressive here.

File: app/javascript/mastodon/locales/en.json [hunk 2]
```diff
@@ -525,14 +523,14 @@
...
+  "privacy.direct.long": "Everyone mentioned in the post",
+  "privacy.direct.short": "Specific people",
+  "privacy.private.long": "Only your followers",
+  "privacy.private.short": "Followers",
+  "privacy.public.long": "Anyone on and off Mastodon",
   "privacy.public.short": "Public",
-  "privacy.unlisted.long": "Visible for all, but opted-out of discovery features",
-  "privacy.unlisted.short": "Unlisted",
+  "privacy.unlisted.long": "Public with less reach",
+  "privacy.unlisted.short": "Low-key public",
```
Comment (ClearlyClaire) [inline app/javascript/mastodon/locales/en.json:533]: I am not a fan of changing existing strings, and in this case, the new strings do not seem clearer.

Arguably, all options but the most public ones are “Specific people” only, “Low-key public” is not more understandable than “Unlisted” (although I understand “Unlisted” is often misunderstood as well), “Public with less reach” is not more understandable than “Visible for all, but opted-out of discovery features”.

Also you are describing a group of people, but not what these people can do. It could conceivably be confused with e.g. reply controls.

**Review by ClearlyClaire — COMMENTED** [review]
The code changes are mostly fine, but there are still a few CSS and design issues, especially in narrow views (such as mobile in certain cases, or the advanced interface; screenshots come from the latter):

image
image

- long usernames push the action button out of frame
- long privacy options and language options get ellipsized
- poll settings overflow

I'm also still not convinced with the reply indicator having the username and display name on the same line, which is in contrast of how posts are displayed everywhere, does not leave any space for the username in practice, and may end up being confusing. I think the following would be better:
image

File: app/javascript/mastodon/locales/en.json (hunk 2 above)
Comment (Gargron) [reply app/javascript/mastodon/locales/en.json:533]: This can be iterated on after the holidays, when Sam is back.

Comment (ClearlyClaire) [reply app/javascript/mastodon/locales/en.json:533]: I guess, but this will be all the more iterations translators will have to work with :/

**Comment by nclm** [comment]
Super nice to see the compose form updated!

I particularly like the visibility settings and the language being upgraded as bubbles instead of icons.

The content warning box is fun but very out of style and a little scary looking. I wonder if reworking along the lines of the “Editing” header could work better (as well as providing a visible label for the field).

Something like:
cw1

Or it could even be in the accent colour?
cw2

Maybe the gray box could even be kept for other sort of attachments, like polls?
poll1

It also makes it clearer how to remove a poll, a content warning, etc, as we get the X icon there.

Just quick drafty mock-ups, but I feel that having reusable bits with clear delimitations and labels could make the interface better. But in general, I like the direction this is going!

**Comment by brendanjones** [comment]
While doing this can we please take the opportunity to fix the alignment of the compose box and the user profile? As per https://github.com/mastodon/mastodon/issues/19816

**Comment by renchap** [comment]
This has already been fixed

image

**Comment by vmstan** [comment]
Does not appear to have changed on mobile.

image

**Comment by vmstan** [comment]
Closes #1249

**Comment by ClearlyClaire** [comment]
Seems like `spec/system/share_entrypoint_spec.rb` needs an update for the composer markup changes.

File: app/javascript/mastodon/components/autosuggest_textarea.jsx (hunk 1 above)
Comment (Gargron) [reply app/javascript/mastodon/components/autosuggest_textarea.jsx]: I'm pretty sure an `aria-label` can replace this.

**Comment by Andre601** [comment]
Okay, can I ask for more understandable commit messages?

Constantly getting "Change design of compose form in web UI" in notifications does nothing in telling me what changed.
And looking at the actual changes may also not be easy to understand...

**Comment by vmstan** [comment]
CleanShot 2024-01-23 at 10 02 25

The placeholder "What's on your mind" text color needs to be lightened up, but I love the new dark text box.

**Comment by vmstan** [comment]
@Gargron looks good in latest commit.

**Comment by tsmethurst** [comment]
> I've renamed the confusing "Unlisted" into a slightly less misleading "Low-key public"

I'm surprised nobody else has commented on this yet. In my opinion "low-key public" is much more confusing than "unlisted". "Public" and "unlisted" actually have distinct semantic meaning and complement each other. "Low-key public" on the other hand is essentially meaningless. If you want people to understand what "unlisted" means, then in my view a better approach is to support it properly, clearly document it, and provide a link to documentation about it. Every time you noodle around renaming something like this, it invalidates all the community knowledge that's been built up around the old term.

**Review by ClearlyClaire — COMMENTED** [review]
On the code side, this is a welcome refactor, especially the move to functional components.

I have only skimmed through the CSS changes but they seem sensible.

On the design side, this is mostly an improvement but I still have significant concerns with:
- various text not getting enough horizontal space in some languages, especially (but not only) in width-constrained environments like the “advanced interface” and some mobile screens
- low contrast across the board, including the high contrast theme
- ~~surprising color choice in the light theme, to the point of the form looking disabled~~ (edit: addressed for now)
- string changes like “Unlisted / Visible for all, but opted-out of discovery features” becoming “Low-key public / Public with less reach”: I don't think this communicates what it does any better, and may make people who already understand what “Unlisted” means believe that the functionality somehow changed

**Comment by Andre601** [comment]
> > I've renamed the confusing "Unlisted" into a slightly less misleading "Low-key public"
> 
> I'm surprised nobody else has commented on this yet. In my opinion "low-key public" is much more confusing than "unlisted". "Public" and "unlisted" actually have distinct semantic meaning and complement each other. "Low-key public" on the other hand is essentially meaningless. If you want people to understand what "unlisted" means, then in my view a better approach is to support it properly, clearly document it, and provide a link to documentation about it. Consistency is important: every time you noodle around renaming something like this, it invalidates all the community knowledge that's been built up around the old term.
> 
> EDIT: also the half moon icon makes very little sense. What is it trying to convey?

I agree on this... I have no idea what "Low-key public" should mean, but "Unlisted" makes sense to me.
If anything would "Hidden" be a better option if "Unlisted" really shouldn't be used anymore...

Not to mention is "Low-key public" just more wordy...

**Comment by tullo-x86** [comment]
In what world does "Public with less reach" convey more information than "Visible for all, but opted-out of discovery features"?

If a user sees "low-key public" for the first time, and would like to find out what the site means by "less reach", what resource is available for them to find out what it does differently to "public"? And if this change necessitates **directing the user away from their current activity** — the compose box — to find that information, perhaps it makes more sense to simply leave the description as "Visible for all, but opted-out of discovery features" _since that's what it represents_.

**Comment by yeenbean** [comment]
imagine thinking "low-key public" is less confusing than "unlisted" 💀

**Comment by ThisIsMissEm** [comment]
Can we perhaps please take the discussion about what to call "unlisted" to a new issue? It's really just one of the changes here, and this PR is already notifying a lot of people, so the discussion is starting to get a little off topic, especially with comments that don't really add much to the conversation

**Comment by tullo-x86** [comment]
> Can we perhaps please take the discussion about what to call "unlisted" to a new issue?

Indeed — that verbiage change is fairly off-topic for this pull request.

Speaking of which, what's that change doing intermingled with these styling changes in the first place? Surely it deserves its own PR…

**Comment by tsmethurst** [comment]
It seems a bit odd to put the burden on reviewers to make an issue in order to discuss a change included in a pull request. Creating an issue should be the responsibility of the person proposing the changes, in order to gauge interest in a change / gather feedback *before* writing code, should it not?

But anyway *this* comment about procedure is indeed off topic and I'm not a contributor anyway so I'll leave the thread be.

**Comment by renchap** [comment]
I created a specific discussion for this change: https://github.com/mastodon/mastodon/discussions/28887

As noted in the header, I was not involved in the decision but I tried to gather some context to understand the reasons for this change.

Let's keep the comments here about the refactor, and use the discussion above to discuss the "Unlisted" name change.

**Comment by Akselmo** [comment]
what does lowkey public mean

**Comment by msikma** [comment]
> Can we perhaps please take the discussion about what to call "unlisted" to a new issue?

I understand what you're saying, and I say this with respect, but I don't think there's any reason to consider what looks like a regression in interface intuitiveness as something not relevant to the PR, when this PR is specifically about design improvements. It would be better to get this cleared up one way or another before this is merged, rather than "just open a separate issue if you don't like it and we'll fix it someday maybe."

**Comment by nileane** [comment]
Something I just noticed while working on adapting my custom theme to the new compose form, the selected visibility icon has an "icon-undefined" class regardless of what visibility is selected (which is problematic in my case for assigning a custom icon to each visibility setting).

Safari - 2024-01-25 à 16 24 2@2x

File: app/javascript/mastodon/features/compose/components/privacy_dropdown.jsx [hunk 3]
```diff
@@ -259,23 +245,21 @@ class PrivacyDropdown extends PureComponent {
...
+          aria-expanded={open}
           onClick={this.handleToggle}
           onMouseDown={this.handleMouseDown}
           onKeyDown={this.handleButtonKeyDown}
-          style={{ height: null, lineHeight: '27px' }}
           disabled={disabled}
-        />
+          className={classNames('dropdown-button', { active: open })}
+        >
+          <Icon icon={valueOption.iconComponent} />
```
Comment (ClearlyClaire) [inline app/javascript/mastodon/features/compose/components/privacy_dropdown.jsx:258]: This should address @nileane's issue:
```suggestion
          <Icon id={valueOption.icon} icon={valueOption.iconComponent} />
```

Sorry I have not caught that in my review.

File: app/javascript/mastodon/features/compose/components/privacy_dropdown.jsx [hunk 4]
```diff
@@ -135,6 +134,12 @@ class PrivacyDropdownMenu extends PureComponent {
               <strong>{item.text}</strong>
               {item.meta}
             </div>
+
+            {item.extra && (
+              <div className='privacy-dropdown__option__additional' title={item.extra}>
+                <Icon icon={InfoIcon} />
```
Comment (ClearlyClaire) [inline app/javascript/mastodon/features/compose/components/privacy_dropdown.jsx:140]:
```suggestion
                <Icon id='info-circle' icon={InfoIcon} />
```

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]

**Review by ClearlyClaire — APPROVED** [review]

**Comment by renchap** [comment]
This has been merged with an updated label for the previous "Unlisted" option based on the various feedback we received.

This may be changed again after gathering more data and ideas, but we wanted to have the composer update merged so we can have wider testing on it, and any other change will be done in a further PR.

If you want to participate to this discussion about the "Unlisted" visibility, please use the ad-hoc discussion: https://github.com/mastodon/mastodon/discussions/28887

**Comment by nclm** [comment]
Tiny bug report: clicking on the emoji icon when the emoji picker is opened should close the picker (in the same way clicking again the poll or cw icon closes the poll or cw fields). Right now, clicking the emoji icon again seems to reopen the emoji picker which is already opened.

**Comment by Ember-ruby** [comment]
i don't get the change of moving the publish button into the compose box, it just seems to needlessly cramp both it and the compose box

**Comment by omentic** [comment]
Hello, with the addition of scary orange-and-black tape to the content warning field, I have anecdotally noticed a significant reduction in their use. I happen to think that content warnings are extremely useful, as content warnings and also as titles. Having DANGER ALERT style CSS when composing them discourages new users from using them, I think, and I think that's not something to be discouraged.

I would appreciate it if this style change was reverted.
