### PR TITLE
Fix missing value limits for `UserRole` position

### LINKED ISSUE #26256: Creation of a custom role with priority below `-2,147,483,648` yields an `out of range` error.
# Summary
When creating a custom role from the admin _Add role_ page (`/admin/roles/new`), the _Priority_ input field accepts integer values < `-2,147,483,648` which yields a rails `out of range` error upon submitting the form.

# Steps
- Navigate to the _Add role_ page
- Enter an arbitrary string for the _Name_ field
- Enter `-2,147,483,649` for the _Priority_ field
- Click _Save Changes_ to submit the form
outofrange

# Additional information
Priority value input validation prohibits an entry above `999` (presumably so that no custom role supersedes the Owner role), but there is no input validation for negative integers.

### Expected behaviour

The Priority input field for the Add role form should forbid entering a negative value that exceeds the bound of a 4-byte signed integer

### Actual behaviour

A negative value can be entered into the priority input field, yielding an out of range error upon form submission 

### Detailed description

_No response_

### Mastodon instance

dev environment

### Mastodon version

v4.1.5

### Browser name and version

Brave 1.56.11

### Operating system

macOS 13.4.1 (c)

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by mjankowski**
Resolves https://github.com/mastodon/mastodon/issues/26256

Similar to existing https://github.com/mastodon/mastodon/blob/v4.3.2/app/models/webauthn_credential.rb#L18

What is currently an app error becomes an utterly absurd validation error instead:

Screenshot 2024-12-03 at 21 28 40

Possible followup...

- I bet there are more of these where user-supplied values could exceed a column limit, could do audit on that
- I could have sworn there was either a more framework-native way to do this, or a way to introspect into PG/Rails to get these values, but I can't find it

### CODE REVIEW

**Review by oneiros — APPROVED** [review]

File: app/models/user_role.rb [hunk 1]
```diff
@@ -89,6 +91,7 @@ module Flags
 
   validates :name, presence: true, unless: :everyone?
   validates :color, format: { with: /\A#?(?:[A-F0-9]{3}){1,2}\z/i }, unless: -> { color.blank? }
+  validates :position, numericality: { greater_than_or_equal_to: -POSITION_LIMIT, less_than_or_equal_to: POSITION_LIMIT }
```
Comment (ClearlyClaire) [inline app/models/user_role.rb:94]: I think there is an off-by-one, in that `POSITION_LIMIT` should be a disallowed value. But also, the form should not allow it in practice thanks to the `max` attribute.

I think this can also be more concisely and accurately written as:
```suggestion
  validates :position, numericality: { greater_than_or_equal_to: (-POSITION_LIMIT)..POSITION_LIMIT }
```

But in either case, I'm surprised `simple_form` does not output appropriate `min` and `max` values for the input. I'm also surprised there isn't a better way to do this, Rails is already aware of the allowed range, isn't there an option for it to validate against that known valid range instead of coming up with our own limits?

Comment (oneiros) [reply app/models/user_role.rb:94]: > I think there is an off-by-one, in that POSITION_LIMIT should be a disallowed value. 

I had a similar worry, but I believe the added test should have caught this if it was the case.

> I think this can also be more concisely and accurately written as:

Did you mean `in` instead of `greater_than_or_equal_to`? That would be more concise indeed.

Comment (oneiros) [reply app/models/user_role.rb:94]: > I had a similar worry, but I believe the added test should have caught this if it was the case.

Otoh it probably does not try to actually persist the record. Sorry, I am always a bit confused how those shoulda matchers work.

Comment (ClearlyClaire) [reply app/models/user_role.rb:94]: > Did you mean `in` instead of `greater_than_or_equal_to`? That would be more concise indeed.

Yes, that's what I meant!

**Comment by oneiros** [comment]
Looks like I merged this a bit prematurely. The changes do not make anything especially worse, so I am not going to revert.

But would you maybe have a look at that open discussion, @mjankowski? I would really appreciate that.

**Comment by mjankowski** [comment]
> The changes do not make anything especially worse, so I am not going to revert.

Yes, this is at least less bad than no validation. 

> But would you maybe have a look at that open discussion, @mjankowski? I would really appreciate that.

Yes - I think the off by one observation from above is correct. Will fix that and look at other comments in follow up PR.
