### PR TITLE
Fix follow recommendation moderation page default language when using regional variant

### LINKED ISSUE #32380: Follow recommendations page defaults to first alphabetical language (Afrikaans)
### Steps to reproduce the problem

1. Navigate to the "Follow recommendations" moderation page

### Expected behaviour

List is not filtered by Afrikaans

### Actual behaviour

List is filtered by Afrikaans

### Detailed description

More sensible default would probably be: no filter selected (as in trending posts), my current user language, or the server default locale.

### Mastodon instance

sunny.garden

### Mastodon version

v4.3.0

### Browser name and version

Firefox 131.0.2

### Operating system

Microsoft Windows [Version 10.0.19045.4894]

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #32380

### CODE REVIEW

File: app/models/follow_recommendation_filter.rb [hunk 1]
```diff
@@ -11,10 +11,19 @@ class FollowRecommendationFilter
...
   end
 
+  def usable_language(locale)
+    return locale if Trends.available_locales.include?(locale)
+
+    locale = locale.to_s.split(/[_-]/).first
+    return locale if Trends.available_locales.include?(locale)
+
+    nil
+  end
```
Comment (oneiros) [inline app/models/follow_recommendation_filter.rb:25]: How about making this method private and moving it to the bottom? It seems like a small utility method that should not be called from outside.

**Review by oneiros — APPROVED** [review]
