### PR TITLE
Reject announce payload if object is nil

### LINKED ISSUE #33569: AP: Announce with null object will crash AP worker
I got this activity bouncing around the dead queue:

```json
{
    "@context": "https://www.w3.org/ns/activitystreams",
    "id": "https://app.wafrn.net/fediverse/post/2692d835-442c-49cf-947f-51ec17586ba2",
    "type": "Announce",
    "actor": "https://app.wafrn.net/fediverse/blog/fluffye",
    "published": "2024-12-01T13:32:50.510Z",
    "to": [
        "https://www.w3.org/ns/activitystreams#Public"
    ],
    "cc": [
        "https://app.wafrn.net/fediverse/blog/fluffye",
        "https://app.wafrn.net/fediverse/blog/fluffye/followers"
    ],
    "object": null,
    "signature": {
        "type": "RsaSignature2017",
        "creator": "https://app.wafrn.net/fediverse/blog/fluffye",
        "domain": "app.wafrn.net",
        "nonce": "6e1408f8b6799cceed9e1e6a3d4b50b4",
        "created": "2024-12-01T13:32:50.510Z",
        "signatureValue": "LbJfZ8O0dPpK3qcjMT5AI1Q6EiuabpGUWQ1Tc6oXDhWCIylpdwrtWfjlVUntkNLhGFZtELxnLvU4QEvEp586SiBeHeVBTASVQZgR1LBP7WcYyhAAJvz2yppZr3xmjANpMu+sWXGzucEG+Jn1TIUytX9MNwI7Q0CF+Z2CRiw7LcVkIVDXBL+Qoq8bEi5GF4HhMNJpPypunhTOd/u3j/xdrwg0byDEe640BsaRL8f5uGas9rs3eg7dGS3W91IFUlIwtCPMnIDRuXpMelQ7uJSm9APMkwBbhSocfycAlWOLNXXA9TPhi+prtukktSgcj9VkK0587oUbs3FnE0qnJGkzK5H2hZh986cdLeLar8z6XGR3mZc0UA6FVCx+BjkPQlLAecioX816/DDM0WOY3HHb8B1DCxHJTX2xZvMaCY9k4EY+45TG1FHhZgzDPJvfjhtJ9J6VZPk913xbcq05ULsRls9B2C+C+Hx43noHOGtVI5IHVoh0/5FUlG5xW+OhVqMAt2hB/w264yRVYzoz64o5n/K0RJNyQL0he7Adf1WTZZrS9Gy8zxsb6xuJ4Bq7UPiPo4CY8n3/hHNC6EEJzhTVLqNQPxz2XN5gl1zfmXZtymZ1Gtkp9ngTIApONRDX0df9trZTjFt9O4XWag7E8nQs1q5RJIDTvO53rKXF0Rnl8I0="
    }
}
```

I already talked to the dev of the server software (wafrn) about this bug, but it results in this traceback;

```
app/lib/activitypub/activity.rb:83:in `supported_object_type?': undefined method `[]' for nil (NoMethodError)

    equals_or_includes_any?(@object['type'], SUPPORTED_TYPES)
                                   ^^^^^^^^
	from app/lib/activitypub/activity.rb:79:in `unsupported_object_type?'
	from app/lib/activitypub/activity.rb:105:in `status_from_object'
	from app/lib/activitypub/activity/announce.rb:8:in `block in perform'
	from app/models/concerns/lockable.rb:12:in `block (2 levels) in with_redis_lock'
	from mario-redis-lock (1.2.1) lib/redis_lock.rb:44:in `acquire'
	from app/models/concerns/lockable.rb:10:in `block in with_redis_lock'
	from connection_pool (2.4.1) lib/connection_pool.rb:110:in `block (2 levels) in with'
	from connection_pool (2.4.1) lib/connection_pool.rb:109:in `handle_interrupt'
	from connection_pool (2.4.1) lib/connection_pool.rb:109:in `block in with'
	from connection_pool (2.4.1) lib/connection_pool.rb:106:in `handle_interrupt'
	from connection_pool (2.4.1) lib/connection_pool.rb:106:in `with'
	from app/lib/redis_connection.rb:10:in `with'
	from app/models/concerns/redisable.rb:9:in `with_redis'
	from app/models/concerns/lockable.rb:9:in `with_redis_lock'
	from app/lib/activitypub/activity/announce.rb:7:in `perform'
	from app/services/activitypub/process_collection_service.rb:69:in `process_item'
	... 25 levels...
```

(line numbers may possibly be different due to glitch-soc fork, but the equivalent error line is https://github.com/mastodon/mastodon/blob/53885b0fdb8b25bb0d531df2cd90bdb223e21dc6/app/lib/activitypub/activity.rb#L83)

I think that, due to `@object` being `nil`/`null`, this activity should've been discarded earlier in the process, right?

### Detailed description

_No response_

### Mastodon instance

`tech.lgbt`

### Mastodon version

`v4.4.0-alpha.1+glitch`

### PR DESCRIPTION
**Pull request by ShadowJonathan**
Fixes #33569

This will catch;
```json5
{
   "type": "Announce",
   "object": null,
   ...
}
```

and

```json5
{
   "type": "Announce",
   // no "object" key
   ...
}
```

These are remote development bugs, yes, but we should make sure that the AP parser/processor properly exits if it can't do anything about these activities.

### CODE REVIEW

File: app/lib/activitypub/activity/announce.rb [hunk 1]
```diff
@@ -5,6 +5,8 @@ def perform
     return reject_payload! if delete_arrived_first?(@json['id']) || !related_to_local_activity?
 
     with_redis_lock("announce:#{value_or_id(@object)}") do
+      return reject_payload! if @object.nil?
```
Comment (ClearlyClaire) [inline app/lib/activitypub/activity/announce.rb:8]: I think this should go even earlier, you can avoid the Redis lock.

Comment (ShadowJonathan) [reply app/lib/activitypub/activity/announce.rb]: Done, placed it before the redis lock

**Review by ClearlyClaire — APPROVED** [review]
