### PR TITLE
  Fix 404 error after deleting status from detail view (#35800)

### LINKED ISSUE #35800: There is a bug in the deletion of the post details page
### Steps to reproduce the problem

There is a bug in the deletion of the post details page

### Expected behaviour

/

### Actual behaviour

/

### Detailed description

_No response_

### Mastodon instance

mastodon.social

### Mastodon version

/

### Browser name and version

/

### Operating system

/

### Technical details

https://github.com/user-attachments/assets/37d15cb9-c14f-4e79-ac7e-77768162739c

### PR DESCRIPTION
**Pull request by crafkaz**
## Summary

  Fixes #35800 - Resolves bug where users encounter a 404 error after deleting a status from its detail page.

  ### After Fix

  **Detail page deletion (with redirect to profile):**
  [Image from Gyazo](https://gyazo.com/7fcb087f1c2d53addbc552eea3e3817b)

  **Timeline deletion (with success toast):**
  [Image from Gyazo](https://gyazo.com/df8213505ea894eb84214a5d4f4c43d6)

  ### Changes Made

  - **Fix detail view deletion**: When deleting a status from its detail page, users are now properly redirected to their profile timeline instead of staying on the deleted
  status URL
  - **Add success feedback**: Users now receive a toast notification confirming successful deletion
  - **Improve timeline deletion**: Added success toast notifications when deleting posts from timeline views for better user feedback

  ### Technical Details

  - Modified `deleteStatus` action to return a Promise for proper async handling
  - Updated deletion confirmation modal to support success callbacks
  - Enhanced status detail page to redirect to profile after deletion
  - Added localized success messages (English and Japanese)

  ### Test Plan

  - [x] Delete a status from its detail page → redirects to profile with success toast
  - [x] Delete a status from timeline → shows success toast without redirect
  - [x] Verify translations display correctly in both languages
  - [x] Confirm no 404 errors occur after deletion

### CODE REVIEW

File: app/javascript/mastodon/containers/status_container.jsx [hunk 1]
```diff
@@ -1,7 +1,11 @@
-import { injectIntl } from 'react-intl';
+import { injectIntl, defineMessages } from 'react-intl';
 
 import { connect } from 'react-redux';
 
+const messages = defineMessages({
+  deleteSuccess: { id: 'status.delete.success', defaultMessage: 'Post deleted.' },
```
Comment (diondiondion) [inline app/javascript/mastodon/containers/status_container.jsx]: Could you please remove the period `.` from the end of this translation?

File: app/javascript/mastodon/features/status/index.jsx [hunk 2]
```diff
@@ -75,6 +76,7 @@ const messages = defineMessages({
   hideAll: { id: 'status.show_less_all', defaultMessage: 'Show less for all' },
   statusTitleWithAttachments: { id: 'status.title.with_attachments', defaultMessage: '{user} posted {attachmentCount, plural, one {an attachment} other {# attachments}}' },
   detailedStatus: { id: 'status.detailed_status', defaultMessage: 'Detailed conversation view' },
+  deleteSuccess: { id: 'status.delete.success', defaultMessage: 'Post deleted successfully' },
```
Comment (diondiondion) [inline app/javascript/mastodon/features/status/index.jsx]: This should have the same default message as the other message definition.

**Review by diondiondion — CHANGES_REQUESTED** [review]
Thanks for your contribution! To me this looks good, just some feedback about the wording.

File: app/javascript/mastodon/containers/status_container.jsx [hunk 3]
```diff
@@ -105,10 +110,23 @@ const mapDispatchToProps = (dispatch, { contextType }) => ({
   },
 
   onDelete (status, withRedraft = false) {
+    const handleDeleteSuccess = () => {
+      dispatch(showAlert({
```
Comment (Gargron) [inline app/javascript/mastodon/containers/status_container.jsx]: Would it not be better to dispatch the alert from the action itself, similar to what we do for "Post published"? If it repeats in multiple places.

File: app/javascript/mastodon/containers/status_container.jsx (hunk 1 above)
Comment (crafkaz) [reply app/javascript/mastodon/containers/status_container.jsx]: Fixed! Removed the period.

File: app/javascript/mastodon/features/status/index.jsx (hunk 2 above)
Comment (crafkaz) [reply app/javascript/mastodon/features/status/index.jsx]: Fixed! Now using unified message.

File: app/javascript/mastodon/containers/status_container.jsx (hunk 3 above)
Comment (crafkaz) [reply app/javascript/mastodon/containers/status_container.jsx]: Implemented dedicated action.

**Comment by crafkaz** [comment]
@diondiondion @Gargron
  Thanks for the feedback! I've addressed all the points:
  - Removed the period from the translation
  - Consolidated the delete functionality into a dedicated action (similar to "Post published")
  - This eliminates the duplicate alert handling across multiple components

File: app/javascript/mastodon/components/status_container_types.ts [hunk 4]
```diff
@@ -0,0 +1,8 @@
+export interface StatusContainerProps {
+  id: string;
+  contextType?: string;
+  ref?: unknown;
+  wrappedComponentRef?: unknown;
+  children?: React.ReactNode;
+  [key: string]: unknown;
+}
```
Comment (diondiondion) [inline app/javascript/mastodon/components/status_container_types.ts]: Typing the `StatusContainer` component is an unrelated (larger) change and would best be done separately, could you please remove it from this PR?

File: app/javascript/mastodon/containers/status_container.jsx [hunk 5]
```diff
@@ -59,7 +60,7 @@ const makeMapStateToProps = () => {
   return mapStateToProps;
 };
 
-const mapDispatchToProps = (dispatch, { contextType }) => ({
+const mapDispatchToProps = (dispatch, { contextType, intl }) => ({
```
Comment (diondiondion) [inline app/javascript/mastodon/containers/status_container.jsx]: This doesn't sem to be used anymore.

File: app/javascript/mastodon/actions/delete.js
Comment (diondiondion) [inline app/javascript/mastodon/actions/delete.js:1]: While it's not a bad idea in principle to move these actions into their own file, they should still be grouped with the remaining `statuses` actions. So I think either they should be moved back into `statuses.js` for now, or `statuses.js` should be changed to `statuses/index.js` with a separate `statuses/delete.js`. I'd prefer keeping them in statuses.js for now and doing a separate refactor to split them into their own files as necessary.

File: app/javascript/mastodon/components/status_quoted.tsx [hunk 6]
```diff
@@ -221,6 +221,7 @@ export const StatusQuoteManager = (props: StatusQuoteManagerProps) => {
 
   if (quote) {
     return (
+      // @ts-expect-error Redux connected component has complex props
```
Comment (diondiondion) [inline app/javascript/mastodon/components/status_quoted.tsx]: Is this necessary? For me, TS is not flagging an error here or below on the `main` branch.

**Review by diondiondion — CHANGES_REQUESTED** [review]

File: app/javascript/mastodon/components/status_quoted.tsx (hunk 6 above)
Comment (crafkaz) [reply app/javascript/mastodon/components/status_quoted.tsx]: @diondiondion 
This TypeScript error appears in my local build and also showed up in recent GitHub Actions. Since you're not experiencing it on main, should I remove this comment and let the CI test whether it's still needed?

Comment (crafkaz) [reply app/javascript/mastodon/components/status_quoted.tsx]: @diondiondion 
https://github.com/mastodon/mastodon/actions/runs/17221191607/job/48888398086

Comment (diondiondion) [reply app/javascript/mastodon/components/status_quoted.tsx]: Thanks for checking, feel free to keep those comments in then 👍

Comment (crafkaz) [reply app/javascript/mastodon/components/status_quoted.tsx]: @diondiondion 
My apologies! After I fixed app/javascript/mastodon/containers/status_container.jsx, the TypeScript error is now resolved.

File: app/javascript/mastodon/actions/delete.js
Comment (crafkaz) [reply app/javascript/mastodon/actions/delete.js:1]: @diondiondion 
You're absolutely right. I've moved the actions back into statuses.js to keep them grouped together.

I agree that a separate refactor would be the better approach for splitting these files when needed. Thanks for the feedback!

**Review by diondiondion — DISMISSED** [review]

**Comment by Gargron** [comment]
Looks like you need to run `yarn i18n:extract`.

**Comment by crafkaz** [comment]
@Gargron @diondiondion 
The delete success alert was accidentally lost while reverting the changes. I've restored it so the success message is properly displayed across all deletion contexts.

File: app/javascript/mastodon/containers/status_container.jsx [hunk 7]
```diff
@@ -1,7 +1,8 @@
-import { injectIntl } from 'react-intl';
+import { injectIntl, defineMessages } from 'react-intl';
 
 import { connect } from 'react-redux';
 
+
```
Comment (diondiondion) [inline app/javascript/mastodon/containers/status_container.jsx]: Unused import and superfluous added line

**Review by diondiondion — CHANGES_REQUESTED** [review]
Looks like the extra import has also returned after the revert, otherwise this looks ok to me now.

File: app/javascript/mastodon/containers/status_container.jsx (hunk 7 above)
Comment (crafkaz) [reply app/javascript/mastodon/containers/status_container.jsx]: @diondiondion 
 I've removed the unused `defineMessages` import and the extra blank line. Thanks for catching that.

**Review by diondiondion — APPROVED** [review]
