### PR TITLE
Fix: Workaround to load MASTODON_VERSION_* in Docker.

### LINKED ISSUE #26590: version.rb's default value not applied in Docker
### Steps to reproduce the problem

1. Run v4.2.0-beta2 in Docker

### Expected behaviour

Shows version as v4.2.0-beta2

### Actual behaviour

Shows version as v4.2.0

### Detailed description

It seems Dockerfile's default MASTODON_VERSION_FLAGS="" override default value.

### Mastodon instance

_No response_

### Mastodon version

v4.2.0-beta2

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by sinoru**
Currently, Dockerfile sets MASTODON_VERSION_* to empty string as `ARG` and consumes as `ENV`.

Docker doesn't have conditional ENV set, so if these envs are empty string than make it using default value.

Fixes #26590

### CODE REVIEW

File: lib/mastodon/version.rb [hunk 1]
```diff
@@ -17,11 +17,11 @@ def patch
     end
 
     def flags
-      ENV.fetch('MASTODON_VERSION_FLAGS', '-beta2')
+      ENV.fetch('MASTODON_VERSION_FLAGS', nil).presence || '-beta2'
```
Comment (ClearlyClaire) [inline lib/mastodon/version.rb:20]: I feel like this is more idiomatic and easier to read, but not a big deal:
```suggestion
      ENV['MASTODON_VERSION_FLAGS'].presence || '-beta2'
```

File: lib/mastodon/version.rb [hunk 2]
```diff
@@ -17,11 +17,11 @@ def patch
...
     end
 
     def suffix
-      ENV.fetch('MASTODON_VERSION_SUFFIX', '')
+      ENV.fetch('MASTODON_VERSION_SUFFIX', nil).presence || ''
```
Comment (ClearlyClaire) [inline lib/mastodon/version.rb:24]: that change is unnecessary!

Comment (sinoru) [reply lib/mastodon/version.rb]: @ClearlyClaire I reverted it!

**Review by ClearlyClaire — APPROVED** [review]
