### PR TITLE
Fix uncaught NoMethodError error in `/api/v1/admin/canonical_email_blocks/test`

### LINKED ISSUE #21774: API: Uncaught 500 error in canonical_email_blocks/test
### Steps to reproduce the problem

`POST /api/v1/canonical_email_blocks/test`

### Expected behaviour

422 validation failed: email and/or canonical_email_hash are required

### Actual behaviour

500 HTML NoMethodError undefined method `downcase` for nil:NilClass

### Detailed description

_No response_

### Specifications

main

### PR DESCRIPTION
**Pull request by danielmbrasil**
Fix #21774.
Add some test coverage for `the /api/v1/admin/canonical_email_blocks/test` endpoint.

### CODE REVIEW

File: app/controllers/api/v1/admin/canonical_email_blocks_controller.rb [hunk 1]
```diff
@@ -58,6 +58,8 @@ def set_canonical_email_blocks
   end
 
   def set_canonical_email_blocks_from_test
+    raise(Mastodon::ValidationError, "Email can't be blank") if params[:email].blank?
+
     @canonical_email_blocks = CanonicalEmailBlock.matching_email(params[:email])
```
Comment (ClearlyClaire) [inline app/controllers/api/v1/admin/canonical_email_blocks_controller.rb:63]: I think it is more idiomatic to just do `params.require(:email)`, this will raise an `ActionController::ParameterMissing` exception if `email` is blank, which is caught in `Api::BaseController` to return a proper HTTP 400 reply (though the error is not translated)

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]

File: app/controllers/api/v1/admin/canonical_email_blocks_controller.rb [hunk 2]
```diff
@@ -58,6 +58,8 @@ def set_canonical_email_blocks
   end
 
   def set_canonical_email_blocks_from_test
+    params.require(:email)
+
     @canonical_email_blocks = CanonicalEmailBlock.matching_email(params[:email])
```
Comment (ClearlyClaire) [inline app/controllers/api/v1/admin/canonical_email_blocks_controller.rb:63]: I know we have some parts of our codebase using this pattern, but I would just do:
```suggestion
    @canonical_email_blocks = CanonicalEmailBlock.matching_email(params.require(:email))
```

**Review by ClearlyClaire — APPROVED** [review]
