### PR TITLE
`rel="me"` check should be case-insenstive

### LINKED ISSUE #28014: rel=me is case-sensitive on domains
### Steps to reproduce the problem

1. I have domain https://Pxtl.ca
2. I set rel="me" in a link from Pxtl.ca to mastodon.social/@Pxtl
3. I set https://Pxtl.ca in my profile
...
4. Try it again, but with https://pxtl.ca

### Expected behaviour

Highlight confirmed ownership of domain with both casings

### Actual behaviour

Highlight confirmed ownership only works with lower-case naming

image

image

### Detailed description

_No response_

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.1+pr-27634-22407c7

### Browser name and version

Firefox 119.0.1 (64-bit)

### Operating system

Windows 10

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by c960657**
Fixes #28014.

Probably not a big issue in practice, but according to the HTML spec, `rel=` values are case-insensitive. Nokogiri has no native support for case-insensitive comparison, so this must be done in Ruby.

Source:
https://www.w3.org/TR/2014/CR-html5-20140731/links.html#linkTypes

> Link types are always [ASCII case-insensitive](https://www.w3.org/TR/2014/CR-html5-20140731/infrastructure.html#ascii-case-insensitive), and must be compared as such.
>
> > Thus, `rel="next"` is the same as `rel="NEXT"`.

See also PR #31357 for other `rel=` handling.

### CODE REVIEW

File: app/services/verify_link_service.rb [hunk 1]
```diff
@@ -26,7 +26,7 @@ def perform_request!
   def link_back_present?
     return false if @body.blank?
 
-    links = Nokogiri::HTML5(@body).css("a[rel~='me'],link[rel~='me']")
+    links = Nokogiri::HTML5(@body).xpath('//a[@rel] | //link[@rel]').select { |el| el.kwattr_values('rel').any? { |v| v.downcase == 'me' } }
```
Comment (mjankowski) [inline app/services/verify_link_service.rb:29]: This is not the worst - but it'd be great if there was a purely xpath-query-native way to do this that nokogiri supported and we could get the full search done there instead of needing the ruby select.

**Review by mjankowski — COMMENTED** [review]
Outside the scope of this PR maybe - but a good refactor here would be to separate the link/markup search code from the model/field processing.

Either have a method on this class, or maybe a totally separate class which accepts an html string and searches for rel=me links and can operate without any DB records or http activities - and then expland the specs here with more markup scenarios.

File: app/services/verify_link_service.rb (hunk 1 above)
Comment (c960657) [reply app/services/verify_link_service.rb]: Done. I didn't realize that this kind of query occurs several places in the code, but it makes sense to make it a reusable component.

**Comment by c960657** [comment]
Thanks for the review.

I agree about your proposed refactor, but I'd rather do that in a separate PR in order to keep things separate.

**Comment by oneiros** [comment]
@flavorjones tagging you here since you kindly helped us out in the past.

Apparently we have a slight problem, because sometimes HTML allows for case-insensitive attribute values, so e.g. `rel="me"` is to be considered the same as `rel="ME"` etc. (there are more examples in #31357). Seems like there is no easy way to query for that with nokogiri. Or are we missing something?

If not, what do you think of the approach taken here?

I googled around and tried some things and found an xpath workaround using `translate`. Looks like something like this might work as well and might be faster?

```ruby
    document.xpath("//link[translate(@rel, 'ME', 'me')='me']").pick('href')
```

**Comment by flavorjones** [comment]
@oneiros Ah, you're right, libxml's XPath query engine only supports XPath 1.0 which does not have any string functions related to case-sensitivity.

The solution you suggested using `translate()` seems to be the most common workaround people have adopted, and it's likely faster than using a custom XPath handler written in Ruby (because calling from C back into Ruby is comparatively expensive). That said, you should benchmark it to make sure.

**Comment by c960657** [comment]
@flavorjones Thanks for your insights.

Note that for `rel` attributes, we need to do a case-insensitive for a `me` in a space-separated tokens, so a pure XPath 1 solution would also include e.g. `contains()` and `concat()`. XPath 2 has a special function for that, `tokenize()`. See e.g. [this question](https://stackoverflow.com/questions/25496151/xpath-to-match-space-separated-attribute-values) on StackOverflow.

I did some brief benchmarks and posted the results in https://github.com/mastodon/mastodon/pull/31357#issuecomment-2400494648. The overhad of invoking Ruby is negligible, as long as the XPath query is written so that the majority of filtering happens in pure XPath. E.g. when `[@rel]` is added _before_ the condition with the custom handler, the Ruby code is only invoked on tags with a `rel` attribute, i.e. usually less than ~25 on a regular HTML page.

**Comment by c960657** [comment]
I think the use of custom handlers make the code easier to read rather than trying to achieve the same using the limited features of XPath 1. Upgrading to XPath 2 when that becomes available will make the code even more clear.

File: lib/nokogiri_handler.rb [hunk 2]
```diff
@@ -0,0 +1,12 @@
+# frozen_string_literal: true
+
+class NokogiriHandler
+  class << self
+    # See "set of space-separated tokens" in the HTML5 spec.
+    WHITE_SPACE = /[ \x09\x0A\x0C\x0D]+/
+
+    def link_rel_include(token_list, token)
```
Comment (oneiros) [inline lib/nokogiri_handler.rb:8]: I think this could be useful in other places as well. And it is not specific to `rel`, is it?

If I am correct, how about renaming this to something more generic like `case_independent_include` or similar?

**Review by oneiros — CHANGES_REQUESTED** [review]

File: config/application.rb [hunk 3]
```diff
@@ -25,6 +25,7 @@
 require_relative '../lib/exceptions'
 require_relative '../lib/sanitize_ext/sanitize_config'
 require_relative '../lib/redis/namespace_extensions'
+require_relative '../lib/nokogiri_handler'
```
[the remark this answers is not in the document]
Comment (c960657) [reply config/application.rb:28]: I probably don't understand the criteria for using either `lib/` or `app/lib/`. The Nokogiri handler is generic, non-Rails-specific code, and is in that respect similar to e.g. the Redis namespace extension, so I assumed it should go into `lib/`.

What is the criteria exactly?

File: lib/nokogiri_handler.rb (hunk 2 above)
Comment (c960657) [reply lib/nokogiri_handler.rb:8]: In terms of the HTML spec, the attribute contains a case-insensitive list of space-separated DOM tokens. The specific definition of “space” in this context is represented by the regexp. There aren't a lot attributes defined in this way, so I chose a name reflecting the current use-case for the function.

DOM tokens are not always case-insensitive, so I initially created a whole bunch of generic functions for converting to lower-case, splitting into space-separated tokens etc., but then I decided that this would be way too generic for this specific use-case. Mastodon is not a library, so we can easily change the method name or split into separate functions if the need arises.

That was my reasoning, but I would be happy to rename etc. if you think that would be better.

File: config/application.rb (hunk 3 above)
[the remark this answers is not in the document]
Comment (oneiros) [reply config/application.rb:28]: The `lib/` and `app/lib/` split is mostly about autoloading / eager-loading of classes. Code in `lib/` is not autoloaded, code in `app/lib/` is. Autoloading not only means you can omit `require` but also that files get reloaded automatically in `development` when they have changed.

This works well for stand-alone classes like this one, but can lead to problems with code that patches existing classes, especially if those are out of the autoloader's scope. That is why you will find mostly patches for gems we use in `lib/`.

I vaguely remember the README of zeitwerk (the aforementioned autoloader, https://github.com/fxn/zeitwerk) explaining all this very well, but at first glance I cannot seem to find the relevant section. It might have been moved to something rails-specific, or I might misremember and it was in an issue or something :confused:

File: lib/nokogiri_handler.rb (hunk 2 above)
Comment (oneiros) [reply lib/nokogiri_handler.rb:8]: I think another use-case would be the `name` attribute of `<meta>` tags (see a couple of lines below your change in `LinkDetailsExtractor`). If I understand the spec correctly, the name is also case insensitive.

Comment (c960657) [reply lib/nokogiri_handler.rb:8]: It is indeed case-insensitive, but it is not defined as a space-separated list of tokens, so I don't think this function is a perfect fit (though it will probably do the job except in a few edge cases). In #31357 (overlapping with this PR) I have proposed a `casecmp` handler function.

File: config/application.rb (hunk 3 above)
[the remark this answers is not in the document]
Comment (c960657) [reply config/application.rb]: Got it :-) I have moved the file to `app/lib/`.

**Review by oneiros — APPROVED** [review]

File: lib/nokogiri_handler.rb (hunk 2 above)
Comment (oneiros) [reply lib/nokogiri_handler.rb]: Let us agree than once again that naming is hard :slightly_smiling_face: 

I still believe that this method could have utility elsewhere, but you are of course correct: Without a concrete example this point is kind of moot.

So let us leave it as is. Thanks for your patience.
