### PR TITLE
Fix status processing failing halfway when a remote post has a malformed `replies` attribute

### LINKED ISSUE #31230: Notifications not generated for mention received from NodeBB
### Steps to reproduce the problem

1. [NodeBB] Create a new post and tag a user on a mastodon instance (in this case, it was @julian@bb.devnull.land to @devnull@crag.social)
2. [Mastodon] Navigate to the sender's profile (https://crag.social/@julian@bb.devnull.land)
3. [Mastodon] Note that the post has been correctly received, and contains a mention, but that your notification inbox remains empty

### Expected behaviour

I should have been notified due to the mention

### Actual behaviour

I was not notified

### Detailed description

Additional details here: https://community.nodebb.org/topic/18210/mentions-and-notifications-over-the-fediverse

Here is the full Note object containing two mentions, when queried via S2S API:

```
{
	"@context":"https://www.w3.org/ns/activitystreams",
	"id":"https://bb.devnull.land/post/72",
	"type":"Note",
	"to":[
		"https://www.w3.org/ns/activitystreams#Public",
		"https://bb.devnull.land/uid/1"
	],
	"cc":[
		"https://bb.devnull.land/uid/1/followers",
		"https://crag.social/users/devnull",
		"https://activitypub.academy/users/babeta_zondaist"
	],
	"inReplyTo":"https://bb.devnull.land/post/71",
	"published":"2024-07-30T02:49:42.616Z",
	"url":"https://bb.devnull.land/post/72",
	"attributedTo":"https://bb.devnull.land/uid/1",
	"context":"https://bb.devnull.land/topic/38",
	"audience":"https://bb.devnull.land/category/-1",
	"sensitive":false,
	"summary":null,
	"name":"Re: Testing a notification",
	"content":"<p>no context or audience <a href=\"https://crag.social/@devnull\">@devnull@crag.social</a> <a href=\"https://activitypub.academy/@babeta_zondaist\">@babeta_zondaist@activitypub.academy</a></p> ",
	"source":{
		"content":"no context or audience @devnull@crag.social @babeta_zondaist@activitypub.academy",
		"mediaType":"text/markdown"
	},
	"tag":[
		{
			"type":"Mention",
			"href":"https://crag.social/users/devnull",
			"name":"@devnull@crag.social"
		},
		{
			"type":"Mention",
			"href":"https://activitypub.academy/users/babeta_zondaist",
			"name":"@babeta_zondaist@activitypub.academy"
		}
	],
	"attachment":[
	],
	"replies":[
	]
}
```

### Mastodon instance

crag.social, mastodon.social

### Mastodon version

v4.2.10

### Technical details

`crag.social` is hosted via masto.host, but @trwnh, who originally notified me of this issue, has an account on `mastodon.social`.

I was directed to post an issue here by @renchap

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #31230

### CODE REVIEW

File: app/lib/activitypub/activity/create.rb [hunk 1]
```diff
@@ -336,13 +336,15 @@ def resolve_thread(status)
...
     collection = @object['replies']
-    return if collection.nil?
+    return if collection.blank?
 
     replies = ActivityPub::FetchRepliesService.new.call(status, collection, allow_synchronous_requests: false, request_id: @options[:request_id])
     return unless replies.nil?
 
     uri = value_or_id(collection)
     ActivityPub::FetchRepliesWorker.perform_async(status.id, uri, { 'request_id' => @options[:request_id] }) unless uri.nil?
+  rescue e
```
Comment (oneiros) [inline app/lib/activitypub/activity/create.rb:346]: It think this should be `rescue => e`, should it not? And do you really want to rescue all (standard)errors here? (It might make sense, and I might propose this in another context as well, just want to make sure.)

Comment (ClearlyClaire) [reply app/lib/activitypub/activity/create.rb]: Oops, good catch. Yes, catching all standard errors was the intent, in this pretty part that is pretty much non-essential and highly reliant on remote data. We could avoid that, but I'm not confident we won't hit other malformed activities that would trigger other such bugs.

**Review by oneiros — APPROVED** [review]
