### PR TITLE
Fix tag rendering error in hashtag column settings

### LINKED ISSUE #17089: Hashtag column setting is malformed on CJK
### Steps to reproduce the problem

1. Add hashtag column
2. Add some additional hashtags for the column
3. Refresh webpage
...
image
image

### Expected behaviour

Show correct value on column setting

### Actual behaviour

Column setting has broken hashtags, But timeline itself is working correctly

### Specifications

Mastodon v3.4.4+glitch
Vanilla flavour wide web interface

### PR DESCRIPTION
**Pull request by rgroothuijsen**
When additional tags are added to a hashtag column, the tags initially appear correct but turn into empty blocks once the page is refreshed. This is caused by an attempt to convert the configuration's internal representation (i.e. a stack object) to JSON, which does not produce the expected label values. To fix this, the stack is first flattened to a regular array, which is then converted to JSON.

Fixes #17089

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
Ok, trying to understand what's happening there, it seems `toJSON` does not deeply convert to equivalent JS for some reason, unlike what Immutable's documentation says. Instead, `toJS` does the job correctly.

I am not sure why `toJSON` does not work as intended here.

File: app/javascript/mastodon/features/hashtag_timeline/components/column_settings.js [hunk 1]
```diff
@@ -33,8 +33,8 @@ class ColumnSettings extends React.PureComponent {
   tags (mode) {
     let tags = this.props.settings.getIn(['tags', mode]) || [];
 
-    if (tags.toJSON) {
-      return tags.toJSON();
+    if (tags.toArray) {
+      return tags.toArray().map(tag => tag.toJSON());
```
Comment (ClearlyClaire) [inline app/javascript/mastodon/features/hashtag_timeline/components/column_settings.js:37]: Can you use `toJS` instead? I believe this should be the proper fix.

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]

**Review by ClearlyClaire — APPROVED** [review]
