### PR TITLE
Translate CW, poll options and media descriptions

### LINKED ISSUE #21247: Translate button ignores poll options
### Steps to reproduce the problem

1. Create a post with some poll options
2. Click "Translate" to translate it into another language

### Expected behaviour

Both the text and poll options should be translated

### Actual behaviour

Only the post text is translated, while poll options remain in their original language

### Detailed description

Translating posts that contain polls doesn't seem to translate the latter.

Before:
Screenshot 2022-11-20 190742

After:
Screenshot 2022-11-20 190856

As you can see German options remained untranslated

### Specifications

Mastodon 4.0.2

### PR DESCRIPTION
**Pull request by c960657**
Translate CW text, poll options and media descriptions. Fixes #21247, #22249, #22398, #23676, #24012.

The translation services are modified to accept an array of strings to translate. Both DeepL and LibreTranslate support this.

The translate endpoint returns JSON in a structure similar to the status endpoint (it is a fake example for the purpose of illustration – in practice a poll has no media attachment):
```
{
  "detected_source_language": "de",
  "language": "en",
  "provider": "DeepL.com",
  "spoiler_text": "Spoiler :warning:",
  "content": "<p>Hello :highfive:</p>",
  "poll": {
    "id": "123",
    "options":[
      {
        "title": "Option 1"
      },
      {
        "title": "Option 2"
      }
    ]
  },
  "media_attachments": [
    {
      "id": "110043751121375668",
      "description": "Media description"
    }
  ]
}
```

The result is merged into the Redux state, with both raw and emojified variants (e.g. `spoiler_text` and `spoilerHtml`), just like the original status fields.

Before passing the text to the translation service, custom emojis are rendered to `` elements to prevent the shortcode from being translated. An additional `data-shortcode` attribute is added, and after translation this is used to convert the image back to the shortcode, so I can be emojified client-side. Both translation services leave this attribute intact.

For statuses with a CW the translate button is now visible even when the content is not expanded. This allows the user to translate the CW before pressing _Show more_.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
Thank you for your contribution! This was one of the next things I was planning to tackle :sweat_smile:

I'll try to review this shortly.

File: app/services/translate_status_service.rb [hunk 1]
```diff
@@ -32,6 +40,67 @@ def languages
   end
 
   def content_hash
-    Digest::SHA256.base64digest(@content)
+    Digest::SHA256.base64digest(@source_texts.transform_keys { |key| key.respond_to?(:id) ? "#{key.class}-#{key.id}" : key }.to_json)
```
Comment (ClearlyClaire) [inline app/services/translate_status_service.rb:43]: That doesn't sound right. For `content` and `spoiler_text`, the key would just be that. Poll options can be edited, and so can media attachment descriptions.

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]

File: app/services/translate_status_service.rb (hunk 1 above)
Comment (c960657) [reply app/services/translate_status_service.rb:43]: It is the only keys that are transformed. The result is e.g. this:

```json
{
  "content": "<p>This is content</p>",
  "Poll::Option-0": "Option 1",
  "Poll::Option-1": "Option 2",
}
```

File: app/javascript/mastodon/components/status.jsx [hunk 2]
```diff
@@ -410,14 +420,15 @@ class Status extends ImmutablePureComponent {
         );
       } else if (status.getIn(['media_attachments', 0, 'type']) === 'audio') {
         const attachment = status.getIn(['media_attachments', 0]);
+        const description = translation ? attachment.getIn(['translation', 'description']) : attachment.get('description');
```
Comment (ClearlyClaire) [inline app/javascript/mastodon/components/status.jsx:423]: Same about using `translation` as a boolean.

File: app/javascript/mastodon/components/status.jsx [hunk 3]
```diff
@@ -437,6 +448,7 @@ class Status extends ImmutablePureComponent {
         );
       } else if (status.getIn(['media_attachments', 0, 'type']) === 'video') {
         const attachment = status.getIn(['media_attachments', 0]);
+        const description = translation ? attachment.getIn(['translation', 'description']) : attachment.get('description');
```
Comment (ClearlyClaire) [inline app/javascript/mastodon/components/status.jsx:451]: Same about using `translation` as a boolean.

File: app/javascript/mastodon/features/account_gallery/components/media_item.jsx
Comment (ClearlyClaire) [inline app/javascript/mastodon/features/account_gallery/components/media_item.jsx:1]: I am not sure how useful it is to change this file at all, since there is no control in this view to toggle between original content and its translation.

File: app/javascript/mastodon/features/status/components/detailed_status.jsx [hunk 4]
```diff
@@ -129,17 +129,21 @@ class DetailedStatus extends ImmutablePureComponent {
...
 
+    const translation = status.get('translation');
+    const language = translation ? translation.get('language') : status.get('language');
+
     if (pictureInPicture.get('inUse')) {
       media = <PictureInPicturePlaceholder />;
     } else if (status.get('media_attachments').size > 0) {
       if (status.getIn(['media_attachments', 0, 'type']) === 'audio') {
         const attachment = status.getIn(['media_attachments', 0]);
+        const description = translation ? attachment.getIn(['translation', 'description']) : attachment.get('description');
```
Comment (ClearlyClaire) [inline app/javascript/mastodon/features/status/components/detailed_status.jsx:140]: Same about using `translation` as a boolean.

File: app/javascript/mastodon/features/ui/components/media_modal.jsx [hunk 5]
```diff
@@ -135,17 +136,21 @@ class MediaModal extends ImmutablePureComponent {
...
     const leftNav  = media.size > 1 && <button tabIndex='0' className='media-modal__nav media-modal__nav--left' onClick={this.handlePrevClick} aria-label={intl.formatMessage(messages.previous)}><Icon id='chevron-left' fixedWidth /></button>;
     const rightNav = media.size > 1 && <button tabIndex='0' className='media-modal__nav  media-modal__nav--right' onClick={this.handleNextClick} aria-label={intl.formatMessage(messages.next)}><Icon id='chevron-right' fixedWidth /></button>;
 
+    const translation = status.get('translation');
+    const languague = translation ? translation.get('language') : status.get('language');
+
     const content = media.map((image) => {
       const width  = image.getIn(['meta', 'original', 'width']) || null;
       const height = image.getIn(['meta', 'original', 'height']) || null;
+      const description = translation ? image.getIn(['translation', 'description']) : image.get('description');
```
Comment (ClearlyClaire) [inline app/javascript/mastodon/features/ui/components/media_modal.jsx:153]: Same about `translation` being used as a boolean.

File: app/javascript/mastodon/features/account_gallery/components/media_item.jsx
Comment (c960657) [reply app/javascript/mastodon/features/account_gallery/components/media_item.jsx:1]: Even though the translation for each status is global, it does seem weird to show translated texts if there is no toggle. I have reverted changes to this file.

File: app/javascript/mastodon/components/media_attachments.jsx [hunk 6]
```diff
@@ -49,23 +49,26 @@ export default class MediaAttachments extends ImmutablePureComponent {
...
+    const translation = status.get('translation');
+    const language = translation ? translation.get('language') : (status.get('language') || this.props.lang);
 
     if (mediaAttachments.size === 0) {
       return null;
     }
 
     if (mediaAttachments.getIn([0, 'type']) === 'audio') {
       const audio = mediaAttachments.get(0);
+      const description = translation ? audio.getIn(['translation', 'description']) : audio.get('description');
```
[the remark this answers is not in the document]
Comment (c960657) [reply app/javascript/mastodon/components/media_attachments.jsx]: I agree, that is better. I have fixed all occurrences.

**Review by ClearlyClaire — APPROVED** [review]

**Comment by ClearlyClaire** [comment]
@Gargron may want to have a quick look, especially at the API changes, but this looks good to me!

**Comment by c960657** [comment]
Documentation of the new API attributes: https://github.com/mastodon/documentation/pull/1203

**Comment by c960657** [comment]
> @Gargron may want to have a quick look, especially at the API changes, but this looks good to me!

@Gargron How do you like this? :-)

File: app/serializers/rest/translation_serializer.rb [hunk 7]
```diff
@@ -1,9 +0,0 @@
-# frozen_string_literal: true
-
-class REST::TranslationSerializer < ActiveModel::Serializer
```
Comment (Gargron) [inline app/serializers/rest/translation_serializer.rb:3]: I see no reason rename this, you can just add everything to this one.

File: app/controllers/api/v1/statuses/translations_controller.rb [hunk 8]
```diff
@@ -11,7 +11,7 @@ class Api::V1::Statuses::TranslationsController < Api::BaseController
   rescue_from TranslationService::UnexpectedResponseError, TranslationService::QuotaExceededError, TranslationService::TooManyRequestsError, with: :service_unavailable
 
   def create
-    render json: @translation, serializer: REST::TranslationSerializer
+    render json: @status_translation, serializer: REST::StatusTranslationSerializer
```
Comment (Gargron) [inline app/controllers/api/v1/statuses/translations_controller.rb:14]: I see no need for renaming these.

File: app/services/translate_status_service.rb [hunk 9]
```diff
@@ -32,6 +40,69 @@ def languages
...
+          description: translation.text
+        )
+      end
+    end
+
+    status_translation
+  end
+
+  def prerender_custom_emojis(text)
+    EmojiFormatter.new(html_escape(text), @status.emojis, { data_shortcode: true }).to_s
```
Comment (Gargron) [inline app/services/translate_status_service.rb:97]: We don't pre-render custom emoji as image tags in the API, so this is a big change. Image tags are not expected in the returned HTML. I would just wrap shortcodes in `<span class="notranslate">`

**Review by Gargron — CHANGES_REQUESTED** [review]

File: app/services/translate_status_service.rb (hunk 9 above)
Comment (c960657) [reply app/services/translate_status_service.rb:97]: Good point.

I have verified that `<span translate="no">:tag:</span>` works with both DeepL and LibreTranslate (the standardized [`translate` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/translate) is probably more reliable than `class`). So I agree that that is a simpler+better approach. I'll look into that.

File: app/services/translate_status_service.rb [hunk 10]
```diff
@@ -32,6 +40,69 @@ def languages
...
+          description: translation.text
+        )
+      end
+    end
+
+    status_translation
+  end
+
+  def prerender_custom_emojis(text)
+    EmojiFormatter.new(html_escape(text), @status.emojis, { raw_shortcode: true }).to_s
```
Comment (ClearlyClaire) [inline app/services/translate_status_service.rb:97]: Wait, I'm confused by the `html_escape` here. Sounds like the wrong place, as a formatted post's text is supposed to be HTML.

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]
Sorry this is involving so much back-and-forth.

I've done another review pass and I think it's shaping up. There are a few issues I reported with inline comments. If the client-side one are too much to deal with right now, it may make sense to split the PR between backend and front-end changes, so that the backend changes can get merged earlier and we continue to go forward.

File: app/javascript/mastodon/features/ui/components/media_modal.jsx [hunk 11]
```diff
@@ -22,7 +22,7 @@ const messages = defineMessages({
 });
 
 const mapStateToProps = (state, { statusId }) => ({
-  language: state.getIn(['statuses', statusId, 'language']),
+  status: state.getIn(['statuses', statusId]),
```
[the remark this answers is not in the document]
Comment (c960657) [reply app/javascript/mastodon/features/ui/components/media_modal.jsx:25]: I'll wait for #24806/#24816 to be merged before changing this.

File: app/services/translate_status_service.rb (hunk 10 above)
Comment (c960657) [reply app/services/translate_status_service.rb]: You are right. Good catch. I added some tests for this.

**Review by ClearlyClaire — APPROVED** [review]

**Review by Gargron — APPROVED** [review]
