### PR TITLE
Streaming: Fix BIND IPv6 handling

### LINKED ISSUE #31395: IPv6 only
### Steps to reproduce the problem

The **IPv6 only** installation of Mastodon (Docker) seems to have several problems.

### Expected behaviour

run a single stack IPv6 server

### Actual behaviour

have to run a dual stack server or an IPv4 server

### Detailed description

It would be nice to test all new versions of Mastodon on an **IPv6 only** environment.

### Mastodon instance

_No response_

### Mastodon version

v4.x

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by ThisIsMissEm**
Fixes #31395

Mastodon Web [uses the URI syntax](https://github.com/mastodon/mastodon/blob/1d557305d2fbd53a8a0e66af4e46ccc84d597ce8/config/puma.rb#L12) for `BIND` (versus rails' `BINDING` environment variable which uses the correct syntax). As Streaming needs to accept the `BIND` value but convert it to something Node.js understands, we need to strip the square brackets if present.

Newer versions of Node.js will actually through if BIND is malformed: https://github.com/nodejs/node/pull/54470

### CODE REVIEW

File: streaming/index.js [hunk 1]
```diff
@@ -1351,15 +1351,23 @@ const startServer = async () => {
  * @param {function(string): void} [onSuccess]
  */
 const attachServerWithConfig = (server, onSuccess) => {
-  if (process.env.SOCKET || process.env.PORT && isNaN(+process.env.PORT)) {
-    server.listen(process.env.SOCKET || process.env.PORT, () => {
+  if (process.env.SOCKET) {
+    server.listen(process.env.SOCKET, () => {
```
Comment (ThisIsMissEm) [inline streaming/index.js:1355]: For some reason we supported either SOCKET or PORT as a non-port here for unix sockets, whilst puma did not. This aligns the two.

**Review by ClearlyClaire — APPROVED** [review]

**Comment by jakecastelli** [comment]
Hi folks, just want to give a quick mention that the PR in nodejs (54470) unfortunately has been reverted due to more issues introduced than it is fixing.

**Comment by ThisIsMissEm** [comment]
> Hi folks, just want to give a quick mention that the PR in nodejs (54470) unfortunately has been reverted due to more issues introduced than it is fixing.

I think I saw that, for now the fix we do here will work well enough.
