### PR TITLE
fix: More "Followers you know" polish & bug fixes

### LINKED ISSUE #34687: Followers you know: add “you know” after “others”
### Pitch

Following #34652:

Add the word “you know” after “and XXX others”.

### Motivation

Right now it can be read:
> 452 followers
> Followed by her, him, them, and 3 others

And that amounts to 6, not 452.

### PR DESCRIPTION
**Pull request by diondiondion**
Fixes #34687

Changes proposed in this PR:
- Fixes emoji rendering in the followers you know widget
- Fixes the number of avatars not being limited to 3 anymore
- Adds the word "you know" when there are more than 2 familiar followers
- Make link styles more consistent (e.g. with the Notifications page)
- Moves the widget up on the account page, underneath the user name and badges

image

### CODE REVIEW

File: app/javascript/mastodon/features/account_timeline/components/familiar_followers.tsx [hunk 1]
```diff
@@ -13,11 +13,13 @@ import { useAppDispatch, useAppSelector } from '@/mastodon/store';
 
 const AccountLink: React.FC<{ account?: Account }> = ({ account }) => {
   // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing
```
Comment (Gargron) [inline app/javascript/mastodon/features/account_timeline/components/familiar_followers.tsx:15]: Why disable the lint instead of using `??`?

**Review by Gargron — DISMISSED** [review]

File: app/javascript/mastodon/features/account_timeline/components/familiar_followers.tsx (hunk 1 above)
Comment (diondiondion) [reply app/javascript/mastodon/features/account_timeline/components/familiar_followers.tsx:15]: `account?.display_name` could be an empty string, so it needed the fallback to not always resolve to the left-hand side with nullish coalescing.

But I just realised that `display_name_html` is auto-populated with `.acct` if no display name is defined, so I can actually remove the entire line now and use it directly 🎉

**Review by Gargron — APPROVED** [review]
