### PR TITLE
Deduplicate accounts and make unique username/domain index case-insensitive

### LINKED ISSUE #6667: Issues after changing WEB_DOMAIN to be the same as LOCAL_DOMAIN
So I started out on a setup with different `LOCAL_DOMAIN` and `WEB_DOMAIN` in order to run mastodon on a subdomain while using top-level user ids.

I decided to try changing my setup by commenting out `WEB_DOMAIN` and effectively moving mastodon to top-level. However, after the change, my instance seems to have trouble communicating with other mastodon instances (GNU social instances seem to be just fine with the change).

Here are some of the errors I see in the Sidekiq panel:

**First**, this is the error I got when trying to follow `@a@functional.cafe` from `@b@nda.li`:

- Job: `ActivityPub::DeliveryWorker`
- Arguments:
```
"{\"@context\":[\"https://www.w3.org/ns/activitystreams\",\"https://w3id.org/security/v1\",{\"manuallyApprovesFollowers\":\"as:manuallyApprovesFollowers\",\"sensitive\":\"as:sensitive\",\"movedTo\":\"as:movedTo\",\"Hashtag\":\"as:Hashtag\",\"ostatus\":\"http://ostatus.org#\",\"atomUri\":\"ostatus:atomUri\",\"inReplyToAtomUri\":\"ostatus:inReplyToAtomUri\",\"conversation\":\"ostatus:conversation\",\"toot\":\"http://joinmastodon.org/ns#\",\"Emoji\":\"toot:Emoji\",\"focalPoint\":{\"@container\":\"@list\",\"@id\":\"toot:focalPoint\"},\"featured\":\"toot:featured\"}],\"id\":\"https://nda.li/users/b#follows/32\",\"type\":\"Follow\",\"actor\":\"https://nda.li/users/b\",\"object\":\"https://functional.cafe/users/a\",\"signature\":{\"type\":\"RsaSignature2017\",\"creator\":\"https://nda.li/users/b#main-key\",\"created\":\"2018-03-07T02:40:14Z\",\"signatureValue\":\"HTL/KVz69jV/4hu2nMYn5Uq8DDZqFMLDI4FP7rk+IApFsBhJFo9bNKvtIPOGGiY8eobvM97Y0jwiTC/oUpY2/C/vv1jOo6TPZbt/CuHkkkqKYUi8PFy01APBNEuXSum3uQUYWT6DJTtEv4kMbZSzrXySQxrAs7Htu0Fa/t+3z6IWviddLtQ1bb5PaRKX6D4TgGNdACsdGrbmXGYgwrCXI5iT2JcQdMM987jqrY7kBfo9EAfNcFbaKT4sFM420JMP35VNen45/rPi1C5e81oHulaKTximk2on2G82Jpe9LYi5Yla+iJaTyp7BkYSzuNrXLgKeyXrwYVZZQFMsdiNv+Q==\"}}", 1, "https://functional.cafe/users/a/inbox"
```
- Error: `Mastodon::UnexpectedResponseError: Delivery failed for https://functional.cafe/users/a/inbox: https://functional.cafe/users/a/inbox returned code 422`

**Secondly**, here's another error when trying to unfollow:

- Job: `ActivityPub::DeliveryWorker`
- Arguments:
```
"{\"@context\":[\"https://www.w3.org/ns/activitystreams\",\"https://w3id.org/security/v1\",{\"manuallyApprovesFollowers\":\"as:manuallyApprovesFollowers\",\"sensitive\":\"as:sensitive\",\"movedTo\":\"as:movedTo\",\"Hashtag\":\"as:Hashtag\",\"ostatus\":\"http://ostatus.org#\",\"atomUri\":\"ostatus:atomUri\",\"inReplyToAtomUri\":\"ostatus:inReplyToAtomUri\",\"conversation\":\"ostatus:conversation\",\"toot\":\"http://joinmastodon.org/ns#\",\"Emoji\":\"toot:Emoji\",\"focalPoint\":{\"@container\":\"@list\",\"@id\":\"toot:focalPoint\"},\"featured\":\"toot:featured\"}],\"id\":\"https://nda.li/users/b#follows/32/undo\",\"type\":\"Undo\",\"actor\":\"https://nda.li/users/b\",\"object\":{\"id\":\"https://nda.li/users/b#follows/32\",\"type\":\"Follow\",\"actor\":\"https://nda.li/users/b\",\"object\":\"https://functional.cafe/users/a\"},\"signature\":{\"type\":\"RsaSignature2017\",\"creator\":\"https://nda.li/users/b#main-key\",\"created\":\"2018-03-07T02:40:25Z\",\"signatureValue\":\"EV3wYByh27XFOZvYvqPlCgt4efDlsu10lDRHBGisMisPtdS5D+nTdHYXxGwksSIIliY1paWxtPjhYs07aAWllqz1GJ5Xqm1eRHblzTubiGf2x618cUBxvx8P4wb32MThuNesMWBenLRFvYpFY2fKcveA1uALjRg6EKPJfMh3c7UixVy+mB5vRoCLhatW0lQdEGYx7tmzzN7HBZGc2vLmqtWxzf2utsGvgQLb9qVIUzNBpM9TCy59PWWMlAytfOJP8gYHJv6OU/Tr/jHq+XmzJfMdtuSv7awSRrsG2eOdo0Kp3QdZXdoMgjWDz/RiP3/olSc8d3CYEQJHphdHBPkrJQ==\"}}", 1, "https://functional.cafe/users/a/inbox"
```
- Error: `Mastodon::UnexpectedResponseError: Delivery failed for https://functional.cafe/users/a/inbox: https://functional.cafe/users/a/inbox returned code 422`

Of course; neither of the actions were successfully carried out.

Any ideas or possible solutions?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

### LINKED ISSUE #6837: Usernames are case-sensitive on local database, but not on remote domain (even with the same id)
Earlier today, Krita made an account on mastodon.art, and I followed `@krita@mastodon.art` from `mastodon.social`. The account followed me back. But later in my home column, I see a boost from `@Krita@mastodon.art`, and attempting to load it in the webapp seems to be treating it as a different account that is neither following me nor am I following it. However, loading the profile URLs `mastodon.art/@krita` or `mastodon.art/@Krita` both resolve to the same account. 

krita in webapp: 
chrome_2018-03-19_14-38-25

Krita in webapp
chrome_2018-03-19_14-38-40

krita in profile
chrome_2018-03-19_14-37-49

Krita in profile
chrome_2018-03-19_14-37-55

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

### LINKED ISSUE #6937: Unique index on accounts username/domain is not case insensitive
For some reason (a mistake, oversight or confusion), there are two indices on the accounts table:

- lower(username), lower(domain): case-insensitive, *not* unique
- username, domain: case-*sensitive*, unique

Only the last one is unique! That's a waste of space, but it's also bad because it allows duplicate accounts to be created under race conditions or other edge cases (those that were discovered, were patched already, though)

We need to:

- Turn the case-insensitive index unique and remove the redundant one
- But before we can do that, we need to, in an automated manner, "fix" duplicate rows, by either merging, removing, or renaming the accounts

In the case of merging, that would require updating all associate records to a different account_id. In case of removing, need to decide which of the accounts to keep... This is further complicated by the bug (already fixed) that occurred in 2.3.2 and allowed, under some circumstances, multiple local accounts with the same username (different casing).

Very likely related issue: #3005

### PR DESCRIPTION
**Pull request by Gargron**
> **Previously on Mastodon**: Username/domain uniqueness constraint exists, but is case-*sensitive*. Case-insensitive index also exists, but is not unique. Duplicates caused primarily by admins changing casing of usernames in database, and that one time we had a missing validation in Ruby for one short release.

Fix #6937
Fix #6837
Fix #6667

1. Get all accounts with overlapping username/domain
2. For each account:
    1. Select most recently updated (used) one to be the reference account
    2. Compare others against it
        - If the public key is the same, it's definitely the same person, so they can be merged. Change attributions on owned associations to the reference account
        - Delete the other account
3. Re-create case-insensitive index with uniqueness constraint
4. Remove now useless case-sensitive unique index

> Damn, why do all those issues end in 7s. I just noticed.

### CODE REVIEW

**Comment by Gargron** [comment]
@ThibG @aschmitz Check this out. Is this alright?

**Comment by aschmitz** [comment]
I'll defer to @marrus-sh on whether or not this makes sense in APub, but the code looks like it does what you describe.

It's not clear to me if/how this would fix #6667, though: that appears to be a difference in domain, not capitalization. (Unless I've missed something?)

**Comment by aschmitz** [comment]
To repost my comment from Mastodon:

Technically it's a bit racey: If something comes in from the other account while you're in the process of merging, it could get missed. This is unlikely, but possible. I'm not sure if you can fix that, though: maybe `other_account.delete` before the `merge_accounts!` if statement? Any of the necessary cleanup from `.destroy` is probably handled in your reassigning bits.

**Comment by Gargron** [comment]
>It's not clear to me if/how this would fix #6667, though: that appears to be a difference in domain, not capitalization. (Unless I've missed something?)

The index on `uri` is not unique, so that wasn't the problem (unlike my first comment in the issue suggests, I was wrong). When you change WEB_DOMAIN/LOCAL_DOMAIN setup, the `domain` doesn't actually change (since the point of WEB_DOMAIN is having a top-level domain while running from a subdomain), it's the URI that changes, because the URI has to be resolveable, it's based on WEB_DOMAIN. So the URI changed but domain remained the same, but because the code tried finding/creating based on URI first and domain second, it tried to make a duplicate and failed. This was fixed in #6842, actually, I dunno why I didn't close that issue then.

**Comment by Gargron** [comment]
>Technically it's a bit racey: If something comes in from the other account while you're in the process of merging, it could get missed. This is unlikely, but possible. I'm not sure if you can fix that, though: maybe other_account.delete before the merge_accounts! if statement? Any of the necessary cleanup from .destroy is probably handled in your reassigning bits.

Reference account is the most recently updated one, it's highly unlikely that both accounts could be active at the same time, therefore any new content would arrive to the reference account, not the other accounts.

Foreign keys should take care of any orphaned associations.

Mostly duplicates should be rare, so any resulting oddities would likely not be noticed.

One thing that does give me pause is the treatment of local duplicates. Those were possible due to a short-lived bug in a release. My migration will just delete them. I don't see a lot of choice here, since automatically changing the usernames would both be difficult to implement and it would mess with federation. There is also a previously added rake task for finding such local duplicates to manually deal with, if one is inclined to do so.

**Comment by aschmitz** [comment]
In theory could merging the local accounts work? Other Mastodon clients will eventually merge the two anyway, though I'm not sure about other servers. (I'm a little iffy on merging local accounts given that they *could* be completely different users, though.)

**Comment by Gargron** [comment]
@aschmitz Two local accounts are *always definitely* different people, with different user record, password, e-mail etc.

**Comment by Gargron** [comment]
>Other Mastodon clients will eventually merge the two anyway

If you mean other servers, since we perform the public_key comparison, if they're really two different accounts, they will not be merged either.

**Comment by aschmitz** [comment]
Ah, okay, fair enough. Is there a convenient way to simply disable/rename one? The admin would have to handle notifying the users somehow (or we could fire off an email), but it might be better than deleting a whole user's information.

**Comment by Gargron** [comment]
No, there's not - if it remains in the database, it will prevent the fixed index from being created.

**Comment by aschmitz** [comment]
Not even renaming to, say, `username_1` etc.? (This may be bad because users can't rename themselves after the fact, but could potentially be preferable to actually deleting all of their data.)

**Comment by Gargron** [comment]
Automatically changing the usernames would both be difficult to implement (now have to loop over to make sure username1 doesn't exist, username2, username3, etc) and it would mess with federation.

Since duplicate accounts are a mistake, and a rare one at that, it's okay and cleaner to just delete them.

**Comment by ThibG** [comment]
I'm still not sold on having case-insensitive handling of usernames, it's yet another deviation from the spec.
Otherwise, this seems to do what you described.
If you go that route, you might also want to change `app/models/account.rb:72`.

**Comment by Gargron** [comment]
>I'm still not sold on having case-insensitive handling of usernames, it's yet another deviation from the spec.

**_I am the spec_**

<details>
  <summary>Click to expand</summary>
  That's a Star Wars reference, I am not the spec. However, the spec is unusable without webfinger anyway.
</details>

**Comment by nightpool** [comment]
@ThibG 

The fact that we require unique and immutable preferredUsernames at all is a deviation from the spec. (which only requires unique ids and doesn't talk about immutability at all). Given that, and the justifications we have for it ("textual @-mentions should map 1:1 with accounts"), i dont think case-sensitive verses case-insenstive is a meaningful change here.

File: db/migrate/20180528141303_fix_accounts_unique_index.rb [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+      if other_account.public_key == reference_account.public_key
+        # The accounts definitely point to the same resource, so
+        # it's safe to re-attribute content and relationships
+        merge_accounts!(reference_account, other_account)
+      elsif other_account.local?
+        # Since domain is in the GROUP BY clause, both accounts
+        # are always either going to be local or not local, so only
+        # one check is needed. Since we cannot support two users with
+        # the same username locally, one has to go. 😢
+        other_account.user.destroy
```
Comment (nightpool) [inline db/migrate/20180528141303_fix_accounts_unique_index.rb]: I think it's preferable to error out here and force admins to resolve this manually, to pick the account with the most statuses/followers/etc. would be very bad if this ended up destroying a legit account. (although unlikely given the raciness involved in getting this to happen in the first place)

File: db/migrate/20180528141303_fix_accounts_unique_index.rb [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+    raise ActiveRecord::IrreversibleMigration
+  end
+
+  private
+
+  def deduplicate_account!(account_ids)
+    accounts          = Account.where(id: account_ids).order(updated_at: :desc)
+    reference_account = accounts.shift
+
+    accounts.each do |other_account|
```
Comment (nightpool) [inline db/migrate/20180528141303_fix_accounts_unique_index.rb]: the each block here should be wrapped in a transaction I think?

**Review by nightpool — CHANGES_REQUESTED** [review]

File: db/migrate/20180528141303_fix_accounts_unique_index.rb (hunk 2 above)
Comment (Gargron) [reply db/migrate/20180528141303_fix_accounts_unique_index.rb]: Is that really necessary? Even if it fails halfway through, that's still work done that won't need to be repeated on a future run.

File: db/migrate/20180528141303_fix_accounts_unique_index.rb (hunk 1 above)
Comment (Gargron) [reply db/migrate/20180528141303_fix_accounts_unique_index.rb]: Is anything stopping me from using TTY prompts here to give dynamic options? Except that it feels wrong for migrations to require interactive input.

**Comment by trwnh** [comment]
>@Gargron:
>>Two local accounts are always definitely different people, with different user record, password, e-mail etc.
> 
>@ThibG:
>>I'm still not sold on having case-insensitive handling of usernames, it's yet another deviation from the spec.

One other thing to consider besides simple case-sensitivity: what if a hypothetical future ActivityPub implementation allows for changing usernames? In that situation, "case-insensitive" isn't enough either. Or how about another ActivityPub implementation that allows export/import of accounts to a completely different domain (and also may or may not allow for username changes)?

In both those cases, it's still the same Account, with the same public key, just with a different Webfinger pointer. Perhaps this is out-of-scope for this particular PR, but it's definitely a future extension to consider. This would also technically be the superset of the problem: when a pointer changes but the account is the same, for any reason.

ThibG has a point where two accounts are *different* and have the same name with different casing (e.g. claudia/Claudia @ mastodon.social, two different people). Over federation, a remote instance could follow both. On the local instance, any user can follow both. The case-insensitivity only matters when changing username on the same account (e.g. krita/Krita @ mastodon.art, same account).

I guess ultimately this PR is addressing one narrow case: it assumes overlaps ONLY occur on case-insensitive user/domain pairs. If we use public keys to deduplicate, then worst-case we would have to scan over all users the instance is aware of. Perhaps the more robust alternative would be to use public-key as an index in the database, so that duplicate public keys are detected immediately. Of course, that in turn assumes that public keys are unique for every single ActivityPub account...

File: db/migrate/20180528141303_fix_accounts_unique_index.rb (hunk 2 above)
Comment (nightpool) [reply db/migrate/20180528141303_fix_accounts_unique_index.rb]: I'm saying each iteration of the loop should be a new transaction, so we don't lose half the progress but an error doesn't leave an account in a half-deleted state.

**Comment by nightpool** [comment]
@Jarred-Sumner we can't change the type of the column at this point. Plus, we don't want the behavior citext gives here—if two accounts share the same name with different casing, we want to fail fast rather then running into nasty compatibility issues down the line when software that assumes they should be distinct ends up "sharing" the same account on our end.

File: db/migrate/20180528141303_fix_accounts_unique_index.rb (hunk 1 above)
Comment (nightpool) [reply db/migrate/20180528141303_fix_accounts_unique_index.rb]: lots of people do unmonitored deploys, heroku deploys, etc, that would break here

**Comment by nightpool** [comment]
Question—given what I said above, do ActivityPub processing queries/webfinger lookup queries **use** the new index? since the index is a function index on `lower(username), lower(domain)` we might not end up using it in any of our queries.

File: db/migrate/20180528141303_fix_accounts_unique_index.rb [hunk 3]
```diff
@@ -0,0 +1,84 @@
...
+    say 'It will *not* lock tables for any significant time, but it may run'
+    say 'for a very long time. We will pause for 10 seconds to allow you to'
+    say 'interrupt this migration if you are not ready.'
+    say ''
+    say 'This migration will irreversibly delete user accounts with duplicate'
+    say 'usernames. You may use the `rake mastodon:maintenance:find_duplicate_usernames`'
+    say 'task to manually deal with such accounts before running this migration.'
+
+    10.downto(1) do |i|
+      say "Continuing in #{i} second#{i == 1 ? '' : 's'}...", true
```
Comment (nightpool) [inline db/migrate/20180528141303_fix_accounts_unique_index.rb]: should be `:subitem` instead of true, so what the flag does is more obvious.

**Review by nightpool — APPROVED** [review]
i'd prefer if you change the boolean flag -> self-documenting symbol thing but it's not a huge deal

**Comment by trwnh** [comment]
>Nothing I do here will change the fact that changing usernames will break things in Mastodon. So let's not even bring it up.

Just wondering how this PR could be expanded upon in the future. If there's a better place that would be on-topic, I can post it there instead, but my question was moreso about the deduplication itself rather than a user/domain change. In a future where Webfinger is used only for lookup and addressing (not for database), and where accounts can be fully migrated, it would probably be worth considering deduplicating in more cases than just case-sensitivity. Still, this PR is an important first step towards solving the larger issue. Right now, it's database admins making manual edits, and we assume that they only change the case.

File: db/migrate/20180528141303_fix_accounts_unique_index.rb [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+    # Since it's the same remote resource, the remote resource likely
+    # already believes we are following/blocking, so it's safe to
+    # re-attribute the relationships too. However, during the presence
+    # of the index bug users could have *also* followed the reference
+    # account already, therefore mass update will not work and we need
+    # to check for (and skip past) uniqueness errors
+    [Follow, FollowRequest, Block, Mute].each do |klass|
+      klass.where(account_id: duplicate_account.id).find_each do |record|
+        record.update(account_id: main_account.id)
+      rescue ActiveRecord::RecordNotUnique
```
Comment (ykzts) [inline db/migrate/20180528141303_fix_accounts_unique_index.rb]: `do`-`rescue` is not support on Ruby 2.4
