### PR TITLE
fix: Fix glitchy status keyboard navigation

### LINKED ISSUE #27259: Page Up and Page Down miss bits of the timeline
### Steps to reproduce the problem

1. Position my timeline so that https://ohai.social/@conansysadmin@mstdn.social/111168608294311247 is partially visible at the bottom, with the line for 0070 at the bottom of the browser window.

2. Press page down key

Expected result: https://ohai.social/@conansysadmin@mstdn.social/111168608294311247 is partially visible at the top, with the line for 0080 at the top of the browser window just below the heading which bears a "Home" link and an options icon.

Actual result: https://ohai.social/@conansysadmin@mstdn.social/111168608294311247 is partially visible at the top, with the line for 00d0 at the top of the browser window just below the heading which bears a "Home" link and an options icon. The following rows did not display to me as they are presumably hidden under the heading div:

0080
0090
00a0
00b0
00c0

Attempted workaround: 

4. Right-click the heading and choose Inspect Element
5. Look up the DOM tree until I see 
`<div class="tabs-bar__wrapper">`
6. Click on that div element in the DOM tree
7. Press delete
8. Click X to close the inspector

Result: 00d0 is still at the top of the browser window. Further, I can't click on toots to display their thread. I have to reload the page.

### Expected behaviour

I don't lose any content when using page down or page up

### Actual behaviour

A horizontal sliver of the content never displays when using page down or page up

### Detailed description

I am trying to read my timeline solely with the keyboard. I expect Page Up and Page Down to let me read the full timeline without losing any content. However, every time I press those keys I lose a little bit of the timeline. I can only see the full timeline by using the scroll bar or scroll wheel. This is an accessibility violation. Additionally, because of #27242, I can't mitigate using arrow up or arrow down (not that I want to have to do that all the time).

### Mastodon instance

ohai.social

### Mastodon version

v4.2.0

### Browser name and version

Safari Version 17.0 (19616.1.27.211.1)

### Operating system

macOS 14.0

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by diondiondion**
Fixes #27259, #29084, #15302, #13200
Supersedes #27560

### Changes proposed in this PR:
- Fixes glitchy status keyboard navigation:
   - Takes load gaps and inline follow suggestions panels into account. It skips empty panels and focuses them when they have content. Navigating away from follow suggestions and load gaps via hotkey is not yet implemented
   - Properly scrolls posts into view if they would otherwise not fit into the current viewport.

### Screenshots

https://github.com/user-attachments/assets/fa3aff5b-619c-4a56-a08a-d1a6344b7904

### CODE REVIEW

File: app/javascript/mastodon/components/status_list.jsx [hunk 1]
```diff
@@ -53,35 +53,58 @@ export default class StatusList extends ImmutablePureComponent {
...
+    const element = loadMoreButton ?? elementContainer.querySelector('.focusable');
 
     if (element) {
-      if (align_top && container.scrollTop > element.offsetTop) {
-        element.scrollIntoView(true);
-      } else if (!align_top && container.scrollTop + container.clientHeight < element.offsetTop + element.offsetHeight) {
-        element.scrollIntoView(false);
+      const elementRect = element.getBoundingClientRect();
+
+      const columnHeaderHeight = 60;
```
Comment (ChaosExAnima) [inline app/javascript/mastodon/components/status_list.jsx]: this feels fragile- while the value is set in the CSS below, that doesn't account for things like custom themes. instead i'd suggest calculating the height using JS.

**Review by ChaosExAnima — COMMENTED** [review]
overall looks good, but one issue i spotted.

File: app/javascript/mastodon/components/status_list.jsx (hunk 1 above)
Comment (diondiondion) [reply app/javascript/mastodon/components/status_list.jsx]: I changed it so the value is now read from CSS so there's a single source of truth. Custom themes will have to set the custom property if needed.

**Review by ChaosExAnima — APPROVED** [review]
