### PR TITLE
Fix improperly checking for blocked domain on followed hashtags

### LINKED ISSUE #19469: Domain block from user is not affected on hashtag following
### Steps to reproduce the problem

1. Follow a hashtag
2. Block a domain (as a user)
3. Post using the hashtag from blocked domain
...

### Expected behaviour

Posts from blocked domain not appear on home timeline

### Actual behaviour

Posts from blocked domain appear on home timeline

### Detailed description

_No response_

### Specifications

Mastodon 3ad0a2ae3dcd36e4a9e0be5f72273f9c30df7548

### PR DESCRIPTION
**Pull request by Gargron**
Fix #19469

### CODE REVIEW

File: app/lib/feed_manager.rb [hunk 1]
```diff
@@ -426,7 +426,7 @@ def filter_from_list?(status, list)
   # @param [Hash] crutches
   # @return [Boolean]
   def filter_from_tags?(status, receiver_id, crutches)
-    receiver_id != status.account_id && (((crutches[:active_mentions][status.id] || []) + [status.account_id]).any? { |target_account_id| crutches[:blocking][target_account_id] || crutches[:muting][target_account_id] } || crutches[:blocked_by][status.account_id] || crutches[:domain_blocking][status.account.domain])
+    receiver_id == status.account_id || ((crutches[:active_mentions][status.id] || []) + [status.account_id]).any? { |target_account_id| crutches[:blocking][target_account_id] || crutches[:muting][target_account_id] } || crutches[:blocked_by][status.account_id] || crutches[:domain_blocking][status.account.domain]
```
Comment (ClearlyClaire) [inline app/lib/feed_manager.rb:429]: Why this change?

Comment (Gargron) [reply app/lib/feed_manager.rb:429]: Since it's writing to home feed, the author's own posts will land there anyway, no need to add them twice...

**Review by ClearlyClaire — APPROVED** [review]
