### PR TITLE
Fix crash when marking statuses as sensitive while some statuses are deleted

### LINKED ISSUE #21910: Unable to resolve moderator report if a post has been deleted
### Steps to reproduce the problem

1. Someone submits a report on a multiple posts
2. The original poster deleted one of the posts
3. Click "Mark Sensitive" in the moderator report

### Expected behaviour

The moderator report is resolved and the selected posts are marked sensitive

### Actual behaviour

422 Unprocessable Entity error

### Detailed description

Someone reported a few posts on my instance but when I went to mark them as sensitive the moderator report page gave me an HTTP 422 error. One of the posts that was reported had been deleted by the original user. Didn't matter what combination of posts I had selected, it always gave the 422 error. I reported all the undeleted posts again and was able to resolve the new moderator report.

### Specifications

Mastodon | 4.0.2
Ruby | 3.0.4p208
PostgreSQL | 14.6
Redis | 6.2.7

Chrome 108.0.5359.71

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #21910

Also fixes multiple statuses being marked as sensitive generating multiple strikes for the same report.

### CODE REVIEW

File: app/models/admin/status_batch_action.rb [hunk 1]
```diff
@@ -73,6 +73,7 @@ def handle_mark_as_sensitive!
     # Can't use a transaction here because UpdateStatusService queues
     # Sidekiq jobs
     statuses.includes(:media_attachments, :preview_cards).find_each do |status|
+      next if status.discarded?
```
Comment (Gargron) [inline app/models/admin/status_batch_action.rb:76]: No need to have two different `next` statements, I would just change the `unless` to `if` below.

**Review by Gargron — APPROVED** [review]

**Review by Gargron — APPROVED** [review]
