### PR TITLE
Fix #1426 - Trim long usernames in public follower/following lists

### LINKED ISSUE #1426: Trim long usernames (visually)
I character limit on the showed description on a user must be set. [See](https://naganu.com/users/david/following) the overflow:

screen shot 2017-04-10 at 08 45 38

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### LINKED ISSUE #2221: OpenSSL - SSLError : certificate verify failed
Hello,

Since the 18 April, around 19h30 (07:30 pm) my instance isn't federating. I tried to restart mastodon, apache, even the server, and nothing work.
At first, I thought it was a proxy error, because I had error in my apache errors file about proxy. Now it seems to work, there are no more errors, but it's still not federating.

On sidekiq, there are a lot of failed and "retries" jobs. It all says :
`OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed`

My `openssl version` is `OpenSSL 1.1.0f-dev  xx XXX xxxx`.

I renewed my certificates, but this doesn't solve the problem...

I have updated to v1.2 yesterday, and now I'm on v1.2.2.

I'm lost, what could I do to solve this ?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

### PR DESCRIPTION
**Pull request by Gargron**
Fix #2221 - Catch OpenSSL exceptions when loading remote avatars/headers/attachments
Don't strip "rel" attribute from `<a>` tags when sanitizing (microformats)

### CODE REVIEW

File: app/models/concerns/account_avatar.rb [hunk 1]
```diff
@@ -34,7 +34,7 @@ def avatar_remote_url=(url)
 
       self.avatar              = URI.parse(parsed_url.to_s)
       self[:avatar_remote_url] = url
-    rescue OpenURI::HTTPError => e
+    rescue OpenURI::HTTPError, OpenSSL::SSL::SSLError, Paperclip::Errors::NotIdentifiedByImageMagickError => e
```
Comment (mjankowski) [inline app/models/concerns/account_avatar.rb]: seems unrelated?

Comment (Gargron) [inline app/models/concerns/account_avatar.rb]: This PR fixes two issues.

Comment (mjankowski) [inline app/models/concerns/account_avatar.rb]: I'd put those into separate commits.

I'll approve this PR, can you can decide to split it up or not.

**Review by mjankowski — APPROVED** [review]
