### PR TITLE
fix: OIDC account creation fails for long display names

### LINKED ISSUE #34638: OIDC: Long display name prevents account creation
### Steps to reproduce the problem

1. Have a very long display name that exceeds  `DISPLAY_NAME_LENGTH_LIMIT = 30`.
2. Try to log into a Mastodon instance via OIDC/SSO for the first time.
3. Get a generic error message instead of a shiny new mastodon account.

### Expected behaviour

The display name derived from OIDC claims should be truncated to the maximum allowed length automatically, but still accepted. Users can fix their display name themselves later.

### Actual behaviour

Account creation fails and the user cannot log in.

### Detailed description

When an OIDC user logs in for the first time, an account is created automatically. The display name passed to `User.new` via `account_attributes.display_name` is derived from OIDC claims (either `full_name`, `name` or `first_name + ' ' + last_name`). If this display name is longer than `DISPLAY_NAME_LENGTH_LIMIT` (30 characters) then the associated `Account` instance cannot be saved and fails validation. The `ActiveRecord::RecordInvalid` exception is handled by returning a generic `devise.failure.omniauth_user_creation_failure` error message to the user. The actual root cause is not logged and it took me a while to find out what went wrong.

### Mastodon instance

_No response_

### Mastodon version

v4.3.8

### Technical details

- Ruby version: official docker images
- Node.js version: official docker images

### PR DESCRIPTION
**Pull request by defnull**
Truncate display name for new accounts created during OIDC login. 

fix: #34638

### CODE REVIEW

**Comment by defnull** [comment]
Not tested, I don't have a test deployment ready. Let's see how far we can get with just github and CI/CD :)

**Review by ThisIsMissEm — COMMENTED** [review]
I think this looks good to me? But we should try to have test coverage for this.

**Comment by ThisIsMissEm** [comment]
Take a look at: https://github.com/mastodon/mastodon/blob/741f166407a79b666475aae662339c127f182e24/spec/requests/omniauth_callbacks_spec.rb#L118 which seems to be the specs here

**Review by ClearlyClaire — DISMISSED** [review]
I agree this looks fine but could use some tests.

File: app/models/concerns/user/omniauthable.rb [hunk 1]
```diff
@@ -121,5 +121,10 @@ def ensure_valid_username(starting_username)
       temp_username = starting_username.gsub(/[^a-z0-9_]+/i, '')
       temp_username.truncate(30, omission: '')
     end
+
+    def display_name_from_auth(auth)
+      display_name = auth.info.full_name || auth.info.name || [auth.info.first_name, auth.info.last_name].join(' ')
+      display_name.truncate(Account.DISPLAY_NAME_LENGTH_LIMIT, omission: '')
```
Comment (ClearlyClaire) [inline app/models/concerns/user/omniauthable.rb:127]:
```suggestion
      display_name.truncate(Account::DISPLAY_NAME_LENGTH_LIMIT, omission: '')
```

**Comment by defnull** [comment]
I'm not a ruby-on-rails developer and need some free time to figure out how the test framework works. I'll try, it just may take a while. If you don't want to wait and just do it yourself, feel free. I don't care about attribution :)

**Review by ClearlyClaire — APPROVED** [review]
