### PR TITLE
Only check locally when deduplicating usernames

### LINKED ISSUE #13580: Accounts created through Omniauth are sometimes wrongly de-duplicated (_1 added)
### Expected behaviour

I login using Omniauth and a suggested username of `username`, no other user with that username exists on the instance, so I expect my username and account name to be `username`.

### Actual behaviour

Because a account with `username` exists on another instance, the deduplication logic kicks in and adds a `_1` to the account name.

### Steps to reproduce the problem

- Create an account on SSO with a username that exists on another instance (and is known to this instance)
- Login using Omniauth for the first time (triggers the account creations)

### Specifications

This is a backend issue affecting all versions until `master`.

The problematic bit seems to be: https://github.com/tootsuite/mastodon/blob/master/app/models/concerns/omniauthable.rb#L85

Because this does not test for local accounts specifically, it will detect duplicates that are in fact remote accounts.

### PR DESCRIPTION
**Pull request by kaiyou**
When deduplicating account usernames for OAuthable users, the routine did check if any account was known with that username, including remote accounts. This caused some unnecessary deduplication, and usernames ending with unexpected trailing `_1`.

This fixes #13580

### CODE REVIEW

File: app/models/concerns/omniauthable.rb [hunk 1]
```diff
@@ -82,7 +82,7 @@ def ensure_unique_username(starting_username)
       username = starting_username
       i        = 0
 
-      while Account.exists?(username: username)
+      while Account.exists?(username: username, domain: nil)
```
Comment (ThibG) [inline app/models/concerns/omniauthable.rb:85]: Nitpick: I would use `Account.local.exists?(...)` but this is fine.

**Review by ClearlyClaire — APPROVED** [review]
Looks good to me, thanks!
