### PR TITLE
Fix incorrect signature after HTTP redirect

### LINKED ISSUE #26529: Signature not updated when following HTTP redirects
### Steps to reproduce the problem

1. `Request.new(:get, url).on_behalf_of(user).perform` 
2. have `uri` HTTP 302 to another URL
3. request is re-issued to the redirected URL

### Expected behaviour

The new request's signature is updated to reflect the new `Host` and `(request-target)`

### Actual behaviour

The signature is not updated

### Detailed description

_No response_

### Mastodon instance

_No response_

### Mastodon version

_No response_

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #26529

Currently, we are signing HTTP requests ourselves then letting HTTP.rb do its work, including following redirects.
This means that redirects carry an incorrect signature.

This PR changes it to use HTTP.rb's `on_redirect` callback to recompute the signature from the redirected request. In order to do so, it also refactors signing code a bit.

### CODE REVIEW

**Review by oneiros — DISMISSED** [review]
This is really cool!

I do wonder if there would be a quick way to test this. Something like mock the redirect and make sure the signature header on the subsequent request is different. I do not think this easily possible with webmock and I cannot think of any other simple way, though.

**Comment by ClearlyClaire** [comment]
Added a test. It's not entirely satisfactory because webmock's matching functionality is lacking for headers, but it does test that the redirect is followed, and that the `Signature` header is different between the two requests (not actually testing whether there *is* a `Signature` header in the second request, only that it's not the initial one)

**Review by oneiros — APPROVED** [review]

File: app/lib/http_signature_draft.rb [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+class HttpSignatureDraft
+  REQUEST_TARGET = '(request-target)'
+
+  def initialize(keypair, key_id, full_path: true)
+    @keypair = keypair
+    @key_id = key_id
+    @full_path = full_path
+  end
+
+  def request_target(verb, url)
```
Comment (mjankowski) [inline app/lib/http_signature_draft.rb:15]: Are both paths of this hit by the added spec for `Request`? If not, maybe add unit spec for this new class to make sure we're exercising?
