### PR TITLE
Fix “Mention” appearing for otherwise filtered posts

### LINKED ISSUE #32340: Hide completely checkbox in filters doesn't hide completely in notifications
### Steps to reproduce the problem

1. Make a filter, check hide completely.
2. Check your Notifications

Screenshot 2024-10-09 160133

### Expected behaviour

They should be hidden completely

### Actual behaviour

A container with @ Mention shows up

### Detailed description

_No response_

### Mastodon instance

masto.byrd.ws

### Mastodon version

v4.3

### Browser name and version

Firefox 132

### Operating system

Windows 11

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #32340

### CODE REVIEW

File: app/javascript/mastodon/selectors/filters.ts [hunk 1]
```diff
@@ -0,0 +1,58 @@
+import { createSelector } from '@reduxjs/toolkit';
+
+import type { RootState } from 'mastodon/store';
+import { toServerSideType } from 'mastodon/utils/filters';
+
+// TODO: move to `app/javascript/mastodon/models` and use more globally
+type Filter = Immutable.Record<{
```
Comment (renchap) [inline app/javascript/mastodon/selectors/filters.ts:7]: This is unfortunately incorrect, it's not an `Immutable.Record` but an `Immutable.map<string, unknown>`, which does not allow good typing.
We should convert this to records (or plain JS objects), but until then it is probably best to not try to type this code :(

Comment (ClearlyClaire) [reply app/javascript/mastodon/selectors/filters.ts]: ok, it does work because the interfaces we use are common between `Map` and `Record`, but you're right. Amended the code to still type it correctly, but it makes pretty extensive use of `as`. At least it's self-contained.

Comment (renchap) [reply app/javascript/mastodon/selectors/filters.ts]: Correct, `Record` supports for example `record.attribute`, but `Map` only supports `record.get('attribute')`

**Review by renchap — APPROVED** [review]
