### PR TITLE
Correctly sanitize MathML out of post content

### LINKED ISSUE #26943: Implement FEP-dc88: Formatting Mathematics
### Pitch

Currently, several instances (such as https://mathstodon.xyz and https://types.pl) implement mathematical formatting locally, rendering mathematics between certain delimeters.

However, this can lead to incorrect formatting of incoming posts, and poor interoperability between servers.

[FEP-dc88](https://codeberg.org/fediverse/fep/src/branch/main/fep/dc88/fep-dc88.md) has been put forward to solve these incompatibilities with joint standard. However, it requires a specific sanitation algorithm to be implemented in servers which do not wish to show mathematics. Please see the [tracking issue](https://codeberg.org/fediverse/fep/issues/161) and [forum discussion](https://socialhub.activitypub.rocks/t/fep-dc88-formatting-mathematics/3564) for more information)

This algorithm would need to be implemented in Mastodon.

### Motivation

See #19806 for a previous discussion on this topic, and why mathematical formatting on the fediverse is important.

Fep-dc88 should be implemented in Mastodon in order to implement correct round-tripping of formatted text on instances which do not wish to show rich text. This will improve compatibility with servers which wish to provide mathematical formatting as a feature to their users. 

---
Supersedes #19806

### PR DESCRIPTION
**Pull request by 4e554c4c**
Summary:
-------
This commit correctly sanitizes incoming MathML according to [FEP-dc88]. Instead of completely removing MathML nodes, it replaces them with their LaTeX or plain-text representation, so that the mathematics can be read in some form by mastodon users.

Test Plan:
----------
```
$ RAILS_ENV=test bundle exec rspec spec/lib/sanitize_config_spec.rb -f d
Run options: exclude {:type=>#<Proc: ./spec/rails_helper.rb:79>}

Randomized with seed 58854

Sanitize::Config
  ::MASTODON_STRICT
    sanitizes math blocks to LaTeX
    converts h1 to p strong
    removes "translate" attribute with invalid value
    removes a without href
    removes a without href and only keeps text content
    math sanitizer falls back to plaintext
    keeps ul
    prefers latex
    removes a with unparsable href
    keeps start and reversed attributes of ol
    removes a with unsupported scheme in href
    keeps a with translate="no"
    keeps a with href
    keeps a with supported scheme and no host
    does not re-interpret HTML when removing unsupported links
    sanitizes math to LaTeX

Finished in 0.17323 seconds (files took 3.28 seconds to load)
16 examples, 0 failures

Randomized with seed 58854

```

observed 100% code coverage of `lib/sanitize_ext/sanitize_config.rb`.

Ran mastodon locally, and fetched [reference post][nyancat] and observed that math was converted to plaintext form (and was not missing).
image

Related Discussion:
-------------------

Please see [FEP-dc88], the [FEP tracking issue][tracking] and [FEP forum discussion][socialhub] for more information.

Fixes mastodon/mastodon#26943

[FEP-dc88]: https://codeberg.org/fediverse/fep/src/branch/main/fep/dc88/fep-dc88.md
[tracking]: https://codeberg.org/fediverse/fep/issues/161
[socialhub]: https://socialhub.activitypub.rocks/t/fep-dc88-formatting-mathematics/3564
[nyancat]: https://nyan.network/notice/Aa4IvnBVHysWswRX1s

### CODE REVIEW

**Comment by 4e554c4c** [comment]
well, codecov *used to* be 100% :sweat:

**Comment by omentic** [comment]
This is a tiny PR that would be incredibly beneficial to have, with MathML having now become evergreen a little over a year ago. A few academia-focused instances have merged it on their own (mathstodon.xyz and types.pl, primarily) but it is not very useful without broad adoption as instances can't send HTML that isn't going to render in most clients. It's really the weight of Mastodon that will let forks leave MathJax & co behind.

@ClearlyClaire or @renchap could I re-poke you to give it a look over?

**Comment by ClearlyClaire** [comment]
At first glance, the code seems fine, although I'd need to spend significantly more time reviewing it to make sure it doesn't introduce any issue.

I agree that outright losing information from a remote post is problematic, however, I am not sure how useful displaying raw LaTeX is, as even the simple example in the PR's description is a pain to read.

**Comment by omentic** [comment]
It only renders as plain text because that screenshot is from Tusky - which doesn't run in the browser but rather builds in their own renderer for the subset of HTML Mastodon doesn't strip. Here's how it renders in the web client on my instance that's running the patch. Since Firefox and Chrome have full MathML support, it renders well without further ado.

image

It doesn't render following the link above because a similar patch is still making its way into Akkoma (https://akkoma.dev/AkkomaGang/akkoma/pulls/642), so the MathML elements are stripped which results in the strange half-rendered behavior.

**Comment by 4e554c4c** [comment]
For a version that supports MathML, but tries to scrub all but the necessary information see my glitch-soc PR: glitch-soc/mastodon#1933
The goal of that PR was to get rid of any non-semantic information from the mathml (e.g. formatting info, that would clash with mastodon's style) which might be the right approach here too.

**Comment by omentic** [comment]
> I agree that outright losing information from a remote post is problematic, however, I am not sure how useful displaying raw LaTeX is, as even the simple example in the PR's description is a pain to read.

Ah, apologies - I got this PR and the glitch-soc PR mixed up and thought this one was also "don't strip MathML tags". I think not stripping MathML tags (https://github.com/glitch-soc/mastodon/pull/1933) would be really really nice to merge and beneficial to have (and is tiny!). Supporting MathML means that instances like mathstodon.xyz can target MathML directly, which Firefox and Chrome will automatically render, so posts containing math can be viewable on every instance without client-side patches.

If that PR looks good to you all, maybe @4e554c4c can pull it in here instead?

**Comment by christianp** [comment]
Hi, I'm one of the admins of mathstodon.xyz, and the person who wrote the LaTeX-rendering code for it. I'm keen to have a better solution for posts containing math, and I think this is a good first step.

I told @4e554c4c that we had money available to support developer time sorting this out, but never did anything about that! If there's anything we can do, let me know, either here or by DM to [@christianp@mathstodon.xyz](https://mathstodon.xyz/@christianp).

**Comment by ClearlyClaire** [comment]
Allowing MathML is yet another can of worms. One very significant issue is the sanitization library we use explicitly does not support it: https://github.com/rgrove/sanitize?tab=readme-ov-file#usage

**Comment by 4e554c4c** [comment]
> Allowing MathML is yet another can of worms.

This was my assumption from the start.

Could we maybe go ahead with this PR then, so that information isn't lost? Displaying mathematics in a nice way can be another issue (it can be as simple as bundling KaTeX). In the meantime, this would allow other fediverse implementations to move forward with the FEP.

**Comment by 4e554c4c** [comment]
rebased on main.

File: lib/sanitize_ext/sanitize_config.rb [hunk 1]
```diff
@@ -64,6 +64,43 @@ module Config
...
+          math.swap("$$#{annotation.content}$$")
+        else
+          math.swap("$#{annotation.content}$")
+        end
+        return
+      end
+      # Don't bother surrounding 'text/plain' annotations with dollar signs,
+      # since it isn't LaTeX
+      annotation = semantics.children.find(&is_annotation_with_encoding.curry['text/plain'])
+      math.swap(annotation.content) unless annotation.nil?
```
Comment (ClearlyClaire) [inline lib/sanitize_ext/sanitize_config.rb:101]: The calls to `math.swap` will replace `math` with the contents of the annotation *parsed by Nokogiri*. This is not critical because Sanitize should sanitize the replaced node as well, but this might not be what is expected.

Comment (4e554c4c) [reply lib/sanitize_ext/sanitize_config.rb:101]: I see, so maybe `inner_html` or `children` is a better method to use?

**Comment by mjankowski** [comment]
This is not specific to mathML, but I wonder about some general pattern of trying to somehow preserve "payloads" like this that are in a status that would allow clients to pull it out and render (ie, some math js in this scenario), while not introducing a security issue or weird visual issue in regular usage.

Could we throw any extracted markup into an (escaped) `data` attribute or something? This would allow native clients or JS hooks to look in a well-known place for that sort of payload.

File: lib/sanitize_ext/sanitize_config.rb (hunk 1 above)
Comment (4e554c4c) [reply lib/sanitize_ext/sanitize_config.rb]: it is now sanitized in the same way as above text.

**Comment by 4e554c4c** [comment]
> This is not specific to mathML, but I wonder about some general pattern of trying to somehow preserve "payloads" like this that are in a status that would allow clients to pull it out and render (ie, some math js in this scenario), while not introducing a security issue or weird visual issue in regular usage.
> 
> Could we throw any extracted markup into an (escaped) `data` attribute or something? This would allow native clients or JS hooks to look in a well-known place for that sort of payload.

so i thought about this, but it's kind of unclear where that 'data' would appear in the actual post. this could be done in a similar way to emojos but that really seems overly complicated in this (mastodon specific!!) case.

**Comment by 4e554c4c** [comment]
rebased on main and ready for review.

**Comment by 4e554c4c** [comment]
sorry messed up lints, so i need the workflows to be approved again :sweat_smile:

**Comment by christianp** [comment]
Returning to this, am I right that not wanting to see raw LaTeX in posts is the only thing holding this back?

Since allowing MathML through requires the sanitizer library to support it, would it be worthwhile spending some time looking at how much of [MathML Core](https://www.w3.org/TR/mathml-core) the sanitizer could support? I think the potential for sneaky business in MathML Core is significantly less than in SVG, for example.

**Comment by 4e554c4c** [comment]
> Returning to this, am I right that not wanting to see raw LaTeX in posts is the only thing holding this back?

IMO this shouldn't be a concern, since it's the current experience for non-math-instances interacting with math instances. 

But I would also like to hear what's holding this PR back

**Comment by mjankowski** [comment]
> For reference, this PR always has been about making math look "less bad". Actually displaying math is an entirely different issue.

Noted! I saw that was the conclusion, but wasn't totally sure on full commit/review/diff history.

> This PR specifically avoids adding any math tags to an allowlist, and after the transformer runs sanitize is free to remove all math elements. I believe this avoids the said security risk.

Nice.

> Done. Thanks for the push to update the PR :)

No prob, looks like all ran successfully on current matrix and the diff is now annotation-free for (maybe?) easier code review.

File: lib/sanitize_ext/sanitize_config.rb [hunk 2]
```diff
@@ -64,6 +64,44 @@ module Config
...
+      end
+
+      annotation = semantics.children.find(&is_annotation_with_encoding.curry['application/x-tex'])
+      if annotation
+        text = if math.attributes['display']&.value == 'block'
+                 "$$#{annotation.text}$$"
+               else
+                 "$#{annotation.text}$"
+               end
+        math.replace(Nokogiri::XML::Text.new(text, math.document))
```
Comment (ClearlyClaire) [inline lib/sanitize_ext/sanitize_config.rb:96]: cf. #31812

```suggestion
        math.replace(math.document.create_text_node(text))
```

File: lib/sanitize_ext/sanitize_config.rb [hunk 3]
```diff
@@ -64,6 +64,44 @@ module Config
...
+        return
+      end
+      # Don't bother surrounding 'text/plain' annotations with dollar signs,
+      # since it isn't LaTeX
+      annotation = semantics.children.find(&is_annotation_with_encoding.curry['text/plain'])
+      math.replace(Nokogiri::XML::Text.new(annotation.text, math.document)) unless annotation.nil?
```
Comment (ClearlyClaire) [inline lib/sanitize_ext/sanitize_config.rb:102]: cf. #31812

```suggestion
      math.replace(math.document.create_text_node(annotation.text)) unless annotation.nil?
```

**Comment by ClearlyClaire** [comment]
> Since allowing MathML through requires the sanitizer library to support it, would it be worthwhile spending some time looking at how much of [MathML Core](https://www.w3.org/TR/mathml-core) the sanitizer could support? I think the potential for sneaky business in MathML Core is significantly less than in SVG, for example.

This is outside of area of expertise, neither our focus for the foreseeable future. If anything, this should be done at https://github.com/rgrove/sanitize if they are willing to, but that itself would not guarantee inclusion of MathML Core in Mastodon, as we would still have to make a product design decision on this.

> looks like there was some initial hesitation about full mathml support

Full MathML support is out of question for the foreseeable future. This PR is about providing a fallback for MathML elements with annotations. It does so by replacing the `math` element with a text representation of a `application/x-tex` or `text/plain` annotation, in that order. This seems fairly sensible, although of limited interest. It may make sense to consider the `alttext` attribute of the `math` element.

**Review by ClearlyClaire — DISMISSED** [review]
Added two inline comments but seems ok to me otherwise.

There should be no security downside to this. There might be a very minor performance impact from the extra transformer. I am not sure how useful this is in practice, and maybe it would make more sense to use the `alttext` attribute, which seems more fitting for our purpose. But also, I understand the reason is to favor the `application/x-tex` annotation for client-side rendering using Javascript libraries.

**Comment by 4e554c4c** [comment]
> maybe it would make more sense to use the `alttext` attribute, which seems more fitting for our purpose. But also, I understand the reason is to favor the `application/x-tex` annotation for client-side rendering using Javascript libraries.

The rendering from JS libraries would be an added bonus, but I'm not particularly concerned about this. I've looked far and wide, and haven't found very many resources which use `alttext` for ordinary equations (display or inline math). I've read through a few accessibility guidelines for math on the web, and most of them tend to suggest mathml as being the accessible option, and don't mention alt text.

I'm hesitant to consider `alttext`, since if tools don't use it it'll likely stay a dead code path here.

I would be ok preferring the `text/plain` annotation over the `text/x-tex` one though.

**Review by ClearlyClaire — APPROVED** [review]

**Comment by christianp** [comment]
Thank you very much, everyone, for getting this merged!
