### PR TITLE
Fix crash when switching back/from mobile layout

### LINKED ISSUE #11630: TypeError on frontend when narrowing browser in multi column mode
### Expected behaviour
Browser shows the single expected column after narrowing the browser window in multi column mode.

### Actual behaviour
Browser shows the sad elephant. Browser console shows TypeError in [components/column_header.js](https://github.com/tootsuite/mastodon/blob/706a48e/app/javascript/mastodon/components/column_header.js#L181) because `document.getElementById('tabs-bar__portal')` returns `null`.

shonbori

[ThibG reported](https://github.com/tootsuite/mastodon/pull/11605#issuecomment-522443563) this may also happen for the `ColumnBackButton` component.

### Steps to reproduce the problem
Enable multi column mode, navigate to HTL or LTL, than narrow the browser window.

### Specifications
I noticed the problem on a server running on master at f96f45ef12341648cb8d79d9b70f8c5636f98f64 around August 3rd, 2019. The problem is seen at least on Firefox on macOS, Firefox on Linux, and Chromium on Linux.

It turned out my proposal for a fix on #11605 is premature. I'd like to move the conversation here and seek for a better solution from experts.

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #11630

### CODE REVIEW

File: app/javascript/mastodon/components/column_back_button.js [hunk 1]
```diff
@@ -35,7 +35,19 @@ export default class ColumnBackButton extends React.PureComponent {
     if (multiColumn) {
       return component;
     } else {
-      return createPortal(component, document.getElementById('tabs-bar__portal'));
+      // The portal container and the component may be rendered to the DOM in
+      // the same React render pass, so the container might not be available at
+      // the time `render()` is called.
+      const container = document.getElementById('tabs-bar__portal')
```
Comment (ykzts) [inline app/javascript/mastodon/components/column_back_button.js]:
```suggestion
      const container = document.getElementById('tabs-bar__portal');
```

File: app/javascript/mastodon/components/column_header.js [hunk 2]
```diff
@@ -178,7 +178,19 @@ class ColumnHeader extends React.PureComponent {
     if (multiColumn || placeholder) {
       return component;
     } else {
-      return createPortal(component, document.getElementById('tabs-bar__portal'));
+      // The portal container and the component may be rendered to the DOM in
+      // the same React render pass, so the container might not be available at
+      // the time `render()` is called.
+      const container = document.getElementById('tabs-bar__portal')
```
Comment (ykzts) [inline app/javascript/mastodon/components/column_header.js]:
```suggestion
      const container = document.getElementById('tabs-bar__portal');
```

**Review by ykzts — CHANGES_REQUESTED** [review]
Missing semicolon.

**Review by Gargron — APPROVED** [review]

**Review by ykzts — APPROVED** [review]
