### PR TITLE
Fix compose form behavior in mobile view

### LINKED ISSUE #13094: Reply form not work in Pale Moon
### Expected behaviour

Replying to toots should work in *Pale Moon* (Linux)

### Actual behaviour

pic.1

### Steps to reproduce the problem

Trying to reply to toot.

### Specifications

**Browser:** *Pale Moon* `28.8.2.1` (Linux)

**Hash:**

```
We</n.componentDidUpdate@https://fosstodon.org/packs/js/common-65a40ba0d18598a0834b.js:2:417745
Du@https://fosstodon.org/packs/js/common-65a40ba0d18598a0834b.js:2:1060147
t.unstable_runWithPriority@https://fosstodon.org/packs/js/common-65a40ba0d18598a0834b.js:2:1079629
Xa@https://fosstodon.org/packs/js/common-65a40ba0d18598a0834b.js:2:1004556
Fu@https://fosstodon.org/packs/js/common-65a40ba0d18598a0834b.js:2:1056398
wu@https://fosstodon.org/packs/js/common-65a40ba0d18598a0834b.js:2:1046717
Ja/<@https://fosstodon.org/packs/js/common-65a40ba0d18598a0834b.js:2:1004847
t.unstable_runWithPriority@https://fosstodon.org/packs/js/common-65a40ba0d18598a0834b.js:2:1079629
Xa@https://fosstodon.org/packs/js/common-65a40ba0d18598a0834b.js:2:1004556
Ja@https://fosstodon.org/packs/js/common-65a40ba0d18598a0834b.js:2:1004792
$a@https://fosstodon.org/packs/js/common-65a40ba0d18598a0834b.js:2:1004727
se@https://fosstodon.org/packs/js/common-65a40ba0d18598a0834b.js:2:1073779
xn@https://fosstodon.org/packs/js/common-65a40ba0d18598a0834b.js:2:988375
```

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #13094

Until this PR, when writing toots in mobile view, two `ComposeForm` components were rendered:
- one in the compose pane hidden by CSS
- one corresponding to the `/web/statuses/new` path

The auto-focus and auto-selection code was executed on the hidden `ComposeForm` (causing a crash in PaleMoon, see #13094) and wasn't executed on the displayed `ComposeForm` component.

This PR uses media queries to decide whether to render the compose pane's `ComposeForm`, avoiding unnecessary rendering the hidden component and avoiding the PaleMoon crash, and makes it so the auto-selection and auto-focus code gets executed when replying to toots in mobile view.

### CODE REVIEW

File: app/javascript/mastodon/features/compose/components/compose_form.js [hunk 1]
```diff
@@ -132,6 +132,10 @@ class ComposeForm extends ImmutablePureComponent {
     }
   }
 
+  componentDidMount () {
+    this.componentDidUpdate({ });
```
Comment (Gargron) [inline app/javascript/mastodon/features/compose/components/compose_form.js:136]: Can you please extract `componentDidUpdate` into another method instead and then call it from both?

**Review by Gargron — CHANGES_REQUESTED** [review]

**Comment by ClearlyClaire** [comment]
ping @Gargron

**Review by Gargron — APPROVED** [review]
