### PR TITLE
Fix account warnings not being recorded in audit log

### LINKED ISSUE #18334: Warnings/account actions have stopped showing up in the audit log
### Steps to reproduce the problem

1. Go to a user's profile page
2. Send a warning
3. Go to the audit log
4. See no warnings
5. (optional) filter by warnings
6. (optional) see the last warning log entry was created in December 2021

### Expected behaviour

All moderator actions should show up in the audit log.

### Actual behaviour

All moderator actions **except for warnings** show up in the audit log.

### Specifications

We're up to date, running Mastodon v3.5.2.

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #18334

### CODE REVIEW

File: app/models/admin/account_action.rb [hunk 1]
```diff
@@ -92,6 +92,10 @@ def process_strike!
       text: text_for_warning,
       status_ids: status_ids
     )
+
+    # A log entry is only interesting if the warning contains
+    # custom text from someone. Otherwise it's just noise.
+    log_action(:create, @warning) if @warning.text.present?
```
Comment (Gargron) [inline app/models/admin/account_action.rb:98]: This does restore the previous logic, but in the previous logic, warnings were mostly separate from other moderator actions, whereas now a moderator action and a warning almost always happen at the same time. Would it make more sense to log if the action is a no-op? So "just" a warning?

Comment (ClearlyClaire) [reply app/models/admin/account_action.rb:98]: Why not.

**Review by Gargron — APPROVED** [review]
