### PR TITLE
Fix PostgreSQL load when linking in announcements

### LINKED ISSUE #13245: PostgreSQL will be overloaded if URL is included in the announcement
### Actual behaviour

Creating an announcement that includes a URL causes high load on the PostgreSQL.

PgHero recorded the following slow query:

Probably [this](https://github.com/tootsuite/mastodon/pull/13212/files#diff-0b3dd38d3bd1723e5bf1552ef75a14f6R377) of #13212 is related.

Maybe, creating an index on `url` of the `statuses` table will solve this.
But it will greatly increase the disk usage of the database. I want to avoid if possible.

### Specifications

Mastodon master branch after aa67036b41d37935210c8b5094ac20c153a62011

This occurred when including a generic URL that was not a toot.
I don't try if it will happen even in the case of a toot URL.

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #13245 by caching status lookups

Since statuses are supposed to be known already and we only
need their URLs and a few other things, caching them should
be fine.

Since it's only used by announcements so far, there won't
be much statuses to cache.

### CODE REVIEW

**Review by Gargron — APPROVED** [review]

**Comment by abcang** [comment]
I think it is very dangerous to search by url.
Running EXPLAIN on my personal instance took about 8 seconds, but I'm guessing that it will be even slower and take several minutes on large instances like mastodon.social and Pawoo.
Currently, there is no index, so it is very slow because it is searching by sequential scan.
Also, this slow query will be executed too if the announcement contains a URL other than the Mastodon instance (for example, YouTube).

```sql
EXPLAIN ANALYZE SELECT "statuses".* FROM "statuses" WHERE "statuses"."deleted_at" IS NULL AND "statuses"."url" = 'https://testingmstdn.abcang.net/' ORDER BY "statuses"."id" DESC LIMIT 1
```

```
Limit  (cost=444085.66..444085.67 rows=1 width=325) (actual time=9161.576..9161.576 rows=0 loops=1)
  ->  Sort  (cost=444085.66..444085.67 rows=1 width=325) (actual time=9161.575..9161.575 rows=0 loops=1)
        Sort Key: id DESC
        Sort Method: quicksort  Memory: 25kB
        ->  Seq Scan on statuses  (cost=0.00..444085.65 rows=1 width=325) (actual time=9161.567..9161.567 rows=0 loops=1)
              Filter: ((deleted_at IS NULL) AND ((url)::text = 'https://testingmstdn.abcang.net/'::text))
              Rows Removed by Filter: 7817774
Planning time: 0.214 ms
Execution time: 9161.636 ms
```

Due to the slowness of the query, it is expected that the announcement API will be run by many users before the query results are recorded in the cache, resulting in many slow queries.

**Comment by abcang** [comment]
I think it is better to stop searching by url. If you stop searching by url, it will not be displayed seamlessly for the URL of other instances, but I did not think it was important.

**Comment by ThibG** [comment]
Hm… I don't know how likely it is that API calls are going to be made while the query is going to run: individual users should only call the API on fetch, not receiving from the streaming API, which is the first thing that happens.

Anyway, yeah, it may not be worth it to perform that query for remote toots…

On the other hand, it's not the only place we perform such queries (e.g., the search box, this is required to find private toots you have the URL to). So maybe we do need an additional index…

**Comment by abcang** [comment]
Indeed, we may not need to think too much about running the announcement API by many user before query results are cached…
I think it's important to fix the search so that it takes less than a few minute.

> On the other hand, it's not the only place we perform such queries (e.g., the search box, this is required to find private toots you have the URL to).

I noticed this issue while investigating the announcement API. The search API Issue has already been created. #13251

**Comment by nightpool** [comment]
I guess I'm just confused why we need to do this query at all. can't we do
it once when updating the status and store the association in a jsonb
column?

**Comment by ThibG** [comment]
For announcements that could definitely work, yeah. It wouldn't for URL search though.

**Comment by ThibG** [comment]
Pushed a commit to perform the lookup when saving the announcement, making sure this is not done more often than needed.
However, this means the action of posting an announcement can timeout, now… and I'm not comfortable with that…
I think the following further changes can be made:
- move the status resolution from a `before_validation` hook to the publishing worker (and make all announcements unpublished until the worker is actually called to avoid clients pulling in incomplete announcement objects)
- fetch toots instead of looking them up in the database… those are public toots so that is possible, and also, faster in general

**Comment by abcang** [comment]
I agree with how to fetch toot. Even if a worker searches an external URL in the background, I think that it will be a slow query and the load on the DB will not change. (I think a large instance will take at least a few minutes to query for an external URL.)

**Comment by ThibG** [comment]
ok changed the PR so that:
- lookups are not made when serializing, but when publishing (in the publishing worker)
- lookups for remote URLs are done by fetching the toot (which cost is only dependent on the remote server, and limited by our timeouts) rather than from the database (which cost is dependent on the number of toots known to the instance)
- remote lookups are cached so that URLs don't get unnecessarily re-fetched when updating an announcement

**Review by abcang — APPROVED** [review]

File: app/lib/entity_cache.rb [hunk 1]
```diff
@@ -7,6 +7,12 @@ class EntityCache
 
   MAX_EXPIRATION = 7.days.freeze
 
+  def status(url)
+    Rails.cache.fetch(to_key(:status, url), expires_in: MAX_EXPIRATION) do
```
Comment (Gargron) [inline app/lib/entity_cache.rb:11]: Would prefer single-line block in this case

File: db/schema.rb [hunk 2]
```diff
@@ -231,6 +231,7 @@
     t.datetime "created_at", null: false
     t.datetime "updated_at", null: false
     t.datetime "published_at"
+    t.bigint "status_ids", array: true
```
Comment (Gargron) [inline db/schema.rb:234]: I am a bit concerned about the inconsistency that we have an explicit field for `status_ids` but not for `account_ids` or `tag_ids`, which itself is not exactly consistent with statuses having `mentions` and `statuses_tags` tables for storing such relations.

File: app/models/announcement.rb [hunk 3]
```diff
@@ -49,7 +50,9 @@ def mentions
   end
 
   def statuses
-    @statuses ||= Status.from_text(text)
+    return [] if status_ids.nil?
```
Comment (Gargron) [inline app/models/announcement.rb:53]: I think I would've opted for a `begin`/`end` block with `if`/`else` inside the assignment instead

File: app/models/announcement.rb [hunk 4]
```diff
@@ -75,6 +78,11 @@ def reactions(account = nil)
     records
   end
 
+  def refresh_status_ids!
```
Comment (Gargron) [inline app/models/announcement.rb:81]: The precedent for this kind of thing is `ProcessMentionsService`, that is, networking code isn't in the `Status` model but outside. Maybe best to keep it this way here too, you're only abstracting a single line of code behind this function, so the networking code could be directly in the `PublishScheduledAnnouncementWorker`. Does that make sense?

File: db/schema.rb (hunk 2 above)
Comment (ThibG) [reply db/schema.rb:234]: Yeah, I'm a bit unsure about this one, but I don't think we need more than an array here. Also, accounts and tags are significantly faster to fetch since we have an index on that, but not for URLs. There is kind of a precedent with reports and conversations holding arrays of toots/accounts too.

**Review by Gargron — APPROVED** [review]

**Comment by abcang** [comment]
@Gargron Is this not included in v3.1.3?

**Comment by Gargron** [comment]
Oops, I thought I merged. Thank you!
