### PR TITLE
fix(emojis): Handle multicode emojis (e.g. country flags)

### LINKED ISSUE #4217: Emoji picker can't insert multi-point emoji after PR #4202 and #4189
Testing on master, the emoji picker is unable to insert composite emoji, such as any of the flags, the family emojis (apart from the first one, which uses only one point), or the skin modifiers (but they didn't work before either).

In addition, the emoji inside the textarea render using the system font, which makes them look ugly and unreadable if you're not on a system with native emoji support.

Also, the emoji tooltips are gone, which was a really useful feature for deciphering hard-to-understand emojis in the timelines.

screenshot_20170716_014206

### PR DESCRIPTION
**Pull request by sorin-davidoi**
Closes #4217.

### CODE REVIEW

File: app/javascript/mastodon/reducers/compose.js [hunk 1]
```diff
@@ -118,7 +118,7 @@ const insertSuggestion = (state, position, token, completion) => {
 };
 
 const insertEmoji = (state, position, emojiData) => {
-  const emoji = String.fromCodePoint(parseInt(emojiData.unicode, 16));
+  const emoji = emojiData.unicode.split('-').map(code => String.fromCodePoint(parseInt(code, 16))).join('')
```
Comment (Gargron) [inline app/javascript/mastodon/reducers/compose.js]: Missing semicolon

**Review by Gargron — CHANGES_REQUESTED** [review]

**Review by Gargron — APPROVED** [review]
