### PR TITLE
Fix home regeneration not being triggered when logging in

### LINKED ISSUE #6331: Home timeline for returning users not fixed?
In #6251 I did a lot to fix #5634, but I got this report from a user of mastodon.social which runs 2.2.0rc1, which included the fix:

>It said the feed was empty, or something similar. It seems to have kind-of sorted itself out now, I'm seeing toots going forward, but I'm still not seeing anything going backwards past this morning
>
>Except! I can see the two new people I followed when I go backwards in my timeline. Everyone else is not showing up.

https://mastodon.social/@VirtualClint/99395232707153354

I'm kind of at the end of my wits because I have tested locally prior to the fix: Followed a bunch of accounts, made a bunch of posts from them, then removed the home timeline from redis, set my current_sign_in_at and last_sign_in_at values to long ago, and I got back a working home timeline that included everything it needed to. I don't know where and how it goes wrong.

**I would appreciate if another person tried debugging this.**

___

Some pointers:

- Home feeds are stored in redis
- They're pruned for ppl who didn't login for 2 weeks
- UserTrackingConcern is responsible for updating login times at most once a day and queueing up the RegenerationWorker if the 2 week absence is detected
- RegenerationWorker iterates over a SQL version of the home timeline and it's supposed to fill the redis timeline

### PR DESCRIPTION
**Pull request by Gargron**
Fix #6331

UserTrackingConcern is circumvented by SessionsController#create because it calls warden, which calls the User#update_tracked_fields! method directly. Move returning user logic to that method.

I.e. the home regeneration logic would work perfectly if you still have a valid cookie. If you have to go through the login form, the login form would update the current_sign_in_at values without triggering home regeneration, and subsequent page visits would not pick up the slack because they think the job is done.

### CODE REVIEW

File: app/models/user.rb [hunk 1]
```diff
@@ -220,9 +225,23 @@ def sanitize_languages
...
 
-  def update_statistics!
+  def prepare_new_user!
     BootstrapTimelineWorker.perform_async(account_id)
     ActivityTracker.increment('activity:accounts:local')
     UserMailer.welcome(self).deliver_later
   end
+
+  def prepare_returning_user!
+    ActivityTracker.record('activity:logins', id)
```
Comment (renatolond) [inline app/models/user.rb]: Couldn't you track more than once per day if the user logs out and then logs in again?

Comment (Gargron) [reply app/models/user.rb]: @renatolond It's a weekly hyperloglog. I.e. adding the same id 2000 times won't count as more than 1 per week.

Comment (renatolond) [reply app/models/user.rb]: Ah, okay, since the previous code was after the return I wasn't sure :)

**Review by renatolond — APPROVED** [review]

**Comment by nightpool** [comment]
LGTM 👍

**Review by nightpool — APPROVED** [review]
