### PR TITLE
Fix error when invalid domain name is submitted

### LINKED ISSUE #19175: API: 500 error when creating a DomainAllow with a space in it
### Steps to reproduce the problem

`POST /api/v1/admin/domain_allows?domain=foo bar`

### Expected behaviour

422 validation error

### Actual behaviour

500 HTML response "invalid character in host" from Rails

### Specifications

latest commits

### PR DESCRIPTION
**Pull request by Gargron**
Fix #19175

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

**Comment by Gargron** [comment]
@ClearlyClaire The code I'm changing was originally written by you, so I need an opinion here.

File: app/controllers/admin/domain_blocks_controller.rb [hunk 1]
```diff
@@ -43,12 +43,8 @@ def create
     def update
       authorize :domain_block, :update?
 
-      @domain_block.update(update_params)
-
-      severity_changed = @domain_block.severity_changed?
-
-      if @domain_block.save
```
Comment (ClearlyClaire) [inline app/controllers/admin/domain_blocks_controller.rb:50]: Seems like you fixed a bug, `update` would have saved to database and `severity_changed?` would have been false.

File: app/controllers/api/v1/admin/domain_allows_controller.rb [hunk 2]
```diff
@@ -19,12 +19,8 @@ class Api::V1::Admin::DomainAllowsController < Api::BaseController
   def create
     authorize :domain_allow, :create?
 
-    @domain_allow = DomainAllow.find_by(resource_params)
-
-    if @domain_allow.nil?
-      @domain_allow = DomainAllow.create!(resource_params)
-      log_action :create, @domain_allow
-    end
```
Comment (ClearlyClaire) [inline app/controllers/api/v1/admin/domain_allows_controller.rb:27]: This was to make the API call idempotent. I don't think there's harm either way.

File: app/controllers/api/v1/admin/domain_blocks_controller.rb [hunk 3]
```diff
@@ -19,12 +19,10 @@ class Api::V1::Admin::DomainBlocksController < Api::BaseController
   def create
     authorize :domain_block, :create?
 
-    existing_domain_block = resource_params[:domain].present? ? DomainBlock.rule_for(resource_params[:domain]) : nil
-    return render json: existing_domain_block, serializer: REST::Admin::ExistingDomainBlockErrorSerializer, status: 422 if existing_domain_block.present?
-
```
Comment (ClearlyClaire) [inline app/controllers/api/v1/admin/domain_blocks_controller.rb:24]: Removing this introduces an inconsistency between the web-based admin interface and the API, where in the former, creating a domain block for a sub-domain will error out, and in the latter, creating such a domain block will succeed.

Overall, it may make sense to allow the latter, but `UnblockDomainService` currently assumes that when lifting a domain block, no other domain block will apply, so before allowing this change we need to take care of that.

File: app/controllers/api/v1/admin/domain_blocks_controller.rb [hunk 4]
```diff
@@ -41,11 +39,10 @@ def show
   def update
     authorize @domain_block, :update?
 
-    @domain_block.update(domain_block_params)
-    severity_changed = @domain_block.severity_changed?
-    @domain_block.save!
-    DomainBlockWorker.perform_async(@domain_block.id, severity_changed)
+    @domain_block.update!(domain_block_params)
+    DomainBlockWorker.perform_async(@domain_block.id, @domain_block.severity_previously_changed?)
```
Comment (ClearlyClaire) [inline app/controllers/api/v1/admin/domain_blocks_controller.rb:43]: Looks good, fixing a bug again.

**Review by ClearlyClaire — DISMISSED** [review]
