### PR TITLE
Change search to use query params in web UI

### LINKED ISSUE #23972: Dissociate Search and Explore
Currently, making a search makes it appear as part of the “Explore” section. This suggestion is about separating it, as it is a little confusing and not entirely logical.

1. Look at the Explore section. It is called “Explore”, has a hashtag icon, and the four tabs Posts, Hashtags, News, and For you. “Explore” is highlighted on the right.
2. Continue browsing for a while.
3. Now make a search. Type a keyword and press enter.
4. Search results appears. It looks like its own section. It is called “Search results”, has a magnifier icon and its own four tabs: All, People, Hashtags, Posts. No section is highlighted on the right.
5. Continue browsing for a while.
6. Now imagine you want to go back to Explore. You click Explore on the right and… surprisingly, you see your previous search results. It’s clearly the Search section, but it’s inexplicably there instead of the Explore section, even though that’s the one highlighted. Worse, it’s not even clear how to leave the search and show the explore content instead (after some clicking around, you might realise you actually need to click on the X in the search bar which is not at all located within the section itself).

This happens to me several times a day, and I cannot get used to it. Search and Explore are clearly different sections in terms of use, interface and content, but somehow Explore opens Search if a search has been done previously. It looks like a confusing bug, but I believe it might just be a leftover of how the explore section was developed into what it is now. But now in its current state, it does not make any sense any more to keep these sections secretly linked like that.

### LINKED ISSUE #24466: Clicking on Explore while in search should clear search query
### Steps to reproduce the problem

1. Search for something like 'test'
2. Click Explore in the side navigation column

### Expected behaviour

To see Posts / Hashtags / News / For you that are trending

### Actual behaviour

Seeing All / Profiles / Hashtags / Posts for the search results

### Detailed description

_No response_

### Specifications

Mastodon 4.1.2
Bird ui, but also occurs on Mastodon social etc

### LINKED ISSUE #26868: Search requests should be stored in a query string
### Pitch

I'd like to be able to share the URl of a search - for example https://mastodon.social/search?q=mastodon%20fediverse

(Longer term, I'd like to be able to save search requests the same way I save hashtag searches, but this would be a great intermediate step.)

### Motivation

Twitter allows me to share a search in a GET request.  For example https://twitter.com/search?q=mastodon%20fediverse

This would be a useful way to be able to share search results with other users - whether they're logged in or not.

### LINKED ISSUE #29991: Use `/search` for search
## Preliminary note

This issue is part of our "help wanted" issues. It represents something that we know we want to implement, and that is defined enough that a contributor can implement it in a way that it would get merged.

If you want to work on this, please add a comment saying so and ask any questions you need, then open a PR referencing this issue!

## Description

At the moment, the state for the search field (auto-complete, history, results…) is stored in Redux. When searching, the URL does change to `/search` but thats all.

We want to move the current search state to the URL, with for example `/search?query=something`, and not use the Redux state for it. We can still use the Redux state to store the results for recent searches (so you can navigate back to the search page and it is cached)

Navigation should work correctly back and from the search page.

When loading the search page, we need to present the user with a search field. A nice improvement would be to display some syntax help near the field, like what is currently displayed in the auto-complete menu (but could be expanded as we would have more space).

Loading screens / indicators could probably be improved as well

This would solve https://github.com/mastodon/mastodon/issues/26868

## Implementation notes

It may be a good idea to modernise the code while you work on this, with functional components and Typescript.

Recent searches could be stored in `LocalStorage` (with a new `useLocalStorage` hook). If a "complex" local state is needed, consider [`useImmer`](https://github.com/immerjs/use-immer).

### LINKED ISSUE #32933: Add loading indicator to search result UI
### Pitch

When user searches for a link to a post or a profile, add an indicator that Mastodon is fetching the link from the other instance.

A progress bar won't work, because we don't know how long it will take, so a round loading indicator thingy or a "Searching…" text would be appropriate here.

### Motivation

Right now, it says "Could not find anything for these search terms" while it's still busy fetching the status.

This is very confusing especially to new users, because there's no way to tell whether the status can still be fetched or not (e.g. one of the 2 servers might have suspended the other).

Image

### PR DESCRIPTION
**Pull request by Gargron**
Instead of managing current search terms and options in internal state, use query params on the search path. Disambiguate search from explore.

___

Fixes MAS-177, fixes #26868, fixes #29991, fixes #24466, fixes #23972, fixes #32933

### CODE REVIEW

**Review by ClearlyClaire — COMMENTED** [review]
From a design point of view, this means that in the advanced interface, the search input and the search results are now on opposite sides of the screen (or even worse if there are more pinned columns)

**Comment by Gargron** [comment]
@ClearlyClaire What would you suggest?

**Comment by ClearlyClaire** [comment]
I'm honestly not sure. Maybe a search bar in the search results column, but it would be kind of redundant with the composer column one…

**Comment by trwnh** [comment]
perhaps a modal or drawer sheet?

**Comment by ClearlyClaire** [comment]
This still features a major usability regression in the advanced interface, where the search bar and results are at opposite ends of the page (which can involve scrolling depending on the number of columns and screen size). One solution to this would be to repeat the search input in the search column if in advanced mode.

File: app/javascript/hooks/useLinks.ts [hunk 1]
```diff
@@ -28,12 +30,22 @@ export const useLinks = () => {
...
+            `/@${result.payload.statuses[0].account.acct}/${result.payload.statuses[0].id}`,
+          );
+        } else {
           window.location.href = element.href;
-        }),
-      );
+        }
+      } else if (isRejected(result)) {
+        window.location.href = element.href;
+      }
```
Comment (ClearlyClaire) [inline app/javascript/hooks/useLinks.ts:48]: This is not new, this is something that I failed to notice when it was introduced, but this causes a very confusing behavior: if those links fail to resolve, clicking them will cause the target to open *in the current tab*, replacing the web interface, which is unlike every other external link in the interface.

Comment (Gargron) [reply app/javascript/hooks/useLinks.ts:48]: Unfortunately, because the execution here is async, using `window.open` would trigger the pop-up blocker. Is that an acceptable trade-off in this scenario?

Comment (ClearlyClaire) [reply app/javascript/hooks/useLinks.ts:48]: I think this is possibly slightly better than having the current tab replaced, but it's indeed not great either way…

**Review by ClearlyClaire — APPROVED** [review]

**Comment by mjankowski** [comment]
Looks approved/queueueued, but just needs a stray conversation resolved?...

**Comment by KaKi87** [comment]
Hi,
When will this be released ?
Thanks

**Comment by renchap** [comment]
This will be released in Mastodon 4.4.0, later today.
