### PR TITLE
Fix hashtags being split by ZWNJ character

### LINKED ISSUE #11761: ZWNJ is not supported in hashtags
### Expected behaviour

I expect ZWNJ to be included in hashtag. I need whole of "نرم‌افزار" be a hashtag.

### Actual behaviour

By now, Hashtag only includes non-ZWNJ characters. So in the given example above, only "نرم" gets converted to link.

### Steps to reproduce the problem

You just add #نرم‌افزار and see how it only includes نرم as hashtag.

### Specifications

It is a general bug in Mastodon

### PR DESCRIPTION
**Pull request by Gargron**
Fix #11761

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

File: app/models/tag.rb [hunk 1]
```diff
@@ -25,8 +25,9 @@ class Tag < ApplicationRecord
   has_many :featured_tags, dependent: :destroy, inverse_of: :tag
   has_one :account_tag_stat, dependent: :destroy
 
-  HASHTAG_NAME_RE = '([[:word:]_][[:word:]_·]*[[:alpha:]_·][[:word:]_·]*[[:word:]_])|([[:word:]_]*[[:alpha:]][[:word:]_]*)'
-  HASHTAG_RE = /(?:^|[^\/\)\w])#(#{HASHTAG_NAME_RE})/i
+  HASHTAG_SEPARATORS = "_\u00B7\u200c"
```
Comment (ThibG) [inline app/models/tag.rb]: I think the · would be more obvious written as is, but otherwise ok

**Review by ClearlyClaire — APPROVED** [review]
