### PR TITLE
Fix exclusive lists interfering with notifications

### LINKED ISSUE #27316: "Hide these posts from home" mutes explicit notification setting
### Steps to reproduce the problem

1. Create list with "Hide these posts from home" toggled on
2. Find user, add user to this list, toggle on "notify me when @[user] posts"
3. Have user post something

### Expected behaviour

Post to only appear in (exclusive) list, and not in home, but also to get a notification when they post

### Actual behaviour

Post only appears in list, not in home, but also doesn't get notified

### Detailed description

Seems to be caused by https://github.com/mastodon/mastodon/blob/3262d1f1b62a984343f0f6c67c1d18921daabb0a/app/workers/feed_insert_worker.rb#L32-L37, which hooks the "exclude from home" feature into the feed-filter mechanism, which then also indadvertedly skips notifying.

### Mastodon instance

tech.lgbt

### Mastodon version

v4.2.0+glitch

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: `ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]`
- Node.js version: `v18.12.1`

### PR DESCRIPTION
**Pull request by ShadowJonathan**
Fixes https://github.com/mastodon/mastodon/issues/27316

I had to rename a parameter, and add a function, to make sure this didn't become too much of a messy hack, but i hope that this is at least still a similar level of cleanliness and understanding

The only annoyance is that this is now building crutches twice, the alternative for that would be to have some enum/flag/symbol kind of return ("hide from home, show notif", "don't show notif, hide from home", `:skip_home, :filter`), but that's a lot more refactoring

if that's the more clean solution, prompt me, then i'll try to refactor around it

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
> The only annoyance is that this is now building crutches twice

This could be an issue, as this part of the code is in a hot path. I think we might want to rework it so that Home, Notifications and List delivery happen in the same job unit, with a single call to `build_crutches`.

**Comment by ShadowJonathan** [comment]
@ClearlyClaire does that mean that you/someone will eventually create a PR that refactors this code, and that this PR won't move forward?

**Comment by ClearlyClaire** [comment]
> @ClearlyClaire does that mean that you/someone will eventually create a PR that refactors this code, and that this PR won't move forward?

I experimented a bit, and the database schema does not lend itself well to what I was suggesting. So we probably want to keep the current split in jobs, at least for the time being, and instead look into keeping your PR but avoiding the duplicate work between `filter?(:home, …)` and ` filter_notification?`.

**Comment by ShadowJonathan** [comment]
Alright, would a symbol return (`:unfiltered, :home_filtered, :filtered`) to `filter?` be a good solution then?

**Comment by ShadowJonathan** [comment]
I'll take a look at this, thanks for bumping

**Comment by ShadowJonathan** [comment]
> Alright, would a symbol return (`:unfiltered, :skip_home, :filtered`) to `filter?` be a good solution then?

@ClearlyClaire this has been a year in the making, but what's your opinion on this?

**Comment by ClearlyClaire** [comment]
What about either a symbol or `nil`? `:filtered` if filtered, `:skip_home` if filtered for `home` when checking for notifications, and `nil` otherwise. That way, the truthy behavior evaluation stays the same, but you can still discriminate between `:skip_home` and `:filtered` in `FeedInsertWorker`?

**Comment by ShadowJonathan** [comment]
Didn't know that atoms were truthy and `nil` was falsey, but yes, that sounds perfect. I'll implement that.

File: app/lib/feed_manager.rb [hunk 1]
```diff
@@ -386,24 +384,22 @@ def filter_from_home?(status, receiver_id, crutches, timeline_type = :home)
...
       should_filter ||= crutches[:blocked_by][status.reblog.account_id]                                                          # or if the author of the reblogged status is blocking me
       should_filter ||= crutches[:domain_blocking][status.reblog.account.domain]                                                 # or the author's domain is blocked
-
-      return !!should_filter
+    else
+      should_filter = false
     end
 
-    false
+    should_filter ? :filter : nil
```
Comment (ShadowJonathan) [inline app/lib/feed_manager.rb:402]: This little weird bit is needed to prevent rubocop from complaining about the increased complexity.

File: app/services/notify_service.rb [hunk 2]
```diff
@@ -126,7 +126,7 @@ def drop?
     private
 
     def blocked_mention?
-      FeedManager.instance.filter?(:mentions, @notification.target_status, @recipient)
+      !!FeedManager.instance.filter?(:mentions, @notification.target_status, @recipient)
```
Comment (ShadowJonathan) [inline app/services/notify_service.rb:129]: There is an argument to be made that `filter` and `filter?` should become two seperate functions, one just testing the truthiness of the other, since else it results in stuff like this, but i'll leave it up to y'all to decide on that.

**Comment by ShadowJonathan** [comment]
@ClearlyClaire @mjankowski this PR is ready for review.

**Comment by ClearlyClaire** [comment]
Ah, this is a little more awkward and involved than I anticipated, and I missed the bit about the function being called `filter?`; by convention, this should return a boolean… I guess having `filter` and `filter?` that just wraps around it would make sense.

**Comment by ShadowJonathan** [comment]
@ClearlyClaire applied! The PR should be much cleaner to review now ^^

**Review by ClearlyClaire — APPROVED** [review]
I wonder if there's a way to make it read less awkward, but it's not *too* bad, and it should fix an actual issue.

File: app/lib/feed_manager.rb [hunk 3]
```diff
@@ -32,26 +32,33 @@ def key(type, id, subtype = nil)
...
 
-  # Check if the status should not be added to a feed
+  # The filter result of the status to a particular feed
   # @param [Symbol] timeline_type
   # @param [Status] status
   # @param [Account|List] receiver
-  # @return [Boolean]
-  def filter?(timeline_type, status, receiver)
+  # @return [void|Symbol] nil, :filter, or :skip_home
+  def filter(timeline_type, status, receiver)
```
Comment (mjankowski) [inline app/lib/feed_manager.rb:40]: The previous public method here was `filter?` - and I think `filter` here is new, and now is essentially internal-only implementation for the `filter?` public method ... should `filter` be private?

**Review by mjankowski — COMMENTED** [review]
I see changes to existing specs to handle the signature change - should there be new spec for the fixed/change list scenario here?

File: app/lib/feed_manager.rb (hunk 3 above)
Comment (ClearlyClaire) [reply app/lib/feed_manager.rb:40]: It should not be private, it's also used by `FeedInsertWorker`.

File: spec/lib/feed_manager_spec.rb [hunk 4]
```diff
@@ -164,6 +164,7 @@
         allow(List).to receive(:where).and_return(list)
         status = Fabricate(:status, text: 'I post a lot', account: bob)
         expect(subject.filter?(:home, status, alice)).to be true
+        expect(subject.filter(:home, status, alice)).to be :skip_home
```
Comment (ShadowJonathan) [inline spec/lib/feed_manager_spec.rb:167]: > I see changes to existing specs to handle the signature change - should there be new spec for the fixed/change list scenario here?

@mjankowski this spot here (and one below) should catch the new changed scenario, or do you want me to write/add `expect(.filter)` to all of these, to catch all of these scenarios?

Comment (mjankowski) [reply spec/lib/feed_manager_spec.rb:167]: > @mjankowski this spot here (and one below) should catch the new changed scenario

Ah, I see ... from the high level description I was expecting a new example, but I see its more of a behavior change/addition to some of the existing cases.

> Is this enough, or do you want me to write/add `expect(.filter)` to all of these, to catch all of these scenarios?

I'm not sure ... this might be enough. I'd say that if the other ones would break if it accidentally changed, they should also check on `:filter` like these check on `:skip_home` ... but if that other behavior is fine with just the existing `filter?` true/false checks, prob fine to skip.

Comment (ShadowJonathan) [reply spec/lib/feed_manager_spec.rb:167]: Alright, what is the proper way to get this PR merged then? Are you able to poke this further internally?

(All the threads need to be resolved, and either I can do that, or someone with permissions from mastodon can do that, but i want an a-ok on those if possible)

Comment (mjankowski) [reply spec/lib/feed_manager_spec.rb:167]: > Alright, what is the proper way to get this PR merged then?

I don't know, and no one will tell me.

> Are you able to poke this further internally?

I doubt it, but I will absolutely try to.

> (All the threads need to be resolved, and either I can do that, or someone with permissions from mastodon can do that, but i want an a-ok on those if possible)

Be the change you want to see in the world, which in this case means go ahead and resolve some conversations.
