### PR TITLE
Fix ISO code for Canadian French

### LINKED ISSUE #24538: `fr-QC` locale is less common than `fr-CA`
### Steps to reproduce the problem

1. Search for `fr-QC`
2. Search for `fr-CA`
3. Compare results.

### Expected behaviour

We should be using the most common code

### Actual behaviour

We are using a very unusual code

### Detailed description

We've had problems on cosocial.ca with the Canadian French language code, fr-QC. The more common ICU locale is fr-CA. As far as I can tell, the language choices are not specific to Quebecois French compared to the French spoken in the rest of Canada.

If there's intention in including fr-QC, it might make sense to have a synonymous code for fr-CA.

### Specifications

mastodon 4.1

### PR DESCRIPTION
**Pull request by gunchleoc**
Closes https://github.com/mastodon/mastodon/issues/24538

### CODE REVIEW

**Comment by nschonni** [comment]
This makes a lot of sense, but also needs to be done on Crowdin, along with the translation file names

**Comment by vmstan** [comment]
config/locales/fr-QC.yml needs to be modified as well

**Comment by gunchleoc** [comment]
I have opened a discussion on Crowdin to see what the translators for this language say https://crowdin.com/project/mastodon/discussions/311

**Comment by gunchleoc** [comment]
I expect this will also need database migrations:

1. Display language setting
2. Default posting language
3. General language filter setting
4. Language filter for follow relationships
5. Post language of individual posts

Release notes also need to inform site admins of the change, in case somebody has set `DEFAULT_LOCALE` to `fr-QC`.

Did I miss anything?

**Comment by gunchleoc** [comment]
I have renamed the files and fixed the keys. `fr-QC` was not available in the language filters, so for the code we now only need migrations for:

1. Display language setting
2. Default posting language

Is there some documentation on how to write database migrations?

**Comment by gunchleoc** [comment]
I have found out how to do the migration, so this should now be complete and ready for review. Branch has been rebased.

**Comment by gunchleoc** [comment]
Canadian French is not available as a posting language; it is rerouted to French. So, no posts or posting language migrations needed.

What does need doing is an update of the configuration in Crowdin to match the translations pull/push to the new locale code.

File: db/migrate/20230813203012_fix_canadian_french_locale.rb [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+
+class FixCanadianFrenchLocale < ActiveRecord::Migration[7.0]
+  class User < ApplicationRecord
+    # Dummy class, to make migration possible across version changes
+  end
+
+  disable_ddl_transaction!
+
+  def up
+    User.where(locale: 'fr-QC').find_in_batches do |users|
```
Comment (mjankowski) [inline db/migrate/20230813203012_fix_canadian_french_locale.rb:11]: Could this just be one SQL update, instead of iterating through user objects?

Comment (gunchleoc) [reply db/migrate/20230813203012_fix_canadian_french_locale.rb:11]: Done. I don't know how to test the change though, since I've already run the migration. I find the Ruby documentation too hard to navigate on this topic, so I'm basically just frankencoding these from older migrations.

Comment (ClearlyClaire) [reply db/migrate/20230813203012_fix_canadian_french_locale.rb:11]: Alright, I can write some migration tests.

**Comment by ClearlyClaire** [comment]
FYI, I just pushed a migration test to the PR, please pull if you intend to force-push again!

File: db/migrate/20230813203012_fix_canadian_french_locale.rb (hunk 1 above)
Comment (ClearlyClaire) [reply db/migrate/20230813203012_fix_canadian_french_locale.rb:11]: Oops, this should be `in_batches` and not `find_in_batches`!

**Comment by gunchleoc** [comment]
> FYI, I just pushed a migration test to the PR, please pull if you intend to force-push again!

Thanks for the test & fix!

**Review by renchap — APPROVED** [review]
