### PR TITLE
Fix punycode encoding of the local domain

### LINKED ISSUE #20906: Punycode-Domain is displayed raw since update to version 4.0.2
### Steps to reproduce the problem

Use a Punycode-Domain

### Expected behaviour

Show human readable domain (for example ratatöskr.de)

### Actual behaviour

Shows Raw Punycode (for example xn--ratatskr-r4a.de)

### Detailed description

When using a Punycode Domain (For example, my Server https://www.ratatöskr.de) everywhere the domain is written in raw punycode (xn--ratatskr-r4a.de) instead of the human-readable domain (ratatöskr.de). Version 3.5.3 was handling it for most written domains correctly. 

### Specifications

Mastodon 4.0.2
Ruby 3.0.4

### PR DESCRIPTION
**Pull request by Tritlo**
This adds a call to `punycode.toUnicode` to prettify the *local* domain, changing e.g.  `@matti@xn--lofll-1sat.is` to `@matti@loðfíll.is`.
This happens on the:
  + local user profile page
  + the footer
  + the about page
  + ..., everywhere {domain} is used directly.

### CODE REVIEW

**Comment by Tritlo** [comment]
Sorry for all the force pushes... I missed a few places in my first attempt. Should be good to go, please review!

**Comment by gol-cha** [comment]
I think it would be better to add prettified local domain to initial-state. Sorry if this is misplaced.
e.g. Add the following line to `InitialStateSerializer`
`pretty_domain: Addressable::IDNA.to_unicode(instance_presenter.domain)`

**Comment by Tritlo** [comment]
My intuition is that we *should* be doing it during rendering, since it *is* just a pretty rendering of a particular string *when the context says it's a URL*. But I might be wrong here.

File: app/javascript/mastodon/components/display_name.js [hunk 1]
```diff
@@ -3,6 +3,7 @@ import ImmutablePropTypes from 'react-immutable-proptypes';
 import PropTypes from 'prop-types';
 import { autoPlayGif } from 'mastodon/initial_state';
 import Skeleton from 'mastodon/components/skeleton';
+import punycode from 'punycode';
```
Comment (ykzts) [inline app/javascript/mastodon/components/display_name.js:6]: The Node.js built-in module `punycode` is deprecated.

see https://nodejs.org/dist/latest-v14.x/docs/api/punycode.html

Comment (Tritlo) [reply app/javascript/mastodon/components/display_name.js:6]: This is the one from npm though, as specified in the package.json.

Comment (Tritlo) [reply app/javascript/mastodon/components/display_name.js]: Ah, I get what you mean. Fixed it so it explicitly references the userland implementation, and fixed an instance where previously defined code was using the built-in one.

**Comment by ClearlyClaire** [comment]
I think it would indeed be much simpler to just have the `domain` from the `initial_state` contain the unicode representation.

**Comment by Tritlo** [comment]
I'm not sure that would be correct, sometimes you *want* the punycoded domain (e.g. for links and such), where the unicode representation would not work. That's the whole idea behind punycode!

**Comment by ClearlyClaire** [comment]
I think `domain` here is pretty much used only for display purposes, though. But I may be wrong, I'd have to double-check.

**Comment by ineffyble** [comment]
Is any defence against homonym attacks needed here? Do we run the risk of fake Mastodon instance impersonating real ones using indistinguishable unicode charts?

File: app/javascript/mastodon/components/status_action_bar.js [hunk 2]
```diff
@@ -301,13 +302,14 @@ class StatusActionBar extends ImmutablePureComponent {
 
       if (account.get('acct') !== account.get('username')) {
         const domain = account.get('acct').split('@')[1];
+        const prettyDomain = domain ? punycode.toUnicode(domain) : domain;
```
Comment (ClearlyClaire) [inline app/javascript/mastodon/components/status_action_bar.js:305]: `account.get('acct')` already returns the “prettified” acct, so this isn't needed here

File: app/javascript/mastodon/containers/status_container.js [hunk 3]
```diff
@@ -222,8 +223,9 @@ const mapDispatchToProps = (dispatch, { intl, contextType }) => ({
   },
 
   onBlockDomain (domain) {
+    const prettyDomain = domain ? punycode.toUnicode(domain) : domain;
```
Comment (ClearlyClaire) [inline app/javascript/mastodon/containers/status_container.js:226]: The `domain` here is already “prettified”, so this isn't needed.

File: app/javascript/mastodon/features/account/components/header.js [hunk 4]
```diff
@@ -160,6 +162,7 @@ class Header extends ImmutablePureComponent {
     const suspended    = account.get('suspended');
     const isRemote     = account.get('acct') !== account.get('username');
     const remoteDomain = isRemote ? account.get('acct').split('@')[1] : null;
+    const prettyRemoteDomain = remoteDomain ? punycode.toUnicode(remoteDomain) : remoteDomain;
```
Comment (ClearlyClaire) [inline app/javascript/mastodon/features/account/components/header.js:165]: It's already the unicode representation.

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]
The remote domains derived from account's `acct` attributes are already utf8-encoded rather than punycode-encoded because the `acct` attribute is “prettified” server-side, so no change is needed client-side there.

I think the local domain passed down from the initial state is only ever used for display, so I think it should be passed down as utf8-encoded rather than prettified in various places on the client-side.

One place I am not entirely sure what the best course of action would be is `app/javascript/mastodon/components/domain.js`, as the server-side code currently returns punycode-encoded domains from the API. So either we indeed need to take care of that client-side, or change the API for consistency with `acct`.

**Comment by ClearlyClaire** [comment]
> Is any defence against homonym attacks needed here? Do we run the risk of fake Mastodon instance impersonating real ones using indistinguishable unicode charts?

I'd say we do not need defense against homonym attacks for the local domain, since the local domain would be controlled by the attacker anyway. We may need defense against homonym attacks for remote domains, but this is not what the current PR is about.

**Comment by ineffyble** [comment]
> We may need defense against homonym attacks for remote domains, but this is not what the current PR is about.

Ah, right, I saw the references to encoding the remote domains in the code, but if they're already encoded then nothing to worry about for this PR.

**Comment by Tritlo** [comment]
I removed the unneccesary ones, per @ClearlyClaire. I still think this is the way to go, to render the domain when it's rendered. But I can change it so that the domain is prettified before being send, if you think it's safe.

**Comment by ClearlyClaire** [comment]
> I removed the unneccesary ones, per @ClearlyClaire. I still think this is the way to go, to render the domain when it's rendered. But I can change it so that the domain is prettified before being sent, if you think it's safe.

I do think it is safe, yes.

**Comment by Tritlo** [comment]
Alright, much simpler now!

**Review by ClearlyClaire — APPROVED** [review]

**Comment by ClearlyClaire** [comment]
> Alright, much simpler now!

Thanks again for the PR!

> (sorry for the all the pushes, my git got into some weird state there for a second).

No worries!
