### PR TITLE
Fix error within error when limiting backtrace to 3 lines

### LINKED ISSUE #13086: NoMethodError in LinkCrawlWorker
on v3.1.1

```
LinkCrawlWorker	
NoMethodError: undefined method `message' for "Net::ReadTimeout with #<TCPSocket:(closed)>":String

LinkCrawlWorker	
NoMethodError: undefined method `message' for "execution expired":String

LinkCrawlWorker	
NoMethodError: undefined method `message' for "end of file reached":String

LinkCrawlWorker	
NoMethodError: undefined method `message' for "Net::OpenTimeout":String
```

### PR DESCRIPTION
**Pull request by Gargron**
Alternative solution within Sidekiq middleware to be more DRY

Fix #13086, close #13113

### CODE REVIEW

**Review by ykzts — APPROVED** [review]

**Review by ClearlyClaire — APPROVED** [review]

File: app/lib/sidekiq_error_handler.rb [hunk 1]
```diff
@@ -1,13 +1,24 @@
 # frozen_string_literal: true
 
 class SidekiqErrorHandler
+  BACKTRACE_LIMIT = 3
+
   def call(*)
     yield
   rescue Mastodon::HostValidationError
     # Do not retry
+  rescue => e
```
Comment (zunda) [inline app/lib/sidekiq_error_handler.rb]: For the Code Climate error "Avoid rescuing without specifying an error class.", we might be able to start `rescue`ing the following exceptions that have been recorded on my server in the last 24 hours:

- HTTP::ConnectionError
- HTTP::TimeoutError
- Mastodon::UnexpectedResponseError
- Stoplight::Error::RedLight (this might go elsewhere with the change in this PR)
