### PR TITLE
Fix race condition when receiving an ActivityPub Create multiple times

### LINKED ISSUE #4905: Remote status from followers with mentions to local users processed twice
Status with mentions to a local user are processed twice, leading to noisy logs, with stuff like “ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_statuses_on_uri"”.

Haven't investigated in-depth yet.

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #4905. The issue is that a same Create activity can be delivered multiple times to the same instance, and will be processed in concurrent tasks. The time from status processing to commit in the database is relatively long, which makes things worse and a race condition more likely to occur.

This proposed looks up the toot locally if an ActiveRecord exception is raised by the transaction. The reasoning behind the `raise e unless status` pattern is that we want to catch issues arising from the race condition, and not other issues, as I fear `ActiveRecord::RecordInvalid` might be too broad and catch unrelated exceptions.

(Or of course we may also use locks, but I have no experience with these in RoR)

### CODE REVIEW

File: app/lib/activitypub/activity/create.rb [hunk 1]
```diff
@@ -4,10 +4,17 @@ class ActivityPub::Activity::Create < ActivityPub::Activity
   def perform
     return if delete_arrived_first?(object_uri) || unsupported_object_type?
 
-    status = find_existing_status
+    RedisLock.acquire(lock_options) do |lock|
+      status = find_existing_status
```
Comment (Gargron) [inline app/lib/activitypub/activity/create.rb]: Gotta do something like `if lock.acquired?`

Comment (Gargron) [reply app/lib/activitypub/activity/create.rb]: I think `status` must be first defined outside of the block, otherwise it's scoped to within the block only. Same thing in `process_status` below.

**Review by Gargron — CHANGES_REQUESTED** [review]

File: app/lib/activitypub/activity/create.rb [hunk 2]
```diff
@@ -4,10 +4,19 @@ class ActivityPub::Activity::Create < ActivityPub::Activity
...
 
-    return status unless status.nil?
+    @status
+  end
+
+  private
 
+  def process_status
     ApplicationRecord.transaction do
       status = Status.create!(status_params)
```
Comment (Gargron) [inline app/lib/activitypub/activity/create.rb]: Scoping issue here as well

**Review by Gargron — CHANGES_REQUESTED** [review]

**Comment by ThibG** [comment]
Sorry for the multiple issues, I planned to test it right away, but I'm having issues with my ISP at the moment. I might not be able to work on it much more today.

**Review by Gargron — APPROVED** [review]
