### PR TITLE
Fix crash on receiving requests with missing Digest header

### LINKED ISSUE #15743: Mastodon v3.3.0 return a 500 error when an inbox query does not have a Digest header
### Expected behaviour

An error is returned when the Digest header is missing

### Actual behaviour

A 500 error without an actionable error message is returned to the caller

### Steps to reproduce the problem

Send a well-formed ActivityPub action to the inbox of a Mastodon v3.3.0 actor, without a Digest header.
I discovered the issue while sending a follow request.

### Specifications

Mastodon v3.3.0

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Return an error pointing out that Digest is missing, instead of crashing.

Fixes #15743

### CODE REVIEW

File: app/controllers/concerns/signature_verification.rb [hunk 1]
```diff
@@ -133,6 +133,7 @@ def verify_signature_strength!
 
   def verify_body_digest!
     return unless signed_headers.include?('digest')
+    raise SignatureVerificationError, 'Digest header missing.' unless request.headers.key?('Digest')
```
Comment (Gargron) [inline app/controllers/concerns/signature_verification.rb:136]: Period not needed

**Review by Gargron — APPROVED** [review]
