### PR TITLE
Disable actions on reports that have already been taken

### LINKED ISSUE #18718: Report interface actions: duplicate actions
### Steps to reproduce the problem

The report interface has a "quick actions" style list of actions to take against the reported user. It would be great if those action buttons indicated if they were useless. In particular, the **"Limit"** action is offered even when the user is already limited.

Additionally, even after pressing the button, there is no reaction to indicate what is going on: are limited users getting an additional notification? Did just nothing happen (while the moderator expected to take a siginificant action)?

### Expected behaviour

Don't show the button / show it greyed out indicating that the user is already limited.

### Actual behaviour

Button is available and gives no feedback after pressing it that anything is amiss.

### Specifications

v3.5.3

### PR DESCRIPTION
**Pull request by ThisIsMissEm**
This fixes #18718

### Screenshots

Report actions when report has no posts and the account is already limited:
Screenshot 2024-09-05 at 19 00 15

Report actions when report has no posts and the account is already suspended:
Screenshot 2024-09-05 at 18 59 51

Custom Actions for Account when Account is already suspended:
Screenshot 2024-09-05 at 18 59 43

Custom Actions for Account when Account is already limited.
Screenshot 2024-09-05 at 18 59 20

### CODE REVIEW

**Comment by ThisIsMissEm** [comment]
Also thinking on custom actions, we should probably add a "cancel" button, which just takes the user back, if possible.

File: app/models/admin/account_action.rb [hunk 1]
```diff
@@ -73,6 +73,14 @@ def types_for_account(account)
       end
     end
 
+    def disabled_types_for_account(account)
+      if account.suspended?
+        %w(silence suspend)
+      elsif account.silenced?
+        %w(silence)
+      end
```
Comment (ThisIsMissEm) [inline app/models/admin/account_action.rb:81]: Arguably disable and sensitive don't really make sense for accounts already suspended either?

**Comment by ThisIsMissEm** [comment]
"Include statuses" probably also doesn't make sense if the report didn't have any attached statuses too?

File: app/views/admin/reports/_actions.html.haml [hunk 2]
```diff
@@ -17,21 +17,27 @@
       .report-actions__item__button
         = form.button t('admin.reports.delete_and_resolve'),
                       name: :delete,
-                      class: 'button button--destructive'
+                      class: 'button button--destructive',
+                      disabled: statuses.empty?,
+                      title: statuses.empty? ? t('admin.reports.actions_no_posts') : ''
```
Comment (ClearlyClaire) [inline app/views/admin/reports/_actions.html.haml:22]: I think this could entirely be skipped when there are no posts selected.

File: app/views/admin/account_actions/new.html.haml [hunk 3]
```diff
@@ -1,6 +1,13 @@
 - content_for :page_title do
   = t('admin.account_actions.title', acct: @account.pretty_acct)
 
+- if @account.suspended?
+  .flash-message.alert
+    = t('admin.account_actions.already_suspended')
+- elsif @account.silenced?
+  .flash-message.warn
+    = t('admin.account_actions.already_silenced')
```
Comment (ClearlyClaire) [inline app/views/admin/account_actions/new.html.haml:9]: Having this information is good, but I would probably not use the flash styles, especially those indicating an error.

**Review by ClearlyClaire — COMMENTED** [review]
That change looks sensible, although I'm not 100% sure about the use of the `title` attribute here

File: app/models/admin/account_action.rb (hunk 1 above)
Comment (ClearlyClaire) [reply app/models/admin/account_action.rb:81]: Arguably, yes, but also, I suppose you may want to e.g. suspend the account, then apply one of those restrictions, and finally roll back that the suspend.

Comment (ThisIsMissEm) [reply app/models/admin/account_action.rb:81]: Maybe, but then would you just freeze?

File: app/views/admin/reports/_actions.html.haml (hunk 2 above)
Comment (ThisIsMissEm) [reply app/views/admin/reports/_actions.html.haml:22]: I asked a few mods and they said they'd rather the buttons be there consistently but disabled, and I think I understand that, since it makes things predictable

File: app/views/admin/account_actions/new.html.haml (hunk 3 above)
Comment (ThisIsMissEm) [reply app/views/admin/account_actions/new.html.haml:9]: Yeah, wasn't a fan of reusing flash styling but wasn't sure how else would look good to style it in an attention grabbing way

**Review by ClearlyClaire — APPROVED** [review]
