### PR TITLE
Dereference object URIs in Create and Update messages

### LINKED ISSUE #14353: support for monsterpit's new federation method?
### Pitch

monsterpit has a new more-private federation method, and I'd like to see it supported.

### Motivation

monsterpit has a new more-private federation method, and it currently doesn't work with masto. it's good stuff and I wanna see it supported.

(there's probably already an issue for this but I couldn't find it.)

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #14353

This is directly a commit cherry-picked from Monsterpit, as I figured it should be enough.

To my understanding, their scheme does not provide any benefit *right now*, but it provides an opportunity for the sending server to check the receiving actor's key has not changed and is still controlled by that person, among other things: https://the.monsterpit.net/@firedemon/104541374145521914

I am not sure this is a trade-off that makes sense to Mastodon itself, as that's an added round-trip for each `Create`/`Update` activity, but supporting `Create` and `Update` activities which object is not inlined is probably fine, and falls within the AP spec.

~~The code does duplicate a few bits from the ActivityPub resource fetching code, so maybe it could be refactored a bit, but otherwise it seems fine to me.~~

### CODE REVIEW

File: app/lib/activitypub/activity.rb [hunk 1]
```diff
@@ -157,6 +157,38 @@ def status_from_object
...
+  def dereference_object!
+    return unless @object.is_a?(String) && object_uri.start_with?('https://', 'http://')
+    return if ActivityPub::TagManager.instance.local_uri?(object_uri)
+
+    object = fetch_resource(@object, true, signed_fetch_account)
+    return unless object.present? && object.is_a?(Hash) && supported_context?(object) && equals_or_includes_any?(object['type'], SUPPORTED_TYPES + CONVERTED_TYPES)
+
+    actor_id = value_or_id(first_of_value(object['attributedTo']))
+    return if actor_id.nil? || object['id'].nil?
+    return unless Addressable::URI.parse(object['id']).normalized_host.casecmp(Addressable::URI.parse(actor_id).normalized_host).zero?
```
Comment (ThibG) [inline app/lib/activitypub/activity.rb:169]: Also, note that most of those checks may not actually be needed as they are performed in the handlers for `Create` and `Update` as well.

**Review by Gargron — APPROVED** [review]
Code is a little messy but correct
