### PR TITLE
Fix not being able to block a subdomain of an already-blocked domain through the API

### LINKED ISSUE #29127: Possible to create domain blocks when a stricter limit already exists in Admin UI
### Steps to reproduce the problem

1. Go to `/admin/instances?limited=1` to manage federation
2. Add a domain block for `example` (noop/none severity)
3. Using the API try to create a domain block for `test.example` observe that an error is returned
4. Go back to the admin UI and create a domain block for `test.example` observe that no error is returned and the block is successfully created.

### Expected behaviour

Both methods for creating domain blocks should have same behaviour

### Actual behaviour

The API failed whilst the Admin UI succeeded

### Detailed description

This bug affects IFTAS FediCheck, where we weren't observing the same logic as `DomainBlock.rule_for` when attempting to create a domain block, which meant an existing block of `example` would fail the block creation of `test.example` leaving us out of sync with the Mastodon server (we also weren't handling the error response from the API correctly.

### Mastodon instance

_No response_

### Mastodon version

main

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: v 3.2.3
- Node.js version: v20.11.0

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #29127

The previous implementation was [deliberately kept simple](https://github.com/mastodon/mastodon/pull/18247#pullrequestreview-987904290) but this outright prevented to create domain blocks for subdomains of already-blocked domains.

### CODE REVIEW

File: app/controllers/api/v1/admin/domain_blocks_controller.rb [hunk 1]
```diff
@@ -29,10 +29,13 @@ def show
   def create
     authorize :domain_block, :create?
 
+    @domain_block = DomainBlock.new(resource_params)
     existing_domain_block = resource_params[:domain].present? ? DomainBlock.rule_for(resource_params[:domain]) : nil
-    return render json: existing_domain_block, serializer: REST::Admin::ExistingDomainBlockErrorSerializer, status: 422 if existing_domain_block.present?
 
-    @domain_block = DomainBlock.create!(resource_params)
+    return render json: existing_domain_block, serializer: REST::Admin::ExistingDomainBlockErrorSerializer, status: 422 if existing_domain_block.present? && !@domain_block.stricter_than?(existing_domain_block)
+    return render json: existing_domain_block, serializer: REST::Admin::ExistingDomainBlockErrorSerializer, status: 422 if existing_domain_block.present? && existing_domain_block.domain == TagManager.instance.normalize_domain(@domain_block.domain)
```
Comment (mjankowski) [inline app/controllers/api/v1/admin/domain_blocks_controller.rb:36]: These two lines on top of each other that are basically the same is sort of weird... possible refactor ideas:

- Convert the full "is there an existing_domain_block present and is either the stricter check or the domain comparison true?" into at least one and maybe multiple private query methods to make this one more readable line?
- Extract `existing_domain_block` into a memoized private method instead of local var in this method?
- Convert the entire "existing check" into a before_action here, instead of in-line check in the action method?

**Comment by ThisIsMissEm** [comment]
I think this looks functionally good to me, I'll let you and Matt sort out code formatting / style issues.

File: app/controllers/api/v1/admin/domain_blocks_controller.rb (hunk 1 above)
Comment (ClearlyClaire) [reply app/controllers/api/v1/admin/domain_blocks_controller.rb]: I don't really see the point in moving the local variable into a memoized private method.

Moving the check to a `before_action` could make sense, but we'd need to move the authorization check in such a filter as well, which is not the pattern we have adopted anywhere else.

I combined the two conditions into one, although I suppose I could further move that check to a private method.

Comment (mjankowski) [reply app/controllers/api/v1/admin/domain_blocks_controller.rb]: > I don't really see the point in moving the local variable into a memoized private method.

On it's own, probably not that useful. If you did extract a query method for the condition check and/or pull the whole thing out to a before_action, it would probably be useful/necessary in those scenarios.

> Moving the check to a `before_action` could make sense, but we'd need to move the authorization check in such a filter as well, which is not the pattern we have adopted anywhere else.

Ah, good point ... b/c we only want to even run this and do the existing if that first condition is passed. Given that, I'd keep this in the method and not bother with the before_action here.

> I combined the two conditions into one, although I suppose I could further move that check to a private method.

I personally think this would be more readable, but not a blocker.

Comment (ClearlyClaire) [reply app/controllers/api/v1/admin/domain_blocks_controller.rb]: Updated to put the condition in a private method.

**Review by renchap — APPROVED** [review]
