### PR TITLE
Fix RTL detection on Ruby side

### LINKED ISSUE #3803: Implementation of rtl? method is incorrect
[1] [rtl?](https://github.com/tootsuite/mastodon/blob/master/app/helpers/stream_entries_helper.rb#L54) method has the following line:

```rb
 rtl_characters = /[\p{Hebrew}|\p{Arabic}|\p{Syriac}|\p{Thaana}|\p{Nko}]+/m.match(text)
```

The vertical lines in `[ ]` are superfluous.
Because of it, vertical lines are counted as a RTL-caracter; so, the toot `a|b`, for example,  will be treated as RTL.

[2] `match` method in the above line will find only the first RTL-word in a toot.
So amount of RTL-characters in a toot will not be evaluated correctly.

### PR DESCRIPTION
**Pull request by unarist**
This fixes #3803, i.e. below bugs:

* pipe characters being counted as RTL character
* only first word being checked

### CODE REVIEW

File: app/helpers/stream_entries_helper.rb [hunk 1]
```diff
@@ -53,11 +53,11 @@ def rtl_status?(status)
 
   def rtl?(text)
     text = simplified_text(text)
-    rtl_characters = /[\p{Hebrew}|\p{Arabic}|\p{Syriac}|\p{Thaana}|\p{Nko}]+/m.match(text)
```
Comment (clworld) [inline app/helpers/stream_entries_helper.rb]: Oh...:sweat_smile:

**Review by clworld — APPROVED** [review]
Looks good to me.

File: app/helpers/stream_entries_helper.rb (hunk 1 above)
Comment (Gargron) [inline app/helpers/stream_entries_helper.rb]: @clworld What?

Comment (Gargron) [inline app/helpers/stream_entries_helper.rb]: I mean, is everything okay with this PR?

Comment (clworld) [inline app/helpers/stream_entries_helper.rb]: Yes.  Everything is okay. I said 'Oh...😅' because old code has '|' in '[]' in Regexp.
