### PR TITLE
Fix sidebar rest position on mobile layout on RTL locales

### LINKED ISSUE #35066: Mobile layout unusable with RTL locales
### Steps to reproduce the problem

1. Use a RTL locale
2. Use the Web UI in a width-constrained window

### Expected behaviour

Layout is usable

### Actual behaviour

Resting position of the sidebar obscures part of the screen

### Detailed description

Image

### Mastodon instance

mastodon.online

### Mastodon version

v4.4.0-nightly.2025-06-17

### Browser name and version

Firefox 139

### Operating system

Debian Linux

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #35066

### CODE REVIEW

File: app/javascript/mastodon/features/navigation_panel/index.tsx [hunk 1]
```diff
@@ -238,25 +242,37 @@ export const NavigationPanel: React.FC = () => {
...
-    ({ last, offset: [ox], velocity: [vx], direction: [dx], cancel }) => {
-      if (ox < -70) {
+    ({
+      last,
+      offset: [xOffset],
+      velocity: [xVelocity],
+      direction: [xDirection],
+      cancel,
+    }) => {
+      const hasReachedDragThreshold = xOffset * xDirection > 70;
```
Comment (ClearlyClaire) [inline app/javascript/mastodon/features/navigation_panel/index.tsx]: This is a behavior change, isn't it? The previous behavior was cancelling if you go too far against the “rubber banding”, while right now it'd be in any direction?

File: app/javascript/mastodon/features/navigation_panel/index.tsx [hunk 2]
```diff
@@ -238,25 +242,37 @@ export const NavigationPanel: React.FC = () => {
...
+
+      if (hasReachedDragThreshold) {
         cancel();
       }
 
       if (last) {
-        if (ox > MENU_WIDTH / 2 || (vx > 0.5 && dx > 0)) {
-          void spring.start({ x: MENU_WIDTH });
+        const isAboveOpenThreshold = xOffset > MENU_WIDTH / 2;
```
Comment (ClearlyClaire) [inline app/javascript/mastodon/features/navigation_panel/index.tsx]: Doesn't that need to take account `isLtrDir` as well?

File: app/javascript/mastodon/features/navigation_panel/index.tsx (hunk 1 above)
Comment (diondiondion) [reply app/javascript/mastodon/features/navigation_panel/index.tsx]: You're right, I'll check again. I reverted some things while cleaning up and it looks I kept the wrong variable 🙈

File: app/javascript/mastodon/features/navigation_panel/index.tsx (hunk 2 above)
Comment (diondiondion) [reply app/javascript/mastodon/features/navigation_panel/index.tsx]: Yes, I think it should, thanks.

File: app/javascript/mastodon/features/navigation_panel/index.tsx (hunk 1 above)
Comment (diondiondion) [reply app/javascript/mastodon/features/navigation_panel/index.tsx]: Thanks for catching these, they should now be fixed.

**Review by diondiondion — APPROVED** [review]

**Review by renchap — APPROVED** [review]
