### PR TITLE
Fix boosts of local users being filtered in account timelines

### LINKED ISSUE #27195: Caught mastodon.social dropping boosts
### Steps to reproduce the problem

I am logged into mastodon.social. At this exact moment, if I open https://mastodon.social/@graydon@types.pl , I see this

image

Notice the reference to a "last boost".

If I go directly to graydon's feed on types.pl https://types.pl/@graydon , I see this:

image

Beneath the crawfordsm post, I see the microplastics post. There is a post missing from this feed, but *only* when I view from mastodon.social.

@crawfordsm@mastodon.social is on mastodon.social, so I assume that there is not a federation issue preventing me from seeing the post. I do not have crawfordsm blocked or muted. I have no filters which hide posts completly (only hide with warning) and none of my filters would apply to this post. It is possible crawfordsm has me blocked, but I assume not because I can see the original post on mastodon.social https://mastodon.social/@crawfordsm/110700335570308419 , I can see crawfordsm's profile, and the UI does not stop me from trying to @-mention Dr. Crawford.

### Expected behaviour

I expect that boosts and regular statuses should be shown to me in chronological order if the account is on a peer server in good standing.

### Actual behaviour

Post from my instance boosted on other instance missing from user feed

### Detailed description

_No response_

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.0+pr-27116-50e1f46

### Browser name and version

Chrome 117.0.5938.92 (Official Build) (64-bit)

### Operating system

Windows 10

### Technical details

_No response_

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #27195

### CODE REVIEW

File: app/lib/account_statuses_filter.rb [hunk 1]
```diff
@@ -60,8 +60,8 @@ def filtered_reblogs_scope
       .where(reblog_of_id: nil)
       .or(
         scope
+          .where(reblog: { accounts: { domain: nil } }).or(scope.where.not(reblog: { accounts: { domain: current_account.excluded_from_timeline_domains } }))
           .where.not(reblog: { account_id: current_account.excluded_from_timeline_account_ids })
-          .where.not(reblog: { accounts: { domain: current_account.excluded_from_timeline_domains } })
```
Comment (ClearlyClaire) [inline app/lib/account_statuses_filter.rb:64]: To reduce code duplication and improve legibility, I'd like to use the `Status.not_excluded_by_account` and `Status.not_domain_blocked_by_account` scopes… however, I don't know if this is possible to do specifically on `reblog`.

**Review by renchap — APPROVED** [review]
