### PR TITLE
Fix multiple issues with replies collection for pages further than self-replies

### LINKED ISSUE #11568: Publish valid replies in "replies" collection [JSON][ActivityPub]
### Pitch

Currently only self-replies are included. I propose including all valid replies.

### Motivation

The current thread construction behavior is flawed, and intersects with a lot of issues that have presented long-standing UX issues: #8565, #9409, #10916, #11503 (particularly https://github.com/tootsuite/mastodon/issues/11503#issuecomment-518748342 as it interfaces with #9409), #10865, and possibly more.

Including all valid replies is the first step to being able to query `replies` (which is needed for the above issues).

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #11568

### CODE REVIEW

File: app/controllers/activitypub/replies_controller.rb [hunk 1]
```diff
@@ -38,7 +38,7 @@ def replies_collection_presenter
       type: :unordered,
       part_of: account_status_replies_url(@account, @status),
       next: next_page,
-      items: @replies.map { |status| status.local ? status : status.id }
+      items: @replies.map { |status| status.local ? status : status.uri }
```
Comment (Gargron) [inline app/controllers/activitypub/replies_controller.rb]: For consistency shouldn't this use TagManager?

File: app/serializers/activitypub/note_serializer.rb [hunk 2]
```diff
@@ -55,7 +55,7 @@ def replies
         type: :unordered,
         part_of: ActivityPub::TagManager.instance.replies_uri_for(object),
         items: replies.map(&:second),
-        next: last_id ? ActivityPub::TagManager.instance.replies_uri_for(object, page: true, min_id: last_id) : nil
+        next: last_id ? ActivityPub::TagManager.instance.replies_uri_for(object, page: true, min_id: last_id) : ActivityPub::TagManager.instance.replies_uri_for(object, page: true, other_accounts: true)
```
Comment (Gargron) [inline app/serializers/activitypub/note_serializer.rb]: I feel like `other_accounts` is an unhelpful param name. I have no idea what it does. Initially I assumed it would be an array of accounts!

**Review by Gargron — CHANGES_REQUESTED** [review]

File: app/controllers/activitypub/replies_controller.rb (hunk 1 above)
Comment (ThibG) [reply app/controllers/activitypub/replies_controller.rb]: I'm not sure I see the use for that. I don't think calling TagManager for the remote case would make things clearer. The local case returns the full status inlined, not only its identifier.

File: app/serializers/activitypub/note_serializer.rb (hunk 2 above)
Comment (ThibG) [reply app/serializers/activitypub/note_serializer.rb]: What should it be, then? When it isn't set, the endpoint will return self-replies only, when it is set, it will return only replies from other accounts.

Comment (Gargron) [reply app/serializers/activitypub/note_serializer.rb]: I think `only_self_replies` could be a good alternative

File: app/controllers/activitypub/replies_controller.rb (hunk 1 above)
Comment (Gargron) [reply app/controllers/activitypub/replies_controller.rb]: Mh okay then

File: app/serializers/activitypub/note_serializer.rb (hunk 2 above)
Comment (ThibG) [reply app/serializers/activitypub/note_serializer.rb]: `only_other_accounts` to not change the logic?

Comment (Gargron) [reply app/serializers/activitypub/note_serializer.rb]: Okay.

**Review by Gargron — APPROVED** [review]
